// Code generated by odjson. DO NOT EDIT.
//
// Source: odjson

package crosspkg

import (
	"bytes"
	"encoding/json/jsontext"
	"github.com/mazrean/odjson/internal/testfixture/other"
	"github.com/mazrean/odjson/odjsonrt"
	"slices"
)

// odjsonAppend appends the JSON encoding of v to dst.
func (v *Holder) odjsonAppend(dst []byte, m odjsonrt.StringMode) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, "{\"thing\":"...)
	dst, err = odjsonOtherThingAppend(dst, &v.Thing, m)
	if err != nil {
		return nil, err
	}
	dst = append(dst, ",\"ptr\":"...)
	if v.Ptr == nil {
		dst = append(dst, 'n', 'u', 'l', 'l')
	} else {
		dst, err = odjsonOtherThingAppend(dst, v.Ptr, m)
		if err != nil {
			return nil, err
		}
	}
	dst = append(dst, ",\"wrapper\":"...)
	dst, err = odjsonOtherWrapperAppend(dst, &v.Wrapper, m)
	if err != nil {
		return nil, err
	}
	dst = append(dst, ",\"list\":"...)
	if v.List == nil {
		dst = odjsonrt.AppendNilSlice(dst, m)
	} else {
		dst = append(dst, '[')
		for i1 := range v.List {
			if i1 > 0 {
				dst = append(dst, ',')
			}
			dst, err = odjsonOtherThingAppend(dst, &v.List[i1], m)
			if err != nil {
				return nil, err
			}
		}
		dst = append(dst, ']')
	}
	dst = append(dst, ",\"map\":"...)
	if v.Map == nil {
		dst = odjsonrt.AppendNilMap(dst, m)
	} else {
		keys2 := make([]string, 0, len(v.Map))
		for k3 := range v.Map {
			keys2 = append(keys2, string(k3))
		}
		slices.Sort(keys2)
		dst = append(dst, '{')
		for i4, k3 := range keys2 {
			if i4 > 0 {
				dst = append(dst, ',')
			}
			dst = append(dst, '"')
			dst, err = odjsonrt.AppendStringBodyChecked(dst, k3, m)
			if err != nil {
				return nil, err
			}
			dst = append(dst, '"', ':')
			mv5 := v.Map[k3]
			dst, err = odjsonOtherThingAppend(dst, &mv5, m)
			if err != nil {
				return nil, err
			}
		}
		dst = append(dst, '}')
	}
	dst = append(dst, ",\"deep\":"...)
	if v.Deep == nil {
		dst = odjsonrt.AppendNilSlice(dst, m)
	} else {
		dst = append(dst, '[')
		for i6 := range v.Deep {
			if i6 > 0 {
				dst = append(dst, ',')
			}
			if v.Deep[i6] == nil {
				dst = append(dst, 'n', 'u', 'l', 'l')
			} else {
				dst, err = odjsonOtherWrapperAppend(dst, v.Deep[i6], m)
				if err != nil {
					return nil, err
				}
			}
		}
		dst = append(dst, ']')
	}
	dst = append(dst, "}"...)
	return dst, nil
}

// odjsonCapHolderList remembers how long v.List has been, to allocate it once.
var odjsonCapHolderList odjsonrt.CapHint

// odjsonCapHolderDeep remembers how long v.Deep has been, to allocate it once.
var odjsonCapHolderDeep odjsonrt.CapHint

// odjsonParse decodes the JSON object starting at p into v and
// returns the offset just past it. Strings are interned through
// sc, which may be nil.
func (v *Holder) odjsonParse(data []byte, p int, sc *odjsonrt.StringCache) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		return np, nil
	}
	if p >= len(data) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "Holder")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if p < len(data) && data[p] == '}' {
		return p + 1, nil
	}
	for {
		var key []byte
		p = odjsonrt.SkipSpace(data, p)
		idx := -1
		rest := data[p:]
		if len(rest) > 1 {
			switch rest[1] {
			case 't':
				if len(rest) >= 7 && string(rest[:7]) == "\"thing\"" {
					idx, p = 0, p+7
				}
			case 'p':
				if len(rest) >= 5 && string(rest[:5]) == "\"ptr\"" {
					idx, p = 1, p+5
				}
			case 'w':
				if len(rest) >= 9 && string(rest[:9]) == "\"wrapper\"" {
					idx, p = 2, p+9
				}
			case 'l':
				if len(rest) >= 6 && string(rest[:6]) == "\"list\"" {
					idx, p = 3, p+6
				}
			case 'm':
				if len(rest) >= 5 && string(rest[:5]) == "\"map\"" {
					idx, p = 4, p+5
				}
			case 'd':
				if len(rest) >= 6 && string(rest[:6]) == "\"deep\"" {
					idx, p = 5, p+6
				}
			}
		}
		if idx >= 0 {
			if np := odjsonrt.AfterName(data, p); np > 0 {
				p = np
			} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
				return p, err
			}
		} else {
			key, _, p, err = odjsonrt.ParseKey(data, p)
			if err != nil {
				return p, err
			}
			switch string(key) {
			case "thing":
				idx = 0
			case "ptr":
				idx = 1
			case "wrapper":
				idx = 2
			case "list":
				idx = 3
			case "map":
				idx = 4
			case "deep":
				idx = 5
			}
		}
		switch idx {
		case 0:
			p, err = odjsonOtherThingParse(data, &v.Thing, p, sc)
			if err != nil {
				return p, err
			}
		case 1:
			if np7, ok8 := odjsonrt.ParseNull(data, p); ok8 {
				v.Ptr = nil
				p = np7
			} else {
				if v.Ptr == nil {
					v.Ptr = new(other.Thing)
				}
				p, err = odjsonOtherThingParse(data, v.Ptr, p, sc)
				if err != nil {
					return p, err
				}
			}
		case 2:
			p, err = odjsonOtherWrapperParse(data, &v.Wrapper, p, sc)
			if err != nil {
				return p, err
			}
		case 3:
			if np9, ok10 := odjsonrt.ParseNull(data, p); ok10 {
				p = np9
				v.List = nil
			} else {
				if p >= len(data) || data[p] != '[' {
					return p, odjsonrt.ErrType(data, p, "[]other.Thing")
				}
				p++
				s11 := v.List[:0]
				p = odjsonrt.SkipSpace(data, p)
				if p < len(data) && data[p] == ']' {
					p++
				} else {
					if cap(s11) == 0 {
						s11 = make([]other.Thing, 0, odjsonrt.CapFor[other.Thing](&odjsonCapHolderList))
					}
					for {
						var e12 other.Thing
						p, err = odjsonOtherThingParse(data, &e12, p, sc)
						if err != nil {
							return p, err
						}
						s11 = append(s11, e12)
						p = odjsonrt.SkipSpace(data, p)
						if p >= len(data) {
							return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
						}
						if data[p] == ',' {
							p++
							continue
						}
						if data[p] == ']' {
							p++
							break
						}
						return p, odjsonrt.ErrSyntax(data, p, "after array element")
					}
					odjsonCapHolderList.Record(len(s11))
				}
				if s11 == nil {
					s11 = []other.Thing{}
				}
				v.List = s11
			}
		case 4:
			if np13, ok14 := odjsonrt.ParseNull(data, p); ok14 {
				p = np13
				v.Map = nil
			} else {
				if p >= len(data) || data[p] != '{' {
					return p, odjsonrt.ErrType(data, p, "map[string]other.Thing")
				}
				p++
				m15 := v.Map
				if m15 == nil {
					m15 = make(map[string]other.Thing)
				}
				p = odjsonrt.SkipSpace(data, p)
				if p < len(data) && data[p] == '}' {
					p++
				} else {
					for {
						var k16 []byte
						p = odjsonrt.SkipSpace(data, p)
						k16, _, p, err = odjsonrt.ParseKey(data, p)
						if err != nil {
							return p, err
						}
						var mv17 other.Thing
						p, err = odjsonOtherThingParse(data, &mv17, p, sc)
						if err != nil {
							return p, err
						}
						m15[sc.Make(k16)] = mv17
						p = odjsonrt.SkipSpace(data, p)
						if p >= len(data) {
							return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
						}
						if data[p] == ',' {
							p++
							continue
						}
						if data[p] == '}' {
							p++
							break
						}
						return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
					}
				}
				v.Map = m15
			}
		case 5:
			if np18, ok19 := odjsonrt.ParseNull(data, p); ok19 {
				p = np18
				v.Deep = nil
			} else {
				if p >= len(data) || data[p] != '[' {
					return p, odjsonrt.ErrType(data, p, "[]*other.Wrapper")
				}
				p++
				s20 := v.Deep[:0]
				p = odjsonrt.SkipSpace(data, p)
				if p < len(data) && data[p] == ']' {
					p++
				} else {
					if cap(s20) == 0 {
						s20 = make([]*other.Wrapper, 0, odjsonrt.CapFor[*other.Wrapper](&odjsonCapHolderDeep))
					}
					for {
						var e21 *other.Wrapper
						p = odjsonrt.SkipSpace(data, p)
						if np22, ok23 := odjsonrt.ParseNull(data, p); ok23 {
							e21 = nil
							p = np22
						} else {
							if e21 == nil {
								e21 = new(other.Wrapper)
							}
							p, err = odjsonOtherWrapperParse(data, e21, p, sc)
							if err != nil {
								return p, err
							}
						}
						s20 = append(s20, e21)
						p = odjsonrt.SkipSpace(data, p)
						if p >= len(data) {
							return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
						}
						if data[p] == ',' {
							p++
							continue
						}
						if data[p] == ']' {
							p++
							break
						}
						return p, odjsonrt.ErrSyntax(data, p, "after array element")
					}
					odjsonCapHolderDeep.Record(len(s20))
				}
				if s20 == nil {
					s20 = []*other.Wrapper{}
				}
				v.Deep = s20
			}
		default:
			p = odjsonrt.SkipSpace(data, p)
			p, err = odjsonrt.SkipValue(data, p)
			if err != nil {
				return p, err
			}
		}
		p = odjsonrt.SkipSpace(data, p)
		if p >= len(data) {
			return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
		}
		switch data[p] {
		case ',':
			p++
		case '}':
			return p + 1, nil
		default:
			return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
		}
	}
}

// odjsonParseV2 is odjsonParse under encoding/json/v2's semantics, for
// input a jsontext.Decoder has already validated when strict is false,
// and for bytes nobody has looked at when it is true.
func (v *Holder) odjsonParseV2(data []byte, p int, sc *odjsonrt.StringCache, strict bool) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		*v = Holder{}
		return np, nil
	}
	if p >= len(data) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "Holder")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if p < len(data) && data[p] == '}' {
		return p + 1, nil
	}
	var seen [1]uint64
	_ = seen
	unknown, umark := odjsonrt.UnknownNames(sc)
	for {
		var key []byte
		p = odjsonrt.SkipSpace(data, p)
		kp := p
		idx := -1
		rest := data[p:]
		if len(rest) > 1 {
			switch rest[1] {
			case 't':
				if len(rest) >= 7 && string(rest[:7]) == "\"thing\"" {
					idx, p = 0, p+7
				}
			case 'p':
				if len(rest) >= 5 && string(rest[:5]) == "\"ptr\"" {
					idx, p = 1, p+5
				}
			case 'w':
				if len(rest) >= 9 && string(rest[:9]) == "\"wrapper\"" {
					idx, p = 2, p+9
				}
			case 'l':
				if len(rest) >= 6 && string(rest[:6]) == "\"list\"" {
					idx, p = 3, p+6
				}
			case 'm':
				if len(rest) >= 5 && string(rest[:5]) == "\"map\"" {
					idx, p = 4, p+5
				}
			case 'd':
				if len(rest) >= 6 && string(rest[:6]) == "\"deep\"" {
					idx, p = 5, p+6
				}
			}
		}
		if idx >= 0 {
			if np := odjsonrt.AfterName(data, p); np > 0 {
				p = np
			} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
				return p, err
			}
		} else {
			key, p, err = odjsonrt.ParseKeyV2(data, p, strict)
			if err != nil {
				return p, err
			}
			switch string(key) {
			case "thing":
				idx = 0
			case "ptr":
				idx = 1
			case "wrapper":
				idx = 2
			case "list":
				idx = 3
			case "map":
				idx = 4
			case "deep":
				idx = 5
			}
		}
		switch idx {
		case 0:
			if strict && seen[0]&(1<<0) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 0
			p, err = odjsonOtherThingParseV2(data, &v.Thing, p, sc, strict)
			if err != nil {
				return p, err
			}
		case 1:
			if strict && seen[0]&(1<<1) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 1
			if np24, ok25 := odjsonrt.ParseNull(data, p); ok25 {
				v.Ptr = nil
				p = np24
			} else {
				if v.Ptr == nil {
					v.Ptr = new(other.Thing)
				}
				p, err = odjsonOtherThingParseV2(data, v.Ptr, p, sc, strict)
				if err != nil {
					return p, err
				}
			}
		case 2:
			if strict && seen[0]&(1<<2) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 2
			p, err = odjsonOtherWrapperParseV2(data, &v.Wrapper, p, sc, strict)
			if err != nil {
				return p, err
			}
		case 3:
			if strict && seen[0]&(1<<3) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 3
			if np26, ok27 := odjsonrt.ParseNull(data, p); ok27 {
				p = np26
				v.List = nil
			} else {
				if p >= len(data) || data[p] != '[' {
					return p, odjsonrt.ErrType(data, p, "[]other.Thing")
				}
				p++
				s28 := v.List[:0]
				p = odjsonrt.SkipSpace(data, p)
				if p < len(data) && data[p] == ']' {
					p++
				} else {
					if cap(s28) == 0 {
						s28 = make([]other.Thing, 0, odjsonrt.CapFor[other.Thing](&odjsonCapHolderList))
					}
					for {
						var e29 other.Thing
						p, err = odjsonOtherThingParseV2(data, &e29, p, sc, strict)
						if err != nil {
							return p, err
						}
						s28 = append(s28, e29)
						p = odjsonrt.SkipSpace(data, p)
						if p >= len(data) {
							return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
						}
						if data[p] == ',' {
							p++
							continue
						}
						if data[p] == ']' {
							p++
							break
						}
						return p, odjsonrt.ErrSyntax(data, p, "after array element")
					}
					odjsonCapHolderList.Record(len(s28))
				}
				if s28 == nil {
					s28 = []other.Thing{}
				}
				v.List = s28
			}
		case 4:
			if strict && seen[0]&(1<<4) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 4
			if np30, ok31 := odjsonrt.ParseNull(data, p); ok31 {
				p = np30
				v.Map = nil
			} else {
				if p >= len(data) || data[p] != '{' {
					return p, odjsonrt.ErrType(data, p, "map[string]other.Thing")
				}
				p++
				m32 := v.Map
				if m32 == nil {
					m32 = make(map[string]other.Thing)
				}
				var seen35 map[string]struct{}
				if strict && len(m32) > 0 {
					seen35 = make(map[string]struct{})
				}
				p = odjsonrt.SkipSpace(data, p)
				if p < len(data) && data[p] == '}' {
					p++
				} else {
					for {
						var k33 []byte
						p = odjsonrt.SkipSpace(data, p)
						kp36 := p
						k33, p, err = odjsonrt.ParseKeyV2(data, p, strict)
						if err != nil {
							return p, err
						}
						if !strict {
						} else if seen35 == nil {
							if _, dup := m32[string(k33)]; dup {
								return p, odjsonrt.ErrDuplicateName(data, kp36, k33)
							}
						} else {
							if _, dup := seen35[string(k33)]; dup {
								return p, odjsonrt.ErrDuplicateName(data, kp36, k33)
							}
							seen35[string(k33)] = struct{}{}
						}
						var mv34 other.Thing
						p, err = odjsonOtherThingParseV2(data, &mv34, p, sc, strict)
						if err != nil {
							return p, err
						}
						m32[sc.Make(k33)] = mv34
						p = odjsonrt.SkipSpace(data, p)
						if p >= len(data) {
							return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
						}
						if data[p] == ',' {
							p++
							continue
						}
						if data[p] == '}' {
							p++
							break
						}
						return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
					}
				}
				v.Map = m32
			}
		case 5:
			if strict && seen[0]&(1<<5) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 5
			if np37, ok38 := odjsonrt.ParseNull(data, p); ok38 {
				p = np37
				v.Deep = nil
			} else {
				if p >= len(data) || data[p] != '[' {
					return p, odjsonrt.ErrType(data, p, "[]*other.Wrapper")
				}
				p++
				s39 := v.Deep[:0]
				p = odjsonrt.SkipSpace(data, p)
				if p < len(data) && data[p] == ']' {
					p++
				} else {
					if cap(s39) == 0 {
						s39 = make([]*other.Wrapper, 0, odjsonrt.CapFor[*other.Wrapper](&odjsonCapHolderDeep))
					}
					for {
						var e40 *other.Wrapper
						p = odjsonrt.SkipSpace(data, p)
						if np41, ok42 := odjsonrt.ParseNull(data, p); ok42 {
							e40 = nil
							p = np41
						} else {
							if e40 == nil {
								e40 = new(other.Wrapper)
							}
							p, err = odjsonOtherWrapperParseV2(data, e40, p, sc, strict)
							if err != nil {
								return p, err
							}
						}
						s39 = append(s39, e40)
						p = odjsonrt.SkipSpace(data, p)
						if p >= len(data) {
							return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
						}
						if data[p] == ',' {
							p++
							continue
						}
						if data[p] == ']' {
							p++
							break
						}
						return p, odjsonrt.ErrSyntax(data, p, "after array element")
					}
					odjsonCapHolderDeep.Record(len(s39))
				}
				if s39 == nil {
					s39 = []*other.Wrapper{}
				}
				v.Deep = s39
			}
		default:
			if strict {
				for _, u := range unknown[umark:] {
					if string(u) == string(key) {
						return kp, odjsonrt.ErrDuplicateName(data, kp, key)
					}
				}
				unknown = append(unknown, key)
			}
			p = odjsonrt.SkipSpace(data, p)
			p, err = odjsonrt.SkipValueV2(data, p, strict)
			if err != nil {
				return p, err
			}
		}
		p = odjsonrt.SkipSpace(data, p)
		if p >= len(data) {
			return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
		}
		switch data[p] {
		case ',':
			p++
		case '}':
			odjsonrt.EndUnknownNames(sc, unknown, umark)
			return p + 1, nil
		default:
			return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
		}
	}
}

// odjsonParseFrom decodes the next value in dec into v,
// driving the decoder token by token so the document is
// parsed once rather than twice.
func (v *Holder) odjsonParseFrom(dec *jsontext.Decoder, sc *odjsonrt.StringCache) error {
	var err error
	_ = err
	if odjsonrt.WholeValue(dec) {
		var val jsontext.Value
		if val, err = dec.ReadValue(); err != nil {
			return err
		}
		_, err = v.odjsonParseV2(val, 0, sc, false)
		return err
	}
	switch odjsonrt.NextKind(dec) {
	case 'n':
		if _, err = dec.ReadToken(); err != nil {
			return err
		}
		*v = Holder{}
		return nil
	case '{':
	default:
		return odjsonrt.ErrKindFrom(dec, "Holder")
	}
	if _, err = dec.ReadToken(); err != nil {
		return err
	}
	for odjsonrt.NextKind(dec) != '}' {
		var key jsontext.Value
		key, err = dec.ReadValue()
		if err != nil {
			return err
		}
		idx := -1
		switch string(key) {
		case "\"thing\"":
			idx = 0
		case "\"ptr\"":
			idx = 1
		case "\"wrapper\"":
			idx = 2
		case "\"list\"":
			idx = 3
		case "\"map\"":
			idx = 4
		case "\"deep\"":
			idx = 5
		}
		if idx < 0 && bytes.IndexByte(key, '\\') >= 0 {
			if name, ok := odjsonrt.UnquoteName(key); ok {
				switch string(name) {
				case "thing":
					idx = 0
				case "ptr":
					idx = 1
				case "wrapper":
					idx = 2
				case "list":
					idx = 3
				case "map":
					idx = 4
				case "deep":
					idx = 5
				}
			}
		}
		switch idx {
		case 0:
			if err = odjsonOtherThingParseFrom(dec, &v.Thing, sc); err != nil {
				return err
			}
		case 1:
			if odjsonrt.NextKind(dec) == 'n' {
				if _, err = dec.ReadToken(); err != nil {
					return err
				}
				v.Ptr = nil
			} else {
				if v.Ptr == nil {
					v.Ptr = new(other.Thing)
				}
				if err = odjsonOtherThingParseFrom(dec, v.Ptr, sc); err != nil {
					return err
				}
			}
		case 2:
			if err = odjsonOtherWrapperParseFrom(dec, &v.Wrapper, sc); err != nil {
				return err
			}
		case 3:
			switch odjsonrt.NextKind(dec) {
			case 'n':
				if _, err = dec.ReadToken(); err != nil {
					return err
				}
				v.List = nil
			case '[':
				if _, err = dec.ReadToken(); err != nil {
					return err
				}
				s43 := v.List[:0]
				if odjsonrt.NextKind(dec) != ']' && cap(s43) == 0 {
					s43 = make([]other.Thing, 0, odjsonrt.CapFor[other.Thing](&odjsonCapHolderList))
				}
				for odjsonrt.NextKind(dec) != ']' {
					var e44 other.Thing
					if err = odjsonOtherThingParseFrom(dec, &e44, sc); err != nil {
						return err
					}
					s43 = append(s43, e44)
				}
				if _, err = dec.ReadToken(); err != nil {
					return err
				}
				if len(s43) > 0 {
					odjsonCapHolderList.Record(len(s43))
				}
				if s43 == nil {
					s43 = []other.Thing{}
				}
				v.List = s43
			default:
				return odjsonrt.ErrKindFrom(dec, "[]other.Thing")
			}
		case 4:
			switch odjsonrt.NextKind(dec) {
			case 'n':
				if _, err = dec.ReadToken(); err != nil {
					return err
				}
				v.Map = nil
			case '{':
				if _, err = dec.ReadToken(); err != nil {
					return err
				}
				m45 := v.Map
				if m45 == nil {
					m45 = make(map[string]other.Thing)
				}
				for odjsonrt.NextKind(dec) != '}' {
					var k46 jsontext.Value
					k46, err = dec.ReadValue()
					if err != nil {
						return err
					}
					name47, ok48 := odjsonrt.UnquoteName(k46)
					if !ok48 {
						return odjsonrt.ErrSyntax(k46, 0, "invalid object name")
					}
					key49 := sc.Make(name47)
					var mv50 other.Thing
					if err = odjsonOtherThingParseFrom(dec, &mv50, sc); err != nil {
						return err
					}
					m45[key49] = mv50
				}
				if _, err = dec.ReadToken(); err != nil {
					return err
				}
				v.Map = m45
			default:
				return odjsonrt.ErrKindFrom(dec, "map[string]other.Thing")
			}
		case 5:
			switch odjsonrt.NextKind(dec) {
			case 'n':
				if _, err = dec.ReadToken(); err != nil {
					return err
				}
				v.Deep = nil
			case '[':
				if _, err = dec.ReadToken(); err != nil {
					return err
				}
				s51 := v.Deep[:0]
				if odjsonrt.NextKind(dec) != ']' && cap(s51) == 0 {
					s51 = make([]*other.Wrapper, 0, odjsonrt.CapFor[*other.Wrapper](&odjsonCapHolderDeep))
				}
				for odjsonrt.NextKind(dec) != ']' {
					var e52 *other.Wrapper
					if odjsonrt.NextKind(dec) == 'n' {
						if _, err = dec.ReadToken(); err != nil {
							return err
						}
						e52 = nil
					} else {
						if e52 == nil {
							e52 = new(other.Wrapper)
						}
						if err = odjsonOtherWrapperParseFrom(dec, e52, sc); err != nil {
							return err
						}
					}
					s51 = append(s51, e52)
				}
				if _, err = dec.ReadToken(); err != nil {
					return err
				}
				if len(s51) > 0 {
					odjsonCapHolderDeep.Record(len(s51))
				}
				if s51 == nil {
					s51 = []*other.Wrapper{}
				}
				v.Deep = s51
			default:
				return odjsonrt.ErrKindFrom(dec, "[]*other.Wrapper")
			}
		default:
			if _, err = dec.ReadValue(); err != nil {
				return err
			}
		}
	}
	_, err = dec.ReadToken()
	return err
}

// odjsonSizeHolder sizes the buffer the encoders allocate.
var odjsonSizeHolder odjsonrt.SizeHint

// MarshalJSON implements encoding/json.Marshaler.
func (v Holder) MarshalJSON() ([]byte, error) {
	buf, err := v.odjsonAppend(odjsonSizeHolder.New(), odjsonrt.ModeHTML)
	if err != nil {
		return nil, err
	}
	odjsonSizeHolder.Record(buf)
	return buf, nil
}

// UnmarshalJSON implements encoding/json.Unmarshaler.
func (v *Holder) UnmarshalJSON(data []byte) error {
	// The cache plays the part of encoding/json/v2's string cache: a
	// value that recurs in the document is allocated once.
	sc := odjsonrt.GetStringCache()
	p, err := v.odjsonParse(data, odjsonrt.SkipSpace(data, 0), sc)
	odjsonrt.PutStringCache(sc)
	if err != nil {
		return err
	}
	return odjsonrt.EndOfDocument(data, p)
}

// MarshalJSONTo implements encoding/json/v2.MarshalerTo.
func (v Holder) MarshalJSONTo(enc *jsontext.Encoder) error {
	// Under a plain json.Marshal, from encoding/json/v2 or encoding/json,
	// the value is appended straight into the encoder's buffer at any
	// depth; see odjsonrt.BeginDirectEncodeMode for what qualifies and
	// for the mode, which does that call's escaping itself since nothing
	// downstream looks at the bytes.
	if buf, m, ok := odjsonrt.BeginDirectEncodeMode(enc); ok {
		n := len(buf)
		buf, err := v.odjsonAppend(buf, m)
		if err != nil {
			return err
		}
		odjsonSizeHolder.Record(buf[n:])
		odjsonrt.EndDirectEncode(enc, buf)
		return nil
	}
	// Otherwise WriteValue copies what it is given, so the scratch buffer
	// can go straight back to the pool. ModeStream leaves the HTML escaping
	// and the UTF-8 validation to the encoder, which performs both while
	// reformatting the value either way.
	buf := odjsonrt.GetBuffer()
	var err error
	if buf.B, err = v.odjsonAppend(buf.B, odjsonrt.ModeStream); err == nil {
		odjsonSizeHolder.Record(buf.B)
		err = enc.WriteValue(buf.B)
	}
	odjsonrt.PutBuffer(buf)
	return err
}

// UnmarshalJSONFrom implements encoding/json/v2.UnmarshalerFrom.
func (v *Holder) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	// The cache plays the part of json/v2's own string cache: a value
	// that recurs in the document is allocated once.
	sc := odjsonrt.GetStringCache()
	var err error
	// Under a plain json.Unmarshal the value is parsed straight out of
	// the decoder's buffer at any depth; see odjsonrt.BeginDirectDecodeAt
	// for what qualifies. Nobody has validated those bytes, so
	// odjsonParseV2 rejects what jsontext would have.
	if data, p, ok := odjsonrt.BeginDirectDecodeAt(dec); ok {
		var end int
		if end, err = v.odjsonParseV2(data, p, sc, true); err == nil {
			odjsonrt.EndDirectDecodeAt(dec, p, end)
		}
	} else {
		err = v.odjsonParseFrom(dec, sc)
	}
	odjsonrt.PutStringCache(sc)
	return err
}

// odjsonOtherThingAppend appends the JSON encoding of v to dst.
func odjsonOtherThingAppend(dst []byte, v *other.Thing, m odjsonrt.StringMode) ([]byte, error) {
	var err error
	_ = err
	start := len(dst)
	dst = append(dst, ",\"id\":"...)
	dst = odjsonrt.AppendInt(dst, int64(v.ID))
	if len(v.Name) != 0 {
		dst = append(dst, ",\"name\":\""...)
		dst, err = odjsonrt.AppendStringBodyChecked(dst, string(v.Name), m)
		if err != nil {
			return nil, err
		}
		dst = append(dst, '"')
	}
	if len(dst) == start {
		dst = append(dst, '{', '}')
	} else {
		dst[start] = '{'
		dst = append(dst, '}')
	}
	return dst, nil
}

// odjsonOtherThingParse decodes the JSON object starting at p into v and
// returns the offset just past it. Strings are interned through
// sc, which may be nil.
func odjsonOtherThingParse(data []byte, v *other.Thing, p int, sc *odjsonrt.StringCache) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		return np, nil
	}
	if p >= len(data) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "other.Thing")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if p < len(data) && data[p] == '}' {
		return p + 1, nil
	}
	for {
		var key []byte
		p = odjsonrt.SkipSpace(data, p)
		idx := -1
		rest := data[p:]
		if len(rest) > 1 {
			switch rest[1] {
			case 'i':
				if len(rest) >= 4 && string(rest[:4]) == "\"id\"" {
					idx, p = 0, p+4
				}
			case 'n':
				if len(rest) >= 6 && string(rest[:6]) == "\"name\"" {
					idx, p = 1, p+6
				}
			}
		}
		if idx >= 0 {
			if np := odjsonrt.AfterName(data, p); np > 0 {
				p = np
			} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
				return p, err
			}
		} else {
			key, _, p, err = odjsonrt.ParseKey(data, p)
			if err != nil {
				return p, err
			}
			switch string(key) {
			case "id":
				idx = 0
			case "name":
				idx = 1
			}
		}
		switch idx {
		case 0:
			if np53, ok54 := odjsonrt.ParseNull(data, p); ok54 {
				p = np53
			} else {
				if x55, np56, ok57 := odjsonrt.ParseDecimal(data, p); ok57 {
					v.ID = int(x55)
					p = np56
				} else {
					var x58 int64
					x58, p, err = odjsonrt.ParseInt(data, p, 64)
					if err != nil {
						return p, err
					}
					v.ID = int(x58)
				}
			}
		case 1:
			if np59, ok60 := odjsonrt.ParseNull(data, p); ok60 {
				p = np59
			} else {
				var x61 string
				x61, p, err = odjsonrt.ParseStringCached(data, p, sc)
				if err != nil {
					return p, err
				}
				v.Name = x61
			}
		default:
			p = odjsonrt.SkipSpace(data, p)
			p, err = odjsonrt.SkipValue(data, p)
			if err != nil {
				return p, err
			}
		}
		p = odjsonrt.SkipSpace(data, p)
		if p >= len(data) {
			return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
		}
		switch data[p] {
		case ',':
			p++
		case '}':
			return p + 1, nil
		default:
			return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
		}
	}
}

// odjsonOtherThingParseV2 is odjsonOtherThingParse under encoding/json/v2's semantics, for
// input a jsontext.Decoder has already validated when strict is false,
// and for bytes nobody has looked at when it is true.
func odjsonOtherThingParseV2(data []byte, v *other.Thing, p int, sc *odjsonrt.StringCache, strict bool) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		*v = other.Thing{}
		return np, nil
	}
	if p >= len(data) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "other.Thing")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if p < len(data) && data[p] == '}' {
		return p + 1, nil
	}
	var seen [1]uint64
	_ = seen
	unknown, umark := odjsonrt.UnknownNames(sc)
	for {
		var key []byte
		p = odjsonrt.SkipSpace(data, p)
		kp := p
		idx := -1
		rest := data[p:]
		if len(rest) > 1 {
			switch rest[1] {
			case 'i':
				if len(rest) >= 4 && string(rest[:4]) == "\"id\"" {
					idx, p = 0, p+4
				}
			case 'n':
				if len(rest) >= 6 && string(rest[:6]) == "\"name\"" {
					idx, p = 1, p+6
				}
			}
		}
		if idx >= 0 {
			if np := odjsonrt.AfterName(data, p); np > 0 {
				p = np
			} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
				return p, err
			}
		} else {
			key, p, err = odjsonrt.ParseKeyV2(data, p, strict)
			if err != nil {
				return p, err
			}
			switch string(key) {
			case "id":
				idx = 0
			case "name":
				idx = 1
			}
		}
		switch idx {
		case 0:
			if strict && seen[0]&(1<<0) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 0
			if np62, ok63 := odjsonrt.ParseNull(data, p); ok63 {
				p = np62
				v.ID = 0
			} else {
				if x64, np65, ok66 := odjsonrt.ParseDecimal(data, p); ok66 {
					v.ID = int(x64)
					p = np65
				} else {
					var x67 int64
					x67, p, err = odjsonrt.ParseInt(data, p, 64)
					if err != nil {
						return p, err
					}
					v.ID = int(x67)
				}
			}
		case 1:
			if strict && seen[0]&(1<<1) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 1
			if np68, ok69 := odjsonrt.ParseNull(data, p); ok69 {
				p = np68
				v.Name = ""
			} else {
				var x70 string
				x70, p, err = odjsonrt.ParseStringV2(data, p, sc, strict)
				if err != nil {
					return p, err
				}
				v.Name = x70
			}
		default:
			if strict {
				for _, u := range unknown[umark:] {
					if string(u) == string(key) {
						return kp, odjsonrt.ErrDuplicateName(data, kp, key)
					}
				}
				unknown = append(unknown, key)
			}
			p = odjsonrt.SkipSpace(data, p)
			p, err = odjsonrt.SkipValueV2(data, p, strict)
			if err != nil {
				return p, err
			}
		}
		p = odjsonrt.SkipSpace(data, p)
		if p >= len(data) {
			return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
		}
		switch data[p] {
		case ',':
			p++
		case '}':
			odjsonrt.EndUnknownNames(sc, unknown, umark)
			return p + 1, nil
		default:
			return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
		}
	}
}

// odjsonOtherThingParseFrom decodes the next value in dec into v,
// driving the decoder token by token so the document is
// parsed once rather than twice.
func odjsonOtherThingParseFrom(dec *jsontext.Decoder, v *other.Thing, sc *odjsonrt.StringCache) error {
	var err error
	_ = err
	if odjsonrt.WholeValue(dec) {
		var val jsontext.Value
		if val, err = dec.ReadValue(); err != nil {
			return err
		}
		_, err = odjsonOtherThingParseV2(val, v, 0, sc, false)
		return err
	}
	switch odjsonrt.NextKind(dec) {
	case 'n':
		if _, err = dec.ReadToken(); err != nil {
			return err
		}
		*v = other.Thing{}
		return nil
	case '{':
	default:
		return odjsonrt.ErrKindFrom(dec, "other.Thing")
	}
	if _, err = dec.ReadToken(); err != nil {
		return err
	}
	for odjsonrt.NextKind(dec) != '}' {
		var key jsontext.Value
		key, err = dec.ReadValue()
		if err != nil {
			return err
		}
		idx := -1
		switch string(key) {
		case "\"id\"":
			idx = 0
		case "\"name\"":
			idx = 1
		}
		if idx < 0 && bytes.IndexByte(key, '\\') >= 0 {
			if name, ok := odjsonrt.UnquoteName(key); ok {
				switch string(name) {
				case "id":
					idx = 0
				case "name":
					idx = 1
				}
			}
		}
		switch idx {
		case 0:
			var val71 jsontext.Value
			val71, err = dec.ReadValue()
			if err != nil {
				return err
			}
			if val71[0] == 'n' {
				v.ID = 0
			} else {
				var x72 int64
				x72, _, err = odjsonrt.ParseInt(val71, 0, 64)
				if err != nil {
					return err
				}
				v.ID = int(x72)
			}
		case 1:
			var val73 jsontext.Value
			val73, err = dec.ReadValue()
			if err != nil {
				return err
			}
			if val73[0] == 'n' {
				v.Name = ""
			} else {
				var x74 string
				x74, err = odjsonrt.ParseStringValue(val73, sc)
				if err != nil {
					return err
				}
				v.Name = x74
			}
		default:
			if _, err = dec.ReadValue(); err != nil {
				return err
			}
		}
	}
	_, err = dec.ReadToken()
	return err
}

// odjsonOtherWrapperAppend appends the JSON encoding of v to dst.
func odjsonOtherWrapperAppend(dst []byte, v *other.Wrapper, m odjsonrt.StringMode) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, "{\"thing\":"...)
	dst, err = odjsonOtherThingAppend(dst, &v.Thing, m)
	if err != nil {
		return nil, err
	}
	dst = append(dst, ",\"ptr\":"...)
	if v.Ptr == nil {
		dst = append(dst, 'n', 'u', 'l', 'l')
	} else {
		dst, err = odjsonOtherThingAppend(dst, v.Ptr, m)
		if err != nil {
			return nil, err
		}
	}
	dst = append(dst, ",\"list\":"...)
	if v.List == nil {
		dst = odjsonrt.AppendNilSlice(dst, m)
	} else {
		dst = append(dst, '[')
		for i75 := range v.List {
			if i75 > 0 {
				dst = append(dst, ',')
			}
			dst, err = odjsonOtherThingAppend(dst, &v.List[i75], m)
			if err != nil {
				return nil, err
			}
		}
		dst = append(dst, ']')
	}
	dst = append(dst, "}"...)
	return dst, nil
}

// odjsonCapodjsonOtherWrapperList remembers how long v.List has been, to allocate it once.
var odjsonCapodjsonOtherWrapperList odjsonrt.CapHint

// odjsonOtherWrapperParse decodes the JSON object starting at p into v and
// returns the offset just past it. Strings are interned through
// sc, which may be nil.
func odjsonOtherWrapperParse(data []byte, v *other.Wrapper, p int, sc *odjsonrt.StringCache) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		return np, nil
	}
	if p >= len(data) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "other.Wrapper")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if p < len(data) && data[p] == '}' {
		return p + 1, nil
	}
	for {
		var key []byte
		p = odjsonrt.SkipSpace(data, p)
		idx := -1
		rest := data[p:]
		if len(rest) > 1 {
			switch rest[1] {
			case 't':
				if len(rest) >= 7 && string(rest[:7]) == "\"thing\"" {
					idx, p = 0, p+7
				}
			case 'p':
				if len(rest) >= 5 && string(rest[:5]) == "\"ptr\"" {
					idx, p = 1, p+5
				}
			case 'l':
				if len(rest) >= 6 && string(rest[:6]) == "\"list\"" {
					idx, p = 2, p+6
				}
			}
		}
		if idx >= 0 {
			if np := odjsonrt.AfterName(data, p); np > 0 {
				p = np
			} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
				return p, err
			}
		} else {
			key, _, p, err = odjsonrt.ParseKey(data, p)
			if err != nil {
				return p, err
			}
			switch string(key) {
			case "thing":
				idx = 0
			case "ptr":
				idx = 1
			case "list":
				idx = 2
			}
		}
		switch idx {
		case 0:
			p, err = odjsonOtherThingParse(data, &v.Thing, p, sc)
			if err != nil {
				return p, err
			}
		case 1:
			if np76, ok77 := odjsonrt.ParseNull(data, p); ok77 {
				v.Ptr = nil
				p = np76
			} else {
				if v.Ptr == nil {
					v.Ptr = new(other.Thing)
				}
				p, err = odjsonOtherThingParse(data, v.Ptr, p, sc)
				if err != nil {
					return p, err
				}
			}
		case 2:
			if np78, ok79 := odjsonrt.ParseNull(data, p); ok79 {
				p = np78
				v.List = nil
			} else {
				if p >= len(data) || data[p] != '[' {
					return p, odjsonrt.ErrType(data, p, "[]other.Thing")
				}
				p++
				s80 := v.List[:0]
				p = odjsonrt.SkipSpace(data, p)
				if p < len(data) && data[p] == ']' {
					p++
				} else {
					if cap(s80) == 0 {
						s80 = make([]other.Thing, 0, odjsonrt.CapFor[other.Thing](&odjsonCapodjsonOtherWrapperList))
					}
					for {
						var e81 other.Thing
						p, err = odjsonOtherThingParse(data, &e81, p, sc)
						if err != nil {
							return p, err
						}
						s80 = append(s80, e81)
						p = odjsonrt.SkipSpace(data, p)
						if p >= len(data) {
							return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
						}
						if data[p] == ',' {
							p++
							continue
						}
						if data[p] == ']' {
							p++
							break
						}
						return p, odjsonrt.ErrSyntax(data, p, "after array element")
					}
					odjsonCapodjsonOtherWrapperList.Record(len(s80))
				}
				if s80 == nil {
					s80 = []other.Thing{}
				}
				v.List = s80
			}
		default:
			p = odjsonrt.SkipSpace(data, p)
			p, err = odjsonrt.SkipValue(data, p)
			if err != nil {
				return p, err
			}
		}
		p = odjsonrt.SkipSpace(data, p)
		if p >= len(data) {
			return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
		}
		switch data[p] {
		case ',':
			p++
		case '}':
			return p + 1, nil
		default:
			return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
		}
	}
}

// odjsonOtherWrapperParseV2 is odjsonOtherWrapperParse under encoding/json/v2's semantics, for
// input a jsontext.Decoder has already validated when strict is false,
// and for bytes nobody has looked at when it is true.
func odjsonOtherWrapperParseV2(data []byte, v *other.Wrapper, p int, sc *odjsonrt.StringCache, strict bool) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		*v = other.Wrapper{}
		return np, nil
	}
	if p >= len(data) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "other.Wrapper")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if p < len(data) && data[p] == '}' {
		return p + 1, nil
	}
	var seen [1]uint64
	_ = seen
	unknown, umark := odjsonrt.UnknownNames(sc)
	for {
		var key []byte
		p = odjsonrt.SkipSpace(data, p)
		kp := p
		idx := -1
		rest := data[p:]
		if len(rest) > 1 {
			switch rest[1] {
			case 't':
				if len(rest) >= 7 && string(rest[:7]) == "\"thing\"" {
					idx, p = 0, p+7
				}
			case 'p':
				if len(rest) >= 5 && string(rest[:5]) == "\"ptr\"" {
					idx, p = 1, p+5
				}
			case 'l':
				if len(rest) >= 6 && string(rest[:6]) == "\"list\"" {
					idx, p = 2, p+6
				}
			}
		}
		if idx >= 0 {
			if np := odjsonrt.AfterName(data, p); np > 0 {
				p = np
			} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
				return p, err
			}
		} else {
			key, p, err = odjsonrt.ParseKeyV2(data, p, strict)
			if err != nil {
				return p, err
			}
			switch string(key) {
			case "thing":
				idx = 0
			case "ptr":
				idx = 1
			case "list":
				idx = 2
			}
		}
		switch idx {
		case 0:
			if strict && seen[0]&(1<<0) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 0
			p, err = odjsonOtherThingParseV2(data, &v.Thing, p, sc, strict)
			if err != nil {
				return p, err
			}
		case 1:
			if strict && seen[0]&(1<<1) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 1
			if np82, ok83 := odjsonrt.ParseNull(data, p); ok83 {
				v.Ptr = nil
				p = np82
			} else {
				if v.Ptr == nil {
					v.Ptr = new(other.Thing)
				}
				p, err = odjsonOtherThingParseV2(data, v.Ptr, p, sc, strict)
				if err != nil {
					return p, err
				}
			}
		case 2:
			if strict && seen[0]&(1<<2) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 2
			if np84, ok85 := odjsonrt.ParseNull(data, p); ok85 {
				p = np84
				v.List = nil
			} else {
				if p >= len(data) || data[p] != '[' {
					return p, odjsonrt.ErrType(data, p, "[]other.Thing")
				}
				p++
				s86 := v.List[:0]
				p = odjsonrt.SkipSpace(data, p)
				if p < len(data) && data[p] == ']' {
					p++
				} else {
					if cap(s86) == 0 {
						s86 = make([]other.Thing, 0, odjsonrt.CapFor[other.Thing](&odjsonCapodjsonOtherWrapperList))
					}
					for {
						var e87 other.Thing
						p, err = odjsonOtherThingParseV2(data, &e87, p, sc, strict)
						if err != nil {
							return p, err
						}
						s86 = append(s86, e87)
						p = odjsonrt.SkipSpace(data, p)
						if p >= len(data) {
							return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
						}
						if data[p] == ',' {
							p++
							continue
						}
						if data[p] == ']' {
							p++
							break
						}
						return p, odjsonrt.ErrSyntax(data, p, "after array element")
					}
					odjsonCapodjsonOtherWrapperList.Record(len(s86))
				}
				if s86 == nil {
					s86 = []other.Thing{}
				}
				v.List = s86
			}
		default:
			if strict {
				for _, u := range unknown[umark:] {
					if string(u) == string(key) {
						return kp, odjsonrt.ErrDuplicateName(data, kp, key)
					}
				}
				unknown = append(unknown, key)
			}
			p = odjsonrt.SkipSpace(data, p)
			p, err = odjsonrt.SkipValueV2(data, p, strict)
			if err != nil {
				return p, err
			}
		}
		p = odjsonrt.SkipSpace(data, p)
		if p >= len(data) {
			return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
		}
		switch data[p] {
		case ',':
			p++
		case '}':
			odjsonrt.EndUnknownNames(sc, unknown, umark)
			return p + 1, nil
		default:
			return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
		}
	}
}

// odjsonOtherWrapperParseFrom decodes the next value in dec into v,
// driving the decoder token by token so the document is
// parsed once rather than twice.
func odjsonOtherWrapperParseFrom(dec *jsontext.Decoder, v *other.Wrapper, sc *odjsonrt.StringCache) error {
	var err error
	_ = err
	if odjsonrt.WholeValue(dec) {
		var val jsontext.Value
		if val, err = dec.ReadValue(); err != nil {
			return err
		}
		_, err = odjsonOtherWrapperParseV2(val, v, 0, sc, false)
		return err
	}
	switch odjsonrt.NextKind(dec) {
	case 'n':
		if _, err = dec.ReadToken(); err != nil {
			return err
		}
		*v = other.Wrapper{}
		return nil
	case '{':
	default:
		return odjsonrt.ErrKindFrom(dec, "other.Wrapper")
	}
	if _, err = dec.ReadToken(); err != nil {
		return err
	}
	for odjsonrt.NextKind(dec) != '}' {
		var key jsontext.Value
		key, err = dec.ReadValue()
		if err != nil {
			return err
		}
		idx := -1
		switch string(key) {
		case "\"thing\"":
			idx = 0
		case "\"ptr\"":
			idx = 1
		case "\"list\"":
			idx = 2
		}
		if idx < 0 && bytes.IndexByte(key, '\\') >= 0 {
			if name, ok := odjsonrt.UnquoteName(key); ok {
				switch string(name) {
				case "thing":
					idx = 0
				case "ptr":
					idx = 1
				case "list":
					idx = 2
				}
			}
		}
		switch idx {
		case 0:
			if err = odjsonOtherThingParseFrom(dec, &v.Thing, sc); err != nil {
				return err
			}
		case 1:
			if odjsonrt.NextKind(dec) == 'n' {
				if _, err = dec.ReadToken(); err != nil {
					return err
				}
				v.Ptr = nil
			} else {
				if v.Ptr == nil {
					v.Ptr = new(other.Thing)
				}
				if err = odjsonOtherThingParseFrom(dec, v.Ptr, sc); err != nil {
					return err
				}
			}
		case 2:
			switch odjsonrt.NextKind(dec) {
			case 'n':
				if _, err = dec.ReadToken(); err != nil {
					return err
				}
				v.List = nil
			case '[':
				if _, err = dec.ReadToken(); err != nil {
					return err
				}
				s88 := v.List[:0]
				if odjsonrt.NextKind(dec) != ']' && cap(s88) == 0 {
					s88 = make([]other.Thing, 0, odjsonrt.CapFor[other.Thing](&odjsonCapodjsonOtherWrapperList))
				}
				for odjsonrt.NextKind(dec) != ']' {
					var e89 other.Thing
					if err = odjsonOtherThingParseFrom(dec, &e89, sc); err != nil {
						return err
					}
					s88 = append(s88, e89)
				}
				if _, err = dec.ReadToken(); err != nil {
					return err
				}
				if len(s88) > 0 {
					odjsonCapodjsonOtherWrapperList.Record(len(s88))
				}
				if s88 == nil {
					s88 = []other.Thing{}
				}
				v.List = s88
			default:
				return odjsonrt.ErrKindFrom(dec, "[]other.Thing")
			}
		default:
			if _, err = dec.ReadValue(); err != nil {
				return err
			}
		}
	}
	_, err = dec.ReadToken()
	return err
}
