// Code generated by odjson. DO NOT EDIT.
//
// Source: odjson

package crosspkg

import (
	"bytes"
	"encoding/json/jsontext"
	"github.com/mazrean/odjson/internal/testfixture/other"
	"github.com/mazrean/odjson/odjsonrt"
	"slices"
)

// odjsonAppend appends the JSON encoding of v to dst.
func (v *Holder) odjsonAppend(dst []byte, m odjsonrt.StringMode) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, "{\"thing\":"...)
	dst, err = odjsonOtherThingAppend(dst, &v.Thing, m)
	if err != nil {
		return nil, err
	}
	if v.Ptr == nil {
		dst = append(dst, ",\"ptr\":null,\"wra"...)
		dst = append(dst, "pper\":"...)
	} else {
		dst = append(dst, ",\"ptr\":"...)
		dst, err = odjsonOtherThingAppend(dst, v.Ptr, m)
		if err != nil {
			return nil, err
		}
		dst = append(dst, ",\"wrapper\":"...)
	}
	dst, err = odjsonOtherWrapperAppend(dst, &v.Wrapper, m)
	if err != nil {
		return nil, err
	}
	if v.List == nil {
		if m.V2() {
			dst = append(dst, ",\"list\":[],\"map\""...)
			dst = append(dst, ":"...)
		} else {
			dst = append(dst, ",\"list\":null,\"ma"...)
			dst = append(dst, "p\":"...)
		}
	} else {
		dst = append(dst, ",\"list\":["...)
		for i1 := range v.List {
			if i1 > 0 {
				dst = append(dst, ',')
			}
			dst, err = odjsonOtherThingAppend(dst, &v.List[i1], m)
			if err != nil {
				return nil, err
			}
		}
		dst = append(dst, "],\"map\":"...)
	}
	if v.Map == nil {
		if m.V2() {
			dst = append(dst, "{},\"deep\":"...)
		} else {
			dst = append(dst, "null,\"deep\":"...)
		}
	} else {
		keys2 := make([]string, 0, len(v.Map))
		for k3 := range v.Map {
			keys2 = append(keys2, string(k3))
		}
		if m != odjsonrt.ModeV2 {
			slices.Sort(keys2)
		}
		dst = append(dst, "{"...)
		for i4, k3 := range keys2 {
			if i4 > 0 {
				dst = append(dst, ',')
			}
			dst = append(dst, '"')
			dst, err = odjsonrt.AppendStringBodyChecked(dst, k3, m)
			if err != nil {
				return nil, err
			}
			mv5 := v.Map[k3]
			dst = append(dst, "\":"...)
			dst, err = odjsonOtherThingAppend(dst, &mv5, m)
			if err != nil {
				return nil, err
			}
		}
		dst = append(dst, "},\"deep\":"...)
	}
	if v.Deep == nil {
		if m.V2() {
			dst = append(dst, "[]}"...)
		} else {
			dst = append(dst, "null}"...)
		}
	} else {
		dst = append(dst, "["...)
		for i6 := range v.Deep {
			if i6 > 0 {
				dst = append(dst, ',')
			}
			if v.Deep[i6] == nil {
				dst = append(dst, "null"...)
			} else {
				dst, err = odjsonOtherWrapperAppend(dst, v.Deep[i6], m)
				if err != nil {
					return nil, err
				}
			}
		}
		dst = append(dst, "]}"...)
	}
	return dst, nil
}

// odjsonCapHolderList remembers how long v.List has been, to allocate it once.
var odjsonCapHolderList odjsonrt.CapHint

// odjsonCapHolderDeep remembers how long v.Deep has been, to allocate it once.
var odjsonCapHolderDeep odjsonrt.CapHint

// odjsonParse decodes the JSON object starting at p into v and
// returns the offset just past it. Strings are interned through
// sc, which may be nil.
func (v *Holder) odjsonParse(data []byte, p int, sc *odjsonrt.StringCache) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		return np, nil
	}
	if uint(p) >= uint(len(data)) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "Holder")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if uint(p) < uint(len(data)) && data[p] == '}' {
		return p + 1, nil
	}
	for {
		if uint(p) >= uint(len(data)) || data[p] <= ' ' {
			p = odjsonrt.SkipSpace(data, odjsonrt.SkipIndent(data, p))
		}
		rest := data[p:]
		if len(rest) > 1 {
			switch rest[1] {
			case 't':
				if len(rest) >= 7 && string(rest[:7]) == "\"thing\"" {
					p += 7
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m7
				}
			case 'p':
				if len(rest) >= 5 && string(rest[:5]) == "\"ptr\"" {
					p += 5
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m8
				}
			case 'w':
				if len(rest) >= 9 && string(rest[:9]) == "\"wrapper\"" {
					p += 9
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m9
				}
			case 'l':
				if len(rest) >= 6 && string(rest[:6]) == "\"list\"" {
					p += 6
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m10
				}
			case 'm':
				if len(rest) >= 5 && string(rest[:5]) == "\"map\"" {
					p += 5
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m11
				}
			case 'd':
				if len(rest) >= 6 && string(rest[:6]) == "\"deep\"" {
					p += 6
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m12
				}
			}
		}
		{
			var key []byte
			key, _, p, err = odjsonrt.ParseKey(data, p)
			if err != nil {
				return p, err
			}
			switch string(key) {
			case "thing":
				goto m7
			case "ptr":
				goto m8
			case "wrapper":
				goto m9
			case "list":
				goto m10
			case "map":
				goto m11
			case "deep":
				goto m12
			}
			p = odjsonrt.SkipSpace(data, p)
			p, err = odjsonrt.SkipValue(data, p)
			if err != nil {
				return p, err
			}
			goto next13
		}
	m7:
		{
			p, err = odjsonOtherThingParse(data, &v.Thing, p, sc)
			if err != nil {
				return p, err
			}
			goto next13
		}
	m8:
		{
			if np14, ok15 := odjsonrt.ParseNull(data, p); ok15 {
				v.Ptr = nil
				p = np14
			} else {
				if v.Ptr == nil {
					v.Ptr = new(other.Thing)
				}
				p, err = odjsonOtherThingParse(data, v.Ptr, p, sc)
				if err != nil {
					return p, err
				}
			}
			goto next13
		}
	m9:
		{
			p, err = odjsonOtherWrapperParse(data, &v.Wrapper, p, sc)
			if err != nil {
				return p, err
			}
			goto next13
		}
	m10:
		{
			if np16, ok17 := odjsonrt.ParseNull(data, p); ok17 {
				p = np16
				v.List = nil
			} else {
				if uint(p) >= uint(len(data)) || data[p] != '[' {
					return p, odjsonrt.ErrType(data, p, "[]other.Thing")
				}
				p++
				s18 := v.List[:0]
				p = odjsonrt.SkipSpace(data, p)
				if uint(p) < uint(len(data)) && data[p] == ']' {
					p++
				} else {
					if cap(s18) == 0 {
						s18 = make([]other.Thing, 0, odjsonrt.CapFor[other.Thing](&odjsonCapHolderList))
					}
					for {
						var e19 other.Thing
						if uint(p) >= uint(len(data)) || data[p] <= ' ' {
							p = odjsonrt.SkipSpace(data, odjsonrt.SkipIndent(data, p))
						}
						p, err = odjsonOtherThingParse(data, &e19, p, sc)
						if err != nil {
							return p, err
						}
						s18 = append(s18, e19)
						p = odjsonrt.SkipSpace(data, p)
						if uint(p) >= uint(len(data)) {
							return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
						}
						if data[p] == ',' {
							p++
							continue
						}
						if data[p] == ']' {
							p++
							break
						}
						return p, odjsonrt.ErrSyntax(data, p, "after array element")
					}
					odjsonCapHolderList.Record(len(s18))
				}
				if s18 == nil {
					s18 = []other.Thing{}
				}
				v.List = s18
			}
			goto next13
		}
	m11:
		{
			if np20, ok21 := odjsonrt.ParseNull(data, p); ok21 {
				p = np20
				v.Map = nil
			} else {
				if uint(p) >= uint(len(data)) || data[p] != '{' {
					return p, odjsonrt.ErrType(data, p, "map[string]other.Thing")
				}
				p++
				m22 := v.Map
				if m22 == nil {
					m22 = make(map[string]other.Thing)
				}
				p = odjsonrt.SkipSpace(data, p)
				if uint(p) < uint(len(data)) && data[p] == '}' {
					p++
				} else {
					for {
						var k23 []byte
						p = odjsonrt.SkipSpace(data, p)
						k23, _, p, err = odjsonrt.ParseKey(data, p)
						if err != nil {
							return p, err
						}
						var mv24 other.Thing
						p, err = odjsonOtherThingParse(data, &mv24, p, sc)
						if err != nil {
							return p, err
						}
						m22[sc.Make(k23)] = mv24
						p = odjsonrt.SkipSpace(data, p)
						if uint(p) >= uint(len(data)) {
							return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
						}
						if data[p] == ',' {
							p++
							continue
						}
						if data[p] == '}' {
							p++
							break
						}
						return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
					}
				}
				v.Map = m22
			}
			goto next13
		}
	m12:
		{
			if np26, ok27 := odjsonrt.ParseNull(data, p); ok27 {
				p = np26
				v.Deep = nil
			} else {
				if uint(p) >= uint(len(data)) || data[p] != '[' {
					return p, odjsonrt.ErrType(data, p, "[]*other.Wrapper")
				}
				p++
				s28 := v.Deep[:0]
				p = odjsonrt.SkipSpace(data, p)
				if uint(p) < uint(len(data)) && data[p] == ']' {
					p++
				} else {
					if cap(s28) == 0 {
						s28 = make([]*other.Wrapper, 0, odjsonrt.CapFor[*other.Wrapper](&odjsonCapHolderDeep))
					}
					for {
						var e29 *other.Wrapper
						if uint(p) >= uint(len(data)) || data[p] <= ' ' {
							p = odjsonrt.SkipSpace(data, odjsonrt.SkipIndent(data, p))
						}
						if np30, ok31 := odjsonrt.ParseNull(data, p); ok31 {
							e29 = nil
							p = np30
						} else {
							if e29 == nil {
								e29 = new(other.Wrapper)
							}
							p, err = odjsonOtherWrapperParse(data, e29, p, sc)
							if err != nil {
								return p, err
							}
						}
						s28 = append(s28, e29)
						p = odjsonrt.SkipSpace(data, p)
						if uint(p) >= uint(len(data)) {
							return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
						}
						if data[p] == ',' {
							p++
							continue
						}
						if data[p] == ']' {
							p++
							break
						}
						return p, odjsonrt.ErrSyntax(data, p, "after array element")
					}
					odjsonCapHolderDeep.Record(len(s28))
				}
				if s28 == nil {
					s28 = []*other.Wrapper{}
				}
				v.Deep = s28
			}
		}
	next13:
		{
			p = odjsonrt.SkipSpace(data, p)
			if uint(p) >= uint(len(data)) {
				return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
			}
			switch data[p] {
			case ',':
				p++
			case '}':
				return p + 1, nil
			default:
				return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
			}
		}
	}
}

// odjsonParseV2 is odjsonParse under encoding/json/v2's semantics, for
// input a jsontext.Decoder has already validated when strict is false,
// and for bytes nobody has looked at when it is true.
func (v *Holder) odjsonParseV2(data []byte, p int, sc *odjsonrt.StringCache, strict bool) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		*v = Holder{}
		return np, nil
	}
	if uint(p) >= uint(len(data)) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "Holder")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if uint(p) < uint(len(data)) && data[p] == '}' {
		return p + 1, nil
	}
	var seen [1]uint64
	_ = seen
	unknown, umark := odjsonrt.UnknownNames(sc)
	var ufilter uint64
	_ = ufilter
	for {
		if uint(p) >= uint(len(data)) || data[p] <= ' ' {
			p = odjsonrt.SkipSpace(data, odjsonrt.SkipIndent(data, p))
		}
		kp := p
		rest := data[p:]
		if len(rest) > 1 {
			switch rest[1] {
			case 't':
				if len(rest) >= 7 && string(rest[:7]) == "\"thing\"" {
					p += 7
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m32
				}
			case 'p':
				if len(rest) >= 5 && string(rest[:5]) == "\"ptr\"" {
					p += 5
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m33
				}
			case 'w':
				if len(rest) >= 9 && string(rest[:9]) == "\"wrapper\"" {
					p += 9
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m34
				}
			case 'l':
				if len(rest) >= 6 && string(rest[:6]) == "\"list\"" {
					p += 6
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m35
				}
			case 'm':
				if len(rest) >= 5 && string(rest[:5]) == "\"map\"" {
					p += 5
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m36
				}
			case 'd':
				if len(rest) >= 6 && string(rest[:6]) == "\"deep\"" {
					p += 6
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m37
				}
			}
		}
		{
			var key []byte
			key, p, err = odjsonrt.ParseKeyV2(data, p, strict)
			if err != nil {
				return p, err
			}
			switch string(key) {
			case "thing":
				goto m32
			case "ptr":
				goto m33
			case "wrapper":
				goto m34
			case "list":
				goto m35
			case "map":
				goto m36
			case "deep":
				goto m37
			}
			if strict {
				var dup bool
				if unknown, dup = odjsonrt.UnknownName(sc, unknown, umark, &ufilter, key); dup {
					return kp, odjsonrt.ErrDuplicateName(data, kp, key)
				}
			}
			p = odjsonrt.SkipSpace(data, p)
			p, err = odjsonrt.SkipValueV2(data, p, strict)
			if err != nil {
				return p, err
			}
			goto next38
		}
	m32:
		{
			if strict && seen[0]&(1<<0) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 0
			p, err = odjsonOtherThingParseV2(data, &v.Thing, p, sc, strict)
			if err != nil {
				return p, err
			}
			goto next38
		}
	m33:
		{
			if strict && seen[0]&(1<<1) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 1
			if np39, ok40 := odjsonrt.ParseNull(data, p); ok40 {
				v.Ptr = nil
				p = np39
			} else {
				if v.Ptr == nil {
					v.Ptr = new(other.Thing)
				}
				p, err = odjsonOtherThingParseV2(data, v.Ptr, p, sc, strict)
				if err != nil {
					return p, err
				}
			}
			goto next38
		}
	m34:
		{
			if strict && seen[0]&(1<<2) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 2
			p, err = odjsonOtherWrapperParseV2(data, &v.Wrapper, p, sc, strict)
			if err != nil {
				return p, err
			}
			goto next38
		}
	m35:
		{
			if strict && seen[0]&(1<<3) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 3
			if np41, ok42 := odjsonrt.ParseNull(data, p); ok42 {
				p = np41
				v.List = nil
			} else {
				if uint(p) >= uint(len(data)) || data[p] != '[' {
					return p, odjsonrt.ErrType(data, p, "[]other.Thing")
				}
				p++
				s43 := v.List[:0]
				p = odjsonrt.SkipSpace(data, p)
				if uint(p) < uint(len(data)) && data[p] == ']' {
					p++
				} else {
					if cap(s43) == 0 {
						s43 = make([]other.Thing, 0, odjsonrt.CapFor[other.Thing](&odjsonCapHolderList))
					}
					for {
						var e44 other.Thing
						if uint(p) >= uint(len(data)) || data[p] <= ' ' {
							p = odjsonrt.SkipSpace(data, odjsonrt.SkipIndent(data, p))
						}
						p, err = odjsonOtherThingParseV2(data, &e44, p, sc, strict)
						if err != nil {
							return p, err
						}
						s43 = append(s43, e44)
						p = odjsonrt.SkipSpace(data, p)
						if uint(p) >= uint(len(data)) {
							return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
						}
						if data[p] == ',' {
							p++
							continue
						}
						if data[p] == ']' {
							p++
							break
						}
						return p, odjsonrt.ErrSyntax(data, p, "after array element")
					}
					odjsonCapHolderList.Record(len(s43))
				}
				if s43 == nil {
					s43 = []other.Thing{}
				}
				v.List = s43
			}
			goto next38
		}
	m36:
		{
			if strict && seen[0]&(1<<4) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 4
			if np45, ok46 := odjsonrt.ParseNull(data, p); ok46 {
				p = np45
				v.Map = nil
			} else {
				if uint(p) >= uint(len(data)) || data[p] != '{' {
					return p, odjsonrt.ErrType(data, p, "map[string]other.Thing")
				}
				p++
				m47 := v.Map
				if m47 == nil {
					m47 = make(map[string]other.Thing)
				}
				var seen50 map[string]struct{}
				if strict && len(m47) > 0 {
					seen50 = make(map[string]struct{})
				}
				p = odjsonrt.SkipSpace(data, p)
				if uint(p) < uint(len(data)) && data[p] == '}' {
					p++
				} else {
					for {
						var k48 []byte
						p = odjsonrt.SkipSpace(data, p)
						kp51 := p
						k48, p, err = odjsonrt.ParseKeyV2(data, p, strict)
						if err != nil {
							return p, err
						}
						if strict && seen50 != nil {
							if _, dup := seen50[string(k48)]; dup {
								return p, odjsonrt.ErrDuplicateName(data, kp51, k48)
							}
							seen50[string(k48)] = struct{}{}
						}
						var mv49 other.Thing
						p, err = odjsonOtherThingParseV2(data, &mv49, p, sc, strict)
						if err != nil {
							return p, err
						}
						n52 := len(m47)
						m47[sc.Make(k48)] = mv49
						if strict && seen50 == nil && len(m47) == n52 {
							return p, odjsonrt.ErrDuplicateName(data, kp51, k48)
						}
						p = odjsonrt.SkipSpace(data, p)
						if uint(p) >= uint(len(data)) {
							return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
						}
						if data[p] == ',' {
							p++
							continue
						}
						if data[p] == '}' {
							p++
							break
						}
						return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
					}
				}
				v.Map = m47
			}
			goto next38
		}
	m37:
		{
			if strict && seen[0]&(1<<5) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 5
			if np53, ok54 := odjsonrt.ParseNull(data, p); ok54 {
				p = np53
				v.Deep = nil
			} else {
				if uint(p) >= uint(len(data)) || data[p] != '[' {
					return p, odjsonrt.ErrType(data, p, "[]*other.Wrapper")
				}
				p++
				s55 := v.Deep[:0]
				p = odjsonrt.SkipSpace(data, p)
				if uint(p) < uint(len(data)) && data[p] == ']' {
					p++
				} else {
					if cap(s55) == 0 {
						s55 = make([]*other.Wrapper, 0, odjsonrt.CapFor[*other.Wrapper](&odjsonCapHolderDeep))
					}
					for {
						var e56 *other.Wrapper
						if uint(p) >= uint(len(data)) || data[p] <= ' ' {
							p = odjsonrt.SkipSpace(data, odjsonrt.SkipIndent(data, p))
						}
						if np57, ok58 := odjsonrt.ParseNull(data, p); ok58 {
							e56 = nil
							p = np57
						} else {
							if e56 == nil {
								e56 = new(other.Wrapper)
							}
							p, err = odjsonOtherWrapperParseV2(data, e56, p, sc, strict)
							if err != nil {
								return p, err
							}
						}
						s55 = append(s55, e56)
						p = odjsonrt.SkipSpace(data, p)
						if uint(p) >= uint(len(data)) {
							return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
						}
						if data[p] == ',' {
							p++
							continue
						}
						if data[p] == ']' {
							p++
							break
						}
						return p, odjsonrt.ErrSyntax(data, p, "after array element")
					}
					odjsonCapHolderDeep.Record(len(s55))
				}
				if s55 == nil {
					s55 = []*other.Wrapper{}
				}
				v.Deep = s55
			}
		}
	next38:
		{
			p = odjsonrt.SkipSpace(data, p)
			if uint(p) >= uint(len(data)) {
				return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
			}
			switch data[p] {
			case ',':
				p++
			case '}':
				odjsonrt.EndUnknownNames(sc, unknown, umark)
				return p + 1, nil
			default:
				return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
			}
		}
	}
}

// odjsonParseFrom decodes the next value in dec into v,
// driving the decoder token by token so the document is
// parsed once rather than twice.
func (v *Holder) odjsonParseFrom(dec *jsontext.Decoder, sc *odjsonrt.StringCache) error {
	var err error
	_ = err
	if odjsonrt.WholeValue(dec) {
		var val jsontext.Value
		if val, err = dec.ReadValue(); err != nil {
			return err
		}
		_, err = v.odjsonParseV2(val, 0, sc, false)
		return err
	}
	switch odjsonrt.NextKind(dec) {
	case 'n':
		if _, err = dec.ReadToken(); err != nil {
			return err
		}
		*v = Holder{}
		return nil
	case '{':
	default:
		return odjsonrt.ErrKindFrom(dec, "Holder")
	}
	if _, err = dec.ReadToken(); err != nil {
		return err
	}
	for odjsonrt.NextKind(dec) != '}' {
		var key jsontext.Value
		key, err = dec.ReadValue()
		if err != nil {
			return err
		}
		idx := -1
		switch string(key) {
		case "\"thing\"":
			idx = 0
		case "\"ptr\"":
			idx = 1
		case "\"wrapper\"":
			idx = 2
		case "\"list\"":
			idx = 3
		case "\"map\"":
			idx = 4
		case "\"deep\"":
			idx = 5
		}
		if idx < 0 && bytes.IndexByte(key, '\\') >= 0 {
			if name, ok := odjsonrt.UnquoteName(key); ok {
				switch string(name) {
				case "thing":
					idx = 0
				case "ptr":
					idx = 1
				case "wrapper":
					idx = 2
				case "list":
					idx = 3
				case "map":
					idx = 4
				case "deep":
					idx = 5
				}
			}
		}
		switch idx {
		case 0:
			if err = odjsonOtherThingParseFrom(dec, &v.Thing, sc); err != nil {
				return err
			}
		case 1:
			if odjsonrt.NextKind(dec) == 'n' {
				if _, err = dec.ReadToken(); err != nil {
					return err
				}
				v.Ptr = nil
			} else {
				if v.Ptr == nil {
					v.Ptr = new(other.Thing)
				}
				if err = odjsonOtherThingParseFrom(dec, v.Ptr, sc); err != nil {
					return err
				}
			}
		case 2:
			if err = odjsonOtherWrapperParseFrom(dec, &v.Wrapper, sc); err != nil {
				return err
			}
		case 3:
			switch odjsonrt.NextKind(dec) {
			case 'n':
				if _, err = dec.ReadToken(); err != nil {
					return err
				}
				v.List = nil
			case '[':
				if _, err = dec.ReadToken(); err != nil {
					return err
				}
				s59 := v.List[:0]
				if odjsonrt.NextKind(dec) != ']' && cap(s59) == 0 {
					s59 = make([]other.Thing, 0, odjsonrt.CapFor[other.Thing](&odjsonCapHolderList))
				}
				for odjsonrt.NextKind(dec) != ']' {
					var e60 other.Thing
					if err = odjsonOtherThingParseFrom(dec, &e60, sc); err != nil {
						return err
					}
					s59 = append(s59, e60)
				}
				if _, err = dec.ReadToken(); err != nil {
					return err
				}
				if len(s59) > 0 {
					odjsonCapHolderList.Record(len(s59))
				}
				if s59 == nil {
					s59 = []other.Thing{}
				}
				v.List = s59
			default:
				return odjsonrt.ErrKindFrom(dec, "[]other.Thing")
			}
		case 4:
			switch odjsonrt.NextKind(dec) {
			case 'n':
				if _, err = dec.ReadToken(); err != nil {
					return err
				}
				v.Map = nil
			case '{':
				if _, err = dec.ReadToken(); err != nil {
					return err
				}
				m61 := v.Map
				if m61 == nil {
					m61 = make(map[string]other.Thing)
				}
				for odjsonrt.NextKind(dec) != '}' {
					var k62 jsontext.Value
					k62, err = dec.ReadValue()
					if err != nil {
						return err
					}
					name63, ok64 := odjsonrt.UnquoteName(k62)
					if !ok64 {
						return odjsonrt.ErrSyntax(k62, 0, "invalid object name")
					}
					key65 := sc.Make(name63)
					var mv66 other.Thing
					if err = odjsonOtherThingParseFrom(dec, &mv66, sc); err != nil {
						return err
					}
					m61[key65] = mv66
				}
				if _, err = dec.ReadToken(); err != nil {
					return err
				}
				v.Map = m61
			default:
				return odjsonrt.ErrKindFrom(dec, "map[string]other.Thing")
			}
		case 5:
			switch odjsonrt.NextKind(dec) {
			case 'n':
				if _, err = dec.ReadToken(); err != nil {
					return err
				}
				v.Deep = nil
			case '[':
				if _, err = dec.ReadToken(); err != nil {
					return err
				}
				s67 := v.Deep[:0]
				if odjsonrt.NextKind(dec) != ']' && cap(s67) == 0 {
					s67 = make([]*other.Wrapper, 0, odjsonrt.CapFor[*other.Wrapper](&odjsonCapHolderDeep))
				}
				for odjsonrt.NextKind(dec) != ']' {
					var e68 *other.Wrapper
					if odjsonrt.NextKind(dec) == 'n' {
						if _, err = dec.ReadToken(); err != nil {
							return err
						}
						e68 = nil
					} else {
						if e68 == nil {
							e68 = new(other.Wrapper)
						}
						if err = odjsonOtherWrapperParseFrom(dec, e68, sc); err != nil {
							return err
						}
					}
					s67 = append(s67, e68)
				}
				if _, err = dec.ReadToken(); err != nil {
					return err
				}
				if len(s67) > 0 {
					odjsonCapHolderDeep.Record(len(s67))
				}
				if s67 == nil {
					s67 = []*other.Wrapper{}
				}
				v.Deep = s67
			default:
				return odjsonrt.ErrKindFrom(dec, "[]*other.Wrapper")
			}
		default:
			if _, err = dec.ReadValue(); err != nil {
				return err
			}
		}
	}
	_, err = dec.ReadToken()
	return err
}

// odjsonSizeHolder sizes the buffer the encoders allocate.
var odjsonSizeHolder odjsonrt.SizeHint

// MarshalJSON implements encoding/json.Marshaler.
func (v Holder) MarshalJSON() ([]byte, error) {
	buf, err := v.odjsonAppend(odjsonSizeHolder.New(), odjsonrt.ModeHTML)
	if err != nil {
		return nil, err
	}
	odjsonSizeHolder.Record(buf)
	return buf, nil
}

// UnmarshalJSON implements encoding/json.Unmarshaler.
func (v *Holder) UnmarshalJSON(data []byte) error {
	// The cache plays the part of encoding/json/v2's string cache: a
	// value that recurs in the document is allocated once.
	sc := odjsonrt.GetStringCache()
	p, err := v.odjsonParse(data, odjsonrt.SkipSpace(data, 0), sc)
	odjsonrt.PutStringCache(sc)
	if err != nil {
		return err
	}
	return odjsonrt.EndOfDocument(data, p)
}

// MarshalJSONTo implements encoding/json/v2.MarshalerTo.
func (v Holder) MarshalJSONTo(enc *jsontext.Encoder) error {
	// Under a plain json.Marshal, from encoding/json/v2 or encoding/json,
	// the value is appended straight into the encoder's buffer at any
	// depth; see odjsonrt.BeginDirectEncodeMode for what qualifies and
	// for the mode, which does that call's escaping itself since nothing
	// downstream looks at the bytes.
	if buf, m, ok := odjsonrt.BeginDirectEncodeMode(enc); ok {
		n := len(buf)
		buf, err := v.odjsonAppend(buf, m)
		if err != nil {
			return err
		}
		odjsonSizeHolder.Record(buf[n:])
		odjsonrt.EndDirectEncode(enc, buf)
		return nil
	}
	// Otherwise WriteValue copies what it is given, so the scratch buffer
	// can go straight back to the pool. ModeStream leaves the HTML escaping
	// and the UTF-8 validation to the encoder, which performs both while
	// reformatting the value either way.
	buf := odjsonrt.GetBuffer()
	var err error
	if buf.B, err = v.odjsonAppend(buf.B, odjsonrt.ModeStream); err == nil {
		odjsonSizeHolder.Record(buf.B)
		err = enc.WriteValue(buf.B)
	}
	odjsonrt.PutBuffer(buf)
	return err
}

// UnmarshalJSONFrom implements encoding/json/v2.UnmarshalerFrom.
func (v *Holder) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	// The cache plays the part of json/v2's own string cache: a value
	// that recurs in the document is allocated once.
	sc := odjsonrt.GetStringCache()
	var err error
	// Under a plain json.Unmarshal the value is parsed straight out of
	// the decoder's buffer at any depth; see odjsonrt.BeginDirectDecodeAt
	// for what qualifies. Nobody has validated those bytes, so
	// odjsonParseV2 rejects what jsontext would have.
	if data, p, ok := odjsonrt.BeginDirectDecodeAt(dec); ok {
		var end int
		if end, err = v.odjsonParseV2(data, p, sc, true); err == nil {
			odjsonrt.EndDirectDecodeAt(dec, p, end)
		}
	} else {
		err = v.odjsonParseFrom(dec, sc)
	}
	odjsonrt.PutStringCache(sc)
	return err
}

// odjsonOtherThingAppend appends the JSON encoding of v to dst.
func odjsonOtherThingAppend(dst []byte, v *other.Thing, m odjsonrt.StringMode) ([]byte, error) {
	var err error
	_ = err
	start := len(dst)
	dst = append(dst, ",\"id\":"...)
	dst = odjsonrt.AppendInt(dst, int64(v.ID))
	if len(v.Name) != 0 {
		dst = append(dst, ",\"name\":\""...)
		dst, err = odjsonrt.AppendStringBodyChecked(dst, string(v.Name), m)
		if err != nil {
			return nil, err
		}
		dst = append(dst, "\""...)
	}
	dst[start] = '{'
	dst = append(dst, "}"...)
	return dst, nil
}

// odjsonOtherThingParse decodes the JSON object starting at p into v and
// returns the offset just past it. Strings are interned through
// sc, which may be nil.
func odjsonOtherThingParse(data []byte, v *other.Thing, p int, sc *odjsonrt.StringCache) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		return np, nil
	}
	if uint(p) >= uint(len(data)) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "other.Thing")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if uint(p) < uint(len(data)) && data[p] == '}' {
		return p + 1, nil
	}
	for {
		if uint(p) >= uint(len(data)) || data[p] <= ' ' {
			p = odjsonrt.SkipSpace(data, odjsonrt.SkipIndent(data, p))
		}
		rest := data[p:]
		if len(rest) > 1 {
			switch rest[1] {
			case 'i':
				if len(rest) >= 4 && string(rest[:4]) == "\"id\"" {
					p += 4
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m69
				}
			case 'n':
				if len(rest) >= 6 && string(rest[:6]) == "\"name\"" {
					p += 6
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m70
				}
			}
		}
		{
			var key []byte
			key, _, p, err = odjsonrt.ParseKey(data, p)
			if err != nil {
				return p, err
			}
			switch string(key) {
			case "id":
				goto m69
			case "name":
				goto m70
			}
			p = odjsonrt.SkipSpace(data, p)
			p, err = odjsonrt.SkipValue(data, p)
			if err != nil {
				return p, err
			}
			goto next71
		}
	m69:
		{
			if np72, ok73 := odjsonrt.ParseNull(data, p); ok73 {
				p = np72
			} else {
				if x74, np75, ok76 := odjsonrt.ParseDecimal(data, p); ok76 {
					v.ID = int(x74)
					p = np75
				} else {
					var x77 int64
					x77, p, err = odjsonrt.ParseInt(data, p, 64)
					if err != nil {
						return p, err
					}
					v.ID = int(x77)
				}
			}
			goto next71
		}
	m70:
		{
			if np78, ok79 := odjsonrt.ParseNull(data, p); ok79 {
				p = np78
			} else {
				var x80 string
				x80, p, err = odjsonrt.ParseStringCached(data, p, sc)
				if err != nil {
					return p, err
				}
				v.Name = x80
			}
		}
	next71:
		{
			p = odjsonrt.SkipSpace(data, p)
			if uint(p) >= uint(len(data)) {
				return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
			}
			switch data[p] {
			case ',':
				p++
			case '}':
				return p + 1, nil
			default:
				return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
			}
		}
	}
}

// odjsonOtherThingParseV2 is odjsonOtherThingParse under encoding/json/v2's semantics, for
// input a jsontext.Decoder has already validated when strict is false,
// and for bytes nobody has looked at when it is true.
func odjsonOtherThingParseV2(data []byte, v *other.Thing, p int, sc *odjsonrt.StringCache, strict bool) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		*v = other.Thing{}
		return np, nil
	}
	if uint(p) >= uint(len(data)) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "other.Thing")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if uint(p) < uint(len(data)) && data[p] == '}' {
		return p + 1, nil
	}
	var seen [1]uint64
	_ = seen
	unknown, umark := odjsonrt.UnknownNames(sc)
	var ufilter uint64
	_ = ufilter
	for {
		if uint(p) >= uint(len(data)) || data[p] <= ' ' {
			p = odjsonrt.SkipSpace(data, odjsonrt.SkipIndent(data, p))
		}
		kp := p
		rest := data[p:]
		if len(rest) > 1 {
			switch rest[1] {
			case 'i':
				if len(rest) >= 4 && string(rest[:4]) == "\"id\"" {
					p += 4
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m81
				}
			case 'n':
				if len(rest) >= 6 && string(rest[:6]) == "\"name\"" {
					p += 6
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m82
				}
			}
		}
		{
			var key []byte
			key, p, err = odjsonrt.ParseKeyV2(data, p, strict)
			if err != nil {
				return p, err
			}
			switch string(key) {
			case "id":
				goto m81
			case "name":
				goto m82
			}
			if strict {
				var dup bool
				if unknown, dup = odjsonrt.UnknownName(sc, unknown, umark, &ufilter, key); dup {
					return kp, odjsonrt.ErrDuplicateName(data, kp, key)
				}
			}
			p = odjsonrt.SkipSpace(data, p)
			p, err = odjsonrt.SkipValueV2(data, p, strict)
			if err != nil {
				return p, err
			}
			goto next83
		}
	m81:
		{
			if strict && seen[0]&(1<<0) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 0
			if np84, ok85 := odjsonrt.ParseNull(data, p); ok85 {
				p = np84
				v.ID = 0
			} else {
				if x86, np87, ok88 := odjsonrt.ParseDecimal(data, p); ok88 {
					v.ID = int(x86)
					p = np87
				} else {
					var x89 int64
					x89, p, err = odjsonrt.ParseInt(data, p, 64)
					if err != nil {
						return p, err
					}
					v.ID = int(x89)
				}
			}
			goto next83
		}
	m82:
		{
			if strict && seen[0]&(1<<1) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 1
			if np90, ok91 := odjsonrt.ParseNull(data, p); ok91 {
				p = np90
				v.Name = ""
			} else {
				var x92 string
				x92, p, err = odjsonrt.ParseStringV2(data, p, sc, strict)
				if err != nil {
					return p, err
				}
				v.Name = x92
			}
		}
	next83:
		{
			p = odjsonrt.SkipSpace(data, p)
			if uint(p) >= uint(len(data)) {
				return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
			}
			switch data[p] {
			case ',':
				p++
			case '}':
				odjsonrt.EndUnknownNames(sc, unknown, umark)
				return p + 1, nil
			default:
				return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
			}
		}
	}
}

// odjsonOtherThingParseFrom decodes the next value in dec into v,
// driving the decoder token by token so the document is
// parsed once rather than twice.
func odjsonOtherThingParseFrom(dec *jsontext.Decoder, v *other.Thing, sc *odjsonrt.StringCache) error {
	var err error
	_ = err
	if odjsonrt.WholeValue(dec) {
		var val jsontext.Value
		if val, err = dec.ReadValue(); err != nil {
			return err
		}
		_, err = odjsonOtherThingParseV2(val, v, 0, sc, false)
		return err
	}
	switch odjsonrt.NextKind(dec) {
	case 'n':
		if _, err = dec.ReadToken(); err != nil {
			return err
		}
		*v = other.Thing{}
		return nil
	case '{':
	default:
		return odjsonrt.ErrKindFrom(dec, "other.Thing")
	}
	if _, err = dec.ReadToken(); err != nil {
		return err
	}
	for odjsonrt.NextKind(dec) != '}' {
		var key jsontext.Value
		key, err = dec.ReadValue()
		if err != nil {
			return err
		}
		idx := -1
		switch string(key) {
		case "\"id\"":
			idx = 0
		case "\"name\"":
			idx = 1
		}
		if idx < 0 && bytes.IndexByte(key, '\\') >= 0 {
			if name, ok := odjsonrt.UnquoteName(key); ok {
				switch string(name) {
				case "id":
					idx = 0
				case "name":
					idx = 1
				}
			}
		}
		switch idx {
		case 0:
			var val93 jsontext.Value
			val93, err = dec.ReadValue()
			if err != nil {
				return err
			}
			if val93[0] == 'n' {
				v.ID = 0
			} else {
				var x94 int64
				x94, _, err = odjsonrt.ParseInt(val93, 0, 64)
				if err != nil {
					return err
				}
				v.ID = int(x94)
			}
		case 1:
			var val95 jsontext.Value
			val95, err = dec.ReadValue()
			if err != nil {
				return err
			}
			if val95[0] == 'n' {
				v.Name = ""
			} else {
				var x96 string
				x96, err = odjsonrt.ParseStringValue(val95, sc)
				if err != nil {
					return err
				}
				v.Name = x96
			}
		default:
			if _, err = dec.ReadValue(); err != nil {
				return err
			}
		}
	}
	_, err = dec.ReadToken()
	return err
}

// odjsonOtherWrapperAppend appends the JSON encoding of v to dst.
func odjsonOtherWrapperAppend(dst []byte, v *other.Wrapper, m odjsonrt.StringMode) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, "{\"thing\":"...)
	dst, err = odjsonOtherThingAppend(dst, &v.Thing, m)
	if err != nil {
		return nil, err
	}
	if v.Ptr == nil {
		dst = append(dst, ",\"ptr\":null,\"lis"...)
		dst = append(dst, "t\":"...)
	} else {
		dst = append(dst, ",\"ptr\":"...)
		dst, err = odjsonOtherThingAppend(dst, v.Ptr, m)
		if err != nil {
			return nil, err
		}
		dst = append(dst, ",\"list\":"...)
	}
	if v.List == nil {
		if m.V2() {
			dst = append(dst, "[]}"...)
		} else {
			dst = append(dst, "null}"...)
		}
	} else {
		dst = append(dst, "["...)
		for i97 := range v.List {
			if i97 > 0 {
				dst = append(dst, ',')
			}
			dst, err = odjsonOtherThingAppend(dst, &v.List[i97], m)
			if err != nil {
				return nil, err
			}
		}
		dst = append(dst, "]}"...)
	}
	return dst, nil
}

// odjsonCapodjsonOtherWrapperList remembers how long v.List has been, to allocate it once.
var odjsonCapodjsonOtherWrapperList odjsonrt.CapHint

// odjsonOtherWrapperParse decodes the JSON object starting at p into v and
// returns the offset just past it. Strings are interned through
// sc, which may be nil.
func odjsonOtherWrapperParse(data []byte, v *other.Wrapper, p int, sc *odjsonrt.StringCache) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		return np, nil
	}
	if uint(p) >= uint(len(data)) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "other.Wrapper")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if uint(p) < uint(len(data)) && data[p] == '}' {
		return p + 1, nil
	}
	for {
		if uint(p) >= uint(len(data)) || data[p] <= ' ' {
			p = odjsonrt.SkipSpace(data, odjsonrt.SkipIndent(data, p))
		}
		rest := data[p:]
		if len(rest) > 1 {
			switch rest[1] {
			case 't':
				if len(rest) >= 7 && string(rest[:7]) == "\"thing\"" {
					p += 7
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m98
				}
			case 'p':
				if len(rest) >= 5 && string(rest[:5]) == "\"ptr\"" {
					p += 5
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m99
				}
			case 'l':
				if len(rest) >= 6 && string(rest[:6]) == "\"list\"" {
					p += 6
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m100
				}
			}
		}
		{
			var key []byte
			key, _, p, err = odjsonrt.ParseKey(data, p)
			if err != nil {
				return p, err
			}
			switch string(key) {
			case "thing":
				goto m98
			case "ptr":
				goto m99
			case "list":
				goto m100
			}
			p = odjsonrt.SkipSpace(data, p)
			p, err = odjsonrt.SkipValue(data, p)
			if err != nil {
				return p, err
			}
			goto next101
		}
	m98:
		{
			p, err = odjsonOtherThingParse(data, &v.Thing, p, sc)
			if err != nil {
				return p, err
			}
			goto next101
		}
	m99:
		{
			if np102, ok103 := odjsonrt.ParseNull(data, p); ok103 {
				v.Ptr = nil
				p = np102
			} else {
				if v.Ptr == nil {
					v.Ptr = new(other.Thing)
				}
				p, err = odjsonOtherThingParse(data, v.Ptr, p, sc)
				if err != nil {
					return p, err
				}
			}
			goto next101
		}
	m100:
		{
			if np104, ok105 := odjsonrt.ParseNull(data, p); ok105 {
				p = np104
				v.List = nil
			} else {
				if uint(p) >= uint(len(data)) || data[p] != '[' {
					return p, odjsonrt.ErrType(data, p, "[]other.Thing")
				}
				p++
				s106 := v.List[:0]
				p = odjsonrt.SkipSpace(data, p)
				if uint(p) < uint(len(data)) && data[p] == ']' {
					p++
				} else {
					if cap(s106) == 0 {
						s106 = make([]other.Thing, 0, odjsonrt.CapFor[other.Thing](&odjsonCapodjsonOtherWrapperList))
					}
					for {
						var e107 other.Thing
						if uint(p) >= uint(len(data)) || data[p] <= ' ' {
							p = odjsonrt.SkipSpace(data, odjsonrt.SkipIndent(data, p))
						}
						p, err = odjsonOtherThingParse(data, &e107, p, sc)
						if err != nil {
							return p, err
						}
						s106 = append(s106, e107)
						p = odjsonrt.SkipSpace(data, p)
						if uint(p) >= uint(len(data)) {
							return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
						}
						if data[p] == ',' {
							p++
							continue
						}
						if data[p] == ']' {
							p++
							break
						}
						return p, odjsonrt.ErrSyntax(data, p, "after array element")
					}
					odjsonCapodjsonOtherWrapperList.Record(len(s106))
				}
				if s106 == nil {
					s106 = []other.Thing{}
				}
				v.List = s106
			}
		}
	next101:
		{
			p = odjsonrt.SkipSpace(data, p)
			if uint(p) >= uint(len(data)) {
				return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
			}
			switch data[p] {
			case ',':
				p++
			case '}':
				return p + 1, nil
			default:
				return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
			}
		}
	}
}

// odjsonOtherWrapperParseV2 is odjsonOtherWrapperParse under encoding/json/v2's semantics, for
// input a jsontext.Decoder has already validated when strict is false,
// and for bytes nobody has looked at when it is true.
func odjsonOtherWrapperParseV2(data []byte, v *other.Wrapper, p int, sc *odjsonrt.StringCache, strict bool) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		*v = other.Wrapper{}
		return np, nil
	}
	if uint(p) >= uint(len(data)) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "other.Wrapper")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if uint(p) < uint(len(data)) && data[p] == '}' {
		return p + 1, nil
	}
	var seen [1]uint64
	_ = seen
	unknown, umark := odjsonrt.UnknownNames(sc)
	var ufilter uint64
	_ = ufilter
	for {
		if uint(p) >= uint(len(data)) || data[p] <= ' ' {
			p = odjsonrt.SkipSpace(data, odjsonrt.SkipIndent(data, p))
		}
		kp := p
		rest := data[p:]
		if len(rest) > 1 {
			switch rest[1] {
			case 't':
				if len(rest) >= 7 && string(rest[:7]) == "\"thing\"" {
					p += 7
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m108
				}
			case 'p':
				if len(rest) >= 5 && string(rest[:5]) == "\"ptr\"" {
					p += 5
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m109
				}
			case 'l':
				if len(rest) >= 6 && string(rest[:6]) == "\"list\"" {
					p += 6
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m110
				}
			}
		}
		{
			var key []byte
			key, p, err = odjsonrt.ParseKeyV2(data, p, strict)
			if err != nil {
				return p, err
			}
			switch string(key) {
			case "thing":
				goto m108
			case "ptr":
				goto m109
			case "list":
				goto m110
			}
			if strict {
				var dup bool
				if unknown, dup = odjsonrt.UnknownName(sc, unknown, umark, &ufilter, key); dup {
					return kp, odjsonrt.ErrDuplicateName(data, kp, key)
				}
			}
			p = odjsonrt.SkipSpace(data, p)
			p, err = odjsonrt.SkipValueV2(data, p, strict)
			if err != nil {
				return p, err
			}
			goto next111
		}
	m108:
		{
			if strict && seen[0]&(1<<0) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 0
			p, err = odjsonOtherThingParseV2(data, &v.Thing, p, sc, strict)
			if err != nil {
				return p, err
			}
			goto next111
		}
	m109:
		{
			if strict && seen[0]&(1<<1) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 1
			if np112, ok113 := odjsonrt.ParseNull(data, p); ok113 {
				v.Ptr = nil
				p = np112
			} else {
				if v.Ptr == nil {
					v.Ptr = new(other.Thing)
				}
				p, err = odjsonOtherThingParseV2(data, v.Ptr, p, sc, strict)
				if err != nil {
					return p, err
				}
			}
			goto next111
		}
	m110:
		{
			if strict && seen[0]&(1<<2) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 2
			if np114, ok115 := odjsonrt.ParseNull(data, p); ok115 {
				p = np114
				v.List = nil
			} else {
				if uint(p) >= uint(len(data)) || data[p] != '[' {
					return p, odjsonrt.ErrType(data, p, "[]other.Thing")
				}
				p++
				s116 := v.List[:0]
				p = odjsonrt.SkipSpace(data, p)
				if uint(p) < uint(len(data)) && data[p] == ']' {
					p++
				} else {
					if cap(s116) == 0 {
						s116 = make([]other.Thing, 0, odjsonrt.CapFor[other.Thing](&odjsonCapodjsonOtherWrapperList))
					}
					for {
						var e117 other.Thing
						if uint(p) >= uint(len(data)) || data[p] <= ' ' {
							p = odjsonrt.SkipSpace(data, odjsonrt.SkipIndent(data, p))
						}
						p, err = odjsonOtherThingParseV2(data, &e117, p, sc, strict)
						if err != nil {
							return p, err
						}
						s116 = append(s116, e117)
						p = odjsonrt.SkipSpace(data, p)
						if uint(p) >= uint(len(data)) {
							return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
						}
						if data[p] == ',' {
							p++
							continue
						}
						if data[p] == ']' {
							p++
							break
						}
						return p, odjsonrt.ErrSyntax(data, p, "after array element")
					}
					odjsonCapodjsonOtherWrapperList.Record(len(s116))
				}
				if s116 == nil {
					s116 = []other.Thing{}
				}
				v.List = s116
			}
		}
	next111:
		{
			p = odjsonrt.SkipSpace(data, p)
			if uint(p) >= uint(len(data)) {
				return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
			}
			switch data[p] {
			case ',':
				p++
			case '}':
				odjsonrt.EndUnknownNames(sc, unknown, umark)
				return p + 1, nil
			default:
				return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
			}
		}
	}
}

// odjsonOtherWrapperParseFrom decodes the next value in dec into v,
// driving the decoder token by token so the document is
// parsed once rather than twice.
func odjsonOtherWrapperParseFrom(dec *jsontext.Decoder, v *other.Wrapper, sc *odjsonrt.StringCache) error {
	var err error
	_ = err
	if odjsonrt.WholeValue(dec) {
		var val jsontext.Value
		if val, err = dec.ReadValue(); err != nil {
			return err
		}
		_, err = odjsonOtherWrapperParseV2(val, v, 0, sc, false)
		return err
	}
	switch odjsonrt.NextKind(dec) {
	case 'n':
		if _, err = dec.ReadToken(); err != nil {
			return err
		}
		*v = other.Wrapper{}
		return nil
	case '{':
	default:
		return odjsonrt.ErrKindFrom(dec, "other.Wrapper")
	}
	if _, err = dec.ReadToken(); err != nil {
		return err
	}
	for odjsonrt.NextKind(dec) != '}' {
		var key jsontext.Value
		key, err = dec.ReadValue()
		if err != nil {
			return err
		}
		idx := -1
		switch string(key) {
		case "\"thing\"":
			idx = 0
		case "\"ptr\"":
			idx = 1
		case "\"list\"":
			idx = 2
		}
		if idx < 0 && bytes.IndexByte(key, '\\') >= 0 {
			if name, ok := odjsonrt.UnquoteName(key); ok {
				switch string(name) {
				case "thing":
					idx = 0
				case "ptr":
					idx = 1
				case "list":
					idx = 2
				}
			}
		}
		switch idx {
		case 0:
			if err = odjsonOtherThingParseFrom(dec, &v.Thing, sc); err != nil {
				return err
			}
		case 1:
			if odjsonrt.NextKind(dec) == 'n' {
				if _, err = dec.ReadToken(); err != nil {
					return err
				}
				v.Ptr = nil
			} else {
				if v.Ptr == nil {
					v.Ptr = new(other.Thing)
				}
				if err = odjsonOtherThingParseFrom(dec, v.Ptr, sc); err != nil {
					return err
				}
			}
		case 2:
			switch odjsonrt.NextKind(dec) {
			case 'n':
				if _, err = dec.ReadToken(); err != nil {
					return err
				}
				v.List = nil
			case '[':
				if _, err = dec.ReadToken(); err != nil {
					return err
				}
				s118 := v.List[:0]
				if odjsonrt.NextKind(dec) != ']' && cap(s118) == 0 {
					s118 = make([]other.Thing, 0, odjsonrt.CapFor[other.Thing](&odjsonCapodjsonOtherWrapperList))
				}
				for odjsonrt.NextKind(dec) != ']' {
					var e119 other.Thing
					if err = odjsonOtherThingParseFrom(dec, &e119, sc); err != nil {
						return err
					}
					s118 = append(s118, e119)
				}
				if _, err = dec.ReadToken(); err != nil {
					return err
				}
				if len(s118) > 0 {
					odjsonCapodjsonOtherWrapperList.Record(len(s118))
				}
				if s118 == nil {
					s118 = []other.Thing{}
				}
				v.List = s118
			default:
				return odjsonrt.ErrKindFrom(dec, "[]other.Thing")
			}
		default:
			if _, err = dec.ReadValue(); err != nil {
				return err
			}
		}
	}
	_, err = dec.ReadToken()
	return err
}
