//go:build ignore

// pow10gen writes pow10tab.go: the 128-bit scaled powers of ten that
// ftoa.go's shortest-digit search multiplies by. See ftoa.go for the range
// and the form of each entry.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"math/big"
	"os"
)

// The exponents ftoa.go can ask for: see ftoaPow10Min and ftoaPow10Max in
// ftoa.go, which must match these.
const (
	minExp = -350
	maxExp = 350
)

func main() {
	log.SetPrefix("pow10gen: ")
	log.SetFlags(0)

	one := big.NewInt(1)
	two := big.NewRat(2, 1)
	pow2to64 := new(big.Int).Lsh(one, 64)
	pow2to128 := new(big.Rat).SetInt(new(big.Int).Lsh(one, 128))

	var out bytes.Buffer
	fmt.Fprintf(&out, "// Code generated by go run pow10gen.go. DO NOT EDIT.\n\n")
	fmt.Fprintf(&out, "package odjsonrt\n\n")
	fmt.Fprintf(&out, "// ftoaPow10 holds, for each p from ftoaPow10Min to ftoaPow10Max, the\n")
	fmt.Fprintf(&out, "// 128-bit integer ⌈10^p · 2^k⌉ with k chosen so that it lies in\n")
	fmt.Fprintf(&out, "// [2^127, 2^128), stored as {hi, lo} meaning hi·2^64 − lo. See ftoa.go.\n")
	fmt.Fprintf(&out, "var ftoaPow10 = [...]pow10Entry{\n")
	for p := int64(minExp); p <= maxExp; p++ {
		r := new(big.Rat)
		if p >= 0 {
			r.SetInt(new(big.Int).Exp(big.NewInt(10), big.NewInt(p), nil))
		} else {
			r.SetFrac(one, new(big.Int).Exp(big.NewInt(10), big.NewInt(-p), nil))
		}
		k := 0
		for r.Cmp(pow2to128) < 0 {
			r.Mul(r, two)
			k++
		}
		for r.Cmp(pow2to128) >= 0 {
			r.Quo(r, two)
			k--
		}
		// Round up to an integer.
		d := new(big.Int).Quo(r.Num(), r.Denom())
		if !r.IsInt() {
			d.Add(d, one)
		}
		hi, lo := new(big.Int).QuoRem(d, pow2to64, new(big.Int))
		uhi, ulo := hi.Uint64(), lo.Uint64()
		// hi·2^64 + lo = (hi+1)·2^64 − (2^64 − lo) when lo is not zero.
		if ulo != 0 {
			uhi++
			ulo = -ulo
		}
		fmt.Fprintf(&out, "\t{%#016x, %#016x}, // 1e%d · 2^%d\n", uhi, ulo, p, k)
	}
	fmt.Fprintf(&out, "}\n")

	src, err := format.Source(out.Bytes())
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile("pow10tab.go", src, 0o644); err != nil {
		log.Fatal(err)
	}
}
