// Package codegen turns odjson's intermediate representation into Go source
// implementing reflection-free JSON encoders and decoders.
package codegen

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"strconv"
	"strings"

	"github.com/mazrean/odjson/internal/analyzer"
)

// Options configures the generated code.
type Options struct {
	// EscapeHTML mirrors encoding/json's default of escaping <, > and & so
	// the output is safe to embed in HTML.
	EscapeHTML bool
	// CaseInsensitive enables encoding/json's fallback that matches an
	// object member to a field name ignoring case.
	CaseInsensitive bool
	// JSONV2 additionally emits the encoding/json/v2 marshaler and
	// unmarshaler methods.
	JSONV2 bool
	// Methods emits MarshalJSON and UnmarshalJSON (and their v2
	// counterparts) on the generated types. Turning it off keeps the
	// package's existing encoding/json behaviour untouched and exposes the
	// direct Marshal/Unmarshal functions only.
	Methods bool
	// Command is recorded in the file header.
	Command string
}

type generator struct {
	buf  bytes.Buffer
	opts Options
	pkg  *analyzer.Package
	n    int
}

// ctx names the variables a decoding fragment reads from, and how it reports
// failure.
type ctx struct {
	data string
	pos  string
	ret  string
	// single makes the fragment return only an error, which is what the
	// jsontext driven decoders need.
	single bool
	// trusted tells the fragment that the bytes came from a
	// jsontext.Decoder, which has already validated their UTF-8.
	trusted bool
	// trimmed says the position is already at the first byte of the value,
	// so the fragment's leading whitespace skip can be dropped.
	trimmed bool
	// v2 selects encoding/json/v2's decoding semantics: a null stores the
	// zero value whatever the target, and a fixed size array must match the
	// document's length exactly.
	v2 bool
	// cache names the *odjsonrt.StringCache the fragment interns strings
	// through, or is empty when it allocates every string.
	cache string
	// strict says nobody has validated the bytes, so the fragment must
	// reject what encoding/json/v2 rejects: invalid UTF-8 and duplicate
	// object names.
	strict bool
}

// fail renders the statement returning expr as the fragment's error.
func (c ctx) fail(expr string) string {
	if c.single {
		return "return " + expr
	}
	return "return " + c.ret + ", " + expr
}

// Generate renders the complete generated file for pkg.
func Generate(pkg *analyzer.Package, opts Options) ([]byte, error) {
	g := &generator{opts: opts, pkg: pkg}

	pkg.Imports.Add(analyzer.RuntimePath, "odjsonrt")
	var body bytes.Buffer
	for _, s := range pkg.Structs {
		g.buf.Reset()
		g.structCodec(s)
		body.Write(g.buf.Bytes())
	}

	render := func(imports []string) []byte {
		var out bytes.Buffer
		out.WriteString("// Code generated by odjson. DO NOT EDIT.\n")
		if opts.Command != "" {
			fmt.Fprintf(&out, "//\n// Source: %s\n", opts.Command)
		}
		fmt.Fprintf(&out, "\npackage %s\n\n", pkg.Name)
		if len(imports) > 0 {
			out.WriteString("import (\n")
			for _, l := range imports {
				fmt.Fprintf(&out, "\t%s\n", l)
			}
			out.WriteString(")\n")
		}
		out.Write(body.Bytes())
		return out.Bytes()
	}

	// Rendering a type expression registers its package, even when the
	// expression never reaches the output — json.RawMessage, for instance, is
	// only ever converted to []byte. Drop those again by looking at which
	// identifiers the finished file actually qualifies.
	draft := render(pkg.Imports.Lines())
	used, err := qualifiers(draft)
	if err != nil {
		return draft, err
	}
	src, err := format.Source(render(pkg.Imports.LinesFor(used)))
	if err != nil {
		return draft, fmt.Errorf("format generated source: %w", err)
	}
	return src, nil
}

// qualifiers returns the set of identifiers the file uses on the left of a
// selector, which is exactly the set of import identifiers it needs.
func qualifiers(src []byte) (map[string]bool, error) {
	f, err := parser.ParseFile(token.NewFileSet(), "odjson_gen.go", src, parser.SkipObjectResolution)
	if err != nil {
		return nil, fmt.Errorf("parse generated source: %w", err)
	}
	used := map[string]bool{}
	ast.Inspect(f, func(n ast.Node) bool {
		if sel, ok := n.(*ast.SelectorExpr); ok {
			if id, ok := sel.X.(*ast.Ident); ok {
				used[id.Name] = true
			}
		}
		return true
	})
	return used, nil
}

func (g *generator) tmp(prefix string) string {
	g.n++
	return fmt.Sprintf("%s%d", prefix, g.n)
}

func (g *generator) pf(format string, args ...any) {
	fmt.Fprintf(&g.buf, format, args...)
	g.buf.WriteByte('\n')
}

// structCodec writes every function and method belonging to one struct type.
func (g *generator) structCodec(s *analyzer.StructInfo) {
	g.pf("")
	if s.Local {
		g.pf("// odjsonAppend appends the JSON encoding of v to dst.")
		g.pf("func (v *%s) odjsonAppend(dst []byte, m odjsonrt.StringMode) ([]byte, error) {", s.Expr)
	} else {
		g.pf("// %sAppend appends the JSON encoding of v to dst.", s.Helper)
		g.pf("func %sAppend(dst []byte, v *%s, m odjsonrt.StringMode) ([]byte, error) {", s.Helper, s.Expr)
	}
	g.encodeStruct(s)
	g.pf("}")

	g.pf("")
	if s.Local {
		g.pf("// odjsonParse decodes the JSON object starting at p into v and")
		g.pf("// returns the offset just past it.")
		g.pf("func (v *%s) odjsonParse(data []byte, p int) (int, error) {", s.Expr)
	} else {
		g.pf("// %sParse decodes the JSON object starting at p into v and", s.Helper)
		g.pf("// returns the offset just past it.")
		g.pf("func %sParse(data []byte, v *%s, p int) (int, error) {", s.Helper, s.Expr)
	}
	g.decodeStruct(s, ctx{data: "data", pos: "p", ret: "p"})
	g.pf("}")

	if g.opts.Methods && g.opts.JSONV2 {
		g.pkg.Imports.Add(analyzer.JSONTextPath, "jsontext")
		g.pf("")
		if s.Local {
			g.pf("// odjsonParseV2 is odjsonParse under encoding/json/v2's semantics, for")
			g.pf("// input a jsontext.Decoder has already validated when strict is false,")
			g.pf("// and for bytes nobody has looked at when it is true.")
			g.pf("func (v *%s) odjsonParseV2(data []byte, p int, %s *odjsonrt.StringCache, strict bool) (int, error) {", s.Expr, cache)
		} else {
			g.pf("// %sParseV2 is %sParse under encoding/json/v2's semantics, for", s.Helper, s.Helper)
			g.pf("// input a jsontext.Decoder has already validated when strict is false,")
			g.pf("// and for bytes nobody has looked at when it is true.")
			g.pf("func %sParseV2(data []byte, v *%s, p int, %s *odjsonrt.StringCache, strict bool) (int, error) {", s.Helper, s.Expr, cache)
		}
		g.decodeStruct(s, ctx{data: "data", pos: "p", ret: "p", v2: true, cache: cache, strict: true})
		g.pf("}")
		g.pf("")
		if s.Local {
			g.pf("// odjsonParseFrom decodes the next value in dec into v,")
			g.pf("// driving the decoder token by token so the document is")
			g.pf("// parsed once rather than twice.")
			g.pf("func (v *%s) odjsonParseFrom(dec *jsontext.Decoder, %s *odjsonrt.StringCache) error {", s.Expr, cache)
		} else {
			g.pf("// %sParseFrom decodes the next value in dec into v,", s.Helper)
			g.pf("// driving the decoder token by token so the document is")
			g.pf("// parsed once rather than twice.")
			g.pf("func %sParseFrom(dec *jsontext.Decoder, v *%s, %s *odjsonrt.StringCache) error {", s.Helper, s.Expr, cache)
		}
		g.decodeStructFrom(s)
		g.pf("}")
	}

	if !s.Local {
		return
	}

	name := s.Name
	g.pf("")
	g.pf("// Append%s appends the JSON encoding of v to dst.", name)
	g.pf("func Append%s(dst []byte, v *%s) ([]byte, error) {", name, s.Expr)
	g.pf("\treturn v.odjsonAppend(dst, %s)", g.v1Mode())
	g.pf("}")

	g.pf("")
	g.pf("// odjsonSize%s sizes the buffer Marshal%s allocates.", name, name)
	g.pf("var odjsonSize%s odjsonrt.SizeHint", name)
	g.pf("")
	g.pf("// Marshal%s returns the JSON encoding of v.", name)
	g.pf("func Marshal%s(v *%s) ([]byte, error) {", name, s.Expr)
	g.pf("\tbuf, err := v.odjsonAppend(odjsonSize%s.New(), %s)", name, g.v1Mode())
	g.pf("\tif err != nil {")
	g.pf("\t\treturn nil, err")
	g.pf("\t}")
	g.pf("\todjsonSize%s.Record(buf)", name)
	g.pf("\treturn buf, nil")
	g.pf("}")

	g.pf("")
	g.pf("// Unmarshal%s decodes the JSON document data into v.", name)
	g.pf("func Unmarshal%s(data []byte, v *%s) error {", name, s.Expr)
	g.pf("\tp, err := v.odjsonParse(data, odjsonrt.SkipSpace(data, 0))")
	g.pf("\tif err != nil {")
	g.pf("\t\treturn err")
	g.pf("\t}")
	g.pf("\treturn odjsonrt.EndOfDocument(data, p)")
	g.pf("}")

	if !g.opts.Methods {
		return
	}

	g.pf("")
	g.pf("// MarshalJSON implements encoding/json.Marshaler.")
	g.pf("func (v %s) MarshalJSON() ([]byte, error) {", s.Expr)
	g.pf("\treturn Marshal%s(&v)", name)
	g.pf("}")

	g.pf("")
	g.pf("// UnmarshalJSON implements encoding/json.Unmarshaler.")
	g.pf("func (v *%s) UnmarshalJSON(data []byte) error {", s.Expr)
	g.pf("\treturn Unmarshal%s(data, v)", name)
	g.pf("}")

	if !g.opts.JSONV2 {
		return
	}
	g.pkg.Imports.Add(analyzer.JSONTextPath, "jsontext")

	g.pf("")
	g.pf("// MarshalJSONTo implements encoding/json/v2.MarshalerTo.")
	g.pf("func (v %s) MarshalJSONTo(enc *jsontext.Encoder) error {", s.Expr)
	g.pf("\t// A top-level value under a plain json.Marshal is appended straight")
	g.pf("\t// into the encoder's buffer; see odjsonrt.BeginDirectEncode for what")
	g.pf("\t// qualifies. Nothing downstream looks at those bytes, so ModeV2 does")
	g.pf("\t// json/v2's own escaping and rejects invalid UTF-8 itself.")
	g.pf("\tif buf, ok := odjsonrt.BeginDirectEncode(enc); ok {")
	g.pf("\t\tbuf, err := v.odjsonAppend(buf, odjsonrt.ModeV2)")
	g.pf("\t\tif err != nil {")
	g.pf("\t\t\treturn err")
	g.pf("\t\t}")
	g.pf("\t\todjsonSize%s.Record(buf)", name)
	g.pf("\t\todjsonrt.EndDirectEncode(enc, buf)")
	g.pf("\t\treturn nil")
	g.pf("\t}")
	g.pf("\t// Otherwise WriteValue copies what it is given, so the scratch buffer")
	g.pf("\t// can go straight back to the pool. ModeStream leaves the HTML escaping")
	g.pf("\t// and the UTF-8 validation to the encoder, which performs both while")
	g.pf("\t// reformatting the value either way.")
	g.pf("\tbuf := odjsonrt.GetBuffer()")
	g.pf("\tvar err error")
	g.pf("\tif buf.B, err = v.odjsonAppend(buf.B, odjsonrt.ModeStream); err == nil {")
	g.pf("\t\todjsonSize%s.Record(buf.B)", name)
	g.pf("\t\terr = enc.WriteValue(buf.B)")
	g.pf("\t}")
	g.pf("\todjsonrt.PutBuffer(buf)")
	g.pf("\treturn err")
	g.pf("}")

	g.pf("")
	g.pf("// UnmarshalJSONFrom implements encoding/json/v2.UnmarshalerFrom.")
	g.pf("func (v *%s) UnmarshalJSONFrom(dec *jsontext.Decoder) error {", s.Expr)
	g.pf("\t// The cache plays the part of json/v2's own string cache: a value")
	g.pf("\t// that recurs in the document is allocated once.")
	g.pf("\t%s := odjsonrt.GetStringCache()", cache)
	g.pf("\tvar err error")
	g.pf("\t// A top-level value under a plain json.Unmarshal is parsed straight")
	g.pf("\t// out of the decoder's buffer; see odjsonrt.BeginDirectDecode for what")
	g.pf("\t// qualifies. Nobody has validated those bytes, so odjsonParseV2 rejects")
	g.pf("\t// what jsontext would have.")
	g.pf("\tif data, ok := odjsonrt.BeginDirectDecode(dec); ok {")
	g.pf("\t\tvar end int")
	g.pf("\t\tif end, err = v.odjsonParseV2(data, 0, %s, true); err == nil {", cache)
	g.pf("\t\t\todjsonrt.EndDirectDecode(dec, end)")
	g.pf("\t\t}")
	g.pf("\t} else {")
	g.pf("\t\terr = v.odjsonParseFrom(dec, %s)", cache)
	g.pf("\t}")
	g.pf("\todjsonrt.PutStringCache(%s)", cache)
	g.pf("\treturn err")
	g.pf("}")
}

// selector renders the Go expression selecting f from the receiver variable.
func selector(f *analyzer.Field) string {
	var b strings.Builder
	b.WriteString("v")
	for _, s := range f.Steps {
		b.WriteByte('.')
		b.WriteString(s.Name)
	}
	b.WriteByte('.')
	b.WriteString(f.Name)
	return b.String()
}

// guard renders the nil checks required to reach f through embedded pointers.
func guard(f *analyzer.Field) string {
	var conds []string
	path := "v"
	for _, s := range f.Steps {
		path += "." + s.Name
		if s.Ptr {
			conds = append(conds, path+" != nil")
		}
	}
	return strings.Join(conds, " && ")
}

// addr renders the address of expr, collapsing the &(*x) that a pointer field
// would otherwise produce back to x.
func addr(expr string) string {
	if strings.HasPrefix(expr, "(*") && strings.HasSuffix(expr, ")") {
		return expr[2 : len(expr)-1]
	}
	return "&" + expr
}

func quoteBytes(s string) string {
	return strconv.Quote(s)
}
