// Package codegen turns odjson's intermediate representation into Go source
// implementing reflection-free JSON encoders and decoders.
package codegen

import (
	"go/ast"
	"go/token"
	"strconv"

	"github.com/mazrean/odjson/internal/analyzer"
)

// Options configures the generated code.
type Options struct {
	// EscapeHTML mirrors encoding/json's default of escaping <, > and & so
	// the output is safe to embed in HTML.
	EscapeHTML bool
	// CaseInsensitive enables encoding/json's fallback that matches an
	// object member to a field name ignoring case.
	CaseInsensitive bool
	// Command is recorded in the file header.
	Command string
}

type generator struct {
	opts Options
	pkg  *analyzer.Package
	n    int

	// decls and comments are the file so far; line is the number of lines
	// they occupy. See emit.go for how lines become positions.
	decls    []ast.Decl
	comments []*ast.CommentGroup
	line     int
}

// ctx names the variables a decoding fragment reads from, and how it reports
// failure.
type ctx struct {
	data string
	pos  string
	ret  string
	// single makes the fragment return only an error, which is what the
	// jsontext driven decoders need.
	single bool
	// trusted tells the fragment that the bytes came from a
	// jsontext.Decoder, which has already validated their UTF-8.
	trusted bool
	// trimmed says the position is already at the first byte of the value,
	// so the fragment's leading whitespace skip can be dropped.
	trimmed bool
	// v2 selects encoding/json/v2's decoding semantics: a null stores the
	// zero value whatever the target, and a fixed size array must match the
	// document's length exactly.
	v2 bool
	// cache names the *odjsonrt.StringCache the fragment interns strings
	// through, or is empty when it allocates every string.
	cache string
	// strict says nobody has validated the bytes, so the fragment must
	// reject what encoding/json/v2 rejects: invalid UTF-8 and duplicate
	// object names.
	strict bool
}

// fail renders the statement returning x as the fragment's error.
func (c ctx) fail(x ast.Expr) ast.Stmt {
	if c.single {
		return ret(x)
	}
	return ret(id(c.ret), x)
}

// Generate renders the complete generated file for pkg.
func Generate(pkg *analyzer.Package, opts Options) (src []byte, err error) {
	defer func() {
		if r := recover(); r != nil {
			te, ok := r.(*typeError)
			if !ok {
				panic(r)
			}
			src, err = nil, te
		}
	}()
	g := &generator{opts: opts, pkg: pkg}

	pkg.Imports.Add(analyzer.RuntimePath, "odjsonrt")
	for _, s := range pkg.Structs {
		g.structCodec(s)
	}

	header := []string{"// Code generated by odjson. DO NOT EDIT."}
	if opts.Command != "" {
		header = append(header, "//", "// Source: "+opts.Command)
	}

	// Rendering a type expression registers its package, even when the
	// expression never reaches the output — json.RawMessage, for instance, is
	// only ever converted to []byte. Drop those again by looking at which
	// identifiers the finished tree actually qualifies.
	return g.render(header, pkg.Imports.LinesFor(qualifiers(g.decls)))
}

// qualifiers returns the set of identifiers the declarations use on the left
// of a selector, which is exactly the set of import identifiers they need.
func qualifiers(decls []ast.Decl) map[string]bool {
	used := map[string]bool{}
	for _, d := range decls {
		ast.Inspect(d, func(n ast.Node) bool {
			if sel, ok := n.(*ast.SelectorExpr); ok {
				if id, ok := sel.X.(*ast.Ident); ok {
					used[id.Name] = true
				}
			}
			return true
		})
	}
	return used
}

func (g *generator) tmp(prefix string) string {
	g.n++
	return prefix + strconv.Itoa(g.n)
}

// Identifiers the generated codecs share.
var (
	v    = id("v")
	dst  = id("dst")
	data = id("data")
	p    = id("p")
	errV = id("err")
	nilV = id("nil")
)

// receiver renders (v *T), or (v T) when value is set.
func receiver(s *analyzer.StructInfo, value bool) *ast.Field {
	if value {
		return field("v", typ(s.Expr))
	}
	return field("v", ptr(typ(s.Expr)))
}

// structCodec writes every function and method belonging to one struct type.
func (g *generator) structCodec(s *analyzer.StructInfo) {
	mode := field("m", rt("StringMode"))
	cacheParam := field(cache, ptr(rt("StringCache")))
	if s.Local {
		g.funcDecl([]string{"// odjsonAppend appends the JSON encoding of v to dst."},
			receiver(s, false), "odjsonAppend",
			signature([]*ast.Field{field("dst", sliceType(id("byte"))), mode}, sliceType(id("byte")), id("error")),
			func(b *block) { g.encodeStruct(b, s) })
	} else {
		g.funcDecl([]string{"// " + s.Helper + "Append appends the JSON encoding of v to dst."},
			nil, s.Helper+"Append",
			signature([]*ast.Field{field("dst", sliceType(id("byte"))), receiver(s, false), mode}, sliceType(id("byte")), id("error")),
			func(b *block) { g.encodeStruct(b, s) })
	}

	parseDoc := func(name string) []string {
		return []string{
			"// " + name + " decodes the JSON object starting at p into v and",
			"// returns the offset just past it. Strings are interned through",
			"// " + cache + ", which may be nil.",
		}
	}
	parseCtx := ctx{data: "data", pos: "p", ret: "p", cache: cache}
	if s.Local {
		g.funcDecl(parseDoc("odjsonParse"), receiver(s, false), "odjsonParse",
			signature([]*ast.Field{field("data", sliceType(id("byte"))), field("p", id("int")), cacheParam}, id("int"), id("error")),
			func(b *block) { g.decodeStruct(b, s, parseCtx) })
	} else {
		g.funcDecl(parseDoc(s.Helper+"Parse"), nil, s.Helper+"Parse",
			signature([]*ast.Field{field("data", sliceType(id("byte"))), receiver(s, false), field("p", id("int")), cacheParam}, id("int"), id("error")),
			func(b *block) { g.decodeStruct(b, s, parseCtx) })
	}

	g.pkg.Imports.Add(analyzer.JSONTextPath, "jsontext")
	v2Doc := func(name, base string) []string {
		return []string{
			"// " + name + " is " + base + " under encoding/json/v2's semantics, for",
			"// input a jsontext.Decoder has already validated when strict is false,",
			"// and for bytes nobody has looked at when it is true.",
		}
	}
	v2Ctx := ctx{data: "data", pos: "p", ret: "p", v2: true, cache: cache, strict: true}
	strict := field("strict", id("bool"))
	if s.Local {
		g.funcDecl(v2Doc("odjsonParseV2", "odjsonParse"), receiver(s, false), "odjsonParseV2",
			signature([]*ast.Field{field("data", sliceType(id("byte"))), field("p", id("int")), cacheParam, strict}, id("int"), id("error")),
			func(b *block) { g.decodeStruct(b, s, v2Ctx) })
	} else {
		g.funcDecl(v2Doc(s.Helper+"ParseV2", s.Helper+"Parse"), nil, s.Helper+"ParseV2",
			signature([]*ast.Field{field("data", sliceType(id("byte"))), receiver(s, false), field("p", id("int")), cacheParam, strict}, id("int"), id("error")),
			func(b *block) { g.decodeStruct(b, s, v2Ctx) })
	}
	fromDoc := func(name string) []string {
		return []string{
			"// " + name + " decodes the next value in dec into v,",
			"// driving the decoder token by token so the document is",
			"// parsed once rather than twice.",
		}
	}
	dec := field("dec", ptr(sel(id("jsontext"), "Decoder")))
	if s.Local {
		g.funcDecl(fromDoc("odjsonParseFrom"), receiver(s, false), "odjsonParseFrom",
			signature([]*ast.Field{dec, cacheParam}, id("error")),
			func(b *block) { g.decodeStructFrom(b, s) })
	} else {
		g.funcDecl(fromDoc(s.Helper+"ParseFrom"), nil, s.Helper+"ParseFrom",
			signature([]*ast.Field{dec, receiver(s, false), cacheParam}, id("error")),
			func(b *block) { g.decodeStructFrom(b, s) })
	}

	if !s.Local {
		return
	}

	name := s.Name
	size := id("odjsonSize" + name)
	sc := id(cache)

	g.varDeclTop([]string{"// odjsonSize" + name + " sizes the buffer the encoders allocate."},
		"odjsonSize"+name, rt("SizeHint"))

	g.funcDecl([]string{"// MarshalJSON implements encoding/json.Marshaler."},
		receiver(s, true), "MarshalJSON",
		signature(nil, sliceType(id("byte")), id("error")),
		func(b *block) {
			buf := id("buf")
			g.emit(b, assignN(token.DEFINE, []ast.Expr{buf, errV},
				call(sel(v, "odjsonAppend"), call(sel(size, "New")), g.v1Mode())))
			g.ifStmt(b, nil, bin(errV, token.NEQ, nilV), func(b *block) {
				g.emit(b, ret(nilV, errV))
			})
			g.emit(b, expr(call(sel(size, "Record"), buf)))
			g.emit(b, ret(buf, nilV))
		})

	g.funcDecl([]string{"// UnmarshalJSON implements encoding/json.Unmarshaler."},
		receiver(s, false), "UnmarshalJSON",
		signature([]*ast.Field{field("data", sliceType(id("byte")))}, id("error")),
		func(b *block) {
			g.comment(b,
				"// The cache plays the part of encoding/json/v2's string cache: a",
				"// value that recurs in the document is allocated once.")
			g.emit(b, define(sc, callRT("GetStringCache")))
			g.emit(b, assignN(token.DEFINE, []ast.Expr{p, errV},
				call(sel(v, "odjsonParse"), data, callRT("SkipSpace", data, num(0)), sc)))
			g.emit(b, expr(callRT("PutStringCache", sc)))
			g.ifStmt(b, nil, bin(errV, token.NEQ, nilV), func(b *block) {
				g.emit(b, ret(errV))
			})
			g.emit(b, ret(callRT("EndOfDocument", data, p)))
		})

	enc, decV := id("enc"), id("dec")
	g.funcDecl([]string{"// MarshalJSONTo implements encoding/json/v2.MarshalerTo."},
		receiver(s, true), "MarshalJSONTo",
		signature([]*ast.Field{field("enc", ptr(sel(id("jsontext"), "Encoder")))}, id("error")),
		func(b *block) {
			buf, n, m := id("buf"), id("n"), id("m")
			g.comment(b,
				"// Under a plain json.Marshal, from encoding/json/v2 or encoding/json,",
				"// the value is appended straight into the encoder's buffer at any",
				"// depth; see odjsonrt.BeginDirectEncodeMode for what qualifies and",
				"// for the mode, which does that call's escaping itself since nothing",
				"// downstream looks at the bytes.")
			g.ifStmt(b,
				assignN(token.DEFINE, []ast.Expr{buf, m, id("ok")}, callRT("BeginDirectEncodeMode", enc)),
				id("ok"),
				func(b *block) {
					g.emit(b, define(n, call(id("len"), buf)))
					g.emit(b, assignN(token.DEFINE, []ast.Expr{buf, errV},
						call(sel(v, "odjsonAppend"), buf, m)))
					g.ifStmt(b, nil, bin(errV, token.NEQ, nilV), func(b *block) {
						g.emit(b, ret(errV))
					})
					g.emit(b, expr(call(sel(size, "Record"), slice(buf, n, nil))))
					g.emit(b, expr(callRT("EndDirectEncode", enc, buf)))
					g.emit(b, ret(nilV))
				})
			g.comment(b,
				"// Otherwise WriteValue copies what it is given, so the scratch buffer",
				"// can go straight back to the pool. ModeStream leaves the HTML escaping",
				"// and the UTF-8 validation to the encoder, which performs both while",
				"// reformatting the value either way.")
			g.emit(b, define(buf, callRT("GetBuffer")))
			g.emit(b, varDecl("err", id("error")))
			g.ifStmt(b,
				assignN(token.ASSIGN, []ast.Expr{sel(buf, "B"), errV},
					call(sel(v, "odjsonAppend"), sel(buf, "B"), rt("ModeStream"))),
				bin(errV, token.EQL, nilV),
				func(b *block) {
					g.emit(b, expr(call(sel(size, "Record"), sel(buf, "B"))))
					g.emit(b, assign(errV, call(sel(enc, "WriteValue"), sel(buf, "B"))))
				})
			g.emit(b, expr(callRT("PutBuffer", buf)))
			g.emit(b, ret(errV))
		})

	g.funcDecl([]string{"// UnmarshalJSONFrom implements encoding/json/v2.UnmarshalerFrom."},
		receiver(s, false), "UnmarshalJSONFrom",
		signature([]*ast.Field{field("dec", ptr(sel(id("jsontext"), "Decoder")))}, id("error")),
		func(b *block) {
			g.comment(b,
				"// The cache plays the part of json/v2's own string cache: a value",
				"// that recurs in the document is allocated once.")
			g.emit(b, define(sc, callRT("GetStringCache")))
			g.emit(b, varDecl("err", id("error")))
			g.comment(b,
				"// Under a plain json.Unmarshal the value is parsed straight out of",
				"// the decoder's buffer at any depth; see odjsonrt.BeginDirectDecodeAt",
				"// for what qualifies. Nobody has validated those bytes, so",
				"// odjsonParseV2 rejects what jsontext would have.")
			s := g.ifStmt(b,
				assignN(token.DEFINE, []ast.Expr{data, p, id("ok")}, callRT("BeginDirectDecodeAt", decV)),
				id("ok"),
				func(b *block) {
					end := id("end")
					g.emit(b, varDecl("end", id("int")))
					g.ifStmt(b,
						assignN(token.ASSIGN, []ast.Expr{end, errV},
							call(sel(v, "odjsonParseV2"), data, p, sc, id("true"))),
						bin(errV, token.EQL, nilV),
						func(b *block) {
							g.emit(b, expr(callRT("EndDirectDecodeAt", decV, p, end)))
						})
				})
			g.elseBlock(s, func(b *block) {
				g.emit(b, assign(errV, call(sel(v, "odjsonParseFrom"), decV, sc)))
			})
			g.emit(b, expr(callRT("PutStringCache", sc)))
			g.emit(b, ret(errV))
		})
}

// selector renders the Go expression selecting f from the receiver variable.
func selector(f *analyzer.Field) ast.Expr {
	var x ast.Expr = v
	for _, s := range f.Steps {
		x = sel(x, s.Name)
	}
	return sel(x, f.Name)
}

// guard renders the nil checks required to reach f through embedded pointers,
// or nil when there are none.
func guard(f *analyzer.Field) ast.Expr {
	var conds []ast.Expr
	var path ast.Expr = v
	for _, s := range f.Steps {
		path = sel(path, s.Name)
		if s.Ptr {
			conds = append(conds, bin(path, token.NEQ, nilV))
		}
	}
	if len(conds) == 0 {
		return nil
	}
	return and(conds...)
}

// addr renders the address of x, collapsing the &(*x) that a pointer field
// would otherwise produce back to x.
func addr(x ast.Expr) ast.Expr {
	if pe, ok := x.(*ast.ParenExpr); ok {
		if se, ok := pe.X.(*ast.StarExpr); ok {
			return se.X
		}
	}
	return ref(x)
}
