// Code generated by odjson. DO NOT EDIT.
//
// Source: odjson

package fallback

import (
	"github.com/mazrean/odjson/odjsonrt"
)

// odjsonAppend appends the JSON encoding of v to dst.
func (v *Fallbacks) odjsonAppend(dst []byte) ([]byte, error) {
	var err error
	_ = err
	start := len(dst)
	dst = append(dst, ",\"generic\":"...)
	dst, err = odjsonrt.AppendAny(dst, v.Generic, true)
	if err != nil {
		return nil, err
	}
	dst = append(dst, ",\"generic_ptr\":"...)
	if v.GenericPtr == nil {
		dst = append(dst, 'n', 'u', 'l', 'l')
	} else {
		dst, err = odjsonrt.AppendAny(dst, (*v.GenericPtr), true)
		if err != nil {
			return nil, err
		}
	}
	dst = append(dst, ",\"anon\":"...)
	dst, err = odjsonrt.AppendAny(dst, v.Anon, true)
	if err != nil {
		return nil, err
	}
	dst = append(dst, ",\"int_map\":"...)
	dst, err = odjsonrt.AppendAny(dst, v.IntMap, true)
	if err != nil {
		return nil, err
	}
	dst = append(dst, ",\"custom\":"...)
	dst, err = odjsonrt.AppendMarshaler(dst, v.Custom, true)
	if err != nil {
		return nil, err
	}
	dst = append(dst, ",\"custom_ptr\":"...)
	if v.CustomPtr == nil {
		dst = append(dst, 'n', 'u', 'l', 'l')
	} else {
		dst, err = odjsonrt.AppendMarshaler(dst, (*v.CustomPtr), true)
		if err != nil {
			return nil, err
		}
	}
	dst = append(dst, ",\"text\":"...)
	dst, err = odjsonrt.AppendTextMarshaler(dst, v.Text, true)
	if err != nil {
		return nil, err
	}
	dst = append(dst, ",\"text_ptr\":"...)
	if v.TextPtr == nil {
		dst = append(dst, 'n', 'u', 'l', 'l')
	} else {
		dst, err = odjsonrt.AppendTextMarshaler(dst, (*v.TextPtr), true)
		if err != nil {
			return nil, err
		}
	}
	dst = append(dst, ",\"plain\":"...)
	dst = odjsonrt.AppendString(dst, string(v.Plain), true)
	if len(dst) == start {
		dst = append(dst, '{', '}')
	} else {
		dst[start] = '{'
		dst = append(dst, '}')
	}
	return dst, nil
}

// odjsonParse decodes the JSON object starting at p into v and
// returns the offset just past it.
func (v *Fallbacks) odjsonParse(data []byte, p int) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		return np, nil
	}
	if p >= len(data) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "Fallbacks")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if p < len(data) && data[p] == '}' {
		return p + 1, nil
	}
	for {
		var key []byte
		p = odjsonrt.SkipSpace(data, p)
		key, _, p, err = odjsonrt.ParseKey(data, p)
		if err != nil {
			return p, err
		}
		p = odjsonrt.SkipSpace(data, p)
		idx := -1
		switch string(key) {
		case "generic":
			idx = 0
		case "generic_ptr":
			idx = 1
		case "anon":
			idx = 2
		case "int_map":
			idx = 3
		case "custom":
			idx = 4
		case "custom_ptr":
			idx = 5
		case "text":
			idx = 6
		case "text_ptr":
			idx = 7
		case "plain":
			idx = 8
		}
		if idx < 0 {
			switch {
			case odjsonrt.EqualFold(key, "generic"):
				idx = 0
			case odjsonrt.EqualFold(key, "generic_ptr"):
				idx = 1
			case odjsonrt.EqualFold(key, "anon"):
				idx = 2
			case odjsonrt.EqualFold(key, "int_map"):
				idx = 3
			case odjsonrt.EqualFold(key, "custom"):
				idx = 4
			case odjsonrt.EqualFold(key, "custom_ptr"):
				idx = 5
			case odjsonrt.EqualFold(key, "text"):
				idx = 6
			case odjsonrt.EqualFold(key, "text_ptr"):
				idx = 7
			case odjsonrt.EqualFold(key, "plain"):
				idx = 8
			}
		}
		switch idx {
		case 0:
			p = odjsonrt.SkipSpace(data, p)
			if np1, ok2 := odjsonrt.ParseNull(data, p); ok2 {
				p = np1
			} else {
				p, err = odjsonrt.ParseInto(data, p, &v.Generic)
				if err != nil {
					return p, err
				}
			}
		case 1:
			p = odjsonrt.SkipSpace(data, p)
			if np3, ok4 := odjsonrt.ParseNull(data, p); ok4 {
				v.GenericPtr = nil
				p = np3
			} else {
				if v.GenericPtr == nil {
					v.GenericPtr = new(Box[string])
				}
				p = odjsonrt.SkipSpace(data, p)
				if np5, ok6 := odjsonrt.ParseNull(data, p); ok6 {
					p = np5
				} else {
					p, err = odjsonrt.ParseInto(data, p, v.GenericPtr)
					if err != nil {
						return p, err
					}
				}
			}
		case 2:
			p = odjsonrt.SkipSpace(data, p)
			if np7, ok8 := odjsonrt.ParseNull(data, p); ok8 {
				p = np7
			} else {
				p, err = odjsonrt.ParseInto(data, p, &v.Anon)
				if err != nil {
					return p, err
				}
			}
		case 3:
			p = odjsonrt.SkipSpace(data, p)
			if np9, ok10 := odjsonrt.ParseNull(data, p); ok10 {
				p = np9
			} else {
				p, err = odjsonrt.ParseInto(data, p, &v.IntMap)
				if err != nil {
					return p, err
				}
			}
		case 4:
			p, err = odjsonrt.ParseUnmarshaler(data, p, &v.Custom)
			if err != nil {
				return p, err
			}
		case 5:
			p = odjsonrt.SkipSpace(data, p)
			if np11, ok12 := odjsonrt.ParseNull(data, p); ok12 {
				v.CustomPtr = nil
				p = np11
			} else {
				if v.CustomPtr == nil {
					v.CustomPtr = new(Custom)
				}
				p, err = odjsonrt.ParseUnmarshaler(data, p, v.CustomPtr)
				if err != nil {
					return p, err
				}
			}
		case 6:
			p = odjsonrt.SkipSpace(data, p)
			if np13, ok14 := odjsonrt.ParseNull(data, p); ok14 {
				p = np13
			} else {
				p, err = odjsonrt.ParseTextUnmarshaler(data, p, &v.Text)
				if err != nil {
					return p, err
				}
			}
		case 7:
			p = odjsonrt.SkipSpace(data, p)
			if np15, ok16 := odjsonrt.ParseNull(data, p); ok16 {
				v.TextPtr = nil
				p = np15
			} else {
				if v.TextPtr == nil {
					v.TextPtr = new(Textual)
				}
				p = odjsonrt.SkipSpace(data, p)
				if np17, ok18 := odjsonrt.ParseNull(data, p); ok18 {
					p = np17
				} else {
					p, err = odjsonrt.ParseTextUnmarshaler(data, p, v.TextPtr)
					if err != nil {
						return p, err
					}
				}
			}
		case 8:
			p = odjsonrt.SkipSpace(data, p)
			if np19, ok20 := odjsonrt.ParseNull(data, p); ok20 {
				p = np19
			} else {
				var x21 string
				x21, p, err = odjsonrt.ParseString(data, p)
				if err != nil {
					return p, err
				}
				v.Plain = x21
			}
		default:
			p, err = odjsonrt.SkipValue(data, p)
			if err != nil {
				return p, err
			}
		}
		p = odjsonrt.SkipSpace(data, p)
		if p >= len(data) {
			return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
		}
		switch data[p] {
		case ',':
			p++
		case '}':
			return p + 1, nil
		default:
			return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
		}
	}
}

// AppendFallbacks appends the JSON encoding of v to dst.
func AppendFallbacks(dst []byte, v *Fallbacks) ([]byte, error) {
	return v.odjsonAppend(dst)
}

// odjsonSizeFallbacks sizes the buffer MarshalFallbacks allocates.
var odjsonSizeFallbacks odjsonrt.SizeHint

// MarshalFallbacks returns the JSON encoding of v.
func MarshalFallbacks(v *Fallbacks) ([]byte, error) {
	buf, err := v.odjsonAppend(odjsonSizeFallbacks.New())
	if err != nil {
		return nil, err
	}
	odjsonSizeFallbacks.Record(buf)
	return buf, nil
}

// UnmarshalFallbacks decodes the JSON document data into v.
func UnmarshalFallbacks(data []byte, v *Fallbacks) error {
	p, err := v.odjsonParse(data, odjsonrt.SkipSpace(data, 0))
	if err != nil {
		return err
	}
	return odjsonrt.EndOfDocument(data, p)
}
