// Code generated by odjson. DO NOT EDIT.
//
// Source: odjson

package withmethods

import (
	"bytes"
	"encoding/json/jsontext"
	"github.com/mazrean/odjson/odjsonrt"
)

// odjsonAppend appends the JSON encoding of v to dst.
func (v *Address) odjsonAppend(dst []byte, m odjsonrt.StringMode) ([]byte, error) {
	var err error
	_ = err
	start := len(dst)
	dst = append(dst, ",\"street\":\""...)
	dst, err = odjsonrt.AppendStringBodyChecked(dst, string(v.Street), m)
	if err != nil {
		return nil, err
	}
	dst = append(dst, "\""...)
	if len(v.City) != 0 {
		dst = append(dst, ",\"city\":\""...)
		dst, err = odjsonrt.AppendStringBodyChecked(dst, string(v.City), m)
		if err != nil {
			return nil, err
		}
		dst = append(dst, "\""...)
	}
	dst[start] = '{'
	dst = append(dst, "}"...)
	return dst, nil
}

// odjsonParse decodes the JSON object starting at p into v and
// returns the offset just past it. Strings are interned through
// sc, which may be nil.
func (v *Address) odjsonParse(data []byte, p int, sc *odjsonrt.StringCache) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		return np, nil
	}
	if uint(p) >= uint(len(data)) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "Address")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if uint(p) < uint(len(data)) && data[p] == '}' {
		return p + 1, nil
	}
	for {
		if uint(p) >= uint(len(data)) || data[p] <= ' ' {
			p = odjsonrt.SkipSpace(data, odjsonrt.SkipIndent(data, p))
		}
		rest := data[p:]
		if len(rest) > 1 {
			switch rest[1] {
			case 's':
				if len(rest) >= 8 && string(rest[:8]) == "\"street\"" {
					p += 8
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m1
				}
			case 'c':
				if len(rest) >= 6 && string(rest[:6]) == "\"city\"" {
					p += 6
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m2
				}
			}
		}
		{
			var key []byte
			key, _, p, err = odjsonrt.ParseKey(data, p)
			if err != nil {
				return p, err
			}
			switch string(key) {
			case "street":
				goto m1
			case "city":
				goto m2
			}
			p = odjsonrt.SkipSpace(data, p)
			p, err = odjsonrt.SkipValue(data, p)
			if err != nil {
				return p, err
			}
			goto next3
		}
	m1:
		{
			if np4, ok5 := odjsonrt.ParseNull(data, p); ok5 {
				p = np4
			} else {
				var x6 string
				x6, p, err = odjsonrt.ParseStringCached(data, p, sc)
				if err != nil {
					return p, err
				}
				v.Street = x6
			}
			goto next3
		}
	m2:
		{
			if np7, ok8 := odjsonrt.ParseNull(data, p); ok8 {
				p = np7
			} else {
				var x9 string
				x9, p, err = odjsonrt.ParseStringCached(data, p, sc)
				if err != nil {
					return p, err
				}
				v.City = x9
			}
		}
	next3:
		{
			p = odjsonrt.SkipSpace(data, p)
			if uint(p) >= uint(len(data)) {
				return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
			}
			switch data[p] {
			case ',':
				p++
			case '}':
				return p + 1, nil
			default:
				return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
			}
		}
	}
}

// odjsonParseV2 is odjsonParse under encoding/json/v2's semantics, for
// input a jsontext.Decoder has already validated when strict is false,
// and for bytes nobody has looked at when it is true.
func (v *Address) odjsonParseV2(data []byte, p int, sc *odjsonrt.StringCache, strict bool) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		*v = Address{}
		return np, nil
	}
	if uint(p) >= uint(len(data)) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "Address")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if uint(p) < uint(len(data)) && data[p] == '}' {
		return p + 1, nil
	}
	var seen [1]uint64
	_ = seen
	unknown, umark := odjsonrt.UnknownNames(sc)
	var ufilter uint64
	_ = ufilter
	for {
		if uint(p) >= uint(len(data)) || data[p] <= ' ' {
			p = odjsonrt.SkipSpace(data, odjsonrt.SkipIndent(data, p))
		}
		kp := p
		rest := data[p:]
		if len(rest) > 1 {
			switch rest[1] {
			case 's':
				if len(rest) >= 8 && string(rest[:8]) == "\"street\"" {
					p += 8
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m10
				}
			case 'c':
				if len(rest) >= 6 && string(rest[:6]) == "\"city\"" {
					p += 6
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m11
				}
			}
		}
		{
			var key []byte
			key, p, err = odjsonrt.ParseKeyV2(data, p, strict)
			if err != nil {
				return p, err
			}
			switch string(key) {
			case "street":
				goto m10
			case "city":
				goto m11
			}
			if strict {
				var dup bool
				if unknown, dup = odjsonrt.UnknownName(sc, unknown, umark, &ufilter, key); dup {
					return kp, odjsonrt.ErrDuplicateName(data, kp, key)
				}
			}
			p = odjsonrt.SkipSpace(data, p)
			p, err = odjsonrt.SkipValueV2(data, p, strict)
			if err != nil {
				return p, err
			}
			goto next12
		}
	m10:
		{
			if strict && seen[0]&(1<<0) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 0
			if np13, ok14 := odjsonrt.ParseNull(data, p); ok14 {
				p = np13
				v.Street = ""
			} else {
				var x15 string
				x15, p, err = odjsonrt.ParseStringV2(data, p, sc, strict)
				if err != nil {
					return p, err
				}
				v.Street = x15
			}
			goto next12
		}
	m11:
		{
			if strict && seen[0]&(1<<1) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 1
			if np16, ok17 := odjsonrt.ParseNull(data, p); ok17 {
				p = np16
				v.City = ""
			} else {
				var x18 string
				x18, p, err = odjsonrt.ParseStringV2(data, p, sc, strict)
				if err != nil {
					return p, err
				}
				v.City = x18
			}
		}
	next12:
		{
			p = odjsonrt.SkipSpace(data, p)
			if uint(p) >= uint(len(data)) {
				return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
			}
			switch data[p] {
			case ',':
				p++
			case '}':
				odjsonrt.EndUnknownNames(sc, unknown, umark)
				return p + 1, nil
			default:
				return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
			}
		}
	}
}

// odjsonParseFrom decodes the next value in dec into v,
// driving the decoder token by token so the document is
// parsed once rather than twice.
func (v *Address) odjsonParseFrom(dec *jsontext.Decoder, sc *odjsonrt.StringCache) error {
	var err error
	_ = err
	if odjsonrt.WholeValue(dec) {
		var val jsontext.Value
		if val, err = dec.ReadValue(); err != nil {
			return err
		}
		_, err = v.odjsonParseV2(val, 0, sc, false)
		return err
	}
	switch odjsonrt.NextKind(dec) {
	case 'n':
		if _, err = dec.ReadToken(); err != nil {
			return err
		}
		*v = Address{}
		return nil
	case '{':
	default:
		return odjsonrt.ErrKindFrom(dec, "Address")
	}
	if _, err = dec.ReadToken(); err != nil {
		return err
	}
	for odjsonrt.NextKind(dec) != '}' {
		var key jsontext.Value
		key, err = dec.ReadValue()
		if err != nil {
			return err
		}
		idx := -1
		switch string(key) {
		case "\"street\"":
			idx = 0
		case "\"city\"":
			idx = 1
		}
		if idx < 0 && bytes.IndexByte(key, '\\') >= 0 {
			if name, ok := odjsonrt.UnquoteName(key); ok {
				switch string(name) {
				case "street":
					idx = 0
				case "city":
					idx = 1
				}
			}
		}
		switch idx {
		case 0:
			var val19 jsontext.Value
			val19, err = dec.ReadValue()
			if err != nil {
				return err
			}
			if val19[0] == 'n' {
				v.Street = ""
			} else {
				var x20 string
				x20, err = odjsonrt.ParseStringValue(val19, sc)
				if err != nil {
					return err
				}
				v.Street = x20
			}
		case 1:
			var val21 jsontext.Value
			val21, err = dec.ReadValue()
			if err != nil {
				return err
			}
			if val21[0] == 'n' {
				v.City = ""
			} else {
				var x22 string
				x22, err = odjsonrt.ParseStringValue(val21, sc)
				if err != nil {
					return err
				}
				v.City = x22
			}
		default:
			if _, err = dec.ReadValue(); err != nil {
				return err
			}
		}
	}
	_, err = dec.ReadToken()
	return err
}

// odjsonSizeAddress sizes the buffer the encoders allocate.
var odjsonSizeAddress odjsonrt.SizeHint

// MarshalJSON implements encoding/json.Marshaler.
func (v Address) MarshalJSON() ([]byte, error) {
	buf, err := v.odjsonAppend(odjsonSizeAddress.New(), odjsonrt.ModeHTML)
	if err != nil {
		return nil, err
	}
	odjsonSizeAddress.Record(buf)
	return buf, nil
}

// UnmarshalJSON implements encoding/json.Unmarshaler.
func (v *Address) UnmarshalJSON(data []byte) error {
	// The cache plays the part of encoding/json/v2's string cache: a
	// value that recurs in the document is allocated once.
	sc := odjsonrt.GetStringCache()
	p, err := v.odjsonParse(data, odjsonrt.SkipSpace(data, 0), sc)
	odjsonrt.PutStringCache(sc)
	if err != nil {
		return err
	}
	return odjsonrt.EndOfDocument(data, p)
}

// MarshalJSONTo implements encoding/json/v2.MarshalerTo.
func (v Address) MarshalJSONTo(enc *jsontext.Encoder) error {
	// Under a plain json.Marshal, from encoding/json/v2 or encoding/json,
	// the value is appended straight into the encoder's buffer at any
	// depth; see odjsonrt.BeginDirectEncodeMode for what qualifies and
	// for the mode, which does that call's escaping itself since nothing
	// downstream looks at the bytes.
	if buf, m, ok := odjsonrt.BeginDirectEncodeMode(enc); ok {
		n := len(buf)
		buf, err := v.odjsonAppend(buf, m)
		if err != nil {
			return err
		}
		odjsonSizeAddress.Record(buf[n:])
		odjsonrt.EndDirectEncode(enc, buf)
		return nil
	}
	// Otherwise WriteValue copies what it is given, so the scratch buffer
	// can go straight back to the pool. ModeStream leaves the HTML escaping
	// and the UTF-8 validation to the encoder, which performs both while
	// reformatting the value either way.
	buf := odjsonrt.GetBuffer()
	var err error
	if buf.B, err = v.odjsonAppend(buf.B, odjsonrt.ModeStream); err == nil {
		odjsonSizeAddress.Record(buf.B)
		err = enc.WriteValue(buf.B)
	}
	odjsonrt.PutBuffer(buf)
	return err
}

// UnmarshalJSONFrom implements encoding/json/v2.UnmarshalerFrom.
func (v *Address) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	// The cache plays the part of json/v2's own string cache: a value
	// that recurs in the document is allocated once.
	sc := odjsonrt.GetStringCache()
	var err error
	// Under a plain json.Unmarshal the value is parsed straight out of
	// the decoder's buffer at any depth; see odjsonrt.BeginDirectDecodeAt
	// for what qualifies. Nobody has validated those bytes, so
	// odjsonParseV2 rejects what jsontext would have.
	if data, p, ok := odjsonrt.BeginDirectDecodeAt(dec); ok {
		var end int
		if end, err = v.odjsonParseV2(data, p, sc, true); err == nil {
			odjsonrt.EndDirectDecodeAt(dec, p, end)
		}
	} else {
		err = v.odjsonParseFrom(dec, sc)
	}
	odjsonrt.PutStringCache(sc)
	return err
}

// odjsonAppend appends the JSON encoding of v to dst.
func (v *Person) odjsonAppend(dst []byte, m odjsonrt.StringMode) ([]byte, error) {
	var err error
	_ = err
	start := len(dst)
	dst = append(dst, ",\"name\":\""...)
	dst, err = odjsonrt.AppendStringBodyChecked(dst, string(v.Name), m)
	if err != nil {
		return nil, err
	}
	dst = append(dst, "\",\"age\":"...)
	dst = odjsonrt.AppendInt(dst, int64(v.Age))
	if v.Email != nil {
		if v.Email == nil {
			dst = append(dst, ",\"email\":null"...)
		} else {
			dst = append(dst, ",\"email\":\""...)
			dst, err = odjsonrt.AppendStringBodyChecked(dst, string((*v.Email)), m)
			if err != nil {
				return nil, err
			}
			dst = append(dst, "\""...)
		}
	}
	if len(v.Tags) != 0 {
		if v.Tags == nil {
			if m.V2() {
				dst = append(dst, ",\"tags\":[]"...)
			} else {
				dst = append(dst, ",\"tags\":null"...)
			}
		} else {
			dst = append(dst, ",\"tags\":["...)
			for i23 := range v.Tags {
				if i23 > 0 {
					dst = append(dst, ',')
				}
				dst = append(dst, "\""...)
				dst, err = odjsonrt.AppendStringBodyChecked(dst, string(v.Tags[i23]), m)
				if err != nil {
					return nil, err
				}
				dst = append(dst, "\""...)
			}
			dst = append(dst, "]"...)
		}
	}
	dst = append(dst, ",\"address\":"...)
	dst, err = v.Address.odjsonAppend(dst, m)
	if err != nil {
		return nil, err
	}
	dst[start] = '{'
	dst = append(dst, "}"...)
	return dst, nil
}

// odjsonCapPersonTags remembers how long v.Tags has been, to allocate it once.
var odjsonCapPersonTags odjsonrt.CapHint

// odjsonParse decodes the JSON object starting at p into v and
// returns the offset just past it. Strings are interned through
// sc, which may be nil.
func (v *Person) odjsonParse(data []byte, p int, sc *odjsonrt.StringCache) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		return np, nil
	}
	if uint(p) >= uint(len(data)) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "Person")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if uint(p) < uint(len(data)) && data[p] == '}' {
		return p + 1, nil
	}
	for {
		if uint(p) >= uint(len(data)) || data[p] <= ' ' {
			p = odjsonrt.SkipSpace(data, odjsonrt.SkipIndent(data, p))
		}
		rest := data[p:]
		if len(rest) > 3 {
			switch rest[3] {
			case 'm':
				if len(rest) >= 6 && string(rest[:6]) == "\"name\"" {
					p += 6
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m24
				}
			case 'e':
				if len(rest) >= 5 && string(rest[:5]) == "\"age\"" {
					p += 5
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m25
				}
			case 'a':
				if len(rest) >= 7 && string(rest[:7]) == "\"email\"" {
					p += 7
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m26
				}
			case 'g':
				if len(rest) >= 6 && string(rest[:6]) == "\"tags\"" {
					p += 6
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m27
				}
			case 'd':
				if len(rest) >= 9 && string(rest[:9]) == "\"address\"" {
					p += 9
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m28
				}
			}
		}
		{
			var key []byte
			key, _, p, err = odjsonrt.ParseKey(data, p)
			if err != nil {
				return p, err
			}
			switch string(key) {
			case "name":
				goto m24
			case "age":
				goto m25
			case "email":
				goto m26
			case "tags":
				goto m27
			case "address":
				goto m28
			}
			p = odjsonrt.SkipSpace(data, p)
			p, err = odjsonrt.SkipValue(data, p)
			if err != nil {
				return p, err
			}
			goto next29
		}
	m24:
		{
			if np30, ok31 := odjsonrt.ParseNull(data, p); ok31 {
				p = np30
			} else {
				var x32 string
				x32, p, err = odjsonrt.ParseStringCached(data, p, sc)
				if err != nil {
					return p, err
				}
				v.Name = x32
			}
			goto next29
		}
	m25:
		{
			if np33, ok34 := odjsonrt.ParseNull(data, p); ok34 {
				p = np33
			} else {
				if x35, np36, ok37 := odjsonrt.ParseDecimal(data, p); ok37 {
					v.Age = int(x35)
					p = np36
				} else {
					var x38 int64
					x38, p, err = odjsonrt.ParseInt(data, p, 64)
					if err != nil {
						return p, err
					}
					v.Age = int(x38)
				}
			}
			goto next29
		}
	m26:
		{
			if np39, ok40 := odjsonrt.ParseNull(data, p); ok40 {
				v.Email = nil
				p = np39
			} else {
				if v.Email == nil {
					v.Email = new(string)
				}
				p = odjsonrt.SkipSpace(data, p)
				if np41, ok42 := odjsonrt.ParseNull(data, p); ok42 {
					p = np41
				} else {
					var x43 string
					x43, p, err = odjsonrt.ParseStringCached(data, p, sc)
					if err != nil {
						return p, err
					}
					(*v.Email) = x43
				}
			}
			goto next29
		}
	m27:
		{
			if np44, ok45 := odjsonrt.ParseNull(data, p); ok45 {
				p = np44
				v.Tags = nil
			} else {
				if uint(p) >= uint(len(data)) || data[p] != '[' {
					return p, odjsonrt.ErrType(data, p, "[]string")
				}
				p++
				s46 := v.Tags[:0]
				p = odjsonrt.SkipSpace(data, p)
				if uint(p) < uint(len(data)) && data[p] == ']' {
					p++
				} else {
					if cap(s46) == 0 {
						s46 = odjsonrt.CarveStrings(sc, odjsonrt.CarveCap[string](&odjsonCapPersonTags))
					}
					for {
						var e47 string
						if uint(p) >= uint(len(data)) || data[p] <= ' ' {
							p = odjsonrt.SkipSpace(data, odjsonrt.SkipIndent(data, p))
						}
						if np49, ok50 := odjsonrt.ParseNull(data, p); ok50 {
							p = np49
						} else {
							var x51 string
							x51, p, err = odjsonrt.ParseStringCached(data, p, sc)
							if err != nil {
								return p, err
							}
							e47 = x51
						}
						s46 = append(s46, e47)
						p = odjsonrt.SkipSpace(data, p)
						if uint(p) >= uint(len(data)) {
							return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
						}
						if data[p] == ',' {
							p++
							continue
						}
						if data[p] == ']' {
							p++
							break
						}
						return p, odjsonrt.ErrSyntax(data, p, "after array element")
					}
					odjsonCapPersonTags.Record(len(s46))
				}
				if s46 == nil {
					s46 = []string{}
				}
				v.Tags = s46
			}
			goto next29
		}
	m28:
		{
			p, err = v.Address.odjsonParse(data, p, sc)
			if err != nil {
				return p, err
			}
		}
	next29:
		{
			p = odjsonrt.SkipSpace(data, p)
			if uint(p) >= uint(len(data)) {
				return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
			}
			switch data[p] {
			case ',':
				p++
			case '}':
				return p + 1, nil
			default:
				return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
			}
		}
	}
}

// odjsonParseV2 is odjsonParse under encoding/json/v2's semantics, for
// input a jsontext.Decoder has already validated when strict is false,
// and for bytes nobody has looked at when it is true.
func (v *Person) odjsonParseV2(data []byte, p int, sc *odjsonrt.StringCache, strict bool) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		*v = Person{}
		return np, nil
	}
	if uint(p) >= uint(len(data)) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "Person")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if uint(p) < uint(len(data)) && data[p] == '}' {
		return p + 1, nil
	}
	var seen [1]uint64
	_ = seen
	unknown, umark := odjsonrt.UnknownNames(sc)
	var ufilter uint64
	_ = ufilter
	for {
		if uint(p) >= uint(len(data)) || data[p] <= ' ' {
			p = odjsonrt.SkipSpace(data, odjsonrt.SkipIndent(data, p))
		}
		kp := p
		rest := data[p:]
		if len(rest) > 3 {
			switch rest[3] {
			case 'm':
				if len(rest) >= 6 && string(rest[:6]) == "\"name\"" {
					p += 6
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m52
				}
			case 'e':
				if len(rest) >= 5 && string(rest[:5]) == "\"age\"" {
					p += 5
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m53
				}
			case 'a':
				if len(rest) >= 7 && string(rest[:7]) == "\"email\"" {
					p += 7
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m54
				}
			case 'g':
				if len(rest) >= 6 && string(rest[:6]) == "\"tags\"" {
					p += 6
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m55
				}
			case 'd':
				if len(rest) >= 9 && string(rest[:9]) == "\"address\"" {
					p += 9
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m56
				}
			}
		}
		{
			var key []byte
			key, p, err = odjsonrt.ParseKeyV2(data, p, strict)
			if err != nil {
				return p, err
			}
			switch string(key) {
			case "name":
				goto m52
			case "age":
				goto m53
			case "email":
				goto m54
			case "tags":
				goto m55
			case "address":
				goto m56
			}
			if strict {
				var dup bool
				if unknown, dup = odjsonrt.UnknownName(sc, unknown, umark, &ufilter, key); dup {
					return kp, odjsonrt.ErrDuplicateName(data, kp, key)
				}
			}
			p = odjsonrt.SkipSpace(data, p)
			p, err = odjsonrt.SkipValueV2(data, p, strict)
			if err != nil {
				return p, err
			}
			goto next57
		}
	m52:
		{
			if strict && seen[0]&(1<<0) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 0
			if np58, ok59 := odjsonrt.ParseNull(data, p); ok59 {
				p = np58
				v.Name = ""
			} else {
				var x60 string
				x60, p, err = odjsonrt.ParseStringV2(data, p, sc, strict)
				if err != nil {
					return p, err
				}
				v.Name = x60
			}
			goto next57
		}
	m53:
		{
			if strict && seen[0]&(1<<1) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 1
			if np61, ok62 := odjsonrt.ParseNull(data, p); ok62 {
				p = np61
				v.Age = 0
			} else {
				if x63, np64, ok65 := odjsonrt.ParseDecimal(data, p); ok65 {
					v.Age = int(x63)
					p = np64
				} else {
					var x66 int64
					x66, p, err = odjsonrt.ParseInt(data, p, 64)
					if err != nil {
						return p, err
					}
					v.Age = int(x66)
				}
			}
			goto next57
		}
	m54:
		{
			if strict && seen[0]&(1<<2) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 2
			if np67, ok68 := odjsonrt.ParseNull(data, p); ok68 {
				v.Email = nil
				p = np67
			} else {
				if v.Email == nil {
					v.Email = new(string)
				}
				p = odjsonrt.SkipSpace(data, p)
				if np69, ok70 := odjsonrt.ParseNull(data, p); ok70 {
					p = np69
					(*v.Email) = ""
				} else {
					var x71 string
					x71, p, err = odjsonrt.ParseStringV2(data, p, sc, strict)
					if err != nil {
						return p, err
					}
					(*v.Email) = x71
				}
			}
			goto next57
		}
	m55:
		{
			if strict && seen[0]&(1<<3) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 3
			if np72, ok73 := odjsonrt.ParseNull(data, p); ok73 {
				p = np72
				v.Tags = nil
			} else {
				if uint(p) >= uint(len(data)) || data[p] != '[' {
					return p, odjsonrt.ErrType(data, p, "[]string")
				}
				p++
				s74 := v.Tags[:0]
				p = odjsonrt.SkipSpace(data, p)
				if uint(p) < uint(len(data)) && data[p] == ']' {
					p++
				} else {
					if cap(s74) == 0 {
						s74 = odjsonrt.CarveStrings(sc, odjsonrt.CarveCap[string](&odjsonCapPersonTags))
					}
					for {
						var e75 string
						if uint(p) >= uint(len(data)) || data[p] <= ' ' {
							p = odjsonrt.SkipSpace(data, odjsonrt.SkipIndent(data, p))
						}
						if np77, ok78 := odjsonrt.ParseNull(data, p); ok78 {
							p = np77
							e75 = ""
						} else {
							var x79 string
							x79, p, err = odjsonrt.ParseStringV2(data, p, sc, strict)
							if err != nil {
								return p, err
							}
							e75 = x79
						}
						s74 = append(s74, e75)
						p = odjsonrt.SkipSpace(data, p)
						if uint(p) >= uint(len(data)) {
							return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
						}
						if data[p] == ',' {
							p++
							continue
						}
						if data[p] == ']' {
							p++
							break
						}
						return p, odjsonrt.ErrSyntax(data, p, "after array element")
					}
					odjsonCapPersonTags.Record(len(s74))
				}
				if s74 == nil {
					s74 = []string{}
				}
				v.Tags = s74
			}
			goto next57
		}
	m56:
		{
			if strict && seen[0]&(1<<4) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 4
			p, err = v.Address.odjsonParseV2(data, p, sc, strict)
			if err != nil {
				return p, err
			}
		}
	next57:
		{
			p = odjsonrt.SkipSpace(data, p)
			if uint(p) >= uint(len(data)) {
				return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
			}
			switch data[p] {
			case ',':
				p++
			case '}':
				odjsonrt.EndUnknownNames(sc, unknown, umark)
				return p + 1, nil
			default:
				return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
			}
		}
	}
}

// odjsonParseFrom decodes the next value in dec into v,
// driving the decoder token by token so the document is
// parsed once rather than twice.
func (v *Person) odjsonParseFrom(dec *jsontext.Decoder, sc *odjsonrt.StringCache) error {
	var err error
	_ = err
	if odjsonrt.WholeValue(dec) {
		var val jsontext.Value
		if val, err = dec.ReadValue(); err != nil {
			return err
		}
		_, err = v.odjsonParseV2(val, 0, sc, false)
		return err
	}
	switch odjsonrt.NextKind(dec) {
	case 'n':
		if _, err = dec.ReadToken(); err != nil {
			return err
		}
		*v = Person{}
		return nil
	case '{':
	default:
		return odjsonrt.ErrKindFrom(dec, "Person")
	}
	if _, err = dec.ReadToken(); err != nil {
		return err
	}
	for odjsonrt.NextKind(dec) != '}' {
		var key jsontext.Value
		key, err = dec.ReadValue()
		if err != nil {
			return err
		}
		idx := -1
		switch string(key) {
		case "\"name\"":
			idx = 0
		case "\"age\"":
			idx = 1
		case "\"email\"":
			idx = 2
		case "\"tags\"":
			idx = 3
		case "\"address\"":
			idx = 4
		}
		if idx < 0 && bytes.IndexByte(key, '\\') >= 0 {
			if name, ok := odjsonrt.UnquoteName(key); ok {
				switch string(name) {
				case "name":
					idx = 0
				case "age":
					idx = 1
				case "email":
					idx = 2
				case "tags":
					idx = 3
				case "address":
					idx = 4
				}
			}
		}
		switch idx {
		case 0:
			var val80 jsontext.Value
			val80, err = dec.ReadValue()
			if err != nil {
				return err
			}
			if val80[0] == 'n' {
				v.Name = ""
			} else {
				var x81 string
				x81, err = odjsonrt.ParseStringValue(val80, sc)
				if err != nil {
					return err
				}
				v.Name = x81
			}
		case 1:
			var val82 jsontext.Value
			val82, err = dec.ReadValue()
			if err != nil {
				return err
			}
			if val82[0] == 'n' {
				v.Age = 0
			} else {
				var x83 int64
				x83, _, err = odjsonrt.ParseInt(val82, 0, 64)
				if err != nil {
					return err
				}
				v.Age = int(x83)
			}
		case 2:
			var val84 jsontext.Value
			val84, err = dec.ReadValue()
			if err != nil {
				return err
			}
			vp85 := 0
			if np86, ok87 := odjsonrt.ParseNull(val84, vp85); ok87 {
				v.Email = nil
				vp85 = np86
			} else {
				if v.Email == nil {
					v.Email = new(string)
				}
				vp85 = odjsonrt.SkipSpace(val84, vp85)
				if np88, ok89 := odjsonrt.ParseNull(val84, vp85); ok89 {
					vp85 = np88
					(*v.Email) = ""
				} else {
					var x90 string
					x90, vp85, err = odjsonrt.ParseStringWith(val84, vp85, sc)
					if err != nil {
						return err
					}
					(*v.Email) = x90
				}
			}
			_ = vp85
		case 3:
			var val91 jsontext.Value
			val91, err = dec.ReadValue()
			if err != nil {
				return err
			}
			vp92 := 0
			if np93, ok94 := odjsonrt.ParseNull(val91, vp92); ok94 {
				vp92 = np93
				v.Tags = nil
			} else {
				if uint(vp92) >= uint(len(val91)) || val91[vp92] != '[' {
					return odjsonrt.ErrType(val91, vp92, "[]string")
				}
				vp92++
				s95 := v.Tags[:0]
				vp92 = odjsonrt.SkipSpace(val91, vp92)
				if uint(vp92) < uint(len(val91)) && val91[vp92] == ']' {
					vp92++
				} else {
					if cap(s95) == 0 {
						s95 = odjsonrt.CarveStrings(sc, odjsonrt.CarveCap[string](&odjsonCapPersonTags))
					}
					for {
						var e96 string
						if uint(vp92) >= uint(len(val91)) || val91[vp92] <= ' ' {
							vp92 = odjsonrt.SkipSpace(val91, odjsonrt.SkipIndent(val91, vp92))
						}
						if np98, ok99 := odjsonrt.ParseNull(val91, vp92); ok99 {
							vp92 = np98
							e96 = ""
						} else {
							var x100 string
							x100, vp92, err = odjsonrt.ParseStringWith(val91, vp92, sc)
							if err != nil {
								return err
							}
							e96 = x100
						}
						s95 = append(s95, e96)
						vp92 = odjsonrt.SkipSpace(val91, vp92)
						if uint(vp92) >= uint(len(val91)) {
							return odjsonrt.ErrSyntax(val91, vp92, "unexpected end of JSON input")
						}
						if val91[vp92] == ',' {
							vp92++
							continue
						}
						if val91[vp92] == ']' {
							vp92++
							break
						}
						return odjsonrt.ErrSyntax(val91, vp92, "after array element")
					}
					odjsonCapPersonTags.Record(len(s95))
				}
				if s95 == nil {
					s95 = []string{}
				}
				v.Tags = s95
			}
			_ = vp92
		case 4:
			if err = v.Address.odjsonParseFrom(dec, sc); err != nil {
				return err
			}
		default:
			if _, err = dec.ReadValue(); err != nil {
				return err
			}
		}
	}
	_, err = dec.ReadToken()
	return err
}

// odjsonSizePerson sizes the buffer the encoders allocate.
var odjsonSizePerson odjsonrt.SizeHint

// MarshalJSON implements encoding/json.Marshaler.
func (v Person) MarshalJSON() ([]byte, error) {
	buf, err := v.odjsonAppend(odjsonSizePerson.New(), odjsonrt.ModeHTML)
	if err != nil {
		return nil, err
	}
	odjsonSizePerson.Record(buf)
	return buf, nil
}

// UnmarshalJSON implements encoding/json.Unmarshaler.
func (v *Person) UnmarshalJSON(data []byte) error {
	// The cache plays the part of encoding/json/v2's string cache: a
	// value that recurs in the document is allocated once.
	sc := odjsonrt.GetStringCache()
	p, err := v.odjsonParse(data, odjsonrt.SkipSpace(data, 0), sc)
	odjsonrt.PutStringCache(sc)
	if err != nil {
		return err
	}
	return odjsonrt.EndOfDocument(data, p)
}

// MarshalJSONTo implements encoding/json/v2.MarshalerTo.
func (v Person) MarshalJSONTo(enc *jsontext.Encoder) error {
	// Under a plain json.Marshal, from encoding/json/v2 or encoding/json,
	// the value is appended straight into the encoder's buffer at any
	// depth; see odjsonrt.BeginDirectEncodeMode for what qualifies and
	// for the mode, which does that call's escaping itself since nothing
	// downstream looks at the bytes.
	if buf, m, ok := odjsonrt.BeginDirectEncodeMode(enc); ok {
		n := len(buf)
		buf, err := v.odjsonAppend(buf, m)
		if err != nil {
			return err
		}
		odjsonSizePerson.Record(buf[n:])
		odjsonrt.EndDirectEncode(enc, buf)
		return nil
	}
	// Otherwise WriteValue copies what it is given, so the scratch buffer
	// can go straight back to the pool. ModeStream leaves the HTML escaping
	// and the UTF-8 validation to the encoder, which performs both while
	// reformatting the value either way.
	buf := odjsonrt.GetBuffer()
	var err error
	if buf.B, err = v.odjsonAppend(buf.B, odjsonrt.ModeStream); err == nil {
		odjsonSizePerson.Record(buf.B)
		err = enc.WriteValue(buf.B)
	}
	odjsonrt.PutBuffer(buf)
	return err
}

// UnmarshalJSONFrom implements encoding/json/v2.UnmarshalerFrom.
func (v *Person) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	// The cache plays the part of json/v2's own string cache: a value
	// that recurs in the document is allocated once.
	sc := odjsonrt.GetStringCache()
	var err error
	// Under a plain json.Unmarshal the value is parsed straight out of
	// the decoder's buffer at any depth; see odjsonrt.BeginDirectDecodeAt
	// for what qualifies. Nobody has validated those bytes, so
	// odjsonParseV2 rejects what jsontext would have.
	if data, p, ok := odjsonrt.BeginDirectDecodeAt(dec); ok {
		var end int
		if end, err = v.odjsonParseV2(data, p, sc, true); err == nil {
			odjsonrt.EndDirectDecodeAt(dec, p, end)
		}
	} else {
		err = v.odjsonParseFrom(dec, sc)
	}
	odjsonrt.PutStringCache(sc)
	return err
}
