// Code generated by odjson. DO NOT EDIT.
//
// Source: odjson

package withmethods

import (
	"bytes"
	"encoding/json/jsontext"
	"github.com/mazrean/odjson/odjsonrt"
)

// odjsonAppend appends the JSON encoding of v to dst.
func (v *Address) odjsonAppend(dst []byte, m odjsonrt.StringMode) ([]byte, error) {
	var err error
	_ = err
	start := len(dst)
	dst = append(dst, ",\"street\":\""...)
	dst, err = odjsonrt.AppendStringBodyChecked(dst, string(v.Street), m)
	if err != nil {
		return nil, err
	}
	dst = append(dst, "\""...)
	if len(v.City) != 0 {
		dst = append(dst, ",\"city\":\""...)
		dst, err = odjsonrt.AppendStringBodyChecked(dst, string(v.City), m)
		if err != nil {
			return nil, err
		}
		dst = append(dst, '"')
	}
	if len(dst) == start {
		dst = append(dst, '{', '}')
	} else {
		dst[start] = '{'
		dst = append(dst, '}')
	}
	return dst, nil
}

// odjsonParse decodes the JSON object starting at p into v and
// returns the offset just past it. Strings are interned through
// sc, which may be nil.
func (v *Address) odjsonParse(data []byte, p int, sc *odjsonrt.StringCache) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		return np, nil
	}
	if p >= len(data) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "Address")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if p < len(data) && data[p] == '}' {
		return p + 1, nil
	}
	for {
		var key []byte
		p = odjsonrt.SkipSpace(data, p)
		idx := -1
		rest := data[p:]
		if len(rest) > 1 {
			switch rest[1] {
			case 's':
				if len(rest) >= 8 && string(rest[:8]) == "\"street\"" {
					idx, p = 0, p+8
				}
			case 'c':
				if len(rest) >= 6 && string(rest[:6]) == "\"city\"" {
					idx, p = 1, p+6
				}
			}
		}
		if idx >= 0 {
			if np := odjsonrt.AfterName(data, p); np > 0 {
				p = np
			} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
				return p, err
			}
		} else {
			key, _, p, err = odjsonrt.ParseKey(data, p)
			if err != nil {
				return p, err
			}
			switch string(key) {
			case "street":
				idx = 0
			case "city":
				idx = 1
			}
		}
		switch idx {
		case 0:
			if np1, ok2 := odjsonrt.ParseNull(data, p); ok2 {
				p = np1
			} else {
				var x3 string
				x3, p, err = odjsonrt.ParseStringCached(data, p, sc)
				if err != nil {
					return p, err
				}
				v.Street = x3
			}
		case 1:
			if np4, ok5 := odjsonrt.ParseNull(data, p); ok5 {
				p = np4
			} else {
				var x6 string
				x6, p, err = odjsonrt.ParseStringCached(data, p, sc)
				if err != nil {
					return p, err
				}
				v.City = x6
			}
		default:
			p = odjsonrt.SkipSpace(data, p)
			p, err = odjsonrt.SkipValue(data, p)
			if err != nil {
				return p, err
			}
		}
		p = odjsonrt.SkipSpace(data, p)
		if p >= len(data) {
			return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
		}
		switch data[p] {
		case ',':
			p++
		case '}':
			return p + 1, nil
		default:
			return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
		}
	}
}

// odjsonParseV2 is odjsonParse under encoding/json/v2's semantics, for
// input a jsontext.Decoder has already validated when strict is false,
// and for bytes nobody has looked at when it is true.
func (v *Address) odjsonParseV2(data []byte, p int, sc *odjsonrt.StringCache, strict bool) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		*v = Address{}
		return np, nil
	}
	if p >= len(data) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "Address")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if p < len(data) && data[p] == '}' {
		return p + 1, nil
	}
	var seen [1]uint64
	_ = seen
	unknown, umark := odjsonrt.UnknownNames(sc)
	for {
		var key []byte
		p = odjsonrt.SkipSpace(data, p)
		kp := p
		idx := -1
		rest := data[p:]
		if len(rest) > 1 {
			switch rest[1] {
			case 's':
				if len(rest) >= 8 && string(rest[:8]) == "\"street\"" {
					idx, p = 0, p+8
				}
			case 'c':
				if len(rest) >= 6 && string(rest[:6]) == "\"city\"" {
					idx, p = 1, p+6
				}
			}
		}
		if idx >= 0 {
			if np := odjsonrt.AfterName(data, p); np > 0 {
				p = np
			} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
				return p, err
			}
		} else {
			key, p, err = odjsonrt.ParseKeyV2(data, p, strict)
			if err != nil {
				return p, err
			}
			switch string(key) {
			case "street":
				idx = 0
			case "city":
				idx = 1
			}
		}
		switch idx {
		case 0:
			if strict && seen[0]&(1<<0) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 0
			if np7, ok8 := odjsonrt.ParseNull(data, p); ok8 {
				p = np7
				v.Street = ""
			} else {
				var x9 string
				x9, p, err = odjsonrt.ParseStringV2(data, p, sc, strict)
				if err != nil {
					return p, err
				}
				v.Street = x9
			}
		case 1:
			if strict && seen[0]&(1<<1) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 1
			if np10, ok11 := odjsonrt.ParseNull(data, p); ok11 {
				p = np10
				v.City = ""
			} else {
				var x12 string
				x12, p, err = odjsonrt.ParseStringV2(data, p, sc, strict)
				if err != nil {
					return p, err
				}
				v.City = x12
			}
		default:
			if strict {
				for _, u := range unknown[umark:] {
					if string(u) == string(key) {
						return kp, odjsonrt.ErrDuplicateName(data, kp, key)
					}
				}
				unknown = append(unknown, key)
			}
			p = odjsonrt.SkipSpace(data, p)
			p, err = odjsonrt.SkipValueV2(data, p, strict)
			if err != nil {
				return p, err
			}
		}
		p = odjsonrt.SkipSpace(data, p)
		if p >= len(data) {
			return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
		}
		switch data[p] {
		case ',':
			p++
		case '}':
			odjsonrt.EndUnknownNames(sc, unknown, umark)
			return p + 1, nil
		default:
			return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
		}
	}
}

// odjsonParseFrom decodes the next value in dec into v,
// driving the decoder token by token so the document is
// parsed once rather than twice.
func (v *Address) odjsonParseFrom(dec *jsontext.Decoder, sc *odjsonrt.StringCache) error {
	var err error
	_ = err
	if odjsonrt.WholeValue(dec) {
		var val jsontext.Value
		if val, err = dec.ReadValue(); err != nil {
			return err
		}
		_, err = v.odjsonParseV2(val, 0, sc, false)
		return err
	}
	switch odjsonrt.NextKind(dec) {
	case 'n':
		if _, err = dec.ReadToken(); err != nil {
			return err
		}
		*v = Address{}
		return nil
	case '{':
	default:
		return odjsonrt.ErrKindFrom(dec, "Address")
	}
	if _, err = dec.ReadToken(); err != nil {
		return err
	}
	for odjsonrt.NextKind(dec) != '}' {
		var key jsontext.Value
		key, err = dec.ReadValue()
		if err != nil {
			return err
		}
		idx := -1
		switch string(key) {
		case "\"street\"":
			idx = 0
		case "\"city\"":
			idx = 1
		}
		if idx < 0 && bytes.IndexByte(key, '\\') >= 0 {
			if name, ok := odjsonrt.UnquoteName(key); ok {
				switch string(name) {
				case "street":
					idx = 0
				case "city":
					idx = 1
				}
			}
		}
		switch idx {
		case 0:
			var val13 jsontext.Value
			val13, err = dec.ReadValue()
			if err != nil {
				return err
			}
			if val13[0] == 'n' {
				v.Street = ""
			} else {
				var x14 string
				x14, err = odjsonrt.ParseStringValue(val13, sc)
				if err != nil {
					return err
				}
				v.Street = x14
			}
		case 1:
			var val15 jsontext.Value
			val15, err = dec.ReadValue()
			if err != nil {
				return err
			}
			if val15[0] == 'n' {
				v.City = ""
			} else {
				var x16 string
				x16, err = odjsonrt.ParseStringValue(val15, sc)
				if err != nil {
					return err
				}
				v.City = x16
			}
		default:
			if _, err = dec.ReadValue(); err != nil {
				return err
			}
		}
	}
	_, err = dec.ReadToken()
	return err
}

// odjsonSizeAddress sizes the buffer the encoders allocate.
var odjsonSizeAddress odjsonrt.SizeHint

// MarshalJSON implements encoding/json.Marshaler.
func (v Address) MarshalJSON() ([]byte, error) {
	buf, err := v.odjsonAppend(odjsonSizeAddress.New(), odjsonrt.ModeHTML)
	if err != nil {
		return nil, err
	}
	odjsonSizeAddress.Record(buf)
	return buf, nil
}

// UnmarshalJSON implements encoding/json.Unmarshaler.
func (v *Address) UnmarshalJSON(data []byte) error {
	// The cache plays the part of encoding/json/v2's string cache: a
	// value that recurs in the document is allocated once.
	sc := odjsonrt.GetStringCache()
	p, err := v.odjsonParse(data, odjsonrt.SkipSpace(data, 0), sc)
	odjsonrt.PutStringCache(sc)
	if err != nil {
		return err
	}
	return odjsonrt.EndOfDocument(data, p)
}

// MarshalJSONTo implements encoding/json/v2.MarshalerTo.
func (v Address) MarshalJSONTo(enc *jsontext.Encoder) error {
	// Under a plain json.Marshal, from encoding/json/v2 or encoding/json,
	// the value is appended straight into the encoder's buffer at any
	// depth; see odjsonrt.BeginDirectEncodeMode for what qualifies and
	// for the mode, which does that call's escaping itself since nothing
	// downstream looks at the bytes.
	if buf, m, ok := odjsonrt.BeginDirectEncodeMode(enc); ok {
		n := len(buf)
		buf, err := v.odjsonAppend(buf, m)
		if err != nil {
			return err
		}
		odjsonSizeAddress.Record(buf[n:])
		odjsonrt.EndDirectEncode(enc, buf)
		return nil
	}
	// Otherwise WriteValue copies what it is given, so the scratch buffer
	// can go straight back to the pool. ModeStream leaves the HTML escaping
	// and the UTF-8 validation to the encoder, which performs both while
	// reformatting the value either way.
	buf := odjsonrt.GetBuffer()
	var err error
	if buf.B, err = v.odjsonAppend(buf.B, odjsonrt.ModeStream); err == nil {
		odjsonSizeAddress.Record(buf.B)
		err = enc.WriteValue(buf.B)
	}
	odjsonrt.PutBuffer(buf)
	return err
}

// UnmarshalJSONFrom implements encoding/json/v2.UnmarshalerFrom.
func (v *Address) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	// The cache plays the part of json/v2's own string cache: a value
	// that recurs in the document is allocated once.
	sc := odjsonrt.GetStringCache()
	var err error
	// Under a plain json.Unmarshal the value is parsed straight out of
	// the decoder's buffer at any depth; see odjsonrt.BeginDirectDecodeAt
	// for what qualifies. Nobody has validated those bytes, so
	// odjsonParseV2 rejects what jsontext would have.
	if data, p, ok := odjsonrt.BeginDirectDecodeAt(dec); ok {
		var end int
		if end, err = v.odjsonParseV2(data, p, sc, true); err == nil {
			odjsonrt.EndDirectDecodeAt(dec, p, end)
		}
	} else {
		err = v.odjsonParseFrom(dec, sc)
	}
	odjsonrt.PutStringCache(sc)
	return err
}

// odjsonAppend appends the JSON encoding of v to dst.
func (v *Person) odjsonAppend(dst []byte, m odjsonrt.StringMode) ([]byte, error) {
	var err error
	_ = err
	start := len(dst)
	dst = append(dst, ",\"name\":\""...)
	dst, err = odjsonrt.AppendStringBodyChecked(dst, string(v.Name), m)
	if err != nil {
		return nil, err
	}
	dst = append(dst, "\",\"age\":"...)
	dst = odjsonrt.AppendInt(dst, int64(v.Age))
	if v.Email != nil {
		dst = append(dst, ",\"email\":"...)
		if v.Email == nil {
			dst = append(dst, 'n', 'u', 'l', 'l')
		} else {
			dst = append(dst, '"')
			dst, err = odjsonrt.AppendStringBodyChecked(dst, string((*v.Email)), m)
			if err != nil {
				return nil, err
			}
			dst = append(dst, '"')
		}
	}
	if len(v.Tags) != 0 {
		dst = append(dst, ",\"tags\":"...)
		if v.Tags == nil {
			dst = odjsonrt.AppendNilSlice(dst, m)
		} else {
			dst = append(dst, '[')
			for i17 := range v.Tags {
				if i17 > 0 {
					dst = append(dst, ',')
				}
				dst = append(dst, '"')
				dst, err = odjsonrt.AppendStringBodyChecked(dst, string(v.Tags[i17]), m)
				if err != nil {
					return nil, err
				}
				dst = append(dst, '"')
			}
			dst = append(dst, ']')
		}
	}
	dst = append(dst, ",\"address\":"...)
	dst, err = v.Address.odjsonAppend(dst, m)
	if err != nil {
		return nil, err
	}
	if len(dst) == start {
		dst = append(dst, '{', '}')
	} else {
		dst[start] = '{'
		dst = append(dst, '}')
	}
	return dst, nil
}

// odjsonCapPersonTags remembers how long v.Tags has been, to allocate it once.
var odjsonCapPersonTags odjsonrt.CapHint

// odjsonParse decodes the JSON object starting at p into v and
// returns the offset just past it. Strings are interned through
// sc, which may be nil.
func (v *Person) odjsonParse(data []byte, p int, sc *odjsonrt.StringCache) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		return np, nil
	}
	if p >= len(data) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "Person")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if p < len(data) && data[p] == '}' {
		return p + 1, nil
	}
	for {
		var key []byte
		p = odjsonrt.SkipSpace(data, p)
		idx := -1
		rest := data[p:]
		if len(rest) > 3 {
			switch rest[3] {
			case 'm':
				if len(rest) >= 6 && string(rest[:6]) == "\"name\"" {
					idx, p = 0, p+6
				}
			case 'e':
				if len(rest) >= 5 && string(rest[:5]) == "\"age\"" {
					idx, p = 1, p+5
				}
			case 'a':
				if len(rest) >= 7 && string(rest[:7]) == "\"email\"" {
					idx, p = 2, p+7
				}
			case 'g':
				if len(rest) >= 6 && string(rest[:6]) == "\"tags\"" {
					idx, p = 3, p+6
				}
			case 'd':
				if len(rest) >= 9 && string(rest[:9]) == "\"address\"" {
					idx, p = 4, p+9
				}
			}
		}
		if idx >= 0 {
			if np := odjsonrt.AfterName(data, p); np > 0 {
				p = np
			} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
				return p, err
			}
		} else {
			key, _, p, err = odjsonrt.ParseKey(data, p)
			if err != nil {
				return p, err
			}
			switch string(key) {
			case "name":
				idx = 0
			case "age":
				idx = 1
			case "email":
				idx = 2
			case "tags":
				idx = 3
			case "address":
				idx = 4
			}
		}
		switch idx {
		case 0:
			if np18, ok19 := odjsonrt.ParseNull(data, p); ok19 {
				p = np18
			} else {
				var x20 string
				x20, p, err = odjsonrt.ParseStringCached(data, p, sc)
				if err != nil {
					return p, err
				}
				v.Name = x20
			}
		case 1:
			if np21, ok22 := odjsonrt.ParseNull(data, p); ok22 {
				p = np21
			} else {
				if x23, np24, ok25 := odjsonrt.ParseDecimal(data, p); ok25 {
					v.Age = int(x23)
					p = np24
				} else {
					var x26 int64
					x26, p, err = odjsonrt.ParseInt(data, p, 64)
					if err != nil {
						return p, err
					}
					v.Age = int(x26)
				}
			}
		case 2:
			if np27, ok28 := odjsonrt.ParseNull(data, p); ok28 {
				v.Email = nil
				p = np27
			} else {
				if v.Email == nil {
					v.Email = new(string)
				}
				p = odjsonrt.SkipSpace(data, p)
				if np29, ok30 := odjsonrt.ParseNull(data, p); ok30 {
					p = np29
				} else {
					var x31 string
					x31, p, err = odjsonrt.ParseStringCached(data, p, sc)
					if err != nil {
						return p, err
					}
					(*v.Email) = x31
				}
			}
		case 3:
			if np32, ok33 := odjsonrt.ParseNull(data, p); ok33 {
				p = np32
				v.Tags = nil
			} else {
				if p >= len(data) || data[p] != '[' {
					return p, odjsonrt.ErrType(data, p, "[]string")
				}
				p++
				s34 := v.Tags[:0]
				p = odjsonrt.SkipSpace(data, p)
				if p < len(data) && data[p] == ']' {
					p++
				} else {
					if cap(s34) == 0 {
						s34 = make([]string, 0, odjsonrt.CapFor[string](&odjsonCapPersonTags))
					}
					for {
						var e35 string
						p = odjsonrt.SkipSpace(data, p)
						if np36, ok37 := odjsonrt.ParseNull(data, p); ok37 {
							p = np36
						} else {
							var x38 string
							x38, p, err = odjsonrt.ParseStringCached(data, p, sc)
							if err != nil {
								return p, err
							}
							e35 = x38
						}
						s34 = append(s34, e35)
						p = odjsonrt.SkipSpace(data, p)
						if p >= len(data) {
							return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
						}
						if data[p] == ',' {
							p++
							continue
						}
						if data[p] == ']' {
							p++
							break
						}
						return p, odjsonrt.ErrSyntax(data, p, "after array element")
					}
					odjsonCapPersonTags.Record(len(s34))
				}
				if s34 == nil {
					s34 = []string{}
				}
				v.Tags = s34
			}
		case 4:
			p, err = v.Address.odjsonParse(data, p, sc)
			if err != nil {
				return p, err
			}
		default:
			p = odjsonrt.SkipSpace(data, p)
			p, err = odjsonrt.SkipValue(data, p)
			if err != nil {
				return p, err
			}
		}
		p = odjsonrt.SkipSpace(data, p)
		if p >= len(data) {
			return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
		}
		switch data[p] {
		case ',':
			p++
		case '}':
			return p + 1, nil
		default:
			return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
		}
	}
}

// odjsonParseV2 is odjsonParse under encoding/json/v2's semantics, for
// input a jsontext.Decoder has already validated when strict is false,
// and for bytes nobody has looked at when it is true.
func (v *Person) odjsonParseV2(data []byte, p int, sc *odjsonrt.StringCache, strict bool) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		*v = Person{}
		return np, nil
	}
	if p >= len(data) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "Person")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if p < len(data) && data[p] == '}' {
		return p + 1, nil
	}
	var seen [1]uint64
	_ = seen
	unknown, umark := odjsonrt.UnknownNames(sc)
	for {
		var key []byte
		p = odjsonrt.SkipSpace(data, p)
		kp := p
		idx := -1
		rest := data[p:]
		if len(rest) > 3 {
			switch rest[3] {
			case 'm':
				if len(rest) >= 6 && string(rest[:6]) == "\"name\"" {
					idx, p = 0, p+6
				}
			case 'e':
				if len(rest) >= 5 && string(rest[:5]) == "\"age\"" {
					idx, p = 1, p+5
				}
			case 'a':
				if len(rest) >= 7 && string(rest[:7]) == "\"email\"" {
					idx, p = 2, p+7
				}
			case 'g':
				if len(rest) >= 6 && string(rest[:6]) == "\"tags\"" {
					idx, p = 3, p+6
				}
			case 'd':
				if len(rest) >= 9 && string(rest[:9]) == "\"address\"" {
					idx, p = 4, p+9
				}
			}
		}
		if idx >= 0 {
			if np := odjsonrt.AfterName(data, p); np > 0 {
				p = np
			} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
				return p, err
			}
		} else {
			key, p, err = odjsonrt.ParseKeyV2(data, p, strict)
			if err != nil {
				return p, err
			}
			switch string(key) {
			case "name":
				idx = 0
			case "age":
				idx = 1
			case "email":
				idx = 2
			case "tags":
				idx = 3
			case "address":
				idx = 4
			}
		}
		switch idx {
		case 0:
			if strict && seen[0]&(1<<0) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 0
			if np39, ok40 := odjsonrt.ParseNull(data, p); ok40 {
				p = np39
				v.Name = ""
			} else {
				var x41 string
				x41, p, err = odjsonrt.ParseStringV2(data, p, sc, strict)
				if err != nil {
					return p, err
				}
				v.Name = x41
			}
		case 1:
			if strict && seen[0]&(1<<1) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 1
			if np42, ok43 := odjsonrt.ParseNull(data, p); ok43 {
				p = np42
				v.Age = 0
			} else {
				if x44, np45, ok46 := odjsonrt.ParseDecimal(data, p); ok46 {
					v.Age = int(x44)
					p = np45
				} else {
					var x47 int64
					x47, p, err = odjsonrt.ParseInt(data, p, 64)
					if err != nil {
						return p, err
					}
					v.Age = int(x47)
				}
			}
		case 2:
			if strict && seen[0]&(1<<2) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 2
			if np48, ok49 := odjsonrt.ParseNull(data, p); ok49 {
				v.Email = nil
				p = np48
			} else {
				if v.Email == nil {
					v.Email = new(string)
				}
				p = odjsonrt.SkipSpace(data, p)
				if np50, ok51 := odjsonrt.ParseNull(data, p); ok51 {
					p = np50
					(*v.Email) = ""
				} else {
					var x52 string
					x52, p, err = odjsonrt.ParseStringV2(data, p, sc, strict)
					if err != nil {
						return p, err
					}
					(*v.Email) = x52
				}
			}
		case 3:
			if strict && seen[0]&(1<<3) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 3
			if np53, ok54 := odjsonrt.ParseNull(data, p); ok54 {
				p = np53
				v.Tags = nil
			} else {
				if p >= len(data) || data[p] != '[' {
					return p, odjsonrt.ErrType(data, p, "[]string")
				}
				p++
				s55 := v.Tags[:0]
				p = odjsonrt.SkipSpace(data, p)
				if p < len(data) && data[p] == ']' {
					p++
				} else {
					if cap(s55) == 0 {
						s55 = make([]string, 0, odjsonrt.CapFor[string](&odjsonCapPersonTags))
					}
					for {
						var e56 string
						p = odjsonrt.SkipSpace(data, p)
						if np57, ok58 := odjsonrt.ParseNull(data, p); ok58 {
							p = np57
							e56 = ""
						} else {
							var x59 string
							x59, p, err = odjsonrt.ParseStringV2(data, p, sc, strict)
							if err != nil {
								return p, err
							}
							e56 = x59
						}
						s55 = append(s55, e56)
						p = odjsonrt.SkipSpace(data, p)
						if p >= len(data) {
							return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
						}
						if data[p] == ',' {
							p++
							continue
						}
						if data[p] == ']' {
							p++
							break
						}
						return p, odjsonrt.ErrSyntax(data, p, "after array element")
					}
					odjsonCapPersonTags.Record(len(s55))
				}
				if s55 == nil {
					s55 = []string{}
				}
				v.Tags = s55
			}
		case 4:
			if strict && seen[0]&(1<<4) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 4
			p, err = v.Address.odjsonParseV2(data, p, sc, strict)
			if err != nil {
				return p, err
			}
		default:
			if strict {
				for _, u := range unknown[umark:] {
					if string(u) == string(key) {
						return kp, odjsonrt.ErrDuplicateName(data, kp, key)
					}
				}
				unknown = append(unknown, key)
			}
			p = odjsonrt.SkipSpace(data, p)
			p, err = odjsonrt.SkipValueV2(data, p, strict)
			if err != nil {
				return p, err
			}
		}
		p = odjsonrt.SkipSpace(data, p)
		if p >= len(data) {
			return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
		}
		switch data[p] {
		case ',':
			p++
		case '}':
			odjsonrt.EndUnknownNames(sc, unknown, umark)
			return p + 1, nil
		default:
			return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
		}
	}
}

// odjsonParseFrom decodes the next value in dec into v,
// driving the decoder token by token so the document is
// parsed once rather than twice.
func (v *Person) odjsonParseFrom(dec *jsontext.Decoder, sc *odjsonrt.StringCache) error {
	var err error
	_ = err
	if odjsonrt.WholeValue(dec) {
		var val jsontext.Value
		if val, err = dec.ReadValue(); err != nil {
			return err
		}
		_, err = v.odjsonParseV2(val, 0, sc, false)
		return err
	}
	switch odjsonrt.NextKind(dec) {
	case 'n':
		if _, err = dec.ReadToken(); err != nil {
			return err
		}
		*v = Person{}
		return nil
	case '{':
	default:
		return odjsonrt.ErrKindFrom(dec, "Person")
	}
	if _, err = dec.ReadToken(); err != nil {
		return err
	}
	for odjsonrt.NextKind(dec) != '}' {
		var key jsontext.Value
		key, err = dec.ReadValue()
		if err != nil {
			return err
		}
		idx := -1
		switch string(key) {
		case "\"name\"":
			idx = 0
		case "\"age\"":
			idx = 1
		case "\"email\"":
			idx = 2
		case "\"tags\"":
			idx = 3
		case "\"address\"":
			idx = 4
		}
		if idx < 0 && bytes.IndexByte(key, '\\') >= 0 {
			if name, ok := odjsonrt.UnquoteName(key); ok {
				switch string(name) {
				case "name":
					idx = 0
				case "age":
					idx = 1
				case "email":
					idx = 2
				case "tags":
					idx = 3
				case "address":
					idx = 4
				}
			}
		}
		switch idx {
		case 0:
			var val60 jsontext.Value
			val60, err = dec.ReadValue()
			if err != nil {
				return err
			}
			if val60[0] == 'n' {
				v.Name = ""
			} else {
				var x61 string
				x61, err = odjsonrt.ParseStringValue(val60, sc)
				if err != nil {
					return err
				}
				v.Name = x61
			}
		case 1:
			var val62 jsontext.Value
			val62, err = dec.ReadValue()
			if err != nil {
				return err
			}
			if val62[0] == 'n' {
				v.Age = 0
			} else {
				var x63 int64
				x63, _, err = odjsonrt.ParseInt(val62, 0, 64)
				if err != nil {
					return err
				}
				v.Age = int(x63)
			}
		case 2:
			var val64 jsontext.Value
			val64, err = dec.ReadValue()
			if err != nil {
				return err
			}
			vp65 := 0
			if np66, ok67 := odjsonrt.ParseNull(val64, vp65); ok67 {
				v.Email = nil
				vp65 = np66
			} else {
				if v.Email == nil {
					v.Email = new(string)
				}
				vp65 = odjsonrt.SkipSpace(val64, vp65)
				if np68, ok69 := odjsonrt.ParseNull(val64, vp65); ok69 {
					vp65 = np68
					(*v.Email) = ""
				} else {
					var x70 string
					x70, vp65, err = odjsonrt.ParseStringWith(val64, vp65, sc)
					if err != nil {
						return err
					}
					(*v.Email) = x70
				}
			}
			_ = vp65
		case 3:
			var val71 jsontext.Value
			val71, err = dec.ReadValue()
			if err != nil {
				return err
			}
			vp72 := 0
			if np73, ok74 := odjsonrt.ParseNull(val71, vp72); ok74 {
				vp72 = np73
				v.Tags = nil
			} else {
				if vp72 >= len(val71) || val71[vp72] != '[' {
					return odjsonrt.ErrType(val71, vp72, "[]string")
				}
				vp72++
				s75 := v.Tags[:0]
				vp72 = odjsonrt.SkipSpace(val71, vp72)
				if vp72 < len(val71) && val71[vp72] == ']' {
					vp72++
				} else {
					if cap(s75) == 0 {
						s75 = make([]string, 0, odjsonrt.CapFor[string](&odjsonCapPersonTags))
					}
					for {
						var e76 string
						vp72 = odjsonrt.SkipSpace(val71, vp72)
						if np77, ok78 := odjsonrt.ParseNull(val71, vp72); ok78 {
							vp72 = np77
							e76 = ""
						} else {
							var x79 string
							x79, vp72, err = odjsonrt.ParseStringWith(val71, vp72, sc)
							if err != nil {
								return err
							}
							e76 = x79
						}
						s75 = append(s75, e76)
						vp72 = odjsonrt.SkipSpace(val71, vp72)
						if vp72 >= len(val71) {
							return odjsonrt.ErrSyntax(val71, vp72, "unexpected end of JSON input")
						}
						if val71[vp72] == ',' {
							vp72++
							continue
						}
						if val71[vp72] == ']' {
							vp72++
							break
						}
						return odjsonrt.ErrSyntax(val71, vp72, "after array element")
					}
					odjsonCapPersonTags.Record(len(s75))
				}
				if s75 == nil {
					s75 = []string{}
				}
				v.Tags = s75
			}
			_ = vp72
		case 4:
			if err = v.Address.odjsonParseFrom(dec, sc); err != nil {
				return err
			}
		default:
			if _, err = dec.ReadValue(); err != nil {
				return err
			}
		}
	}
	_, err = dec.ReadToken()
	return err
}

// odjsonSizePerson sizes the buffer the encoders allocate.
var odjsonSizePerson odjsonrt.SizeHint

// MarshalJSON implements encoding/json.Marshaler.
func (v Person) MarshalJSON() ([]byte, error) {
	buf, err := v.odjsonAppend(odjsonSizePerson.New(), odjsonrt.ModeHTML)
	if err != nil {
		return nil, err
	}
	odjsonSizePerson.Record(buf)
	return buf, nil
}

// UnmarshalJSON implements encoding/json.Unmarshaler.
func (v *Person) UnmarshalJSON(data []byte) error {
	// The cache plays the part of encoding/json/v2's string cache: a
	// value that recurs in the document is allocated once.
	sc := odjsonrt.GetStringCache()
	p, err := v.odjsonParse(data, odjsonrt.SkipSpace(data, 0), sc)
	odjsonrt.PutStringCache(sc)
	if err != nil {
		return err
	}
	return odjsonrt.EndOfDocument(data, p)
}

// MarshalJSONTo implements encoding/json/v2.MarshalerTo.
func (v Person) MarshalJSONTo(enc *jsontext.Encoder) error {
	// Under a plain json.Marshal, from encoding/json/v2 or encoding/json,
	// the value is appended straight into the encoder's buffer at any
	// depth; see odjsonrt.BeginDirectEncodeMode for what qualifies and
	// for the mode, which does that call's escaping itself since nothing
	// downstream looks at the bytes.
	if buf, m, ok := odjsonrt.BeginDirectEncodeMode(enc); ok {
		n := len(buf)
		buf, err := v.odjsonAppend(buf, m)
		if err != nil {
			return err
		}
		odjsonSizePerson.Record(buf[n:])
		odjsonrt.EndDirectEncode(enc, buf)
		return nil
	}
	// Otherwise WriteValue copies what it is given, so the scratch buffer
	// can go straight back to the pool. ModeStream leaves the HTML escaping
	// and the UTF-8 validation to the encoder, which performs both while
	// reformatting the value either way.
	buf := odjsonrt.GetBuffer()
	var err error
	if buf.B, err = v.odjsonAppend(buf.B, odjsonrt.ModeStream); err == nil {
		odjsonSizePerson.Record(buf.B)
		err = enc.WriteValue(buf.B)
	}
	odjsonrt.PutBuffer(buf)
	return err
}

// UnmarshalJSONFrom implements encoding/json/v2.UnmarshalerFrom.
func (v *Person) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	// The cache plays the part of json/v2's own string cache: a value
	// that recurs in the document is allocated once.
	sc := odjsonrt.GetStringCache()
	var err error
	// Under a plain json.Unmarshal the value is parsed straight out of
	// the decoder's buffer at any depth; see odjsonrt.BeginDirectDecodeAt
	// for what qualifies. Nobody has validated those bytes, so
	// odjsonParseV2 rejects what jsontext would have.
	if data, p, ok := odjsonrt.BeginDirectDecodeAt(dec); ok {
		var end int
		if end, err = v.odjsonParseV2(data, p, sc, true); err == nil {
			odjsonrt.EndDirectDecodeAt(dec, p, end)
		}
	} else {
		err = v.odjsonParseFrom(dec, sc)
	}
	odjsonrt.PutStringCache(sc)
	return err
}
