// Code generated by odjson. DO NOT EDIT.
//
// Source: odjson -methods

package withmethods

import (
	"bytes"
	"encoding/json/jsontext"
	"github.com/mazrean/odjson/odjsonrt"
)

// odjsonAppend appends the JSON encoding of v to dst.
func (v *Address) odjsonAppend(dst []byte, m odjsonrt.StringMode) ([]byte, error) {
	var err error
	_ = err
	start := len(dst)
	dst = append(dst, ",\"street\":"...)
	dst = odjsonrt.AppendStringMode(dst, string(v.Street), m)
	if len(v.City) != 0 {
		dst = append(dst, ",\"city\":"...)
		dst = odjsonrt.AppendStringMode(dst, string(v.City), m)
	}
	if len(dst) == start {
		dst = append(dst, '{', '}')
	} else {
		dst[start] = '{'
		dst = append(dst, '}')
	}
	return dst, nil
}

// odjsonParse decodes the JSON object starting at p into v and
// returns the offset just past it.
func (v *Address) odjsonParse(data []byte, p int) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		return np, nil
	}
	if p >= len(data) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "Address")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if p < len(data) && data[p] == '}' {
		return p + 1, nil
	}
	for {
		var key []byte
		p = odjsonrt.SkipSpace(data, p)
		key, _, p, err = odjsonrt.ParseKey(data, p)
		if err != nil {
			return p, err
		}
		idx := -1
		switch string(key) {
		case "street":
			idx = 0
		case "city":
			idx = 1
		}
		if idx < 0 {
			fold := !odjsonrt.ASCII(key)
			switch {
			case (len(key) == 6 || fold) && odjsonrt.EqualFold(key, "street"):
				idx = 0
			case (len(key) == 4 || fold) && odjsonrt.EqualFold(key, "city"):
				idx = 1
			}
		}
		switch idx {
		case 0:
			p = odjsonrt.SkipSpace(data, p)
			if np1, ok2 := odjsonrt.ParseNull(data, p); ok2 {
				p = np1
			} else {
				var x3 string
				x3, p, err = odjsonrt.ParseString(data, p)
				if err != nil {
					return p, err
				}
				v.Street = x3
			}
		case 1:
			p = odjsonrt.SkipSpace(data, p)
			if np4, ok5 := odjsonrt.ParseNull(data, p); ok5 {
				p = np4
			} else {
				var x6 string
				x6, p, err = odjsonrt.ParseString(data, p)
				if err != nil {
					return p, err
				}
				v.City = x6
			}
		default:
			p = odjsonrt.SkipSpace(data, p)
			p, err = odjsonrt.SkipValue(data, p)
			if err != nil {
				return p, err
			}
		}
		p = odjsonrt.SkipSpace(data, p)
		if p >= len(data) {
			return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
		}
		switch data[p] {
		case ',':
			p++
		case '}':
			return p + 1, nil
		default:
			return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
		}
	}
}

// odjsonParseFrom decodes the next value in dec into v,
// driving the decoder token by token so the document is
// parsed once rather than twice.
func (v *Address) odjsonParseFrom(dec *jsontext.Decoder) error {
	var err error
	_ = err
	switch k := dec.PeekKind(); k {
	case 'n':
		_, err = dec.ReadToken()
		return err
	case '{':
	default:
		return odjsonrt.ErrKind(byte(k), "Address")
	}
	if _, err = dec.ReadToken(); err != nil {
		return err
	}
	for dec.PeekKind() != '}' {
		var key jsontext.Value
		key, err = dec.ReadValue()
		if err != nil {
			return err
		}
		idx := -1
		switch string(key) {
		case "\"street\"":
			idx = 0
		case "\"city\"":
			idx = 1
		}
		if idx < 0 && bytes.IndexByte(key, '\\') >= 0 {
			if name, ok := odjsonrt.UnquoteName(key); ok {
				switch string(name) {
				case "street":
					idx = 0
				case "city":
					idx = 1
				}
			}
		}
		switch idx {
		case 0:
			var val7 jsontext.Value
			val7, err = dec.ReadValue()
			if err != nil {
				return err
			}
			vp8 := 0
			if np9, ok10 := odjsonrt.ParseNull(val7, vp8); ok10 {
				vp8 = np9
			} else {
				var x11 string
				x11, vp8, err = odjsonrt.ParseStringTrusted(val7, vp8)
				if err != nil {
					return err
				}
				v.Street = x11
			}
			_ = vp8
		case 1:
			var val12 jsontext.Value
			val12, err = dec.ReadValue()
			if err != nil {
				return err
			}
			vp13 := 0
			if np14, ok15 := odjsonrt.ParseNull(val12, vp13); ok15 {
				vp13 = np14
			} else {
				var x16 string
				x16, vp13, err = odjsonrt.ParseStringTrusted(val12, vp13)
				if err != nil {
					return err
				}
				v.City = x16
			}
			_ = vp13
		default:
			if _, err = dec.ReadValue(); err != nil {
				return err
			}
		}
	}
	_, err = dec.ReadToken()
	return err
}

// AppendAddress appends the JSON encoding of v to dst.
func AppendAddress(dst []byte, v *Address) ([]byte, error) {
	return v.odjsonAppend(dst, odjsonrt.ModeHTML)
}

// odjsonSizeAddress sizes the buffer MarshalAddress allocates.
var odjsonSizeAddress odjsonrt.SizeHint

// MarshalAddress returns the JSON encoding of v.
func MarshalAddress(v *Address) ([]byte, error) {
	buf, err := v.odjsonAppend(odjsonSizeAddress.New(), odjsonrt.ModeHTML)
	if err != nil {
		return nil, err
	}
	odjsonSizeAddress.Record(buf)
	return buf, nil
}

// UnmarshalAddress decodes the JSON document data into v.
func UnmarshalAddress(data []byte, v *Address) error {
	p, err := v.odjsonParse(data, odjsonrt.SkipSpace(data, 0))
	if err != nil {
		return err
	}
	return odjsonrt.EndOfDocument(data, p)
}

// MarshalJSON implements encoding/json.Marshaler.
func (v Address) MarshalJSON() ([]byte, error) {
	return MarshalAddress(&v)
}

// UnmarshalJSON implements encoding/json.Unmarshaler.
func (v *Address) UnmarshalJSON(data []byte) error {
	return UnmarshalAddress(data, v)
}

// MarshalJSONTo implements encoding/json/v2.MarshalerTo.
func (v Address) MarshalJSONTo(enc *jsontext.Encoder) error {
	// WriteValue copies what it is given, so the scratch buffer can go
	// straight back to the pool. ModeStream leaves the HTML escaping and
	// the UTF-8 validation to the encoder, which performs both while
	// reformatting the value either way.
	buf := odjsonrt.GetBuffer()
	var err error
	if buf.B, err = v.odjsonAppend(buf.B, odjsonrt.ModeStream); err == nil {
		odjsonSizeAddress.Record(buf.B)
		err = enc.WriteValue(buf.B)
	}
	odjsonrt.PutBuffer(buf)
	return err
}

// UnmarshalJSONFrom implements encoding/json/v2.UnmarshalerFrom.
func (v *Address) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	return v.odjsonParseFrom(dec)
}

// odjsonAppend appends the JSON encoding of v to dst.
func (v *Person) odjsonAppend(dst []byte, m odjsonrt.StringMode) ([]byte, error) {
	var err error
	_ = err
	start := len(dst)
	dst = append(dst, ",\"name\":"...)
	dst = odjsonrt.AppendStringMode(dst, string(v.Name), m)
	dst = append(dst, ",\"age\":"...)
	dst = odjsonrt.AppendInt(dst, int64(v.Age))
	if v.Email != nil {
		dst = append(dst, ",\"email\":"...)
		if v.Email == nil {
			dst = append(dst, 'n', 'u', 'l', 'l')
		} else {
			dst = odjsonrt.AppendStringMode(dst, string((*v.Email)), m)
		}
	}
	if len(v.Tags) != 0 {
		dst = append(dst, ",\"tags\":"...)
		if v.Tags == nil {
			dst = odjsonrt.AppendNilSlice(dst, m)
		} else {
			dst = append(dst, '[')
			for i17 := range v.Tags {
				if i17 > 0 {
					dst = append(dst, ',')
				}
				dst = odjsonrt.AppendStringMode(dst, string(v.Tags[i17]), m)
			}
			dst = append(dst, ']')
		}
	}
	dst = append(dst, ",\"address\":"...)
	dst, err = v.Address.odjsonAppend(dst, m)
	if err != nil {
		return nil, err
	}
	if len(dst) == start {
		dst = append(dst, '{', '}')
	} else {
		dst[start] = '{'
		dst = append(dst, '}')
	}
	return dst, nil
}

// odjsonParse decodes the JSON object starting at p into v and
// returns the offset just past it.
func (v *Person) odjsonParse(data []byte, p int) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		return np, nil
	}
	if p >= len(data) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "Person")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if p < len(data) && data[p] == '}' {
		return p + 1, nil
	}
	for {
		var key []byte
		p = odjsonrt.SkipSpace(data, p)
		key, _, p, err = odjsonrt.ParseKey(data, p)
		if err != nil {
			return p, err
		}
		idx := -1
		switch string(key) {
		case "name":
			idx = 0
		case "age":
			idx = 1
		case "email":
			idx = 2
		case "tags":
			idx = 3
		case "address":
			idx = 4
		}
		if idx < 0 {
			fold := !odjsonrt.ASCII(key)
			switch {
			case (len(key) == 4 || fold) && odjsonrt.EqualFold(key, "name"):
				idx = 0
			case (len(key) == 3 || fold) && odjsonrt.EqualFold(key, "age"):
				idx = 1
			case (len(key) == 5 || fold) && odjsonrt.EqualFold(key, "email"):
				idx = 2
			case (len(key) == 4 || fold) && odjsonrt.EqualFold(key, "tags"):
				idx = 3
			case (len(key) == 7 || fold) && odjsonrt.EqualFold(key, "address"):
				idx = 4
			}
		}
		switch idx {
		case 0:
			p = odjsonrt.SkipSpace(data, p)
			if np18, ok19 := odjsonrt.ParseNull(data, p); ok19 {
				p = np18
			} else {
				var x20 string
				x20, p, err = odjsonrt.ParseString(data, p)
				if err != nil {
					return p, err
				}
				v.Name = x20
			}
		case 1:
			p = odjsonrt.SkipSpace(data, p)
			if np21, ok22 := odjsonrt.ParseNull(data, p); ok22 {
				p = np21
			} else {
				var x23 int64
				x23, p, err = odjsonrt.ParseInt(data, p, 64)
				if err != nil {
					return p, err
				}
				v.Age = int(x23)
			}
		case 2:
			p = odjsonrt.SkipSpace(data, p)
			if np24, ok25 := odjsonrt.ParseNull(data, p); ok25 {
				v.Email = nil
				p = np24
			} else {
				if v.Email == nil {
					v.Email = new(string)
				}
				p = odjsonrt.SkipSpace(data, p)
				if np26, ok27 := odjsonrt.ParseNull(data, p); ok27 {
					p = np26
				} else {
					var x28 string
					x28, p, err = odjsonrt.ParseString(data, p)
					if err != nil {
						return p, err
					}
					(*v.Email) = x28
				}
			}
		case 3:
			p = odjsonrt.SkipSpace(data, p)
			if np29, ok30 := odjsonrt.ParseNull(data, p); ok30 {
				p = np29
				v.Tags = nil
			} else {
				if p >= len(data) || data[p] != '[' {
					return p, odjsonrt.ErrType(data, p, "[]string")
				}
				p++
				s31 := v.Tags[:0]
				p = odjsonrt.SkipSpace(data, p)
				if p < len(data) && data[p] == ']' {
					p++
				} else {
					if cap(s31) == 0 {
						s31 = make([]string, 0, 4)
					}
					for {
						var e32 string
						p = odjsonrt.SkipSpace(data, p)
						if np33, ok34 := odjsonrt.ParseNull(data, p); ok34 {
							p = np33
						} else {
							var x35 string
							x35, p, err = odjsonrt.ParseString(data, p)
							if err != nil {
								return p, err
							}
							e32 = x35
						}
						s31 = append(s31, e32)
						p = odjsonrt.SkipSpace(data, p)
						if p >= len(data) {
							return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
						}
						if data[p] == ',' {
							p++
							continue
						}
						if data[p] == ']' {
							p++
							break
						}
						return p, odjsonrt.ErrSyntax(data, p, "after array element")
					}
				}
				if s31 == nil {
					s31 = []string{}
				}
				v.Tags = s31
			}
		case 4:
			p, err = v.Address.odjsonParse(data, p)
			if err != nil {
				return p, err
			}
		default:
			p = odjsonrt.SkipSpace(data, p)
			p, err = odjsonrt.SkipValue(data, p)
			if err != nil {
				return p, err
			}
		}
		p = odjsonrt.SkipSpace(data, p)
		if p >= len(data) {
			return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
		}
		switch data[p] {
		case ',':
			p++
		case '}':
			return p + 1, nil
		default:
			return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
		}
	}
}

// odjsonParseFrom decodes the next value in dec into v,
// driving the decoder token by token so the document is
// parsed once rather than twice.
func (v *Person) odjsonParseFrom(dec *jsontext.Decoder) error {
	var err error
	_ = err
	switch k := dec.PeekKind(); k {
	case 'n':
		_, err = dec.ReadToken()
		return err
	case '{':
	default:
		return odjsonrt.ErrKind(byte(k), "Person")
	}
	if _, err = dec.ReadToken(); err != nil {
		return err
	}
	for dec.PeekKind() != '}' {
		var key jsontext.Value
		key, err = dec.ReadValue()
		if err != nil {
			return err
		}
		idx := -1
		switch string(key) {
		case "\"name\"":
			idx = 0
		case "\"age\"":
			idx = 1
		case "\"email\"":
			idx = 2
		case "\"tags\"":
			idx = 3
		case "\"address\"":
			idx = 4
		}
		if idx < 0 && bytes.IndexByte(key, '\\') >= 0 {
			if name, ok := odjsonrt.UnquoteName(key); ok {
				switch string(name) {
				case "name":
					idx = 0
				case "age":
					idx = 1
				case "email":
					idx = 2
				case "tags":
					idx = 3
				case "address":
					idx = 4
				}
			}
		}
		switch idx {
		case 0:
			var val36 jsontext.Value
			val36, err = dec.ReadValue()
			if err != nil {
				return err
			}
			vp37 := 0
			if np38, ok39 := odjsonrt.ParseNull(val36, vp37); ok39 {
				vp37 = np38
			} else {
				var x40 string
				x40, vp37, err = odjsonrt.ParseStringTrusted(val36, vp37)
				if err != nil {
					return err
				}
				v.Name = x40
			}
			_ = vp37
		case 1:
			var val41 jsontext.Value
			val41, err = dec.ReadValue()
			if err != nil {
				return err
			}
			vp42 := 0
			if np43, ok44 := odjsonrt.ParseNull(val41, vp42); ok44 {
				vp42 = np43
			} else {
				var x45 int64
				x45, vp42, err = odjsonrt.ParseInt(val41, vp42, 64)
				if err != nil {
					return err
				}
				v.Age = int(x45)
			}
			_ = vp42
		case 2:
			if dec.PeekKind() == 'n' {
				if _, err = dec.ReadToken(); err != nil {
					return err
				}
				v.Email = nil
			} else {
				if v.Email == nil {
					v.Email = new(string)
				}
				var val46 jsontext.Value
				val46, err = dec.ReadValue()
				if err != nil {
					return err
				}
				vp47 := 0
				if np48, ok49 := odjsonrt.ParseNull(val46, vp47); ok49 {
					vp47 = np48
				} else {
					var x50 string
					x50, vp47, err = odjsonrt.ParseStringTrusted(val46, vp47)
					if err != nil {
						return err
					}
					(*v.Email) = x50
				}
				_ = vp47
			}
		case 3:
			switch k := dec.PeekKind(); k {
			case 'n':
				if _, err = dec.ReadToken(); err != nil {
					return err
				}
				v.Tags = nil
			case '[':
				if _, err = dec.ReadToken(); err != nil {
					return err
				}
				s51 := v.Tags[:0]
				if dec.PeekKind() != ']' && cap(s51) == 0 {
					s51 = make([]string, 0, 4)
				}
				for dec.PeekKind() != ']' {
					var e52 string
					var val53 jsontext.Value
					val53, err = dec.ReadValue()
					if err != nil {
						return err
					}
					vp54 := 0
					if np55, ok56 := odjsonrt.ParseNull(val53, vp54); ok56 {
						vp54 = np55
					} else {
						var x57 string
						x57, vp54, err = odjsonrt.ParseStringTrusted(val53, vp54)
						if err != nil {
							return err
						}
						e52 = x57
					}
					_ = vp54
					s51 = append(s51, e52)
				}
				if _, err = dec.ReadToken(); err != nil {
					return err
				}
				if s51 == nil {
					s51 = []string{}
				}
				v.Tags = s51
			default:
				return odjsonrt.ErrKind(byte(k), "[]string")
			}
		case 4:
			if err = v.Address.odjsonParseFrom(dec); err != nil {
				return err
			}
		default:
			if _, err = dec.ReadValue(); err != nil {
				return err
			}
		}
	}
	_, err = dec.ReadToken()
	return err
}

// AppendPerson appends the JSON encoding of v to dst.
func AppendPerson(dst []byte, v *Person) ([]byte, error) {
	return v.odjsonAppend(dst, odjsonrt.ModeHTML)
}

// odjsonSizePerson sizes the buffer MarshalPerson allocates.
var odjsonSizePerson odjsonrt.SizeHint

// MarshalPerson returns the JSON encoding of v.
func MarshalPerson(v *Person) ([]byte, error) {
	buf, err := v.odjsonAppend(odjsonSizePerson.New(), odjsonrt.ModeHTML)
	if err != nil {
		return nil, err
	}
	odjsonSizePerson.Record(buf)
	return buf, nil
}

// UnmarshalPerson decodes the JSON document data into v.
func UnmarshalPerson(data []byte, v *Person) error {
	p, err := v.odjsonParse(data, odjsonrt.SkipSpace(data, 0))
	if err != nil {
		return err
	}
	return odjsonrt.EndOfDocument(data, p)
}

// MarshalJSON implements encoding/json.Marshaler.
func (v Person) MarshalJSON() ([]byte, error) {
	return MarshalPerson(&v)
}

// UnmarshalJSON implements encoding/json.Unmarshaler.
func (v *Person) UnmarshalJSON(data []byte) error {
	return UnmarshalPerson(data, v)
}

// MarshalJSONTo implements encoding/json/v2.MarshalerTo.
func (v Person) MarshalJSONTo(enc *jsontext.Encoder) error {
	// WriteValue copies what it is given, so the scratch buffer can go
	// straight back to the pool. ModeStream leaves the HTML escaping and
	// the UTF-8 validation to the encoder, which performs both while
	// reformatting the value either way.
	buf := odjsonrt.GetBuffer()
	var err error
	if buf.B, err = v.odjsonAppend(buf.B, odjsonrt.ModeStream); err == nil {
		odjsonSizePerson.Record(buf.B)
		err = enc.WriteValue(buf.B)
	}
	odjsonrt.PutBuffer(buf)
	return err
}

// UnmarshalJSONFrom implements encoding/json/v2.UnmarshalerFrom.
func (v *Person) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	return v.odjsonParseFrom(dec)
}
