// Code generated by odjson. DO NOT EDIT.
//
// Source: odjson -direct

package direct

import (
	"bytes"
	"encoding/json/jsontext"
	"github.com/mazrean/odjson/odjsonrt"
	"slices"
)

// odjsonAppend appends the JSON encoding of v to dst.
func (v *Root) odjsonAppend(dst []byte, m odjsonrt.StringMode) ([]byte, error) {
	var err error
	_ = err
	start := len(dst)
	dst = append(dst, ",\"name\":\""...)
	dst, err = odjsonrt.AppendStringBodyChecked(dst, string(v.Name), m)
	if err != nil {
		return nil, err
	}
	dst = append(dst, "\""...)
	if m.V2() || v.Count != 0 {
		dst = append(dst, ",\"count\":"...)
		dst = odjsonrt.AppendInt(dst, int64(v.Count))
	}
	if v.Tags == nil {
		if m.V2() {
			dst = append(dst, ",\"tags\":[],\"rati"...)
			dst = append(dst, "o\":"...)
		} else {
			dst = append(dst, ",\"tags\":null,\"ra"...)
			dst = append(dst, "tio\":"...)
		}
	} else {
		dst = append(dst, ",\"tags\":["...)
		for i1 := range v.Tags {
			if i1 > 0 {
				dst = append(dst, ',')
			}
			dst = append(dst, "\""...)
			dst, err = odjsonrt.AppendStringBodyChecked(dst, string(v.Tags[i1]), m)
			if err != nil {
				return nil, err
			}
			dst = append(dst, "\""...)
		}
		dst = append(dst, "],\"ratio\":"...)
	}
	dst, err = odjsonrt.AppendFloat(dst, float64(v.Ratio), 64)
	if err != nil {
		return nil, err
	}
	dst = append(dst, ",\"nested\":"...)
	dst, err = v.Nested.odjsonAppend(dst, m)
	if err != nil {
		return nil, err
	}
	dst[start] = '{'
	if v.Ptr == nil {
		dst = append(dst, ",\"ptr\":null}"...)
	} else {
		dst = append(dst, ",\"ptr\":"...)
		dst, err = (*v.Ptr).odjsonAppend(dst, m)
		if err != nil {
			return nil, err
		}
		dst = append(dst, "}"...)
	}
	return dst, nil
}

// odjsonCapRootTags remembers how long v.Tags has been, to allocate it once.
var odjsonCapRootTags odjsonrt.CapHint

// odjsonParse decodes the JSON object starting at p into v and
// returns the offset just past it. Strings are interned through
// sc, which may be nil.
func (v *Root) odjsonParse(data []byte, p int, sc *odjsonrt.StringCache) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		return np, nil
	}
	if uint(p) >= uint(len(data)) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "Root")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if uint(p) < uint(len(data)) && data[p] == '}' {
		return p + 1, nil
	}
	for {
		if uint(p) >= uint(len(data)) || data[p] <= ' ' {
			p = odjsonrt.SkipSpace(data, odjsonrt.SkipIndent(data, p))
		}
		rest := data[p:]
		if len(rest) > 3 {
			switch rest[3] {
			case 'm':
				if len(rest) >= 6 && string(rest[:6]) == "\"name\"" {
					p += 6
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m2
				}
			case 'u':
				if len(rest) >= 7 && string(rest[:7]) == "\"count\"" {
					p += 7
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m3
				}
			case 'g':
				if len(rest) >= 6 && string(rest[:6]) == "\"tags\"" {
					p += 6
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m4
				}
			case 't':
				if len(rest) >= 7 && string(rest[:7]) == "\"ratio\"" {
					p += 7
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m5
				}
			case 's':
				if len(rest) >= 8 && string(rest[:8]) == "\"nested\"" {
					p += 8
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m6
				}
			case 'r':
				if len(rest) >= 5 && string(rest[:5]) == "\"ptr\"" {
					p += 5
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m7
				}
			}
		}
		{
			var key []byte
			key, _, p, err = odjsonrt.ParseKey(data, p)
			if err != nil {
				return p, err
			}
			switch string(key) {
			case "name":
				goto m2
			case "count":
				goto m3
			case "tags":
				goto m4
			case "ratio":
				goto m5
			case "nested":
				goto m6
			case "ptr":
				goto m7
			}
			p = odjsonrt.SkipSpace(data, p)
			p, err = odjsonrt.SkipValue(data, p)
			if err != nil {
				return p, err
			}
			goto next8
		}
	m2:
		{
			if np9, ok10 := odjsonrt.ParseNull(data, p); ok10 {
				p = np9
			} else {
				var x11 string
				x11, p, err = odjsonrt.ParseStringCached(data, p, sc)
				if err != nil {
					return p, err
				}
				v.Name = x11
			}
			goto next8
		}
	m3:
		{
			if np12, ok13 := odjsonrt.ParseNull(data, p); ok13 {
				p = np12
			} else {
				if x14, np15, ok16 := odjsonrt.ParseDecimal(data, p); ok16 {
					v.Count = int(x14)
					p = np15
				} else {
					var x17 int64
					x17, p, err = odjsonrt.ParseInt(data, p, 64)
					if err != nil {
						return p, err
					}
					v.Count = int(x17)
				}
			}
			goto next8
		}
	m4:
		{
			if np18, ok19 := odjsonrt.ParseNull(data, p); ok19 {
				p = np18
				v.Tags = nil
			} else {
				if uint(p) >= uint(len(data)) || data[p] != '[' {
					return p, odjsonrt.ErrType(data, p, "[]string")
				}
				p++
				s20 := v.Tags[:0]
				p = odjsonrt.SkipSpace(data, p)
				if uint(p) < uint(len(data)) && data[p] == ']' {
					p++
				} else {
					if cap(s20) == 0 {
						s20 = make([]string, 0, odjsonrt.CapFor[string](&odjsonCapRootTags))
					}
					for {
						var e21 string
						if uint(p) >= uint(len(data)) || data[p] <= ' ' {
							p = odjsonrt.SkipSpace(data, odjsonrt.SkipIndent(data, p))
						}
						if np23, ok24 := odjsonrt.ParseNull(data, p); ok24 {
							p = np23
						} else {
							var x25 string
							x25, p, err = odjsonrt.ParseStringCached(data, p, sc)
							if err != nil {
								return p, err
							}
							e21 = x25
						}
						s20 = append(s20, e21)
						p = odjsonrt.SkipSpace(data, p)
						if uint(p) >= uint(len(data)) {
							return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
						}
						if data[p] == ',' {
							p++
							continue
						}
						if data[p] == ']' {
							p++
							break
						}
						return p, odjsonrt.ErrSyntax(data, p, "after array element")
					}
					odjsonCapRootTags.Record(len(s20))
				}
				if s20 == nil {
					s20 = []string{}
				}
				v.Tags = s20
			}
			goto next8
		}
	m5:
		{
			if np26, ok27 := odjsonrt.ParseNull(data, p); ok27 {
				p = np26
			} else {
				if x28, np29, ok30 := odjsonrt.ParseSimpleFloat(data, p, 64); ok30 {
					v.Ratio = float64(x28)
					p = np29
				} else {
					var x31 float64
					x31, p, err = odjsonrt.ParseFloat(data, p, 64)
					if err != nil {
						return p, err
					}
					v.Ratio = x31
				}
			}
			goto next8
		}
	m6:
		{
			p, err = v.Nested.odjsonParse(data, p, sc)
			if err != nil {
				return p, err
			}
			goto next8
		}
	m7:
		{
			if np32, ok33 := odjsonrt.ParseNull(data, p); ok33 {
				v.Ptr = nil
				p = np32
			} else {
				if v.Ptr == nil {
					v.Ptr = new(nested)
				}
				p, err = (*v.Ptr).odjsonParse(data, p, sc)
				if err != nil {
					return p, err
				}
			}
		}
	next8:
		{
			p = odjsonrt.SkipSpace(data, p)
			if uint(p) >= uint(len(data)) {
				return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
			}
			switch data[p] {
			case ',':
				p++
			case '}':
				return p + 1, nil
			default:
				return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
			}
		}
	}
}

// odjsonParseV2 is odjsonParse under encoding/json/v2's semantics, for
// input a jsontext.Decoder has already validated when strict is false,
// and for bytes nobody has looked at when it is true.
func (v *Root) odjsonParseV2(data []byte, p int, sc *odjsonrt.StringCache, strict bool) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		*v = Root{}
		return np, nil
	}
	if uint(p) >= uint(len(data)) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "Root")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if uint(p) < uint(len(data)) && data[p] == '}' {
		return p + 1, nil
	}
	var seen [1]uint64
	_ = seen
	unknown, umark := odjsonrt.UnknownNames(sc)
	var ufilter uint64
	_ = ufilter
	for {
		if uint(p) >= uint(len(data)) || data[p] <= ' ' {
			p = odjsonrt.SkipSpace(data, odjsonrt.SkipIndent(data, p))
		}
		kp := p
		rest := data[p:]
		if len(rest) > 3 {
			switch rest[3] {
			case 'm':
				if len(rest) >= 6 && string(rest[:6]) == "\"name\"" {
					p += 6
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m34
				}
			case 'u':
				if len(rest) >= 7 && string(rest[:7]) == "\"count\"" {
					p += 7
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m35
				}
			case 'g':
				if len(rest) >= 6 && string(rest[:6]) == "\"tags\"" {
					p += 6
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m36
				}
			case 't':
				if len(rest) >= 7 && string(rest[:7]) == "\"ratio\"" {
					p += 7
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m37
				}
			case 's':
				if len(rest) >= 8 && string(rest[:8]) == "\"nested\"" {
					p += 8
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m38
				}
			case 'r':
				if len(rest) >= 5 && string(rest[:5]) == "\"ptr\"" {
					p += 5
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m39
				}
			}
		}
		{
			var key []byte
			key, p, err = odjsonrt.ParseKeyV2(data, p, strict)
			if err != nil {
				return p, err
			}
			switch string(key) {
			case "name":
				goto m34
			case "count":
				goto m35
			case "tags":
				goto m36
			case "ratio":
				goto m37
			case "nested":
				goto m38
			case "ptr":
				goto m39
			}
			if strict {
				var dup bool
				if unknown, dup = odjsonrt.UnknownName(sc, unknown, umark, &ufilter, key); dup {
					return kp, odjsonrt.ErrDuplicateName(data, kp, key)
				}
			}
			p = odjsonrt.SkipSpace(data, p)
			p, err = odjsonrt.SkipValueV2(data, p, strict)
			if err != nil {
				return p, err
			}
			goto next40
		}
	m34:
		{
			if strict && seen[0]&(1<<0) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 0
			if np41, ok42 := odjsonrt.ParseNull(data, p); ok42 {
				p = np41
				v.Name = ""
			} else {
				var x43 string
				x43, p, err = odjsonrt.ParseStringV2(data, p, sc, strict)
				if err != nil {
					return p, err
				}
				v.Name = x43
			}
			goto next40
		}
	m35:
		{
			if strict && seen[0]&(1<<1) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 1
			if np44, ok45 := odjsonrt.ParseNull(data, p); ok45 {
				p = np44
				v.Count = 0
			} else {
				if x46, np47, ok48 := odjsonrt.ParseDecimal(data, p); ok48 {
					v.Count = int(x46)
					p = np47
				} else {
					var x49 int64
					x49, p, err = odjsonrt.ParseInt(data, p, 64)
					if err != nil {
						return p, err
					}
					v.Count = int(x49)
				}
			}
			goto next40
		}
	m36:
		{
			if strict && seen[0]&(1<<2) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 2
			if np50, ok51 := odjsonrt.ParseNull(data, p); ok51 {
				p = np50
				v.Tags = nil
			} else {
				if uint(p) >= uint(len(data)) || data[p] != '[' {
					return p, odjsonrt.ErrType(data, p, "[]string")
				}
				p++
				s52 := v.Tags[:0]
				p = odjsonrt.SkipSpace(data, p)
				if uint(p) < uint(len(data)) && data[p] == ']' {
					p++
				} else {
					if cap(s52) == 0 {
						s52 = make([]string, 0, odjsonrt.CapFor[string](&odjsonCapRootTags))
					}
					for {
						var e53 string
						if uint(p) >= uint(len(data)) || data[p] <= ' ' {
							p = odjsonrt.SkipSpace(data, odjsonrt.SkipIndent(data, p))
						}
						if np55, ok56 := odjsonrt.ParseNull(data, p); ok56 {
							p = np55
							e53 = ""
						} else {
							var x57 string
							x57, p, err = odjsonrt.ParseStringV2(data, p, sc, strict)
							if err != nil {
								return p, err
							}
							e53 = x57
						}
						s52 = append(s52, e53)
						p = odjsonrt.SkipSpace(data, p)
						if uint(p) >= uint(len(data)) {
							return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
						}
						if data[p] == ',' {
							p++
							continue
						}
						if data[p] == ']' {
							p++
							break
						}
						return p, odjsonrt.ErrSyntax(data, p, "after array element")
					}
					odjsonCapRootTags.Record(len(s52))
				}
				if s52 == nil {
					s52 = []string{}
				}
				v.Tags = s52
			}
			goto next40
		}
	m37:
		{
			if strict && seen[0]&(1<<3) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 3
			if np58, ok59 := odjsonrt.ParseNull(data, p); ok59 {
				p = np58
				v.Ratio = 0
			} else {
				if x60, np61, ok62 := odjsonrt.ParseSimpleFloat(data, p, 64); ok62 {
					v.Ratio = float64(x60)
					p = np61
				} else {
					var x63 float64
					x63, p, err = odjsonrt.ParseFloat(data, p, 64)
					if err != nil {
						return p, err
					}
					v.Ratio = x63
				}
			}
			goto next40
		}
	m38:
		{
			if strict && seen[0]&(1<<4) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 4
			p, err = v.Nested.odjsonParseV2(data, p, sc, strict)
			if err != nil {
				return p, err
			}
			goto next40
		}
	m39:
		{
			if strict && seen[0]&(1<<5) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 5
			if np64, ok65 := odjsonrt.ParseNull(data, p); ok65 {
				v.Ptr = nil
				p = np64
			} else {
				if v.Ptr == nil {
					v.Ptr = new(nested)
				}
				p, err = (*v.Ptr).odjsonParseV2(data, p, sc, strict)
				if err != nil {
					return p, err
				}
			}
		}
	next40:
		{
			p = odjsonrt.SkipSpace(data, p)
			if uint(p) >= uint(len(data)) {
				return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
			}
			switch data[p] {
			case ',':
				p++
			case '}':
				odjsonrt.EndUnknownNames(sc, unknown, umark)
				return p + 1, nil
			default:
				return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
			}
		}
	}
}

// odjsonParseFrom decodes the next value in dec into v,
// driving the decoder token by token so the document is
// parsed once rather than twice.
func (v *Root) odjsonParseFrom(dec *jsontext.Decoder, sc *odjsonrt.StringCache) error {
	var err error
	_ = err
	if odjsonrt.WholeValue(dec) {
		var val jsontext.Value
		if val, err = dec.ReadValue(); err != nil {
			return err
		}
		_, err = v.odjsonParseV2(val, 0, sc, false)
		return err
	}
	switch odjsonrt.NextKind(dec) {
	case 'n':
		if _, err = dec.ReadToken(); err != nil {
			return err
		}
		*v = Root{}
		return nil
	case '{':
	default:
		return odjsonrt.ErrKindFrom(dec, "Root")
	}
	if _, err = dec.ReadToken(); err != nil {
		return err
	}
	for odjsonrt.NextKind(dec) != '}' {
		var key jsontext.Value
		key, err = dec.ReadValue()
		if err != nil {
			return err
		}
		idx := -1
		switch string(key) {
		case "\"name\"":
			idx = 0
		case "\"count\"":
			idx = 1
		case "\"tags\"":
			idx = 2
		case "\"ratio\"":
			idx = 3
		case "\"nested\"":
			idx = 4
		case "\"ptr\"":
			idx = 5
		}
		if idx < 0 && bytes.IndexByte(key, '\\') >= 0 {
			if name, ok := odjsonrt.UnquoteName(key); ok {
				switch string(name) {
				case "name":
					idx = 0
				case "count":
					idx = 1
				case "tags":
					idx = 2
				case "ratio":
					idx = 3
				case "nested":
					idx = 4
				case "ptr":
					idx = 5
				}
			}
		}
		switch idx {
		case 0:
			var val66 jsontext.Value
			val66, err = dec.ReadValue()
			if err != nil {
				return err
			}
			if val66[0] == 'n' {
				v.Name = ""
			} else {
				var x67 string
				x67, err = odjsonrt.ParseStringValue(val66, sc)
				if err != nil {
					return err
				}
				v.Name = x67
			}
		case 1:
			var val68 jsontext.Value
			val68, err = dec.ReadValue()
			if err != nil {
				return err
			}
			if val68[0] == 'n' {
				v.Count = 0
			} else {
				var x69 int64
				x69, _, err = odjsonrt.ParseInt(val68, 0, 64)
				if err != nil {
					return err
				}
				v.Count = int(x69)
			}
		case 2:
			var val70 jsontext.Value
			val70, err = dec.ReadValue()
			if err != nil {
				return err
			}
			vp71 := 0
			if np72, ok73 := odjsonrt.ParseNull(val70, vp71); ok73 {
				vp71 = np72
				v.Tags = nil
			} else {
				if uint(vp71) >= uint(len(val70)) || val70[vp71] != '[' {
					return odjsonrt.ErrType(val70, vp71, "[]string")
				}
				vp71++
				s74 := v.Tags[:0]
				vp71 = odjsonrt.SkipSpace(val70, vp71)
				if uint(vp71) < uint(len(val70)) && val70[vp71] == ']' {
					vp71++
				} else {
					if cap(s74) == 0 {
						s74 = make([]string, 0, odjsonrt.CapFor[string](&odjsonCapRootTags))
					}
					for {
						var e75 string
						if uint(vp71) >= uint(len(val70)) || val70[vp71] <= ' ' {
							vp71 = odjsonrt.SkipSpace(val70, odjsonrt.SkipIndent(val70, vp71))
						}
						if np77, ok78 := odjsonrt.ParseNull(val70, vp71); ok78 {
							vp71 = np77
							e75 = ""
						} else {
							var x79 string
							x79, vp71, err = odjsonrt.ParseStringWith(val70, vp71, sc)
							if err != nil {
								return err
							}
							e75 = x79
						}
						s74 = append(s74, e75)
						vp71 = odjsonrt.SkipSpace(val70, vp71)
						if uint(vp71) >= uint(len(val70)) {
							return odjsonrt.ErrSyntax(val70, vp71, "unexpected end of JSON input")
						}
						if val70[vp71] == ',' {
							vp71++
							continue
						}
						if val70[vp71] == ']' {
							vp71++
							break
						}
						return odjsonrt.ErrSyntax(val70, vp71, "after array element")
					}
					odjsonCapRootTags.Record(len(s74))
				}
				if s74 == nil {
					s74 = []string{}
				}
				v.Tags = s74
			}
			_ = vp71
		case 3:
			var val80 jsontext.Value
			val80, err = dec.ReadValue()
			if err != nil {
				return err
			}
			if val80[0] == 'n' {
				v.Ratio = 0
			} else {
				var x81 float64
				x81, err = odjsonrt.ParseFloatValue(val80, 64)
				if err != nil {
					return err
				}
				v.Ratio = x81
			}
		case 4:
			if err = v.Nested.odjsonParseFrom(dec, sc); err != nil {
				return err
			}
		case 5:
			if odjsonrt.NextKind(dec) == 'n' {
				if _, err = dec.ReadToken(); err != nil {
					return err
				}
				v.Ptr = nil
			} else {
				if v.Ptr == nil {
					v.Ptr = new(nested)
				}
				if err = (*v.Ptr).odjsonParseFrom(dec, sc); err != nil {
					return err
				}
			}
		default:
			if _, err = dec.ReadValue(); err != nil {
				return err
			}
		}
	}
	_, err = dec.ReadToken()
	return err
}

// odjsonSizeRoot sizes the buffer the encoders allocate.
var odjsonSizeRoot odjsonrt.SizeHint

// MarshalJSON implements encoding/json.Marshaler.
func (v Root) MarshalJSON() ([]byte, error) {
	buf, err := v.odjsonAppend(odjsonSizeRoot.New(), odjsonrt.ModeHTML)
	if err != nil {
		return nil, err
	}
	odjsonSizeRoot.Record(buf)
	return buf, nil
}

// UnmarshalJSON implements encoding/json.Unmarshaler.
func (v *Root) UnmarshalJSON(data []byte) error {
	// The cache plays the part of encoding/json/v2's string cache: a
	// value that recurs in the document is allocated once.
	sc := odjsonrt.GetStringCache()
	p, err := v.odjsonParse(data, odjsonrt.SkipSpace(data, 0), sc)
	odjsonrt.PutStringCache(sc)
	if err != nil {
		return err
	}
	return odjsonrt.EndOfDocument(data, p)
}

// MarshalJSONTo implements encoding/json/v2.MarshalerTo.
func (v Root) MarshalJSONTo(enc *jsontext.Encoder) error {
	// Under a plain json.Marshal, from encoding/json/v2 or encoding/json,
	// the value is appended straight into the encoder's buffer at any
	// depth; see odjsonrt.BeginDirectEncodeMode for what qualifies and
	// for the mode, which does that call's escaping itself since nothing
	// downstream looks at the bytes.
	if buf, m, ok := odjsonrt.BeginDirectEncodeMode(enc); ok {
		n := len(buf)
		buf, err := v.odjsonAppend(buf, m)
		if err != nil {
			return err
		}
		odjsonSizeRoot.Record(buf[n:])
		odjsonrt.EndDirectEncode(enc, buf)
		return nil
	}
	// Otherwise WriteValue copies what it is given, so the scratch buffer
	// can go straight back to the pool. ModeStream leaves the HTML escaping
	// and the UTF-8 validation to the encoder, which performs both while
	// reformatting the value either way.
	buf := odjsonrt.GetBuffer()
	var err error
	if buf.B, err = v.odjsonAppend(buf.B, odjsonrt.ModeStream); err == nil {
		odjsonSizeRoot.Record(buf.B)
		err = enc.WriteValue(buf.B)
	}
	odjsonrt.PutBuffer(buf)
	return err
}

// UnmarshalJSONFrom implements encoding/json/v2.UnmarshalerFrom.
func (v *Root) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	// The cache plays the part of json/v2's own string cache: a value
	// that recurs in the document is allocated once.
	sc := odjsonrt.GetStringCache()
	var err error
	// Under a plain json.Unmarshal the value is parsed straight out of
	// the decoder's buffer at any depth; see odjsonrt.BeginDirectDecodeAt
	// for what qualifies. Nobody has validated those bytes, so
	// odjsonParseV2 rejects what jsontext would have.
	if data, p, ok := odjsonrt.BeginDirectDecodeAt(dec); ok {
		var end int
		if end, err = v.odjsonParseV2(data, p, sc, true); err == nil {
			odjsonrt.EndDirectDecodeAt(dec, p, end)
		}
	} else {
		err = v.odjsonParseFrom(dec, sc)
	}
	odjsonrt.PutStringCache(sc)
	return err
}

// MarshalRoot returns the JSON encoding of v, reaching the generated
// encoder without going through encoding/json.
func MarshalRoot(v *Root) ([]byte, error) {
	// The encoding is built in a pooled buffer and copied out once,
	// rather than written into a buffer allocated at the right size:
	// a fresh allocation is handed out zeroed, so writing into it
	// walks cold memory twice, while the copy out of a warm pooled
	// buffer allocates without zeroing and moves the bytes once.
	buf := odjsonrt.GetBuffer()
	var err error
	buf.B, err = v.odjsonAppend(buf.B, odjsonrt.ModeV2HTML)
	if err != nil {
		odjsonrt.PutBuffer(buf)
		return nil, err
	}
	out := bytes.Clone(buf.B)
	odjsonrt.PutBuffer(buf)
	return out, nil
}

// AppendRoot appends the JSON encoding of v to dst and returns the
// extended buffer. On failure dst is returned with nothing appended.
func AppendRoot(dst []byte, v *Root) ([]byte, error) {
	n := len(dst)
	dst, err := v.odjsonAppend(dst, odjsonrt.ModeV2HTML)
	if err != nil {
		return dst[:n], err
	}
	return dst, nil
}

// UnmarshalRoot decodes a complete JSON document into v under
// encoding/json/v2's semantics. Nobody has validated data, so the parser
// rejects what jsontext would have.
func UnmarshalRoot(data []byte, v *Root) error {
	// The cache plays the part of encoding/json/v2's string cache: a
	// value that recurs in the document is allocated once.
	sc := odjsonrt.GetStringCache()
	p, err := v.odjsonParseV2(data, odjsonrt.SkipSpace(data, 0), sc, true)
	odjsonrt.PutStringCache(sc)
	if err != nil {
		return err
	}
	return odjsonrt.EndOfDocument(data, p)
}

// odjsonAppend appends the JSON encoding of v to dst.
func (v *nested) odjsonAppend(dst []byte, m odjsonrt.StringMode) ([]byte, error) {
	var err error
	_ = err
	start := len(dst)
	dst = append(dst, ",\"id\":"...)
	dst = odjsonrt.AppendInt(dst, int64(v.ID))
	if v.Meta == nil {
		if m.V2() {
			dst = append(dst, ",\"meta\":{}"...)
		} else {
			dst = append(dst, ",\"meta\":null"...)
		}
	} else {
		keys82 := make([]string, 0, len(v.Meta))
		for k83 := range v.Meta {
			keys82 = append(keys82, string(k83))
		}
		if m != odjsonrt.ModeV2 {
			slices.Sort(keys82)
		}
		dst = append(dst, ",\"meta\":{"...)
		for i84, k83 := range keys82 {
			if i84 > 0 {
				dst = append(dst, ',')
			}
			dst = append(dst, '"')
			dst, err = odjsonrt.AppendStringBodyChecked(dst, k83, m)
			if err != nil {
				return nil, err
			}
			mv85 := v.Meta[k83]
			dst = append(dst, "\":\""...)
			dst, err = odjsonrt.AppendStringBodyChecked(dst, string(mv85), m)
			if err != nil {
				return nil, err
			}
			dst = append(dst, "\""...)
		}
		dst = append(dst, "}"...)
	}
	if m.V2() || bool(v.On) {
		if bool(v.On) {
			dst = append(dst, ",\"on\":true"...)
		} else {
			dst = append(dst, ",\"on\":false"...)
		}
	}
	dst[start] = '{'
	dst = append(dst, "}"...)
	return dst, nil
}

// odjsonParse decodes the JSON object starting at p into v and
// returns the offset just past it. Strings are interned through
// sc, which may be nil.
func (v *nested) odjsonParse(data []byte, p int, sc *odjsonrt.StringCache) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		return np, nil
	}
	if uint(p) >= uint(len(data)) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "nested")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if uint(p) < uint(len(data)) && data[p] == '}' {
		return p + 1, nil
	}
	for {
		if uint(p) >= uint(len(data)) || data[p] <= ' ' {
			p = odjsonrt.SkipSpace(data, odjsonrt.SkipIndent(data, p))
		}
		rest := data[p:]
		if len(rest) > 1 {
			switch rest[1] {
			case 'i':
				if len(rest) >= 4 && string(rest[:4]) == "\"id\"" {
					p += 4
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m86
				}
			case 'm':
				if len(rest) >= 6 && string(rest[:6]) == "\"meta\"" {
					p += 6
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m87
				}
			case 'o':
				if len(rest) >= 4 && string(rest[:4]) == "\"on\"" {
					p += 4
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m88
				}
			}
		}
		{
			var key []byte
			key, _, p, err = odjsonrt.ParseKey(data, p)
			if err != nil {
				return p, err
			}
			switch string(key) {
			case "id":
				goto m86
			case "meta":
				goto m87
			case "on":
				goto m88
			}
			p = odjsonrt.SkipSpace(data, p)
			p, err = odjsonrt.SkipValue(data, p)
			if err != nil {
				return p, err
			}
			goto next89
		}
	m86:
		{
			if np90, ok91 := odjsonrt.ParseNull(data, p); ok91 {
				p = np90
			} else {
				if x92, np93, ok94 := odjsonrt.ParseDecimal(data, p); ok94 {
					v.ID = int(x92)
					p = np93
				} else {
					var x95 int64
					x95, p, err = odjsonrt.ParseInt(data, p, 64)
					if err != nil {
						return p, err
					}
					v.ID = int(x95)
				}
			}
			goto next89
		}
	m87:
		{
			if np96, ok97 := odjsonrt.ParseNull(data, p); ok97 {
				p = np96
				v.Meta = nil
			} else {
				if uint(p) >= uint(len(data)) || data[p] != '{' {
					return p, odjsonrt.ErrType(data, p, "map[string]string")
				}
				p++
				m98 := v.Meta
				if m98 == nil {
					m98 = make(map[string]string)
				}
				p = odjsonrt.SkipSpace(data, p)
				if uint(p) < uint(len(data)) && data[p] == '}' {
					p++
				} else {
					for {
						var k99 []byte
						p = odjsonrt.SkipSpace(data, p)
						k99, _, p, err = odjsonrt.ParseKey(data, p)
						if err != nil {
							return p, err
						}
						var mv100 string
						p = odjsonrt.SkipSpace(data, p)
						if np102, ok103 := odjsonrt.ParseNull(data, p); ok103 {
							p = np102
						} else {
							var x104 string
							x104, p, err = odjsonrt.ParseStringCached(data, p, sc)
							if err != nil {
								return p, err
							}
							mv100 = x104
						}
						m98[sc.Make(k99)] = mv100
						p = odjsonrt.SkipSpace(data, p)
						if uint(p) >= uint(len(data)) {
							return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
						}
						if data[p] == ',' {
							p++
							continue
						}
						if data[p] == '}' {
							p++
							break
						}
						return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
					}
				}
				v.Meta = m98
			}
			goto next89
		}
	m88:
		{
			if np105, ok106 := odjsonrt.ParseNull(data, p); ok106 {
				p = np105
			} else {
				if uint(p+4) <= uint(len(data)) && string(data[p:p+4]) == "true" {
					v.On = true
					p += 4
				} else if uint(p+5) <= uint(len(data)) && string(data[p:p+5]) == "false" {
					v.On = false
					p += 5
				} else {
					var x107 bool
					x107, p, err = odjsonrt.ParseBool(data, p)
					if err != nil {
						return p, err
					}
					v.On = x107
				}
			}
		}
	next89:
		{
			p = odjsonrt.SkipSpace(data, p)
			if uint(p) >= uint(len(data)) {
				return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
			}
			switch data[p] {
			case ',':
				p++
			case '}':
				return p + 1, nil
			default:
				return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
			}
		}
	}
}

// odjsonParseV2 is odjsonParse under encoding/json/v2's semantics, for
// input a jsontext.Decoder has already validated when strict is false,
// and for bytes nobody has looked at when it is true.
func (v *nested) odjsonParseV2(data []byte, p int, sc *odjsonrt.StringCache, strict bool) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		*v = nested{}
		return np, nil
	}
	if uint(p) >= uint(len(data)) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "nested")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if uint(p) < uint(len(data)) && data[p] == '}' {
		return p + 1, nil
	}
	var seen [1]uint64
	_ = seen
	unknown, umark := odjsonrt.UnknownNames(sc)
	var ufilter uint64
	_ = ufilter
	for {
		if uint(p) >= uint(len(data)) || data[p] <= ' ' {
			p = odjsonrt.SkipSpace(data, odjsonrt.SkipIndent(data, p))
		}
		kp := p
		rest := data[p:]
		if len(rest) > 1 {
			switch rest[1] {
			case 'i':
				if len(rest) >= 4 && string(rest[:4]) == "\"id\"" {
					p += 4
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m108
				}
			case 'm':
				if len(rest) >= 6 && string(rest[:6]) == "\"meta\"" {
					p += 6
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m109
				}
			case 'o':
				if len(rest) >= 4 && string(rest[:4]) == "\"on\"" {
					p += 4
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m110
				}
			}
		}
		{
			var key []byte
			key, p, err = odjsonrt.ParseKeyV2(data, p, strict)
			if err != nil {
				return p, err
			}
			switch string(key) {
			case "id":
				goto m108
			case "meta":
				goto m109
			case "on":
				goto m110
			}
			if strict {
				var dup bool
				if unknown, dup = odjsonrt.UnknownName(sc, unknown, umark, &ufilter, key); dup {
					return kp, odjsonrt.ErrDuplicateName(data, kp, key)
				}
			}
			p = odjsonrt.SkipSpace(data, p)
			p, err = odjsonrt.SkipValueV2(data, p, strict)
			if err != nil {
				return p, err
			}
			goto next111
		}
	m108:
		{
			if strict && seen[0]&(1<<0) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 0
			if np112, ok113 := odjsonrt.ParseNull(data, p); ok113 {
				p = np112
				v.ID = 0
			} else {
				if x114, np115, ok116 := odjsonrt.ParseDecimal(data, p); ok116 {
					v.ID = int(x114)
					p = np115
				} else {
					var x117 int64
					x117, p, err = odjsonrt.ParseInt(data, p, 64)
					if err != nil {
						return p, err
					}
					v.ID = int(x117)
				}
			}
			goto next111
		}
	m109:
		{
			if strict && seen[0]&(1<<1) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 1
			if np118, ok119 := odjsonrt.ParseNull(data, p); ok119 {
				p = np118
				v.Meta = nil
			} else {
				if uint(p) >= uint(len(data)) || data[p] != '{' {
					return p, odjsonrt.ErrType(data, p, "map[string]string")
				}
				p++
				m120 := v.Meta
				if m120 == nil {
					m120 = make(map[string]string)
				}
				var seen123 map[string]struct{}
				if strict && len(m120) > 0 {
					seen123 = make(map[string]struct{})
				}
				p = odjsonrt.SkipSpace(data, p)
				if uint(p) < uint(len(data)) && data[p] == '}' {
					p++
				} else {
					for {
						var k121 []byte
						p = odjsonrt.SkipSpace(data, p)
						kp124 := p
						k121, p, err = odjsonrt.ParseKeyV2(data, p, strict)
						if err != nil {
							return p, err
						}
						if strict && seen123 != nil {
							if _, dup := seen123[string(k121)]; dup {
								return p, odjsonrt.ErrDuplicateName(data, kp124, k121)
							}
							seen123[string(k121)] = struct{}{}
						}
						var mv122 string
						p = odjsonrt.SkipSpace(data, p)
						if np125, ok126 := odjsonrt.ParseNull(data, p); ok126 {
							p = np125
							mv122 = ""
						} else {
							var x127 string
							x127, p, err = odjsonrt.ParseStringV2(data, p, sc, strict)
							if err != nil {
								return p, err
							}
							mv122 = x127
						}
						n128 := len(m120)
						m120[sc.Make(k121)] = mv122
						if strict && seen123 == nil && len(m120) == n128 {
							return p, odjsonrt.ErrDuplicateName(data, kp124, k121)
						}
						p = odjsonrt.SkipSpace(data, p)
						if uint(p) >= uint(len(data)) {
							return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
						}
						if data[p] == ',' {
							p++
							continue
						}
						if data[p] == '}' {
							p++
							break
						}
						return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
					}
				}
				v.Meta = m120
			}
			goto next111
		}
	m110:
		{
			if strict && seen[0]&(1<<2) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 2
			if np129, ok130 := odjsonrt.ParseNull(data, p); ok130 {
				p = np129
				v.On = false
			} else {
				if uint(p+4) <= uint(len(data)) && string(data[p:p+4]) == "true" {
					v.On = true
					p += 4
				} else if uint(p+5) <= uint(len(data)) && string(data[p:p+5]) == "false" {
					v.On = false
					p += 5
				} else {
					var x131 bool
					x131, p, err = odjsonrt.ParseBool(data, p)
					if err != nil {
						return p, err
					}
					v.On = x131
				}
			}
		}
	next111:
		{
			p = odjsonrt.SkipSpace(data, p)
			if uint(p) >= uint(len(data)) {
				return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
			}
			switch data[p] {
			case ',':
				p++
			case '}':
				odjsonrt.EndUnknownNames(sc, unknown, umark)
				return p + 1, nil
			default:
				return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
			}
		}
	}
}

// odjsonParseFrom decodes the next value in dec into v,
// driving the decoder token by token so the document is
// parsed once rather than twice.
func (v *nested) odjsonParseFrom(dec *jsontext.Decoder, sc *odjsonrt.StringCache) error {
	var err error
	_ = err
	if odjsonrt.WholeValue(dec) {
		var val jsontext.Value
		if val, err = dec.ReadValue(); err != nil {
			return err
		}
		_, err = v.odjsonParseV2(val, 0, sc, false)
		return err
	}
	switch odjsonrt.NextKind(dec) {
	case 'n':
		if _, err = dec.ReadToken(); err != nil {
			return err
		}
		*v = nested{}
		return nil
	case '{':
	default:
		return odjsonrt.ErrKindFrom(dec, "nested")
	}
	if _, err = dec.ReadToken(); err != nil {
		return err
	}
	for odjsonrt.NextKind(dec) != '}' {
		var key jsontext.Value
		key, err = dec.ReadValue()
		if err != nil {
			return err
		}
		idx := -1
		switch string(key) {
		case "\"id\"":
			idx = 0
		case "\"meta\"":
			idx = 1
		case "\"on\"":
			idx = 2
		}
		if idx < 0 && bytes.IndexByte(key, '\\') >= 0 {
			if name, ok := odjsonrt.UnquoteName(key); ok {
				switch string(name) {
				case "id":
					idx = 0
				case "meta":
					idx = 1
				case "on":
					idx = 2
				}
			}
		}
		switch idx {
		case 0:
			var val132 jsontext.Value
			val132, err = dec.ReadValue()
			if err != nil {
				return err
			}
			if val132[0] == 'n' {
				v.ID = 0
			} else {
				var x133 int64
				x133, _, err = odjsonrt.ParseInt(val132, 0, 64)
				if err != nil {
					return err
				}
				v.ID = int(x133)
			}
		case 1:
			var val134 jsontext.Value
			val134, err = dec.ReadValue()
			if err != nil {
				return err
			}
			vp135 := 0
			if np136, ok137 := odjsonrt.ParseNull(val134, vp135); ok137 {
				vp135 = np136
				v.Meta = nil
			} else {
				if uint(vp135) >= uint(len(val134)) || val134[vp135] != '{' {
					return odjsonrt.ErrType(val134, vp135, "map[string]string")
				}
				vp135++
				m138 := v.Meta
				if m138 == nil {
					m138 = make(map[string]string)
				}
				vp135 = odjsonrt.SkipSpace(val134, vp135)
				if uint(vp135) < uint(len(val134)) && val134[vp135] == '}' {
					vp135++
				} else {
					for {
						var k139 []byte
						vp135 = odjsonrt.SkipSpace(val134, vp135)
						k139, _, vp135, err = odjsonrt.ParseKey(val134, vp135)
						if err != nil {
							return err
						}
						var mv140 string
						vp135 = odjsonrt.SkipSpace(val134, vp135)
						if np142, ok143 := odjsonrt.ParseNull(val134, vp135); ok143 {
							vp135 = np142
							mv140 = ""
						} else {
							var x144 string
							x144, vp135, err = odjsonrt.ParseStringWith(val134, vp135, sc)
							if err != nil {
								return err
							}
							mv140 = x144
						}
						m138[sc.Make(k139)] = mv140
						vp135 = odjsonrt.SkipSpace(val134, vp135)
						if uint(vp135) >= uint(len(val134)) {
							return odjsonrt.ErrSyntax(val134, vp135, "unexpected end of JSON input")
						}
						if val134[vp135] == ',' {
							vp135++
							continue
						}
						if val134[vp135] == '}' {
							vp135++
							break
						}
						return odjsonrt.ErrSyntax(val134, vp135, "after object key:value pair")
					}
				}
				v.Meta = m138
			}
			_ = vp135
		case 2:
			var val145 jsontext.Value
			val145, err = dec.ReadValue()
			if err != nil {
				return err
			}
			if val145[0] == 'n' {
				v.On = false
			} else {
				var x146 bool
				x146, _, err = odjsonrt.ParseBool(val145, 0)
				if err != nil {
					return err
				}
				v.On = x146
			}
		default:
			if _, err = dec.ReadValue(); err != nil {
				return err
			}
		}
	}
	_, err = dec.ReadToken()
	return err
}

// odjsonSizenested sizes the buffer the encoders allocate.
var odjsonSizenested odjsonrt.SizeHint

// MarshalJSON implements encoding/json.Marshaler.
func (v nested) MarshalJSON() ([]byte, error) {
	buf, err := v.odjsonAppend(odjsonSizenested.New(), odjsonrt.ModeHTML)
	if err != nil {
		return nil, err
	}
	odjsonSizenested.Record(buf)
	return buf, nil
}

// UnmarshalJSON implements encoding/json.Unmarshaler.
func (v *nested) UnmarshalJSON(data []byte) error {
	// The cache plays the part of encoding/json/v2's string cache: a
	// value that recurs in the document is allocated once.
	sc := odjsonrt.GetStringCache()
	p, err := v.odjsonParse(data, odjsonrt.SkipSpace(data, 0), sc)
	odjsonrt.PutStringCache(sc)
	if err != nil {
		return err
	}
	return odjsonrt.EndOfDocument(data, p)
}

// MarshalJSONTo implements encoding/json/v2.MarshalerTo.
func (v nested) MarshalJSONTo(enc *jsontext.Encoder) error {
	// Under a plain json.Marshal, from encoding/json/v2 or encoding/json,
	// the value is appended straight into the encoder's buffer at any
	// depth; see odjsonrt.BeginDirectEncodeMode for what qualifies and
	// for the mode, which does that call's escaping itself since nothing
	// downstream looks at the bytes.
	if buf, m, ok := odjsonrt.BeginDirectEncodeMode(enc); ok {
		n := len(buf)
		buf, err := v.odjsonAppend(buf, m)
		if err != nil {
			return err
		}
		odjsonSizenested.Record(buf[n:])
		odjsonrt.EndDirectEncode(enc, buf)
		return nil
	}
	// Otherwise WriteValue copies what it is given, so the scratch buffer
	// can go straight back to the pool. ModeStream leaves the HTML escaping
	// and the UTF-8 validation to the encoder, which performs both while
	// reformatting the value either way.
	buf := odjsonrt.GetBuffer()
	var err error
	if buf.B, err = v.odjsonAppend(buf.B, odjsonrt.ModeStream); err == nil {
		odjsonSizenested.Record(buf.B)
		err = enc.WriteValue(buf.B)
	}
	odjsonrt.PutBuffer(buf)
	return err
}

// UnmarshalJSONFrom implements encoding/json/v2.UnmarshalerFrom.
func (v *nested) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	// The cache plays the part of json/v2's own string cache: a value
	// that recurs in the document is allocated once.
	sc := odjsonrt.GetStringCache()
	var err error
	// Under a plain json.Unmarshal the value is parsed straight out of
	// the decoder's buffer at any depth; see odjsonrt.BeginDirectDecodeAt
	// for what qualifies. Nobody has validated those bytes, so
	// odjsonParseV2 rejects what jsontext would have.
	if data, p, ok := odjsonrt.BeginDirectDecodeAt(dec); ok {
		var end int
		if end, err = v.odjsonParseV2(data, p, sc, true); err == nil {
			odjsonrt.EndDirectDecodeAt(dec, p, end)
		}
	} else {
		err = v.odjsonParseFrom(dec, sc)
	}
	odjsonrt.PutStringCache(sc)
	return err
}

// marshalNested returns the JSON encoding of v, reaching the generated
// encoder without going through encoding/json.
func marshalNested(v *nested) ([]byte, error) {
	// The encoding is built in a pooled buffer and copied out once,
	// rather than written into a buffer allocated at the right size:
	// a fresh allocation is handed out zeroed, so writing into it
	// walks cold memory twice, while the copy out of a warm pooled
	// buffer allocates without zeroing and moves the bytes once.
	buf := odjsonrt.GetBuffer()
	var err error
	buf.B, err = v.odjsonAppend(buf.B, odjsonrt.ModeV2HTML)
	if err != nil {
		odjsonrt.PutBuffer(buf)
		return nil, err
	}
	out := bytes.Clone(buf.B)
	odjsonrt.PutBuffer(buf)
	return out, nil
}

// appendNested appends the JSON encoding of v to dst and returns the
// extended buffer. On failure dst is returned with nothing appended.
func appendNested(dst []byte, v *nested) ([]byte, error) {
	n := len(dst)
	dst, err := v.odjsonAppend(dst, odjsonrt.ModeV2HTML)
	if err != nil {
		return dst[:n], err
	}
	return dst, nil
}

// unmarshalNested decodes a complete JSON document into v under
// encoding/json/v2's semantics. Nobody has validated data, so the parser
// rejects what jsontext would have.
func unmarshalNested(data []byte, v *nested) error {
	// The cache plays the part of encoding/json/v2's string cache: a
	// value that recurs in the document is allocated once.
	sc := odjsonrt.GetStringCache()
	p, err := v.odjsonParseV2(data, odjsonrt.SkipSpace(data, 0), sc, true)
	odjsonrt.PutStringCache(sc)
	if err != nil {
		return err
	}
	return odjsonrt.EndOfDocument(data, p)
}
