// Code generated by odjson. DO NOT EDIT.
//
// Source: odjson

package suite

import (
	"github.com/mazrean/odjson/odjsonrt"
	"slices"
)

// odjsonAppend appends the JSON encoding of v to dst.
func (v *Raw) odjsonAppend(dst []byte) ([]byte, error) {
	var err error
	_ = err
	start := len(dst)
	dst = append(dst, ",\"x\":"...)
	dst, err = odjsonrt.AppendMarshaler(dst, v.X, true)
	if err != nil {
		return nil, err
	}
	if len(dst) == start {
		dst = append(dst, '{', '}')
	} else {
		dst[start] = '{'
		dst = append(dst, '}')
	}
	return dst, nil
}

// odjsonParse decodes the JSON object starting at p into v and
// returns the offset just past it.
func (v *Raw) odjsonParse(data []byte, p int) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		return np, nil
	}
	if p >= len(data) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "Raw")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if p < len(data) && data[p] == '}' {
		return p + 1, nil
	}
	for {
		var key []byte
		p = odjsonrt.SkipSpace(data, p)
		key, _, p, err = odjsonrt.ParseKey(data, p)
		if err != nil {
			return p, err
		}
		p = odjsonrt.SkipSpace(data, p)
		idx := -1
		switch string(key) {
		case "x":
			idx = 0
		}
		if idx < 0 {
			switch {
			case odjsonrt.EqualFold(key, "x"):
				idx = 0
			}
		}
		switch idx {
		case 0:
			p, err = odjsonrt.ParseUnmarshaler(data, p, &v.X)
			if err != nil {
				return p, err
			}
		default:
			p, err = odjsonrt.SkipValue(data, p)
			if err != nil {
				return p, err
			}
		}
		p = odjsonrt.SkipSpace(data, p)
		if p >= len(data) {
			return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
		}
		switch data[p] {
		case ',':
			p++
		case '}':
			return p + 1, nil
		default:
			return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
		}
	}
}

// AppendRaw appends the JSON encoding of v to dst.
func AppendRaw(dst []byte, v *Raw) ([]byte, error) {
	return v.odjsonAppend(dst)
}

// odjsonSizeRaw sizes the buffer MarshalRaw allocates.
var odjsonSizeRaw odjsonrt.SizeHint

// MarshalRaw returns the JSON encoding of v.
func MarshalRaw(v *Raw) ([]byte, error) {
	buf, err := v.odjsonAppend(odjsonSizeRaw.New())
	if err != nil {
		return nil, err
	}
	odjsonSizeRaw.Record(buf)
	return buf, nil
}

// UnmarshalRaw decodes the JSON document data into v.
func UnmarshalRaw(data []byte, v *Raw) error {
	p, err := v.odjsonParse(data, odjsonrt.SkipSpace(data, 0))
	if err != nil {
		return err
	}
	return odjsonrt.EndOfDocument(data, p)
}

// odjsonAppend appends the JSON encoding of v to dst.
func (v *Value) odjsonAppend(dst []byte) ([]byte, error) {
	var err error
	_ = err
	start := len(dst)
	dst = append(dst, ",\"x\":"...)
	if v.X == nil {
		dst = append(dst, 'n', 'u', 'l', 'l')
	} else {
		dst, err = odjsonrt.AppendAny(dst, v.X, true)
		if err != nil {
			return nil, err
		}
	}
	if len(dst) == start {
		dst = append(dst, '{', '}')
	} else {
		dst[start] = '{'
		dst = append(dst, '}')
	}
	return dst, nil
}

// odjsonParse decodes the JSON object starting at p into v and
// returns the offset just past it.
func (v *Value) odjsonParse(data []byte, p int) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		return np, nil
	}
	if p >= len(data) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "Value")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if p < len(data) && data[p] == '}' {
		return p + 1, nil
	}
	for {
		var key []byte
		p = odjsonrt.SkipSpace(data, p)
		key, _, p, err = odjsonrt.ParseKey(data, p)
		if err != nil {
			return p, err
		}
		p = odjsonrt.SkipSpace(data, p)
		idx := -1
		switch string(key) {
		case "x":
			idx = 0
		}
		if idx < 0 {
			switch {
			case odjsonrt.EqualFold(key, "x"):
				idx = 0
			}
		}
		switch idx {
		case 0:
			p = odjsonrt.SkipSpace(data, p)
			if np1, ok2 := odjsonrt.ParseNull(data, p); ok2 {
				p = np1
				v.X = nil
			} else {
				var a3 any
				a3, p, err = odjsonrt.ParseAny(data, p)
				if err != nil {
					return p, err
				}
				v.X = a3
			}
		default:
			p, err = odjsonrt.SkipValue(data, p)
			if err != nil {
				return p, err
			}
		}
		p = odjsonrt.SkipSpace(data, p)
		if p >= len(data) {
			return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
		}
		switch data[p] {
		case ',':
			p++
		case '}':
			return p + 1, nil
		default:
			return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
		}
	}
}

// AppendValue appends the JSON encoding of v to dst.
func AppendValue(dst []byte, v *Value) ([]byte, error) {
	return v.odjsonAppend(dst)
}

// odjsonSizeValue sizes the buffer MarshalValue allocates.
var odjsonSizeValue odjsonrt.SizeHint

// MarshalValue returns the JSON encoding of v.
func MarshalValue(v *Value) ([]byte, error) {
	buf, err := v.odjsonAppend(odjsonSizeValue.New())
	if err != nil {
		return nil, err
	}
	odjsonSizeValue.Record(buf)
	return buf, nil
}

// UnmarshalValue decodes the JSON document data into v.
func UnmarshalValue(data []byte, v *Value) error {
	p, err := v.odjsonParse(data, odjsonrt.SkipSpace(data, 0))
	if err != nil {
		return err
	}
	return odjsonrt.EndOfDocument(data, p)
}

// odjsonAppend appends the JSON encoding of v to dst.
func (v *Typed) odjsonAppend(dst []byte) ([]byte, error) {
	var err error
	_ = err
	start := len(dst)
	dst = append(dst, ",\"x\":"...)
	dst, err = v.X.odjsonAppend(dst)
	if err != nil {
		return nil, err
	}
	if len(dst) == start {
		dst = append(dst, '{', '}')
	} else {
		dst[start] = '{'
		dst = append(dst, '}')
	}
	return dst, nil
}

// odjsonParse decodes the JSON object starting at p into v and
// returns the offset just past it.
func (v *Typed) odjsonParse(data []byte, p int) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		return np, nil
	}
	if p >= len(data) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "Typed")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if p < len(data) && data[p] == '}' {
		return p + 1, nil
	}
	for {
		var key []byte
		p = odjsonrt.SkipSpace(data, p)
		key, _, p, err = odjsonrt.ParseKey(data, p)
		if err != nil {
			return p, err
		}
		p = odjsonrt.SkipSpace(data, p)
		idx := -1
		switch string(key) {
		case "x":
			idx = 0
		}
		if idx < 0 {
			switch {
			case odjsonrt.EqualFold(key, "x"):
				idx = 0
			}
		}
		switch idx {
		case 0:
			p = odjsonrt.SkipSpace(data, p)
			if np4, ok5 := odjsonrt.ParseNull(data, p); ok5 {
				p = np4
			} else {
				p, err = v.X.odjsonParse(data, p)
				if err != nil {
					return p, err
				}
			}
		default:
			p, err = odjsonrt.SkipValue(data, p)
			if err != nil {
				return p, err
			}
		}
		p = odjsonrt.SkipSpace(data, p)
		if p >= len(data) {
			return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
		}
		switch data[p] {
		case ',':
			p++
		case '}':
			return p + 1, nil
		default:
			return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
		}
	}
}

// AppendTyped appends the JSON encoding of v to dst.
func AppendTyped(dst []byte, v *Typed) ([]byte, error) {
	return v.odjsonAppend(dst)
}

// odjsonSizeTyped sizes the buffer MarshalTyped allocates.
var odjsonSizeTyped odjsonrt.SizeHint

// MarshalTyped returns the JSON encoding of v.
func MarshalTyped(v *Typed) ([]byte, error) {
	buf, err := v.odjsonAppend(odjsonSizeTyped.New())
	if err != nil {
		return nil, err
	}
	odjsonSizeTyped.Record(buf)
	return buf, nil
}

// UnmarshalTyped decodes the JSON document data into v.
func UnmarshalTyped(data []byte, v *Typed) error {
	p, err := v.odjsonParse(data, odjsonrt.SkipSpace(data, 0))
	if err != nil {
		return err
	}
	return odjsonrt.EndOfDocument(data, p)
}

// odjsonAppend appends the JSON encoding of v to dst.
func (v *Inner) odjsonAppend(dst []byte) ([]byte, error) {
	var err error
	_ = err
	start := len(dst)
	dst = append(dst, ",\"s\":"...)
	dst = odjsonrt.AppendString(dst, string(v.S), true)
	dst = append(dst, ",\"n\":"...)
	dst, err = odjsonrt.AppendFloat(dst, float64(v.N), 64)
	if err != nil {
		return nil, err
	}
	dst = append(dst, ",\"b\":"...)
	dst = odjsonrt.AppendBool(dst, bool(v.B))
	dst = append(dst, ",\"l\":"...)
	if v.L == nil {
		dst = append(dst, 'n', 'u', 'l', 'l')
	} else {
		dst = append(dst, '[')
		for i6 := range v.L {
			if i6 > 0 {
				dst = append(dst, ',')
			}
			dst = odjsonrt.AppendInt(dst, int64(v.L[i6]))
		}
		dst = append(dst, ']')
	}
	dst = append(dst, ",\"m\":"...)
	if v.M == nil {
		dst = append(dst, 'n', 'u', 'l', 'l')
	} else {
		keys7 := make([]string, 0, len(v.M))
		for k8 := range v.M {
			keys7 = append(keys7, string(k8))
		}
		slices.Sort(keys7)
		dst = append(dst, '{')
		for i9, k8 := range keys7 {
			if i9 > 0 {
				dst = append(dst, ',')
			}
			dst = odjsonrt.AppendString(dst, k8, true)
			dst = append(dst, ':')
			mv10 := v.M[k8]
			dst = odjsonrt.AppendString(dst, string(mv10), true)
		}
		dst = append(dst, '}')
	}
	dst = append(dst, ",\"a\":"...)
	if v.A == nil {
		dst = append(dst, 'n', 'u', 'l', 'l')
	} else {
		dst, err = odjsonrt.AppendAny(dst, v.A, true)
		if err != nil {
			return nil, err
		}
	}
	if len(dst) == start {
		dst = append(dst, '{', '}')
	} else {
		dst[start] = '{'
		dst = append(dst, '}')
	}
	return dst, nil
}

// odjsonParse decodes the JSON object starting at p into v and
// returns the offset just past it.
func (v *Inner) odjsonParse(data []byte, p int) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		return np, nil
	}
	if p >= len(data) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "Inner")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if p < len(data) && data[p] == '}' {
		return p + 1, nil
	}
	for {
		var key []byte
		p = odjsonrt.SkipSpace(data, p)
		key, _, p, err = odjsonrt.ParseKey(data, p)
		if err != nil {
			return p, err
		}
		p = odjsonrt.SkipSpace(data, p)
		idx := -1
		switch string(key) {
		case "s":
			idx = 0
		case "n":
			idx = 1
		case "b":
			idx = 2
		case "l":
			idx = 3
		case "m":
			idx = 4
		case "a":
			idx = 5
		}
		if idx < 0 {
			switch {
			case odjsonrt.EqualFold(key, "s"):
				idx = 0
			case odjsonrt.EqualFold(key, "n"):
				idx = 1
			case odjsonrt.EqualFold(key, "b"):
				idx = 2
			case odjsonrt.EqualFold(key, "l"):
				idx = 3
			case odjsonrt.EqualFold(key, "m"):
				idx = 4
			case odjsonrt.EqualFold(key, "a"):
				idx = 5
			}
		}
		switch idx {
		case 0:
			p = odjsonrt.SkipSpace(data, p)
			if np11, ok12 := odjsonrt.ParseNull(data, p); ok12 {
				p = np11
			} else {
				var x13 string
				x13, p, err = odjsonrt.ParseString(data, p)
				if err != nil {
					return p, err
				}
				v.S = x13
			}
		case 1:
			p = odjsonrt.SkipSpace(data, p)
			if np14, ok15 := odjsonrt.ParseNull(data, p); ok15 {
				p = np14
			} else {
				var x16 float64
				x16, p, err = odjsonrt.ParseFloat(data, p, 64)
				if err != nil {
					return p, err
				}
				v.N = x16
			}
		case 2:
			p = odjsonrt.SkipSpace(data, p)
			if np17, ok18 := odjsonrt.ParseNull(data, p); ok18 {
				p = np17
			} else {
				var x19 bool
				x19, p, err = odjsonrt.ParseBool(data, p)
				if err != nil {
					return p, err
				}
				v.B = x19
			}
		case 3:
			p = odjsonrt.SkipSpace(data, p)
			if np20, ok21 := odjsonrt.ParseNull(data, p); ok21 {
				p = np20
				v.L = nil
			} else {
				if p >= len(data) || data[p] != '[' {
					return p, odjsonrt.ErrType(data, p, "[]int")
				}
				p++
				s22 := v.L[:0]
				p = odjsonrt.SkipSpace(data, p)
				if p < len(data) && data[p] == ']' {
					p++
				} else {
					for {
						var e23 int
						p = odjsonrt.SkipSpace(data, p)
						if np24, ok25 := odjsonrt.ParseNull(data, p); ok25 {
							p = np24
						} else {
							var x26 int64
							x26, p, err = odjsonrt.ParseInt(data, p, 64)
							if err != nil {
								return p, err
							}
							e23 = int(x26)
						}
						s22 = append(s22, e23)
						p = odjsonrt.SkipSpace(data, p)
						if p >= len(data) {
							return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
						}
						if data[p] == ',' {
							p++
							continue
						}
						if data[p] == ']' {
							p++
							break
						}
						return p, odjsonrt.ErrSyntax(data, p, "after array element")
					}
				}
				if s22 == nil {
					s22 = []int{}
				}
				v.L = s22
			}
		case 4:
			p = odjsonrt.SkipSpace(data, p)
			if np27, ok28 := odjsonrt.ParseNull(data, p); ok28 {
				p = np27
				v.M = nil
			} else {
				if p >= len(data) || data[p] != '{' {
					return p, odjsonrt.ErrType(data, p, "map[string]string")
				}
				p++
				m29 := v.M
				if m29 == nil {
					m29 = make(map[string]string)
				}
				p = odjsonrt.SkipSpace(data, p)
				if p < len(data) && data[p] == '}' {
					p++
				} else {
					for {
						var k30 []byte
						p = odjsonrt.SkipSpace(data, p)
						k30, _, p, err = odjsonrt.ParseKey(data, p)
						if err != nil {
							return p, err
						}
						var mv31 string
						p = odjsonrt.SkipSpace(data, p)
						if np32, ok33 := odjsonrt.ParseNull(data, p); ok33 {
							p = np32
						} else {
							var x34 string
							x34, p, err = odjsonrt.ParseString(data, p)
							if err != nil {
								return p, err
							}
							mv31 = x34
						}
						m29[string(k30)] = mv31
						p = odjsonrt.SkipSpace(data, p)
						if p >= len(data) {
							return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
						}
						if data[p] == ',' {
							p++
							continue
						}
						if data[p] == '}' {
							p++
							break
						}
						return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
					}
				}
				v.M = m29
			}
		case 5:
			p = odjsonrt.SkipSpace(data, p)
			if np35, ok36 := odjsonrt.ParseNull(data, p); ok36 {
				p = np35
				v.A = nil
			} else {
				var a37 any
				a37, p, err = odjsonrt.ParseAny(data, p)
				if err != nil {
					return p, err
				}
				v.A = a37
			}
		default:
			p, err = odjsonrt.SkipValue(data, p)
			if err != nil {
				return p, err
			}
		}
		p = odjsonrt.SkipSpace(data, p)
		if p >= len(data) {
			return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
		}
		switch data[p] {
		case ',':
			p++
		case '}':
			return p + 1, nil
		default:
			return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
		}
	}
}

// AppendInner appends the JSON encoding of v to dst.
func AppendInner(dst []byte, v *Inner) ([]byte, error) {
	return v.odjsonAppend(dst)
}

// odjsonSizeInner sizes the buffer MarshalInner allocates.
var odjsonSizeInner odjsonrt.SizeHint

// MarshalInner returns the JSON encoding of v.
func MarshalInner(v *Inner) ([]byte, error) {
	buf, err := v.odjsonAppend(odjsonSizeInner.New())
	if err != nil {
		return nil, err
	}
	odjsonSizeInner.Record(buf)
	return buf, nil
}

// UnmarshalInner decodes the JSON document data into v.
func UnmarshalInner(data []byte, v *Inner) error {
	p, err := v.odjsonParse(data, odjsonrt.SkipSpace(data, 0))
	if err != nil {
		return err
	}
	return odjsonrt.EndOfDocument(data, p)
}
