// Code generated by odjson. DO NOT EDIT.
//
// Source: odjson

package suite

import (
	"github.com/mazrean/odjson/odjsonrt"
	"slices"
)

// odjsonAppend appends the JSON encoding of v to dst.
func (v *Raw) odjsonAppend(dst []byte, m odjsonrt.StringMode) ([]byte, error) {
	var err error
	_ = err
	start := len(dst)
	dst = append(dst, ",\"x\":"...)
	dst, err = odjsonrt.AppendMarshaler(dst, v.X, m.EscapeHTML())
	if err != nil {
		return nil, err
	}
	if len(dst) == start {
		dst = append(dst, '{', '}')
	} else {
		dst[start] = '{'
		dst = append(dst, '}')
	}
	return dst, nil
}

// odjsonParse decodes the JSON object starting at p into v and
// returns the offset just past it.
func (v *Raw) odjsonParse(data []byte, p int) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		return np, nil
	}
	if p >= len(data) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "Raw")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if p < len(data) && data[p] == '}' {
		return p + 1, nil
	}
	for {
		var key []byte
		p = odjsonrt.SkipSpace(data, p)
		key, _, p, err = odjsonrt.ParseKey(data, p)
		if err != nil {
			return p, err
		}
		idx := -1
		switch string(key) {
		case "x":
			idx = 0
		}
		if idx < 0 {
			fold := !odjsonrt.ASCII(key)
			switch {
			case (len(key) == 1 || fold) && odjsonrt.EqualFold(key, "x"):
				idx = 0
			}
		}
		switch idx {
		case 0:
			p, err = odjsonrt.ParseUnmarshaler(data, p, &v.X)
			if err != nil {
				return p, err
			}
		default:
			p = odjsonrt.SkipSpace(data, p)
			p, err = odjsonrt.SkipValue(data, p)
			if err != nil {
				return p, err
			}
		}
		p = odjsonrt.SkipSpace(data, p)
		if p >= len(data) {
			return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
		}
		switch data[p] {
		case ',':
			p++
		case '}':
			return p + 1, nil
		default:
			return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
		}
	}
}

// AppendRaw appends the JSON encoding of v to dst.
func AppendRaw(dst []byte, v *Raw) ([]byte, error) {
	return v.odjsonAppend(dst, odjsonrt.ModeHTML)
}

// odjsonSizeRaw sizes the buffer MarshalRaw allocates.
var odjsonSizeRaw odjsonrt.SizeHint

// MarshalRaw returns the JSON encoding of v.
func MarshalRaw(v *Raw) ([]byte, error) {
	buf, err := v.odjsonAppend(odjsonSizeRaw.New(), odjsonrt.ModeHTML)
	if err != nil {
		return nil, err
	}
	odjsonSizeRaw.Record(buf)
	return buf, nil
}

// UnmarshalRaw decodes the JSON document data into v.
func UnmarshalRaw(data []byte, v *Raw) error {
	p, err := v.odjsonParse(data, odjsonrt.SkipSpace(data, 0))
	if err != nil {
		return err
	}
	return odjsonrt.EndOfDocument(data, p)
}

// odjsonAppend appends the JSON encoding of v to dst.
func (v *Value) odjsonAppend(dst []byte, m odjsonrt.StringMode) ([]byte, error) {
	var err error
	_ = err
	start := len(dst)
	dst = append(dst, ",\"x\":"...)
	if v.X == nil {
		dst = append(dst, 'n', 'u', 'l', 'l')
	} else {
		dst, err = odjsonrt.AppendAnyMode(dst, v.X, m)
		if err != nil {
			return nil, err
		}
	}
	if len(dst) == start {
		dst = append(dst, '{', '}')
	} else {
		dst[start] = '{'
		dst = append(dst, '}')
	}
	return dst, nil
}

// odjsonParse decodes the JSON object starting at p into v and
// returns the offset just past it.
func (v *Value) odjsonParse(data []byte, p int) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		return np, nil
	}
	if p >= len(data) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "Value")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if p < len(data) && data[p] == '}' {
		return p + 1, nil
	}
	for {
		var key []byte
		p = odjsonrt.SkipSpace(data, p)
		key, _, p, err = odjsonrt.ParseKey(data, p)
		if err != nil {
			return p, err
		}
		idx := -1
		switch string(key) {
		case "x":
			idx = 0
		}
		if idx < 0 {
			fold := !odjsonrt.ASCII(key)
			switch {
			case (len(key) == 1 || fold) && odjsonrt.EqualFold(key, "x"):
				idx = 0
			}
		}
		switch idx {
		case 0:
			p = odjsonrt.SkipSpace(data, p)
			if np1, ok2 := odjsonrt.ParseNull(data, p); ok2 {
				p = np1
				v.X = nil
			} else {
				var a3 any
				a3, p, err = odjsonrt.ParseAny(data, p)
				if err != nil {
					return p, err
				}
				v.X = a3
			}
		default:
			p = odjsonrt.SkipSpace(data, p)
			p, err = odjsonrt.SkipValue(data, p)
			if err != nil {
				return p, err
			}
		}
		p = odjsonrt.SkipSpace(data, p)
		if p >= len(data) {
			return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
		}
		switch data[p] {
		case ',':
			p++
		case '}':
			return p + 1, nil
		default:
			return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
		}
	}
}

// AppendValue appends the JSON encoding of v to dst.
func AppendValue(dst []byte, v *Value) ([]byte, error) {
	return v.odjsonAppend(dst, odjsonrt.ModeHTML)
}

// odjsonSizeValue sizes the buffer MarshalValue allocates.
var odjsonSizeValue odjsonrt.SizeHint

// MarshalValue returns the JSON encoding of v.
func MarshalValue(v *Value) ([]byte, error) {
	buf, err := v.odjsonAppend(odjsonSizeValue.New(), odjsonrt.ModeHTML)
	if err != nil {
		return nil, err
	}
	odjsonSizeValue.Record(buf)
	return buf, nil
}

// UnmarshalValue decodes the JSON document data into v.
func UnmarshalValue(data []byte, v *Value) error {
	p, err := v.odjsonParse(data, odjsonrt.SkipSpace(data, 0))
	if err != nil {
		return err
	}
	return odjsonrt.EndOfDocument(data, p)
}

// odjsonAppend appends the JSON encoding of v to dst.
func (v *Typed) odjsonAppend(dst []byte, m odjsonrt.StringMode) ([]byte, error) {
	var err error
	_ = err
	start := len(dst)
	dst = append(dst, ",\"x\":"...)
	dst, err = v.X.odjsonAppend(dst, m)
	if err != nil {
		return nil, err
	}
	if len(dst) == start {
		dst = append(dst, '{', '}')
	} else {
		dst[start] = '{'
		dst = append(dst, '}')
	}
	return dst, nil
}

// odjsonParse decodes the JSON object starting at p into v and
// returns the offset just past it.
func (v *Typed) odjsonParse(data []byte, p int) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		return np, nil
	}
	if p >= len(data) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "Typed")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if p < len(data) && data[p] == '}' {
		return p + 1, nil
	}
	for {
		var key []byte
		p = odjsonrt.SkipSpace(data, p)
		key, _, p, err = odjsonrt.ParseKey(data, p)
		if err != nil {
			return p, err
		}
		idx := -1
		switch string(key) {
		case "x":
			idx = 0
		}
		if idx < 0 {
			fold := !odjsonrt.ASCII(key)
			switch {
			case (len(key) == 1 || fold) && odjsonrt.EqualFold(key, "x"):
				idx = 0
			}
		}
		switch idx {
		case 0:
			p, err = v.X.odjsonParse(data, p)
			if err != nil {
				return p, err
			}
		default:
			p = odjsonrt.SkipSpace(data, p)
			p, err = odjsonrt.SkipValue(data, p)
			if err != nil {
				return p, err
			}
		}
		p = odjsonrt.SkipSpace(data, p)
		if p >= len(data) {
			return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
		}
		switch data[p] {
		case ',':
			p++
		case '}':
			return p + 1, nil
		default:
			return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
		}
	}
}

// AppendTyped appends the JSON encoding of v to dst.
func AppendTyped(dst []byte, v *Typed) ([]byte, error) {
	return v.odjsonAppend(dst, odjsonrt.ModeHTML)
}

// odjsonSizeTyped sizes the buffer MarshalTyped allocates.
var odjsonSizeTyped odjsonrt.SizeHint

// MarshalTyped returns the JSON encoding of v.
func MarshalTyped(v *Typed) ([]byte, error) {
	buf, err := v.odjsonAppend(odjsonSizeTyped.New(), odjsonrt.ModeHTML)
	if err != nil {
		return nil, err
	}
	odjsonSizeTyped.Record(buf)
	return buf, nil
}

// UnmarshalTyped decodes the JSON document data into v.
func UnmarshalTyped(data []byte, v *Typed) error {
	p, err := v.odjsonParse(data, odjsonrt.SkipSpace(data, 0))
	if err != nil {
		return err
	}
	return odjsonrt.EndOfDocument(data, p)
}

// odjsonAppend appends the JSON encoding of v to dst.
func (v *Inner) odjsonAppend(dst []byte, m odjsonrt.StringMode) ([]byte, error) {
	var err error
	_ = err
	start := len(dst)
	dst = append(dst, ",\"s\":"...)
	dst = odjsonrt.AppendStringMode(dst, string(v.S), m)
	dst = append(dst, ",\"n\":"...)
	dst, err = odjsonrt.AppendFloat(dst, float64(v.N), 64)
	if err != nil {
		return nil, err
	}
	dst = append(dst, ",\"b\":"...)
	dst = odjsonrt.AppendBool(dst, bool(v.B))
	dst = append(dst, ",\"l\":"...)
	if v.L == nil {
		dst = odjsonrt.AppendNilSlice(dst, m)
	} else {
		dst = append(dst, '[')
		for i4 := range v.L {
			if i4 > 0 {
				dst = append(dst, ',')
			}
			dst = odjsonrt.AppendInt(dst, int64(v.L[i4]))
		}
		dst = append(dst, ']')
	}
	dst = append(dst, ",\"m\":"...)
	if v.M == nil {
		dst = odjsonrt.AppendNilMap(dst, m)
	} else {
		keys5 := make([]string, 0, len(v.M))
		for k6 := range v.M {
			keys5 = append(keys5, string(k6))
		}
		slices.Sort(keys5)
		dst = append(dst, '{')
		for i7, k6 := range keys5 {
			if i7 > 0 {
				dst = append(dst, ',')
			}
			dst = odjsonrt.AppendStringMode(dst, k6, m)
			dst = append(dst, ':')
			mv8 := v.M[k6]
			dst = odjsonrt.AppendStringMode(dst, string(mv8), m)
		}
		dst = append(dst, '}')
	}
	dst = append(dst, ",\"a\":"...)
	if v.A == nil {
		dst = append(dst, 'n', 'u', 'l', 'l')
	} else {
		dst, err = odjsonrt.AppendAnyMode(dst, v.A, m)
		if err != nil {
			return nil, err
		}
	}
	dst = append(dst, ",\"p\":"...)
	if v.P == nil {
		dst = append(dst, 'n', 'u', 'l', 'l')
	} else {
		dst, err = (*v.P).odjsonAppend(dst, m)
		if err != nil {
			return nil, err
		}
	}
	if len(dst) == start {
		dst = append(dst, '{', '}')
	} else {
		dst[start] = '{'
		dst = append(dst, '}')
	}
	return dst, nil
}

// odjsonParse decodes the JSON object starting at p into v and
// returns the offset just past it.
func (v *Inner) odjsonParse(data []byte, p int) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		return np, nil
	}
	if p >= len(data) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "Inner")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if p < len(data) && data[p] == '}' {
		return p + 1, nil
	}
	for {
		var key []byte
		p = odjsonrt.SkipSpace(data, p)
		key, _, p, err = odjsonrt.ParseKey(data, p)
		if err != nil {
			return p, err
		}
		idx := -1
		switch string(key) {
		case "s":
			idx = 0
		case "n":
			idx = 1
		case "b":
			idx = 2
		case "l":
			idx = 3
		case "m":
			idx = 4
		case "a":
			idx = 5
		case "p":
			idx = 6
		}
		if idx < 0 {
			fold := !odjsonrt.ASCII(key)
			switch {
			case (len(key) == 1 || fold) && odjsonrt.EqualFold(key, "s"):
				idx = 0
			case (len(key) == 1 || fold) && odjsonrt.EqualFold(key, "n"):
				idx = 1
			case (len(key) == 1 || fold) && odjsonrt.EqualFold(key, "b"):
				idx = 2
			case (len(key) == 1 || fold) && odjsonrt.EqualFold(key, "l"):
				idx = 3
			case (len(key) == 1 || fold) && odjsonrt.EqualFold(key, "m"):
				idx = 4
			case (len(key) == 1 || fold) && odjsonrt.EqualFold(key, "a"):
				idx = 5
			case (len(key) == 1 || fold) && odjsonrt.EqualFold(key, "p"):
				idx = 6
			}
		}
		switch idx {
		case 0:
			p = odjsonrt.SkipSpace(data, p)
			if np9, ok10 := odjsonrt.ParseNull(data, p); ok10 {
				p = np9
			} else {
				var x11 string
				x11, p, err = odjsonrt.ParseString(data, p)
				if err != nil {
					return p, err
				}
				v.S = x11
			}
		case 1:
			p = odjsonrt.SkipSpace(data, p)
			if np12, ok13 := odjsonrt.ParseNull(data, p); ok13 {
				p = np12
			} else {
				var x14 float64
				x14, p, err = odjsonrt.ParseFloat(data, p, 64)
				if err != nil {
					return p, err
				}
				v.N = x14
			}
		case 2:
			p = odjsonrt.SkipSpace(data, p)
			if np15, ok16 := odjsonrt.ParseNull(data, p); ok16 {
				p = np15
			} else {
				var x17 bool
				x17, p, err = odjsonrt.ParseBool(data, p)
				if err != nil {
					return p, err
				}
				v.B = x17
			}
		case 3:
			p = odjsonrt.SkipSpace(data, p)
			if np18, ok19 := odjsonrt.ParseNull(data, p); ok19 {
				p = np18
				v.L = nil
			} else {
				if p >= len(data) || data[p] != '[' {
					return p, odjsonrt.ErrType(data, p, "[]int")
				}
				p++
				s20 := v.L[:0]
				p = odjsonrt.SkipSpace(data, p)
				if p < len(data) && data[p] == ']' {
					p++
				} else {
					if cap(s20) == 0 {
						s20 = make([]int, 0, 4)
					}
					for {
						var e21 int
						p = odjsonrt.SkipSpace(data, p)
						if np22, ok23 := odjsonrt.ParseNull(data, p); ok23 {
							p = np22
						} else {
							var x24 int64
							x24, p, err = odjsonrt.ParseInt(data, p, 64)
							if err != nil {
								return p, err
							}
							e21 = int(x24)
						}
						s20 = append(s20, e21)
						p = odjsonrt.SkipSpace(data, p)
						if p >= len(data) {
							return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
						}
						if data[p] == ',' {
							p++
							continue
						}
						if data[p] == ']' {
							p++
							break
						}
						return p, odjsonrt.ErrSyntax(data, p, "after array element")
					}
				}
				if s20 == nil {
					s20 = []int{}
				}
				v.L = s20
			}
		case 4:
			p = odjsonrt.SkipSpace(data, p)
			if np25, ok26 := odjsonrt.ParseNull(data, p); ok26 {
				p = np25
				v.M = nil
			} else {
				if p >= len(data) || data[p] != '{' {
					return p, odjsonrt.ErrType(data, p, "map[string]string")
				}
				p++
				m27 := v.M
				if m27 == nil {
					m27 = make(map[string]string)
				}
				p = odjsonrt.SkipSpace(data, p)
				if p < len(data) && data[p] == '}' {
					p++
				} else {
					for {
						var k28 []byte
						p = odjsonrt.SkipSpace(data, p)
						k28, _, p, err = odjsonrt.ParseKey(data, p)
						if err != nil {
							return p, err
						}
						var mv29 string
						p = odjsonrt.SkipSpace(data, p)
						if np30, ok31 := odjsonrt.ParseNull(data, p); ok31 {
							p = np30
						} else {
							var x32 string
							x32, p, err = odjsonrt.ParseString(data, p)
							if err != nil {
								return p, err
							}
							mv29 = x32
						}
						m27[string(k28)] = mv29
						p = odjsonrt.SkipSpace(data, p)
						if p >= len(data) {
							return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
						}
						if data[p] == ',' {
							p++
							continue
						}
						if data[p] == '}' {
							p++
							break
						}
						return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
					}
				}
				v.M = m27
			}
		case 5:
			p = odjsonrt.SkipSpace(data, p)
			if np33, ok34 := odjsonrt.ParseNull(data, p); ok34 {
				p = np33
				v.A = nil
			} else {
				var a35 any
				a35, p, err = odjsonrt.ParseAny(data, p)
				if err != nil {
					return p, err
				}
				v.A = a35
			}
		case 6:
			p = odjsonrt.SkipSpace(data, p)
			if np36, ok37 := odjsonrt.ParseNull(data, p); ok37 {
				v.P = nil
				p = np36
			} else {
				if v.P == nil {
					v.P = new(Inner)
				}
				p, err = (*v.P).odjsonParse(data, p)
				if err != nil {
					return p, err
				}
			}
		default:
			p = odjsonrt.SkipSpace(data, p)
			p, err = odjsonrt.SkipValue(data, p)
			if err != nil {
				return p, err
			}
		}
		p = odjsonrt.SkipSpace(data, p)
		if p >= len(data) {
			return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
		}
		switch data[p] {
		case ',':
			p++
		case '}':
			return p + 1, nil
		default:
			return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
		}
	}
}

// AppendInner appends the JSON encoding of v to dst.
func AppendInner(dst []byte, v *Inner) ([]byte, error) {
	return v.odjsonAppend(dst, odjsonrt.ModeHTML)
}

// odjsonSizeInner sizes the buffer MarshalInner allocates.
var odjsonSizeInner odjsonrt.SizeHint

// MarshalInner returns the JSON encoding of v.
func MarshalInner(v *Inner) ([]byte, error) {
	buf, err := v.odjsonAppend(odjsonSizeInner.New(), odjsonrt.ModeHTML)
	if err != nil {
		return nil, err
	}
	odjsonSizeInner.Record(buf)
	return buf, nil
}

// UnmarshalInner decodes the JSON document data into v.
func UnmarshalInner(data []byte, v *Inner) error {
	p, err := v.odjsonParse(data, odjsonrt.SkipSpace(data, 0))
	if err != nil {
		return err
	}
	return odjsonrt.EndOfDocument(data, p)
}
