// Code generated by odjson. DO NOT EDIT.
//
// Source: odjson

package suite

import (
	"bytes"
	"encoding/json/jsontext"
	"github.com/mazrean/odjson/odjsonrt"
	"slices"
)

// odjsonAppend appends the JSON encoding of v to dst.
func (v *Raw) odjsonAppend(dst []byte, m odjsonrt.StringMode) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, "{\"x\":"...)
	dst, err = odjsonrt.AppendMarshaler(dst, v.X, m.EscapeHTML())
	if err != nil {
		return nil, err
	}
	dst = append(dst, "}"...)
	return dst, nil
}

// odjsonParse decodes the JSON object starting at p into v and
// returns the offset just past it. Strings are interned through
// sc, which may be nil.
func (v *Raw) odjsonParse(data []byte, p int, sc *odjsonrt.StringCache) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		return np, nil
	}
	if uint(p) >= uint(len(data)) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "Raw")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if uint(p) < uint(len(data)) && data[p] == '}' {
		return p + 1, nil
	}
	for {
		var key []byte
		if uint(p) >= uint(len(data)) || data[p] <= ' ' {
			p = odjsonrt.SkipSpace(data, odjsonrt.SkipIndent(data, p))
		}
		idx := -1
		rest := data[p:]
		if len(rest) >= 3 && string(rest[:3]) == "\"x\"" {
			idx, p = 0, p+3
		}
		if idx >= 0 {
			if np := odjsonrt.AfterName(data, p); np > 0 {
				p = np
			} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
				return p, err
			}
		} else {
			key, _, p, err = odjsonrt.ParseKey(data, p)
			if err != nil {
				return p, err
			}
			switch string(key) {
			case "x":
				idx = 0
			}
		}
		switch idx {
		case 0:
			p, err = odjsonrt.ParseUnmarshaler(data, p, &v.X)
			if err != nil {
				return p, err
			}
		default:
			p = odjsonrt.SkipSpace(data, p)
			p, err = odjsonrt.SkipValue(data, p)
			if err != nil {
				return p, err
			}
		}
		p = odjsonrt.SkipSpace(data, p)
		if uint(p) >= uint(len(data)) {
			return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
		}
		switch data[p] {
		case ',':
			p++
		case '}':
			return p + 1, nil
		default:
			return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
		}
	}
}

// odjsonParseV2 is odjsonParse under encoding/json/v2's semantics, for
// input a jsontext.Decoder has already validated when strict is false,
// and for bytes nobody has looked at when it is true.
func (v *Raw) odjsonParseV2(data []byte, p int, sc *odjsonrt.StringCache, strict bool) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		*v = Raw{}
		return np, nil
	}
	if uint(p) >= uint(len(data)) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "Raw")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if uint(p) < uint(len(data)) && data[p] == '}' {
		return p + 1, nil
	}
	var seen [1]uint64
	_ = seen
	unknown, umark := odjsonrt.UnknownNames(sc)
	var ufilter uint64
	_ = ufilter
	for {
		var key []byte
		if uint(p) >= uint(len(data)) || data[p] <= ' ' {
			p = odjsonrt.SkipSpace(data, odjsonrt.SkipIndent(data, p))
		}
		kp := p
		idx := -1
		rest := data[p:]
		if len(rest) >= 3 && string(rest[:3]) == "\"x\"" {
			idx, p = 0, p+3
		}
		if idx >= 0 {
			if np := odjsonrt.AfterName(data, p); np > 0 {
				p = np
			} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
				return p, err
			}
		} else {
			key, p, err = odjsonrt.ParseKeyV2(data, p, strict)
			if err != nil {
				return p, err
			}
			switch string(key) {
			case "x":
				idx = 0
			}
		}
		switch idx {
		case 0:
			if strict && seen[0]&(1<<0) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 0
			p, err = odjsonrt.ParseUnmarshalerV2(data, p, &v.X, strict)
			if err != nil {
				return p, err
			}
		default:
			if strict {
				var dup bool
				if unknown, dup = odjsonrt.UnknownName(sc, unknown, umark, &ufilter, key); dup {
					return kp, odjsonrt.ErrDuplicateName(data, kp, key)
				}
			}
			p = odjsonrt.SkipSpace(data, p)
			p, err = odjsonrt.SkipValueV2(data, p, strict)
			if err != nil {
				return p, err
			}
		}
		p = odjsonrt.SkipSpace(data, p)
		if uint(p) >= uint(len(data)) {
			return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
		}
		switch data[p] {
		case ',':
			p++
		case '}':
			odjsonrt.EndUnknownNames(sc, unknown, umark)
			return p + 1, nil
		default:
			return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
		}
	}
}

// odjsonParseFrom decodes the next value in dec into v,
// driving the decoder token by token so the document is
// parsed once rather than twice.
func (v *Raw) odjsonParseFrom(dec *jsontext.Decoder, sc *odjsonrt.StringCache) error {
	var err error
	_ = err
	if odjsonrt.WholeValue(dec) {
		var val jsontext.Value
		if val, err = dec.ReadValue(); err != nil {
			return err
		}
		_, err = v.odjsonParseV2(val, 0, sc, false)
		return err
	}
	switch odjsonrt.NextKind(dec) {
	case 'n':
		if _, err = dec.ReadToken(); err != nil {
			return err
		}
		*v = Raw{}
		return nil
	case '{':
	default:
		return odjsonrt.ErrKindFrom(dec, "Raw")
	}
	if _, err = dec.ReadToken(); err != nil {
		return err
	}
	for odjsonrt.NextKind(dec) != '}' {
		var key jsontext.Value
		key, err = dec.ReadValue()
		if err != nil {
			return err
		}
		idx := -1
		switch string(key) {
		case "\"x\"":
			idx = 0
		}
		if idx < 0 && bytes.IndexByte(key, '\\') >= 0 {
			if name, ok := odjsonrt.UnquoteName(key); ok {
				switch string(name) {
				case "x":
					idx = 0
				}
			}
		}
		switch idx {
		case 0:
			var val1 jsontext.Value
			val1, err = dec.ReadValue()
			if err != nil {
				return err
			}
			vp2 := 0
			vp2, err = odjsonrt.ParseUnmarshaler(val1, vp2, &v.X)
			if err != nil {
				return err
			}
			_ = vp2
		default:
			if _, err = dec.ReadValue(); err != nil {
				return err
			}
		}
	}
	_, err = dec.ReadToken()
	return err
}

// odjsonSizeRaw sizes the buffer the encoders allocate.
var odjsonSizeRaw odjsonrt.SizeHint

// MarshalJSON implements encoding/json.Marshaler.
func (v Raw) MarshalJSON() ([]byte, error) {
	buf, err := v.odjsonAppend(odjsonSizeRaw.New(), odjsonrt.ModeHTML)
	if err != nil {
		return nil, err
	}
	odjsonSizeRaw.Record(buf)
	return buf, nil
}

// UnmarshalJSON implements encoding/json.Unmarshaler.
func (v *Raw) UnmarshalJSON(data []byte) error {
	// The cache plays the part of encoding/json/v2's string cache: a
	// value that recurs in the document is allocated once.
	sc := odjsonrt.GetStringCache()
	p, err := v.odjsonParse(data, odjsonrt.SkipSpace(data, 0), sc)
	odjsonrt.PutStringCache(sc)
	if err != nil {
		return err
	}
	return odjsonrt.EndOfDocument(data, p)
}

// MarshalJSONTo implements encoding/json/v2.MarshalerTo.
func (v Raw) MarshalJSONTo(enc *jsontext.Encoder) error {
	// Under a plain json.Marshal, from encoding/json/v2 or encoding/json,
	// the value is appended straight into the encoder's buffer at any
	// depth; see odjsonrt.BeginDirectEncodeMode for what qualifies and
	// for the mode, which does that call's escaping itself since nothing
	// downstream looks at the bytes.
	if buf, m, ok := odjsonrt.BeginDirectEncodeMode(enc); ok {
		n := len(buf)
		buf, err := v.odjsonAppend(buf, m)
		if err != nil {
			return err
		}
		odjsonSizeRaw.Record(buf[n:])
		odjsonrt.EndDirectEncode(enc, buf)
		return nil
	}
	// Otherwise WriteValue copies what it is given, so the scratch buffer
	// can go straight back to the pool. ModeStream leaves the HTML escaping
	// and the UTF-8 validation to the encoder, which performs both while
	// reformatting the value either way.
	buf := odjsonrt.GetBuffer()
	var err error
	if buf.B, err = v.odjsonAppend(buf.B, odjsonrt.ModeStream); err == nil {
		odjsonSizeRaw.Record(buf.B)
		err = enc.WriteValue(buf.B)
	}
	odjsonrt.PutBuffer(buf)
	return err
}

// UnmarshalJSONFrom implements encoding/json/v2.UnmarshalerFrom.
func (v *Raw) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	// The cache plays the part of json/v2's own string cache: a value
	// that recurs in the document is allocated once.
	sc := odjsonrt.GetStringCache()
	var err error
	// Under a plain json.Unmarshal the value is parsed straight out of
	// the decoder's buffer at any depth; see odjsonrt.BeginDirectDecodeAt
	// for what qualifies. Nobody has validated those bytes, so
	// odjsonParseV2 rejects what jsontext would have.
	if data, p, ok := odjsonrt.BeginDirectDecodeAt(dec); ok {
		var end int
		if end, err = v.odjsonParseV2(data, p, sc, true); err == nil {
			odjsonrt.EndDirectDecodeAt(dec, p, end)
		}
	} else {
		err = v.odjsonParseFrom(dec, sc)
	}
	odjsonrt.PutStringCache(sc)
	return err
}

// odjsonAppend appends the JSON encoding of v to dst.
func (v *Value) odjsonAppend(dst []byte, m odjsonrt.StringMode) ([]byte, error) {
	var err error
	_ = err
	if v.X == nil {
		dst = append(dst, "{\"x\":null}"...)
	} else {
		dst = append(dst, "{\"x\":"...)
		dst, err = odjsonrt.AppendAnyMode(dst, v.X, m)
		if err != nil {
			return nil, err
		}
		dst = append(dst, "}"...)
	}
	return dst, nil
}

// odjsonParse decodes the JSON object starting at p into v and
// returns the offset just past it. Strings are interned through
// sc, which may be nil.
func (v *Value) odjsonParse(data []byte, p int, sc *odjsonrt.StringCache) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		return np, nil
	}
	if uint(p) >= uint(len(data)) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "Value")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if uint(p) < uint(len(data)) && data[p] == '}' {
		return p + 1, nil
	}
	for {
		var key []byte
		if uint(p) >= uint(len(data)) || data[p] <= ' ' {
			p = odjsonrt.SkipSpace(data, odjsonrt.SkipIndent(data, p))
		}
		idx := -1
		rest := data[p:]
		if len(rest) >= 3 && string(rest[:3]) == "\"x\"" {
			idx, p = 0, p+3
		}
		if idx >= 0 {
			if np := odjsonrt.AfterName(data, p); np > 0 {
				p = np
			} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
				return p, err
			}
		} else {
			key, _, p, err = odjsonrt.ParseKey(data, p)
			if err != nil {
				return p, err
			}
			switch string(key) {
			case "x":
				idx = 0
			}
		}
		switch idx {
		case 0:
			if np3, ok4 := odjsonrt.ParseNull(data, p); ok4 {
				p = np3
				v.X = nil
			} else {
				var a5 any
				a5, p, err = odjsonrt.ParseAnyCached(data, p, sc)
				if err != nil {
					return p, err
				}
				v.X = a5
			}
		default:
			p = odjsonrt.SkipSpace(data, p)
			p, err = odjsonrt.SkipValue(data, p)
			if err != nil {
				return p, err
			}
		}
		p = odjsonrt.SkipSpace(data, p)
		if uint(p) >= uint(len(data)) {
			return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
		}
		switch data[p] {
		case ',':
			p++
		case '}':
			return p + 1, nil
		default:
			return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
		}
	}
}

// odjsonParseV2 is odjsonParse under encoding/json/v2's semantics, for
// input a jsontext.Decoder has already validated when strict is false,
// and for bytes nobody has looked at when it is true.
func (v *Value) odjsonParseV2(data []byte, p int, sc *odjsonrt.StringCache, strict bool) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		*v = Value{}
		return np, nil
	}
	if uint(p) >= uint(len(data)) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "Value")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if uint(p) < uint(len(data)) && data[p] == '}' {
		return p + 1, nil
	}
	var seen [1]uint64
	_ = seen
	unknown, umark := odjsonrt.UnknownNames(sc)
	var ufilter uint64
	_ = ufilter
	for {
		var key []byte
		if uint(p) >= uint(len(data)) || data[p] <= ' ' {
			p = odjsonrt.SkipSpace(data, odjsonrt.SkipIndent(data, p))
		}
		kp := p
		idx := -1
		rest := data[p:]
		if len(rest) >= 3 && string(rest[:3]) == "\"x\"" {
			idx, p = 0, p+3
		}
		if idx >= 0 {
			if np := odjsonrt.AfterName(data, p); np > 0 {
				p = np
			} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
				return p, err
			}
		} else {
			key, p, err = odjsonrt.ParseKeyV2(data, p, strict)
			if err != nil {
				return p, err
			}
			switch string(key) {
			case "x":
				idx = 0
			}
		}
		switch idx {
		case 0:
			if strict && seen[0]&(1<<0) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 0
			if np6, ok7 := odjsonrt.ParseNull(data, p); ok7 {
				p = np6
				v.X = nil
			} else {
				var a8 any
				a8, p, err = odjsonrt.ParseAnyV2(data, p, sc, strict)
				if err != nil {
					return p, err
				}
				v.X = a8
			}
		default:
			if strict {
				var dup bool
				if unknown, dup = odjsonrt.UnknownName(sc, unknown, umark, &ufilter, key); dup {
					return kp, odjsonrt.ErrDuplicateName(data, kp, key)
				}
			}
			p = odjsonrt.SkipSpace(data, p)
			p, err = odjsonrt.SkipValueV2(data, p, strict)
			if err != nil {
				return p, err
			}
		}
		p = odjsonrt.SkipSpace(data, p)
		if uint(p) >= uint(len(data)) {
			return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
		}
		switch data[p] {
		case ',':
			p++
		case '}':
			odjsonrt.EndUnknownNames(sc, unknown, umark)
			return p + 1, nil
		default:
			return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
		}
	}
}

// odjsonParseFrom decodes the next value in dec into v,
// driving the decoder token by token so the document is
// parsed once rather than twice.
func (v *Value) odjsonParseFrom(dec *jsontext.Decoder, sc *odjsonrt.StringCache) error {
	var err error
	_ = err
	if odjsonrt.WholeValue(dec) {
		var val jsontext.Value
		if val, err = dec.ReadValue(); err != nil {
			return err
		}
		_, err = v.odjsonParseV2(val, 0, sc, false)
		return err
	}
	switch odjsonrt.NextKind(dec) {
	case 'n':
		if _, err = dec.ReadToken(); err != nil {
			return err
		}
		*v = Value{}
		return nil
	case '{':
	default:
		return odjsonrt.ErrKindFrom(dec, "Value")
	}
	if _, err = dec.ReadToken(); err != nil {
		return err
	}
	for odjsonrt.NextKind(dec) != '}' {
		var key jsontext.Value
		key, err = dec.ReadValue()
		if err != nil {
			return err
		}
		idx := -1
		switch string(key) {
		case "\"x\"":
			idx = 0
		}
		if idx < 0 && bytes.IndexByte(key, '\\') >= 0 {
			if name, ok := odjsonrt.UnquoteName(key); ok {
				switch string(name) {
				case "x":
					idx = 0
				}
			}
		}
		switch idx {
		case 0:
			var val9 jsontext.Value
			val9, err = dec.ReadValue()
			if err != nil {
				return err
			}
			vp10 := 0
			if np11, ok12 := odjsonrt.ParseNull(val9, vp10); ok12 {
				vp10 = np11
				v.X = nil
			} else {
				var a13 any
				a13, vp10, err = odjsonrt.ParseAnyWith(val9, vp10, sc)
				if err != nil {
					return err
				}
				v.X = a13
			}
			_ = vp10
		default:
			if _, err = dec.ReadValue(); err != nil {
				return err
			}
		}
	}
	_, err = dec.ReadToken()
	return err
}

// odjsonSizeValue sizes the buffer the encoders allocate.
var odjsonSizeValue odjsonrt.SizeHint

// MarshalJSON implements encoding/json.Marshaler.
func (v Value) MarshalJSON() ([]byte, error) {
	buf, err := v.odjsonAppend(odjsonSizeValue.New(), odjsonrt.ModeHTML)
	if err != nil {
		return nil, err
	}
	odjsonSizeValue.Record(buf)
	return buf, nil
}

// UnmarshalJSON implements encoding/json.Unmarshaler.
func (v *Value) UnmarshalJSON(data []byte) error {
	// The cache plays the part of encoding/json/v2's string cache: a
	// value that recurs in the document is allocated once.
	sc := odjsonrt.GetStringCache()
	p, err := v.odjsonParse(data, odjsonrt.SkipSpace(data, 0), sc)
	odjsonrt.PutStringCache(sc)
	if err != nil {
		return err
	}
	return odjsonrt.EndOfDocument(data, p)
}

// MarshalJSONTo implements encoding/json/v2.MarshalerTo.
func (v Value) MarshalJSONTo(enc *jsontext.Encoder) error {
	// Under a plain json.Marshal, from encoding/json/v2 or encoding/json,
	// the value is appended straight into the encoder's buffer at any
	// depth; see odjsonrt.BeginDirectEncodeMode for what qualifies and
	// for the mode, which does that call's escaping itself since nothing
	// downstream looks at the bytes.
	if buf, m, ok := odjsonrt.BeginDirectEncodeMode(enc); ok {
		n := len(buf)
		buf, err := v.odjsonAppend(buf, m)
		if err != nil {
			return err
		}
		odjsonSizeValue.Record(buf[n:])
		odjsonrt.EndDirectEncode(enc, buf)
		return nil
	}
	// Otherwise WriteValue copies what it is given, so the scratch buffer
	// can go straight back to the pool. ModeStream leaves the HTML escaping
	// and the UTF-8 validation to the encoder, which performs both while
	// reformatting the value either way.
	buf := odjsonrt.GetBuffer()
	var err error
	if buf.B, err = v.odjsonAppend(buf.B, odjsonrt.ModeStream); err == nil {
		odjsonSizeValue.Record(buf.B)
		err = enc.WriteValue(buf.B)
	}
	odjsonrt.PutBuffer(buf)
	return err
}

// UnmarshalJSONFrom implements encoding/json/v2.UnmarshalerFrom.
func (v *Value) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	// The cache plays the part of json/v2's own string cache: a value
	// that recurs in the document is allocated once.
	sc := odjsonrt.GetStringCache()
	var err error
	// Under a plain json.Unmarshal the value is parsed straight out of
	// the decoder's buffer at any depth; see odjsonrt.BeginDirectDecodeAt
	// for what qualifies. Nobody has validated those bytes, so
	// odjsonParseV2 rejects what jsontext would have.
	if data, p, ok := odjsonrt.BeginDirectDecodeAt(dec); ok {
		var end int
		if end, err = v.odjsonParseV2(data, p, sc, true); err == nil {
			odjsonrt.EndDirectDecodeAt(dec, p, end)
		}
	} else {
		err = v.odjsonParseFrom(dec, sc)
	}
	odjsonrt.PutStringCache(sc)
	return err
}

// odjsonAppend appends the JSON encoding of v to dst.
func (v *Typed) odjsonAppend(dst []byte, m odjsonrt.StringMode) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, "{\"x\":"...)
	dst, err = v.X.odjsonAppend(dst, m)
	if err != nil {
		return nil, err
	}
	dst = append(dst, "}"...)
	return dst, nil
}

// odjsonParse decodes the JSON object starting at p into v and
// returns the offset just past it. Strings are interned through
// sc, which may be nil.
func (v *Typed) odjsonParse(data []byte, p int, sc *odjsonrt.StringCache) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		return np, nil
	}
	if uint(p) >= uint(len(data)) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "Typed")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if uint(p) < uint(len(data)) && data[p] == '}' {
		return p + 1, nil
	}
	for {
		var key []byte
		if uint(p) >= uint(len(data)) || data[p] <= ' ' {
			p = odjsonrt.SkipSpace(data, odjsonrt.SkipIndent(data, p))
		}
		idx := -1
		rest := data[p:]
		if len(rest) >= 3 && string(rest[:3]) == "\"x\"" {
			idx, p = 0, p+3
		}
		if idx >= 0 {
			if np := odjsonrt.AfterName(data, p); np > 0 {
				p = np
			} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
				return p, err
			}
		} else {
			key, _, p, err = odjsonrt.ParseKey(data, p)
			if err != nil {
				return p, err
			}
			switch string(key) {
			case "x":
				idx = 0
			}
		}
		switch idx {
		case 0:
			p, err = v.X.odjsonParse(data, p, sc)
			if err != nil {
				return p, err
			}
		default:
			p = odjsonrt.SkipSpace(data, p)
			p, err = odjsonrt.SkipValue(data, p)
			if err != nil {
				return p, err
			}
		}
		p = odjsonrt.SkipSpace(data, p)
		if uint(p) >= uint(len(data)) {
			return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
		}
		switch data[p] {
		case ',':
			p++
		case '}':
			return p + 1, nil
		default:
			return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
		}
	}
}

// odjsonParseV2 is odjsonParse under encoding/json/v2's semantics, for
// input a jsontext.Decoder has already validated when strict is false,
// and for bytes nobody has looked at when it is true.
func (v *Typed) odjsonParseV2(data []byte, p int, sc *odjsonrt.StringCache, strict bool) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		*v = Typed{}
		return np, nil
	}
	if uint(p) >= uint(len(data)) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "Typed")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if uint(p) < uint(len(data)) && data[p] == '}' {
		return p + 1, nil
	}
	var seen [1]uint64
	_ = seen
	unknown, umark := odjsonrt.UnknownNames(sc)
	var ufilter uint64
	_ = ufilter
	for {
		var key []byte
		if uint(p) >= uint(len(data)) || data[p] <= ' ' {
			p = odjsonrt.SkipSpace(data, odjsonrt.SkipIndent(data, p))
		}
		kp := p
		idx := -1
		rest := data[p:]
		if len(rest) >= 3 && string(rest[:3]) == "\"x\"" {
			idx, p = 0, p+3
		}
		if idx >= 0 {
			if np := odjsonrt.AfterName(data, p); np > 0 {
				p = np
			} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
				return p, err
			}
		} else {
			key, p, err = odjsonrt.ParseKeyV2(data, p, strict)
			if err != nil {
				return p, err
			}
			switch string(key) {
			case "x":
				idx = 0
			}
		}
		switch idx {
		case 0:
			if strict && seen[0]&(1<<0) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 0
			p, err = v.X.odjsonParseV2(data, p, sc, strict)
			if err != nil {
				return p, err
			}
		default:
			if strict {
				var dup bool
				if unknown, dup = odjsonrt.UnknownName(sc, unknown, umark, &ufilter, key); dup {
					return kp, odjsonrt.ErrDuplicateName(data, kp, key)
				}
			}
			p = odjsonrt.SkipSpace(data, p)
			p, err = odjsonrt.SkipValueV2(data, p, strict)
			if err != nil {
				return p, err
			}
		}
		p = odjsonrt.SkipSpace(data, p)
		if uint(p) >= uint(len(data)) {
			return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
		}
		switch data[p] {
		case ',':
			p++
		case '}':
			odjsonrt.EndUnknownNames(sc, unknown, umark)
			return p + 1, nil
		default:
			return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
		}
	}
}

// odjsonParseFrom decodes the next value in dec into v,
// driving the decoder token by token so the document is
// parsed once rather than twice.
func (v *Typed) odjsonParseFrom(dec *jsontext.Decoder, sc *odjsonrt.StringCache) error {
	var err error
	_ = err
	if odjsonrt.WholeValue(dec) {
		var val jsontext.Value
		if val, err = dec.ReadValue(); err != nil {
			return err
		}
		_, err = v.odjsonParseV2(val, 0, sc, false)
		return err
	}
	switch odjsonrt.NextKind(dec) {
	case 'n':
		if _, err = dec.ReadToken(); err != nil {
			return err
		}
		*v = Typed{}
		return nil
	case '{':
	default:
		return odjsonrt.ErrKindFrom(dec, "Typed")
	}
	if _, err = dec.ReadToken(); err != nil {
		return err
	}
	for odjsonrt.NextKind(dec) != '}' {
		var key jsontext.Value
		key, err = dec.ReadValue()
		if err != nil {
			return err
		}
		idx := -1
		switch string(key) {
		case "\"x\"":
			idx = 0
		}
		if idx < 0 && bytes.IndexByte(key, '\\') >= 0 {
			if name, ok := odjsonrt.UnquoteName(key); ok {
				switch string(name) {
				case "x":
					idx = 0
				}
			}
		}
		switch idx {
		case 0:
			if err = v.X.odjsonParseFrom(dec, sc); err != nil {
				return err
			}
		default:
			if _, err = dec.ReadValue(); err != nil {
				return err
			}
		}
	}
	_, err = dec.ReadToken()
	return err
}

// odjsonSizeTyped sizes the buffer the encoders allocate.
var odjsonSizeTyped odjsonrt.SizeHint

// MarshalJSON implements encoding/json.Marshaler.
func (v Typed) MarshalJSON() ([]byte, error) {
	buf, err := v.odjsonAppend(odjsonSizeTyped.New(), odjsonrt.ModeHTML)
	if err != nil {
		return nil, err
	}
	odjsonSizeTyped.Record(buf)
	return buf, nil
}

// UnmarshalJSON implements encoding/json.Unmarshaler.
func (v *Typed) UnmarshalJSON(data []byte) error {
	// The cache plays the part of encoding/json/v2's string cache: a
	// value that recurs in the document is allocated once.
	sc := odjsonrt.GetStringCache()
	p, err := v.odjsonParse(data, odjsonrt.SkipSpace(data, 0), sc)
	odjsonrt.PutStringCache(sc)
	if err != nil {
		return err
	}
	return odjsonrt.EndOfDocument(data, p)
}

// MarshalJSONTo implements encoding/json/v2.MarshalerTo.
func (v Typed) MarshalJSONTo(enc *jsontext.Encoder) error {
	// Under a plain json.Marshal, from encoding/json/v2 or encoding/json,
	// the value is appended straight into the encoder's buffer at any
	// depth; see odjsonrt.BeginDirectEncodeMode for what qualifies and
	// for the mode, which does that call's escaping itself since nothing
	// downstream looks at the bytes.
	if buf, m, ok := odjsonrt.BeginDirectEncodeMode(enc); ok {
		n := len(buf)
		buf, err := v.odjsonAppend(buf, m)
		if err != nil {
			return err
		}
		odjsonSizeTyped.Record(buf[n:])
		odjsonrt.EndDirectEncode(enc, buf)
		return nil
	}
	// Otherwise WriteValue copies what it is given, so the scratch buffer
	// can go straight back to the pool. ModeStream leaves the HTML escaping
	// and the UTF-8 validation to the encoder, which performs both while
	// reformatting the value either way.
	buf := odjsonrt.GetBuffer()
	var err error
	if buf.B, err = v.odjsonAppend(buf.B, odjsonrt.ModeStream); err == nil {
		odjsonSizeTyped.Record(buf.B)
		err = enc.WriteValue(buf.B)
	}
	odjsonrt.PutBuffer(buf)
	return err
}

// UnmarshalJSONFrom implements encoding/json/v2.UnmarshalerFrom.
func (v *Typed) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	// The cache plays the part of json/v2's own string cache: a value
	// that recurs in the document is allocated once.
	sc := odjsonrt.GetStringCache()
	var err error
	// Under a plain json.Unmarshal the value is parsed straight out of
	// the decoder's buffer at any depth; see odjsonrt.BeginDirectDecodeAt
	// for what qualifies. Nobody has validated those bytes, so
	// odjsonParseV2 rejects what jsontext would have.
	if data, p, ok := odjsonrt.BeginDirectDecodeAt(dec); ok {
		var end int
		if end, err = v.odjsonParseV2(data, p, sc, true); err == nil {
			odjsonrt.EndDirectDecodeAt(dec, p, end)
		}
	} else {
		err = v.odjsonParseFrom(dec, sc)
	}
	odjsonrt.PutStringCache(sc)
	return err
}

// odjsonAppend appends the JSON encoding of v to dst.
func (v *Inner) odjsonAppend(dst []byte, m odjsonrt.StringMode) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, "{\"s\":\""...)
	dst, err = odjsonrt.AppendStringBodyChecked(dst, string(v.S), m)
	if err != nil {
		return nil, err
	}
	dst = append(dst, "\",\"n\":"...)
	dst, err = odjsonrt.AppendFloat(dst, float64(v.N), 64)
	if err != nil {
		return nil, err
	}
	if bool(v.B) {
		dst = append(dst, ",\"b\":true,\"l\":"...)
	} else {
		dst = append(dst, ",\"b\":false,\"l\":"...)
	}
	if v.L == nil {
		if m.V2() {
			dst = append(dst, "[],\"m\":"...)
		} else {
			dst = append(dst, "null,\"m\":"...)
		}
	} else {
		dst = append(dst, "["...)
		for i14 := range v.L {
			if i14 > 0 {
				dst = append(dst, ',')
			}
			dst = odjsonrt.AppendInt(dst, int64(v.L[i14]))
		}
		dst = append(dst, "],\"m\":"...)
	}
	if v.M == nil {
		if m.V2() {
			dst = append(dst, "{},\"a\":"...)
		} else {
			dst = append(dst, "null,\"a\":"...)
		}
	} else {
		keys15 := make([]string, 0, len(v.M))
		for k16 := range v.M {
			keys15 = append(keys15, string(k16))
		}
		slices.Sort(keys15)
		dst = append(dst, "{"...)
		for i17, k16 := range keys15 {
			if i17 > 0 {
				dst = append(dst, ',')
			}
			dst = append(dst, '"')
			dst, err = odjsonrt.AppendStringBodyChecked(dst, k16, m)
			if err != nil {
				return nil, err
			}
			mv18 := v.M[k16]
			dst = append(dst, "\":\""...)
			dst, err = odjsonrt.AppendStringBodyChecked(dst, string(mv18), m)
			if err != nil {
				return nil, err
			}
			dst = append(dst, "\""...)
		}
		dst = append(dst, "},\"a\":"...)
	}
	if v.A == nil {
		dst = append(dst, "null,\"p\":"...)
	} else {
		dst, err = odjsonrt.AppendAnyMode(dst, v.A, m)
		if err != nil {
			return nil, err
		}
		dst = append(dst, ",\"p\":"...)
	}
	if v.P == nil {
		dst = append(dst, "null}"...)
	} else {
		dst, err = (*v.P).odjsonAppend(dst, m)
		if err != nil {
			return nil, err
		}
		dst = append(dst, "}"...)
	}
	return dst, nil
}

// odjsonCapInnerL remembers how long v.L has been, to allocate it once.
var odjsonCapInnerL odjsonrt.CapHint

// odjsonParse decodes the JSON object starting at p into v and
// returns the offset just past it. Strings are interned through
// sc, which may be nil.
func (v *Inner) odjsonParse(data []byte, p int, sc *odjsonrt.StringCache) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		return np, nil
	}
	if uint(p) >= uint(len(data)) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "Inner")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if uint(p) < uint(len(data)) && data[p] == '}' {
		return p + 1, nil
	}
	for {
		var key []byte
		if uint(p) >= uint(len(data)) || data[p] <= ' ' {
			p = odjsonrt.SkipSpace(data, odjsonrt.SkipIndent(data, p))
		}
		idx := -1
		rest := data[p:]
		if len(rest) > 1 {
			switch rest[1] {
			case 's':
				if len(rest) >= 3 && string(rest[:3]) == "\"s\"" {
					idx, p = 0, p+3
				}
			case 'n':
				if len(rest) >= 3 && string(rest[:3]) == "\"n\"" {
					idx, p = 1, p+3
				}
			case 'b':
				if len(rest) >= 3 && string(rest[:3]) == "\"b\"" {
					idx, p = 2, p+3
				}
			case 'l':
				if len(rest) >= 3 && string(rest[:3]) == "\"l\"" {
					idx, p = 3, p+3
				}
			case 'm':
				if len(rest) >= 3 && string(rest[:3]) == "\"m\"" {
					idx, p = 4, p+3
				}
			case 'a':
				if len(rest) >= 3 && string(rest[:3]) == "\"a\"" {
					idx, p = 5, p+3
				}
			case 'p':
				if len(rest) >= 3 && string(rest[:3]) == "\"p\"" {
					idx, p = 6, p+3
				}
			}
		}
		if idx >= 0 {
			if np := odjsonrt.AfterName(data, p); np > 0 {
				p = np
			} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
				return p, err
			}
		} else {
			key, _, p, err = odjsonrt.ParseKey(data, p)
			if err != nil {
				return p, err
			}
			switch string(key) {
			case "s":
				idx = 0
			case "n":
				idx = 1
			case "b":
				idx = 2
			case "l":
				idx = 3
			case "m":
				idx = 4
			case "a":
				idx = 5
			case "p":
				idx = 6
			}
		}
		switch idx {
		case 0:
			if np19, ok20 := odjsonrt.ParseNull(data, p); ok20 {
				p = np19
			} else {
				var x21 string
				x21, p, err = odjsonrt.ParseStringCached(data, p, sc)
				if err != nil {
					return p, err
				}
				v.S = x21
			}
		case 1:
			if np22, ok23 := odjsonrt.ParseNull(data, p); ok23 {
				p = np22
			} else {
				if x24, np25, ok26 := odjsonrt.ParseSimpleFloat(data, p, 64); ok26 {
					v.N = float64(x24)
					p = np25
				} else {
					var x27 float64
					x27, p, err = odjsonrt.ParseFloat(data, p, 64)
					if err != nil {
						return p, err
					}
					v.N = x27
				}
			}
		case 2:
			if np28, ok29 := odjsonrt.ParseNull(data, p); ok29 {
				p = np28
			} else {
				if uint(p+4) <= uint(len(data)) && string(data[p:p+4]) == "true" {
					v.B = true
					p += 4
				} else if uint(p+5) <= uint(len(data)) && string(data[p:p+5]) == "false" {
					v.B = false
					p += 5
				} else {
					var x30 bool
					x30, p, err = odjsonrt.ParseBool(data, p)
					if err != nil {
						return p, err
					}
					v.B = x30
				}
			}
		case 3:
			if np31, ok32 := odjsonrt.ParseNull(data, p); ok32 {
				p = np31
				v.L = nil
			} else {
				if uint(p) >= uint(len(data)) || data[p] != '[' {
					return p, odjsonrt.ErrType(data, p, "[]int")
				}
				p++
				s33 := v.L[:0]
				p = odjsonrt.SkipSpace(data, p)
				if uint(p) < uint(len(data)) && data[p] == ']' {
					p++
				} else {
					if cap(s33) == 0 {
						s33 = make([]int, 0, odjsonrt.CapFor[int](&odjsonCapInnerL))
					}
					for {
						var e34 int
						if uint(p) >= uint(len(data)) || data[p] <= ' ' {
							p = odjsonrt.SkipSpace(data, odjsonrt.SkipIndent(data, p))
						}
						if np35, ok36 := odjsonrt.ParseNull(data, p); ok36 {
							p = np35
						} else {
							if x37, np38, ok39 := odjsonrt.ParseDecimal(data, p); ok39 {
								e34 = int(x37)
								p = np38
							} else {
								var x40 int64
								x40, p, err = odjsonrt.ParseInt(data, p, 64)
								if err != nil {
									return p, err
								}
								e34 = int(x40)
							}
						}
						s33 = append(s33, e34)
						p = odjsonrt.SkipSpace(data, p)
						if uint(p) >= uint(len(data)) {
							return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
						}
						if data[p] == ',' {
							p++
							continue
						}
						if data[p] == ']' {
							p++
							break
						}
						return p, odjsonrt.ErrSyntax(data, p, "after array element")
					}
					odjsonCapInnerL.Record(len(s33))
				}
				if s33 == nil {
					s33 = []int{}
				}
				v.L = s33
			}
		case 4:
			if np41, ok42 := odjsonrt.ParseNull(data, p); ok42 {
				p = np41
				v.M = nil
			} else {
				if uint(p) >= uint(len(data)) || data[p] != '{' {
					return p, odjsonrt.ErrType(data, p, "map[string]string")
				}
				p++
				m43 := v.M
				if m43 == nil {
					m43 = make(map[string]string)
				}
				p = odjsonrt.SkipSpace(data, p)
				if uint(p) < uint(len(data)) && data[p] == '}' {
					p++
				} else {
					for {
						var k44 []byte
						p = odjsonrt.SkipSpace(data, p)
						k44, _, p, err = odjsonrt.ParseKey(data, p)
						if err != nil {
							return p, err
						}
						var mv45 string
						p = odjsonrt.SkipSpace(data, p)
						if np47, ok48 := odjsonrt.ParseNull(data, p); ok48 {
							p = np47
						} else {
							var x49 string
							x49, p, err = odjsonrt.ParseStringCached(data, p, sc)
							if err != nil {
								return p, err
							}
							mv45 = x49
						}
						m43[sc.Make(k44)] = mv45
						p = odjsonrt.SkipSpace(data, p)
						if uint(p) >= uint(len(data)) {
							return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
						}
						if data[p] == ',' {
							p++
							continue
						}
						if data[p] == '}' {
							p++
							break
						}
						return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
					}
				}
				v.M = m43
			}
		case 5:
			if np50, ok51 := odjsonrt.ParseNull(data, p); ok51 {
				p = np50
				v.A = nil
			} else {
				var a52 any
				a52, p, err = odjsonrt.ParseAnyCached(data, p, sc)
				if err != nil {
					return p, err
				}
				v.A = a52
			}
		case 6:
			if np53, ok54 := odjsonrt.ParseNull(data, p); ok54 {
				v.P = nil
				p = np53
			} else {
				if v.P == nil {
					v.P = new(Inner)
				}
				p, err = (*v.P).odjsonParse(data, p, sc)
				if err != nil {
					return p, err
				}
			}
		default:
			p = odjsonrt.SkipSpace(data, p)
			p, err = odjsonrt.SkipValue(data, p)
			if err != nil {
				return p, err
			}
		}
		p = odjsonrt.SkipSpace(data, p)
		if uint(p) >= uint(len(data)) {
			return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
		}
		switch data[p] {
		case ',':
			p++
		case '}':
			return p + 1, nil
		default:
			return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
		}
	}
}

// odjsonParseV2 is odjsonParse under encoding/json/v2's semantics, for
// input a jsontext.Decoder has already validated when strict is false,
// and for bytes nobody has looked at when it is true.
func (v *Inner) odjsonParseV2(data []byte, p int, sc *odjsonrt.StringCache, strict bool) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		*v = Inner{}
		return np, nil
	}
	if uint(p) >= uint(len(data)) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "Inner")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if uint(p) < uint(len(data)) && data[p] == '}' {
		return p + 1, nil
	}
	var seen [1]uint64
	_ = seen
	unknown, umark := odjsonrt.UnknownNames(sc)
	var ufilter uint64
	_ = ufilter
	for {
		var key []byte
		if uint(p) >= uint(len(data)) || data[p] <= ' ' {
			p = odjsonrt.SkipSpace(data, odjsonrt.SkipIndent(data, p))
		}
		kp := p
		idx := -1
		rest := data[p:]
		if len(rest) > 1 {
			switch rest[1] {
			case 's':
				if len(rest) >= 3 && string(rest[:3]) == "\"s\"" {
					idx, p = 0, p+3
				}
			case 'n':
				if len(rest) >= 3 && string(rest[:3]) == "\"n\"" {
					idx, p = 1, p+3
				}
			case 'b':
				if len(rest) >= 3 && string(rest[:3]) == "\"b\"" {
					idx, p = 2, p+3
				}
			case 'l':
				if len(rest) >= 3 && string(rest[:3]) == "\"l\"" {
					idx, p = 3, p+3
				}
			case 'm':
				if len(rest) >= 3 && string(rest[:3]) == "\"m\"" {
					idx, p = 4, p+3
				}
			case 'a':
				if len(rest) >= 3 && string(rest[:3]) == "\"a\"" {
					idx, p = 5, p+3
				}
			case 'p':
				if len(rest) >= 3 && string(rest[:3]) == "\"p\"" {
					idx, p = 6, p+3
				}
			}
		}
		if idx >= 0 {
			if np := odjsonrt.AfterName(data, p); np > 0 {
				p = np
			} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
				return p, err
			}
		} else {
			key, p, err = odjsonrt.ParseKeyV2(data, p, strict)
			if err != nil {
				return p, err
			}
			switch string(key) {
			case "s":
				idx = 0
			case "n":
				idx = 1
			case "b":
				idx = 2
			case "l":
				idx = 3
			case "m":
				idx = 4
			case "a":
				idx = 5
			case "p":
				idx = 6
			}
		}
		switch idx {
		case 0:
			if strict && seen[0]&(1<<0) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 0
			if np55, ok56 := odjsonrt.ParseNull(data, p); ok56 {
				p = np55
				v.S = ""
			} else {
				var x57 string
				x57, p, err = odjsonrt.ParseStringV2(data, p, sc, strict)
				if err != nil {
					return p, err
				}
				v.S = x57
			}
		case 1:
			if strict && seen[0]&(1<<1) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 1
			if np58, ok59 := odjsonrt.ParseNull(data, p); ok59 {
				p = np58
				v.N = 0
			} else {
				if x60, np61, ok62 := odjsonrt.ParseSimpleFloat(data, p, 64); ok62 {
					v.N = float64(x60)
					p = np61
				} else {
					var x63 float64
					x63, p, err = odjsonrt.ParseFloat(data, p, 64)
					if err != nil {
						return p, err
					}
					v.N = x63
				}
			}
		case 2:
			if strict && seen[0]&(1<<2) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 2
			if np64, ok65 := odjsonrt.ParseNull(data, p); ok65 {
				p = np64
				v.B = false
			} else {
				if uint(p+4) <= uint(len(data)) && string(data[p:p+4]) == "true" {
					v.B = true
					p += 4
				} else if uint(p+5) <= uint(len(data)) && string(data[p:p+5]) == "false" {
					v.B = false
					p += 5
				} else {
					var x66 bool
					x66, p, err = odjsonrt.ParseBool(data, p)
					if err != nil {
						return p, err
					}
					v.B = x66
				}
			}
		case 3:
			if strict && seen[0]&(1<<3) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 3
			if np67, ok68 := odjsonrt.ParseNull(data, p); ok68 {
				p = np67
				v.L = nil
			} else {
				if uint(p) >= uint(len(data)) || data[p] != '[' {
					return p, odjsonrt.ErrType(data, p, "[]int")
				}
				p++
				s69 := v.L[:0]
				p = odjsonrt.SkipSpace(data, p)
				if uint(p) < uint(len(data)) && data[p] == ']' {
					p++
				} else {
					if cap(s69) == 0 {
						s69 = make([]int, 0, odjsonrt.CapFor[int](&odjsonCapInnerL))
					}
					for {
						var e70 int
						if uint(p) >= uint(len(data)) || data[p] <= ' ' {
							p = odjsonrt.SkipSpace(data, odjsonrt.SkipIndent(data, p))
						}
						if np71, ok72 := odjsonrt.ParseNull(data, p); ok72 {
							p = np71
							e70 = 0
						} else {
							if x73, np74, ok75 := odjsonrt.ParseDecimal(data, p); ok75 {
								e70 = int(x73)
								p = np74
							} else {
								var x76 int64
								x76, p, err = odjsonrt.ParseInt(data, p, 64)
								if err != nil {
									return p, err
								}
								e70 = int(x76)
							}
						}
						s69 = append(s69, e70)
						p = odjsonrt.SkipSpace(data, p)
						if uint(p) >= uint(len(data)) {
							return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
						}
						if data[p] == ',' {
							p++
							continue
						}
						if data[p] == ']' {
							p++
							break
						}
						return p, odjsonrt.ErrSyntax(data, p, "after array element")
					}
					odjsonCapInnerL.Record(len(s69))
				}
				if s69 == nil {
					s69 = []int{}
				}
				v.L = s69
			}
		case 4:
			if strict && seen[0]&(1<<4) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 4
			if np77, ok78 := odjsonrt.ParseNull(data, p); ok78 {
				p = np77
				v.M = nil
			} else {
				if uint(p) >= uint(len(data)) || data[p] != '{' {
					return p, odjsonrt.ErrType(data, p, "map[string]string")
				}
				p++
				m79 := v.M
				if m79 == nil {
					m79 = make(map[string]string)
				}
				var seen82 map[string]struct{}
				if strict && len(m79) > 0 {
					seen82 = make(map[string]struct{})
				}
				p = odjsonrt.SkipSpace(data, p)
				if uint(p) < uint(len(data)) && data[p] == '}' {
					p++
				} else {
					for {
						var k80 []byte
						p = odjsonrt.SkipSpace(data, p)
						kp83 := p
						k80, p, err = odjsonrt.ParseKeyV2(data, p, strict)
						if err != nil {
							return p, err
						}
						if strict && seen82 != nil {
							if _, dup := seen82[string(k80)]; dup {
								return p, odjsonrt.ErrDuplicateName(data, kp83, k80)
							}
							seen82[string(k80)] = struct{}{}
						}
						var mv81 string
						p = odjsonrt.SkipSpace(data, p)
						if np84, ok85 := odjsonrt.ParseNull(data, p); ok85 {
							p = np84
							mv81 = ""
						} else {
							var x86 string
							x86, p, err = odjsonrt.ParseStringV2(data, p, sc, strict)
							if err != nil {
								return p, err
							}
							mv81 = x86
						}
						n87 := len(m79)
						m79[sc.Make(k80)] = mv81
						if strict && seen82 == nil && len(m79) == n87 {
							return p, odjsonrt.ErrDuplicateName(data, kp83, k80)
						}
						p = odjsonrt.SkipSpace(data, p)
						if uint(p) >= uint(len(data)) {
							return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
						}
						if data[p] == ',' {
							p++
							continue
						}
						if data[p] == '}' {
							p++
							break
						}
						return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
					}
				}
				v.M = m79
			}
		case 5:
			if strict && seen[0]&(1<<5) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 5
			if np88, ok89 := odjsonrt.ParseNull(data, p); ok89 {
				p = np88
				v.A = nil
			} else {
				var a90 any
				a90, p, err = odjsonrt.ParseAnyV2(data, p, sc, strict)
				if err != nil {
					return p, err
				}
				v.A = a90
			}
		case 6:
			if strict && seen[0]&(1<<6) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 6
			if np91, ok92 := odjsonrt.ParseNull(data, p); ok92 {
				v.P = nil
				p = np91
			} else {
				if v.P == nil {
					v.P = new(Inner)
				}
				p, err = (*v.P).odjsonParseV2(data, p, sc, strict)
				if err != nil {
					return p, err
				}
			}
		default:
			if strict {
				var dup bool
				if unknown, dup = odjsonrt.UnknownName(sc, unknown, umark, &ufilter, key); dup {
					return kp, odjsonrt.ErrDuplicateName(data, kp, key)
				}
			}
			p = odjsonrt.SkipSpace(data, p)
			p, err = odjsonrt.SkipValueV2(data, p, strict)
			if err != nil {
				return p, err
			}
		}
		p = odjsonrt.SkipSpace(data, p)
		if uint(p) >= uint(len(data)) {
			return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
		}
		switch data[p] {
		case ',':
			p++
		case '}':
			odjsonrt.EndUnknownNames(sc, unknown, umark)
			return p + 1, nil
		default:
			return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
		}
	}
}

// odjsonParseFrom decodes the next value in dec into v,
// driving the decoder token by token so the document is
// parsed once rather than twice.
func (v *Inner) odjsonParseFrom(dec *jsontext.Decoder, sc *odjsonrt.StringCache) error {
	var err error
	_ = err
	if odjsonrt.WholeValue(dec) {
		var val jsontext.Value
		if val, err = dec.ReadValue(); err != nil {
			return err
		}
		_, err = v.odjsonParseV2(val, 0, sc, false)
		return err
	}
	switch odjsonrt.NextKind(dec) {
	case 'n':
		if _, err = dec.ReadToken(); err != nil {
			return err
		}
		*v = Inner{}
		return nil
	case '{':
	default:
		return odjsonrt.ErrKindFrom(dec, "Inner")
	}
	if _, err = dec.ReadToken(); err != nil {
		return err
	}
	for odjsonrt.NextKind(dec) != '}' {
		var key jsontext.Value
		key, err = dec.ReadValue()
		if err != nil {
			return err
		}
		idx := -1
		switch string(key) {
		case "\"s\"":
			idx = 0
		case "\"n\"":
			idx = 1
		case "\"b\"":
			idx = 2
		case "\"l\"":
			idx = 3
		case "\"m\"":
			idx = 4
		case "\"a\"":
			idx = 5
		case "\"p\"":
			idx = 6
		}
		if idx < 0 && bytes.IndexByte(key, '\\') >= 0 {
			if name, ok := odjsonrt.UnquoteName(key); ok {
				switch string(name) {
				case "s":
					idx = 0
				case "n":
					idx = 1
				case "b":
					idx = 2
				case "l":
					idx = 3
				case "m":
					idx = 4
				case "a":
					idx = 5
				case "p":
					idx = 6
				}
			}
		}
		switch idx {
		case 0:
			var val93 jsontext.Value
			val93, err = dec.ReadValue()
			if err != nil {
				return err
			}
			if val93[0] == 'n' {
				v.S = ""
			} else {
				var x94 string
				x94, err = odjsonrt.ParseStringValue(val93, sc)
				if err != nil {
					return err
				}
				v.S = x94
			}
		case 1:
			var val95 jsontext.Value
			val95, err = dec.ReadValue()
			if err != nil {
				return err
			}
			if val95[0] == 'n' {
				v.N = 0
			} else {
				var x96 float64
				x96, err = odjsonrt.ParseFloatValue(val95, 64)
				if err != nil {
					return err
				}
				v.N = x96
			}
		case 2:
			var val97 jsontext.Value
			val97, err = dec.ReadValue()
			if err != nil {
				return err
			}
			if val97[0] == 'n' {
				v.B = false
			} else {
				var x98 bool
				x98, _, err = odjsonrt.ParseBool(val97, 0)
				if err != nil {
					return err
				}
				v.B = x98
			}
		case 3:
			var val99 jsontext.Value
			val99, err = dec.ReadValue()
			if err != nil {
				return err
			}
			vp100 := 0
			if np101, ok102 := odjsonrt.ParseNull(val99, vp100); ok102 {
				vp100 = np101
				v.L = nil
			} else {
				if uint(vp100) >= uint(len(val99)) || val99[vp100] != '[' {
					return odjsonrt.ErrType(val99, vp100, "[]int")
				}
				vp100++
				s103 := v.L[:0]
				vp100 = odjsonrt.SkipSpace(val99, vp100)
				if uint(vp100) < uint(len(val99)) && val99[vp100] == ']' {
					vp100++
				} else {
					if cap(s103) == 0 {
						s103 = make([]int, 0, odjsonrt.CapFor[int](&odjsonCapInnerL))
					}
					for {
						var e104 int
						if uint(vp100) >= uint(len(val99)) || val99[vp100] <= ' ' {
							vp100 = odjsonrt.SkipSpace(val99, odjsonrt.SkipIndent(val99, vp100))
						}
						if np105, ok106 := odjsonrt.ParseNull(val99, vp100); ok106 {
							vp100 = np105
							e104 = 0
						} else {
							if x107, np108, ok109 := odjsonrt.ParseDecimal(val99, vp100); ok109 {
								e104 = int(x107)
								vp100 = np108
							} else {
								var x110 int64
								x110, vp100, err = odjsonrt.ParseInt(val99, vp100, 64)
								if err != nil {
									return err
								}
								e104 = int(x110)
							}
						}
						s103 = append(s103, e104)
						vp100 = odjsonrt.SkipSpace(val99, vp100)
						if uint(vp100) >= uint(len(val99)) {
							return odjsonrt.ErrSyntax(val99, vp100, "unexpected end of JSON input")
						}
						if val99[vp100] == ',' {
							vp100++
							continue
						}
						if val99[vp100] == ']' {
							vp100++
							break
						}
						return odjsonrt.ErrSyntax(val99, vp100, "after array element")
					}
					odjsonCapInnerL.Record(len(s103))
				}
				if s103 == nil {
					s103 = []int{}
				}
				v.L = s103
			}
			_ = vp100
		case 4:
			var val111 jsontext.Value
			val111, err = dec.ReadValue()
			if err != nil {
				return err
			}
			vp112 := 0
			if np113, ok114 := odjsonrt.ParseNull(val111, vp112); ok114 {
				vp112 = np113
				v.M = nil
			} else {
				if uint(vp112) >= uint(len(val111)) || val111[vp112] != '{' {
					return odjsonrt.ErrType(val111, vp112, "map[string]string")
				}
				vp112++
				m115 := v.M
				if m115 == nil {
					m115 = make(map[string]string)
				}
				vp112 = odjsonrt.SkipSpace(val111, vp112)
				if uint(vp112) < uint(len(val111)) && val111[vp112] == '}' {
					vp112++
				} else {
					for {
						var k116 []byte
						vp112 = odjsonrt.SkipSpace(val111, vp112)
						k116, _, vp112, err = odjsonrt.ParseKey(val111, vp112)
						if err != nil {
							return err
						}
						var mv117 string
						vp112 = odjsonrt.SkipSpace(val111, vp112)
						if np119, ok120 := odjsonrt.ParseNull(val111, vp112); ok120 {
							vp112 = np119
							mv117 = ""
						} else {
							var x121 string
							x121, vp112, err = odjsonrt.ParseStringWith(val111, vp112, sc)
							if err != nil {
								return err
							}
							mv117 = x121
						}
						m115[sc.Make(k116)] = mv117
						vp112 = odjsonrt.SkipSpace(val111, vp112)
						if uint(vp112) >= uint(len(val111)) {
							return odjsonrt.ErrSyntax(val111, vp112, "unexpected end of JSON input")
						}
						if val111[vp112] == ',' {
							vp112++
							continue
						}
						if val111[vp112] == '}' {
							vp112++
							break
						}
						return odjsonrt.ErrSyntax(val111, vp112, "after object key:value pair")
					}
				}
				v.M = m115
			}
			_ = vp112
		case 5:
			var val122 jsontext.Value
			val122, err = dec.ReadValue()
			if err != nil {
				return err
			}
			vp123 := 0
			if np124, ok125 := odjsonrt.ParseNull(val122, vp123); ok125 {
				vp123 = np124
				v.A = nil
			} else {
				var a126 any
				a126, vp123, err = odjsonrt.ParseAnyWith(val122, vp123, sc)
				if err != nil {
					return err
				}
				v.A = a126
			}
			_ = vp123
		case 6:
			if odjsonrt.NextKind(dec) == 'n' {
				if _, err = dec.ReadToken(); err != nil {
					return err
				}
				v.P = nil
			} else {
				if v.P == nil {
					v.P = new(Inner)
				}
				if err = (*v.P).odjsonParseFrom(dec, sc); err != nil {
					return err
				}
			}
		default:
			if _, err = dec.ReadValue(); err != nil {
				return err
			}
		}
	}
	_, err = dec.ReadToken()
	return err
}

// odjsonSizeInner sizes the buffer the encoders allocate.
var odjsonSizeInner odjsonrt.SizeHint

// MarshalJSON implements encoding/json.Marshaler.
func (v Inner) MarshalJSON() ([]byte, error) {
	buf, err := v.odjsonAppend(odjsonSizeInner.New(), odjsonrt.ModeHTML)
	if err != nil {
		return nil, err
	}
	odjsonSizeInner.Record(buf)
	return buf, nil
}

// UnmarshalJSON implements encoding/json.Unmarshaler.
func (v *Inner) UnmarshalJSON(data []byte) error {
	// The cache plays the part of encoding/json/v2's string cache: a
	// value that recurs in the document is allocated once.
	sc := odjsonrt.GetStringCache()
	p, err := v.odjsonParse(data, odjsonrt.SkipSpace(data, 0), sc)
	odjsonrt.PutStringCache(sc)
	if err != nil {
		return err
	}
	return odjsonrt.EndOfDocument(data, p)
}

// MarshalJSONTo implements encoding/json/v2.MarshalerTo.
func (v Inner) MarshalJSONTo(enc *jsontext.Encoder) error {
	// Under a plain json.Marshal, from encoding/json/v2 or encoding/json,
	// the value is appended straight into the encoder's buffer at any
	// depth; see odjsonrt.BeginDirectEncodeMode for what qualifies and
	// for the mode, which does that call's escaping itself since nothing
	// downstream looks at the bytes.
	if buf, m, ok := odjsonrt.BeginDirectEncodeMode(enc); ok {
		n := len(buf)
		buf, err := v.odjsonAppend(buf, m)
		if err != nil {
			return err
		}
		odjsonSizeInner.Record(buf[n:])
		odjsonrt.EndDirectEncode(enc, buf)
		return nil
	}
	// Otherwise WriteValue copies what it is given, so the scratch buffer
	// can go straight back to the pool. ModeStream leaves the HTML escaping
	// and the UTF-8 validation to the encoder, which performs both while
	// reformatting the value either way.
	buf := odjsonrt.GetBuffer()
	var err error
	if buf.B, err = v.odjsonAppend(buf.B, odjsonrt.ModeStream); err == nil {
		odjsonSizeInner.Record(buf.B)
		err = enc.WriteValue(buf.B)
	}
	odjsonrt.PutBuffer(buf)
	return err
}

// UnmarshalJSONFrom implements encoding/json/v2.UnmarshalerFrom.
func (v *Inner) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	// The cache plays the part of json/v2's own string cache: a value
	// that recurs in the document is allocated once.
	sc := odjsonrt.GetStringCache()
	var err error
	// Under a plain json.Unmarshal the value is parsed straight out of
	// the decoder's buffer at any depth; see odjsonrt.BeginDirectDecodeAt
	// for what qualifies. Nobody has validated those bytes, so
	// odjsonParseV2 rejects what jsontext would have.
	if data, p, ok := odjsonrt.BeginDirectDecodeAt(dec); ok {
		var end int
		if end, err = v.odjsonParseV2(data, p, sc, true); err == nil {
			odjsonrt.EndDirectDecodeAt(dec, p, end)
		}
	} else {
		err = v.odjsonParseFrom(dec, sc)
	}
	odjsonrt.PutStringCache(sc)
	return err
}
