// Code generated by odjson. DO NOT EDIT.
//
// Source: odjson

package unexported

import (
	"bytes"
	"encoding/json/jsontext"
	"github.com/mazrean/odjson/odjsonrt"
)

// odjsonAppend appends the JSON encoding of v to dst.
func (v *secret) odjsonAppend(dst []byte, m odjsonrt.StringMode) ([]byte, error) {
	var err error
	_ = err
	start := len(dst)
	dst = append(dst, ",\"id\":"...)
	dst = odjsonrt.AppendInt(dst, int64(v.ID))
	if len(v.Name) != 0 {
		dst = append(dst, ",\"name\":\""...)
		dst, err = odjsonrt.AppendStringBodyChecked(dst, string(v.Name), m)
		if err != nil {
			return nil, err
		}
		dst = append(dst, "\""...)
	}
	dst[start] = '{'
	dst = append(dst, "}"...)
	return dst, nil
}

// odjsonParse decodes the JSON object starting at p into v and
// returns the offset just past it. Strings are interned through
// sc, which may be nil.
func (v *secret) odjsonParse(data []byte, p int, sc *odjsonrt.StringCache) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		return np, nil
	}
	if uint(p) >= uint(len(data)) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "secret")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if uint(p) < uint(len(data)) && data[p] == '}' {
		return p + 1, nil
	}
	for {
		if uint(p) >= uint(len(data)) || data[p] <= ' ' {
			p = odjsonrt.SkipSpace(data, odjsonrt.SkipIndent(data, p))
		}
		rest := data[p:]
		if len(rest) > 1 {
			switch rest[1] {
			case 'i':
				if len(rest) >= 4 && string(rest[:4]) == "\"id\"" {
					p += 4
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m1
				}
			case 'n':
				if len(rest) >= 6 && string(rest[:6]) == "\"name\"" {
					p += 6
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m2
				}
			}
		}
		{
			var key []byte
			key, _, p, err = odjsonrt.ParseKey(data, p)
			if err != nil {
				return p, err
			}
			switch string(key) {
			case "id":
				goto m1
			case "name":
				goto m2
			}
			p = odjsonrt.SkipSpace(data, p)
			p, err = odjsonrt.SkipValue(data, p)
			if err != nil {
				return p, err
			}
			goto next3
		}
	m1:
		{
			if np4, ok5 := odjsonrt.ParseNull(data, p); ok5 {
				p = np4
			} else {
				if x6, np7, ok8 := odjsonrt.ParseDecimal(data, p); ok8 {
					v.ID = int(x6)
					p = np7
				} else {
					var x9 int64
					x9, p, err = odjsonrt.ParseInt(data, p, 64)
					if err != nil {
						return p, err
					}
					v.ID = int(x9)
				}
			}
			goto next3
		}
	m2:
		{
			if np10, ok11 := odjsonrt.ParseNull(data, p); ok11 {
				p = np10
			} else {
				var x12 string
				x12, p, err = odjsonrt.ParseStringCached(data, p, sc)
				if err != nil {
					return p, err
				}
				v.Name = x12
			}
		}
	next3:
		{
			p = odjsonrt.SkipSpace(data, p)
			if uint(p) >= uint(len(data)) {
				return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
			}
			switch data[p] {
			case ',':
				p++
			case '}':
				return p + 1, nil
			default:
				return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
			}
		}
	}
}

// odjsonParseV2 is odjsonParse under encoding/json/v2's semantics, for
// input a jsontext.Decoder has already validated when strict is false,
// and for bytes nobody has looked at when it is true.
func (v *secret) odjsonParseV2(data []byte, p int, sc *odjsonrt.StringCache, strict bool) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		*v = secret{}
		return np, nil
	}
	if uint(p) >= uint(len(data)) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "secret")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if uint(p) < uint(len(data)) && data[p] == '}' {
		return p + 1, nil
	}
	var seen [1]uint64
	_ = seen
	unknown, umark := odjsonrt.UnknownNames(sc)
	var ufilter uint64
	_ = ufilter
	for {
		if uint(p) >= uint(len(data)) || data[p] <= ' ' {
			p = odjsonrt.SkipSpace(data, odjsonrt.SkipIndent(data, p))
		}
		kp := p
		rest := data[p:]
		if len(rest) > 1 {
			switch rest[1] {
			case 'i':
				if len(rest) >= 4 && string(rest[:4]) == "\"id\"" {
					p += 4
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m13
				}
			case 'n':
				if len(rest) >= 6 && string(rest[:6]) == "\"name\"" {
					p += 6
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m14
				}
			}
		}
		{
			var key []byte
			key, p, err = odjsonrt.ParseKeyV2(data, p, strict)
			if err != nil {
				return p, err
			}
			switch string(key) {
			case "id":
				goto m13
			case "name":
				goto m14
			}
			if strict {
				var dup bool
				if unknown, dup = odjsonrt.UnknownName(sc, unknown, umark, &ufilter, key); dup {
					return kp, odjsonrt.ErrDuplicateName(data, kp, key)
				}
			}
			p = odjsonrt.SkipSpace(data, p)
			p, err = odjsonrt.SkipValueV2(data, p, strict)
			if err != nil {
				return p, err
			}
			goto next15
		}
	m13:
		{
			if strict && seen[0]&(1<<0) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 0
			if np16, ok17 := odjsonrt.ParseNull(data, p); ok17 {
				p = np16
				v.ID = 0
			} else {
				if x18, np19, ok20 := odjsonrt.ParseDecimal(data, p); ok20 {
					v.ID = int(x18)
					p = np19
				} else {
					var x21 int64
					x21, p, err = odjsonrt.ParseInt(data, p, 64)
					if err != nil {
						return p, err
					}
					v.ID = int(x21)
				}
			}
			goto next15
		}
	m14:
		{
			if strict && seen[0]&(1<<1) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 1
			if np22, ok23 := odjsonrt.ParseNull(data, p); ok23 {
				p = np22
				v.Name = ""
			} else {
				var x24 string
				x24, p, err = odjsonrt.ParseStringV2(data, p, sc, strict)
				if err != nil {
					return p, err
				}
				v.Name = x24
			}
		}
	next15:
		{
			p = odjsonrt.SkipSpace(data, p)
			if uint(p) >= uint(len(data)) {
				return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
			}
			switch data[p] {
			case ',':
				p++
			case '}':
				odjsonrt.EndUnknownNames(sc, unknown, umark)
				return p + 1, nil
			default:
				return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
			}
		}
	}
}

// odjsonParseFrom decodes the next value in dec into v,
// driving the decoder token by token so the document is
// parsed once rather than twice.
func (v *secret) odjsonParseFrom(dec *jsontext.Decoder, sc *odjsonrt.StringCache) error {
	var err error
	_ = err
	if odjsonrt.WholeValue(dec) {
		var val jsontext.Value
		if val, err = dec.ReadValue(); err != nil {
			return err
		}
		_, err = v.odjsonParseV2(val, 0, sc, false)
		return err
	}
	switch odjsonrt.NextKind(dec) {
	case 'n':
		if _, err = dec.ReadToken(); err != nil {
			return err
		}
		*v = secret{}
		return nil
	case '{':
	default:
		return odjsonrt.ErrKindFrom(dec, "secret")
	}
	if _, err = dec.ReadToken(); err != nil {
		return err
	}
	for odjsonrt.NextKind(dec) != '}' {
		var key jsontext.Value
		key, err = dec.ReadValue()
		if err != nil {
			return err
		}
		idx := -1
		switch string(key) {
		case "\"id\"":
			idx = 0
		case "\"name\"":
			idx = 1
		}
		if idx < 0 && bytes.IndexByte(key, '\\') >= 0 {
			if name, ok := odjsonrt.UnquoteName(key); ok {
				switch string(name) {
				case "id":
					idx = 0
				case "name":
					idx = 1
				}
			}
		}
		switch idx {
		case 0:
			var val25 jsontext.Value
			val25, err = dec.ReadValue()
			if err != nil {
				return err
			}
			if val25[0] == 'n' {
				v.ID = 0
			} else {
				var x26 int64
				x26, _, err = odjsonrt.ParseInt(val25, 0, 64)
				if err != nil {
					return err
				}
				v.ID = int(x26)
			}
		case 1:
			var val27 jsontext.Value
			val27, err = dec.ReadValue()
			if err != nil {
				return err
			}
			if val27[0] == 'n' {
				v.Name = ""
			} else {
				var x28 string
				x28, err = odjsonrt.ParseStringValue(val27, sc)
				if err != nil {
					return err
				}
				v.Name = x28
			}
		default:
			if _, err = dec.ReadValue(); err != nil {
				return err
			}
		}
	}
	_, err = dec.ReadToken()
	return err
}

// odjsonSizesecret sizes the buffer the encoders allocate.
var odjsonSizesecret odjsonrt.SizeHint

// MarshalJSON implements encoding/json.Marshaler.
func (v secret) MarshalJSON() ([]byte, error) {
	buf, err := v.odjsonAppend(odjsonSizesecret.New(), odjsonrt.ModeHTML)
	if err != nil {
		return nil, err
	}
	odjsonSizesecret.Record(buf)
	return buf, nil
}

// UnmarshalJSON implements encoding/json.Unmarshaler.
func (v *secret) UnmarshalJSON(data []byte) error {
	// The cache plays the part of encoding/json/v2's string cache: a
	// value that recurs in the document is allocated once.
	sc := odjsonrt.GetStringCache()
	p, err := v.odjsonParse(data, odjsonrt.SkipSpace(data, 0), sc)
	odjsonrt.PutStringCache(sc)
	if err != nil {
		return err
	}
	return odjsonrt.EndOfDocument(data, p)
}

// MarshalJSONTo implements encoding/json/v2.MarshalerTo.
func (v secret) MarshalJSONTo(enc *jsontext.Encoder) error {
	// Under a plain json.Marshal, from encoding/json/v2 or encoding/json,
	// the value is appended straight into the encoder's buffer at any
	// depth; see odjsonrt.BeginDirectEncodeMode for what qualifies and
	// for the mode, which does that call's escaping itself since nothing
	// downstream looks at the bytes.
	if buf, m, ok := odjsonrt.BeginDirectEncodeMode(enc); ok {
		n := len(buf)
		buf, err := v.odjsonAppend(buf, m)
		if err != nil {
			return err
		}
		odjsonSizesecret.Record(buf[n:])
		odjsonrt.EndDirectEncode(enc, buf)
		return nil
	}
	// Otherwise WriteValue copies what it is given, so the scratch buffer
	// can go straight back to the pool. ModeStream leaves the HTML escaping
	// and the UTF-8 validation to the encoder, which performs both while
	// reformatting the value either way.
	buf := odjsonrt.GetBuffer()
	var err error
	if buf.B, err = v.odjsonAppend(buf.B, odjsonrt.ModeStream); err == nil {
		odjsonSizesecret.Record(buf.B)
		err = enc.WriteValue(buf.B)
	}
	odjsonrt.PutBuffer(buf)
	return err
}

// UnmarshalJSONFrom implements encoding/json/v2.UnmarshalerFrom.
func (v *secret) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	// The cache plays the part of json/v2's own string cache: a value
	// that recurs in the document is allocated once.
	sc := odjsonrt.GetStringCache()
	var err error
	// Under a plain json.Unmarshal the value is parsed straight out of
	// the decoder's buffer at any depth; see odjsonrt.BeginDirectDecodeAt
	// for what qualifies. Nobody has validated those bytes, so
	// odjsonParseV2 rejects what jsontext would have.
	if data, p, ok := odjsonrt.BeginDirectDecodeAt(dec); ok {
		var end int
		if end, err = v.odjsonParseV2(data, p, sc, true); err == nil {
			odjsonrt.EndDirectDecodeAt(dec, p, end)
		}
	} else {
		err = v.odjsonParseFrom(dec, sc)
	}
	odjsonrt.PutStringCache(sc)
	return err
}

// odjsonAppend appends the JSON encoding of v to dst.
func (v *lone) odjsonAppend(dst []byte, m odjsonrt.StringMode) ([]byte, error) {
	var err error
	_ = err
	if bool(v.Flag) {
		dst = append(dst, "{\"flag\":true}"...)
	} else {
		dst = append(dst, "{\"flag\":false}"...)
	}
	return dst, nil
}

// odjsonParse decodes the JSON object starting at p into v and
// returns the offset just past it. Strings are interned through
// sc, which may be nil.
func (v *lone) odjsonParse(data []byte, p int, sc *odjsonrt.StringCache) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		return np, nil
	}
	if uint(p) >= uint(len(data)) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "lone")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if uint(p) < uint(len(data)) && data[p] == '}' {
		return p + 1, nil
	}
	for {
		if uint(p) >= uint(len(data)) || data[p] <= ' ' {
			p = odjsonrt.SkipSpace(data, odjsonrt.SkipIndent(data, p))
		}
		rest := data[p:]
		if len(rest) >= 6 && string(rest[:6]) == "\"flag\"" {
			p += 6
			if np := odjsonrt.AfterName(data, p); np > 0 {
				p = np
			} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
				return p, err
			}
			goto m29
		}
		{
			var key []byte
			key, _, p, err = odjsonrt.ParseKey(data, p)
			if err != nil {
				return p, err
			}
			switch string(key) {
			case "flag":
				goto m29
			}
			p = odjsonrt.SkipSpace(data, p)
			p, err = odjsonrt.SkipValue(data, p)
			if err != nil {
				return p, err
			}
			goto next30
		}
	m29:
		{
			if np31, ok32 := odjsonrt.ParseNull(data, p); ok32 {
				p = np31
			} else {
				if uint(p+4) <= uint(len(data)) && string(data[p:p+4]) == "true" {
					v.Flag = true
					p += 4
				} else if uint(p+5) <= uint(len(data)) && string(data[p:p+5]) == "false" {
					v.Flag = false
					p += 5
				} else {
					var x33 bool
					x33, p, err = odjsonrt.ParseBool(data, p)
					if err != nil {
						return p, err
					}
					v.Flag = x33
				}
			}
		}
	next30:
		{
			p = odjsonrt.SkipSpace(data, p)
			if uint(p) >= uint(len(data)) {
				return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
			}
			switch data[p] {
			case ',':
				p++
			case '}':
				return p + 1, nil
			default:
				return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
			}
		}
	}
}

// odjsonParseV2 is odjsonParse under encoding/json/v2's semantics, for
// input a jsontext.Decoder has already validated when strict is false,
// and for bytes nobody has looked at when it is true.
func (v *lone) odjsonParseV2(data []byte, p int, sc *odjsonrt.StringCache, strict bool) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		*v = lone{}
		return np, nil
	}
	if uint(p) >= uint(len(data)) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "lone")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if uint(p) < uint(len(data)) && data[p] == '}' {
		return p + 1, nil
	}
	var seen [1]uint64
	_ = seen
	unknown, umark := odjsonrt.UnknownNames(sc)
	var ufilter uint64
	_ = ufilter
	for {
		if uint(p) >= uint(len(data)) || data[p] <= ' ' {
			p = odjsonrt.SkipSpace(data, odjsonrt.SkipIndent(data, p))
		}
		kp := p
		rest := data[p:]
		if len(rest) >= 6 && string(rest[:6]) == "\"flag\"" {
			p += 6
			if np := odjsonrt.AfterName(data, p); np > 0 {
				p = np
			} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
				return p, err
			}
			goto m34
		}
		{
			var key []byte
			key, p, err = odjsonrt.ParseKeyV2(data, p, strict)
			if err != nil {
				return p, err
			}
			switch string(key) {
			case "flag":
				goto m34
			}
			if strict {
				var dup bool
				if unknown, dup = odjsonrt.UnknownName(sc, unknown, umark, &ufilter, key); dup {
					return kp, odjsonrt.ErrDuplicateName(data, kp, key)
				}
			}
			p = odjsonrt.SkipSpace(data, p)
			p, err = odjsonrt.SkipValueV2(data, p, strict)
			if err != nil {
				return p, err
			}
			goto next35
		}
	m34:
		{
			if strict && seen[0]&(1<<0) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 0
			if np36, ok37 := odjsonrt.ParseNull(data, p); ok37 {
				p = np36
				v.Flag = false
			} else {
				if uint(p+4) <= uint(len(data)) && string(data[p:p+4]) == "true" {
					v.Flag = true
					p += 4
				} else if uint(p+5) <= uint(len(data)) && string(data[p:p+5]) == "false" {
					v.Flag = false
					p += 5
				} else {
					var x38 bool
					x38, p, err = odjsonrt.ParseBool(data, p)
					if err != nil {
						return p, err
					}
					v.Flag = x38
				}
			}
		}
	next35:
		{
			p = odjsonrt.SkipSpace(data, p)
			if uint(p) >= uint(len(data)) {
				return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
			}
			switch data[p] {
			case ',':
				p++
			case '}':
				odjsonrt.EndUnknownNames(sc, unknown, umark)
				return p + 1, nil
			default:
				return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
			}
		}
	}
}

// odjsonParseFrom decodes the next value in dec into v,
// driving the decoder token by token so the document is
// parsed once rather than twice.
func (v *lone) odjsonParseFrom(dec *jsontext.Decoder, sc *odjsonrt.StringCache) error {
	var err error
	_ = err
	if odjsonrt.WholeValue(dec) {
		var val jsontext.Value
		if val, err = dec.ReadValue(); err != nil {
			return err
		}
		_, err = v.odjsonParseV2(val, 0, sc, false)
		return err
	}
	switch odjsonrt.NextKind(dec) {
	case 'n':
		if _, err = dec.ReadToken(); err != nil {
			return err
		}
		*v = lone{}
		return nil
	case '{':
	default:
		return odjsonrt.ErrKindFrom(dec, "lone")
	}
	if _, err = dec.ReadToken(); err != nil {
		return err
	}
	for odjsonrt.NextKind(dec) != '}' {
		var key jsontext.Value
		key, err = dec.ReadValue()
		if err != nil {
			return err
		}
		idx := -1
		switch string(key) {
		case "\"flag\"":
			idx = 0
		}
		if idx < 0 && bytes.IndexByte(key, '\\') >= 0 {
			if name, ok := odjsonrt.UnquoteName(key); ok {
				switch string(name) {
				case "flag":
					idx = 0
				}
			}
		}
		switch idx {
		case 0:
			var val39 jsontext.Value
			val39, err = dec.ReadValue()
			if err != nil {
				return err
			}
			if val39[0] == 'n' {
				v.Flag = false
			} else {
				var x40 bool
				x40, _, err = odjsonrt.ParseBool(val39, 0)
				if err != nil {
					return err
				}
				v.Flag = x40
			}
		default:
			if _, err = dec.ReadValue(); err != nil {
				return err
			}
		}
	}
	_, err = dec.ReadToken()
	return err
}

// odjsonSizelone sizes the buffer the encoders allocate.
var odjsonSizelone odjsonrt.SizeHint

// MarshalJSON implements encoding/json.Marshaler.
func (v lone) MarshalJSON() ([]byte, error) {
	buf, err := v.odjsonAppend(odjsonSizelone.New(), odjsonrt.ModeHTML)
	if err != nil {
		return nil, err
	}
	odjsonSizelone.Record(buf)
	return buf, nil
}

// UnmarshalJSON implements encoding/json.Unmarshaler.
func (v *lone) UnmarshalJSON(data []byte) error {
	// The cache plays the part of encoding/json/v2's string cache: a
	// value that recurs in the document is allocated once.
	sc := odjsonrt.GetStringCache()
	p, err := v.odjsonParse(data, odjsonrt.SkipSpace(data, 0), sc)
	odjsonrt.PutStringCache(sc)
	if err != nil {
		return err
	}
	return odjsonrt.EndOfDocument(data, p)
}

// MarshalJSONTo implements encoding/json/v2.MarshalerTo.
func (v lone) MarshalJSONTo(enc *jsontext.Encoder) error {
	// Under a plain json.Marshal, from encoding/json/v2 or encoding/json,
	// the value is appended straight into the encoder's buffer at any
	// depth; see odjsonrt.BeginDirectEncodeMode for what qualifies and
	// for the mode, which does that call's escaping itself since nothing
	// downstream looks at the bytes.
	if buf, m, ok := odjsonrt.BeginDirectEncodeMode(enc); ok {
		n := len(buf)
		buf, err := v.odjsonAppend(buf, m)
		if err != nil {
			return err
		}
		odjsonSizelone.Record(buf[n:])
		odjsonrt.EndDirectEncode(enc, buf)
		return nil
	}
	// Otherwise WriteValue copies what it is given, so the scratch buffer
	// can go straight back to the pool. ModeStream leaves the HTML escaping
	// and the UTF-8 validation to the encoder, which performs both while
	// reformatting the value either way.
	buf := odjsonrt.GetBuffer()
	var err error
	if buf.B, err = v.odjsonAppend(buf.B, odjsonrt.ModeStream); err == nil {
		odjsonSizelone.Record(buf.B)
		err = enc.WriteValue(buf.B)
	}
	odjsonrt.PutBuffer(buf)
	return err
}

// UnmarshalJSONFrom implements encoding/json/v2.UnmarshalerFrom.
func (v *lone) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	// The cache plays the part of json/v2's own string cache: a value
	// that recurs in the document is allocated once.
	sc := odjsonrt.GetStringCache()
	var err error
	// Under a plain json.Unmarshal the value is parsed straight out of
	// the decoder's buffer at any depth; see odjsonrt.BeginDirectDecodeAt
	// for what qualifies. Nobody has validated those bytes, so
	// odjsonParseV2 rejects what jsontext would have.
	if data, p, ok := odjsonrt.BeginDirectDecodeAt(dec); ok {
		var end int
		if end, err = v.odjsonParseV2(data, p, sc, true); err == nil {
			odjsonrt.EndDirectDecodeAt(dec, p, end)
		}
	} else {
		err = v.odjsonParseFrom(dec, sc)
	}
	odjsonrt.PutStringCache(sc)
	return err
}

// odjsonAppend appends the JSON encoding of v to dst.
func (v *Holder) odjsonAppend(dst []byte, m odjsonrt.StringMode) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, "{\"secret\":"...)
	dst, err = v.Secret.odjsonAppend(dst, m)
	if err != nil {
		return nil, err
	}
	if v.Ptr == nil {
		dst = append(dst, ",\"ptr\":null,\"lis"...)
		dst = append(dst, "t\":"...)
	} else {
		dst = append(dst, ",\"ptr\":"...)
		dst, err = (*v.Ptr).odjsonAppend(dst, m)
		if err != nil {
			return nil, err
		}
		dst = append(dst, ",\"list\":"...)
	}
	if v.List == nil {
		if m.V2() {
			dst = append(dst, "[]}"...)
		} else {
			dst = append(dst, "null}"...)
		}
	} else {
		dst = append(dst, "["...)
		for i41 := range v.List {
			if i41 > 0 {
				dst = append(dst, ',')
			}
			dst, err = v.List[i41].odjsonAppend(dst, m)
			if err != nil {
				return nil, err
			}
		}
		dst = append(dst, "]}"...)
	}
	return dst, nil
}

// odjsonCapHolderList remembers how long v.List has been, to allocate it once.
var odjsonCapHolderList odjsonrt.CapHint

// odjsonParse decodes the JSON object starting at p into v and
// returns the offset just past it. Strings are interned through
// sc, which may be nil.
func (v *Holder) odjsonParse(data []byte, p int, sc *odjsonrt.StringCache) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		return np, nil
	}
	if uint(p) >= uint(len(data)) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "Holder")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if uint(p) < uint(len(data)) && data[p] == '}' {
		return p + 1, nil
	}
	for {
		if uint(p) >= uint(len(data)) || data[p] <= ' ' {
			p = odjsonrt.SkipSpace(data, odjsonrt.SkipIndent(data, p))
		}
		rest := data[p:]
		if len(rest) > 1 {
			switch rest[1] {
			case 's':
				if len(rest) >= 8 && string(rest[:8]) == "\"secret\"" {
					p += 8
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m42
				}
			case 'p':
				if len(rest) >= 5 && string(rest[:5]) == "\"ptr\"" {
					p += 5
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m43
				}
			case 'l':
				if len(rest) >= 6 && string(rest[:6]) == "\"list\"" {
					p += 6
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m44
				}
			}
		}
		{
			var key []byte
			key, _, p, err = odjsonrt.ParseKey(data, p)
			if err != nil {
				return p, err
			}
			switch string(key) {
			case "secret":
				goto m42
			case "ptr":
				goto m43
			case "list":
				goto m44
			}
			p = odjsonrt.SkipSpace(data, p)
			p, err = odjsonrt.SkipValue(data, p)
			if err != nil {
				return p, err
			}
			goto next45
		}
	m42:
		{
			p, err = v.Secret.odjsonParse(data, p, sc)
			if err != nil {
				return p, err
			}
			goto next45
		}
	m43:
		{
			if np46, ok47 := odjsonrt.ParseNull(data, p); ok47 {
				v.Ptr = nil
				p = np46
			} else {
				if v.Ptr == nil {
					v.Ptr = new(secret)
				}
				p, err = (*v.Ptr).odjsonParse(data, p, sc)
				if err != nil {
					return p, err
				}
			}
			goto next45
		}
	m44:
		{
			if np48, ok49 := odjsonrt.ParseNull(data, p); ok49 {
				p = np48
				v.List = nil
			} else {
				if uint(p) >= uint(len(data)) || data[p] != '[' {
					return p, odjsonrt.ErrType(data, p, "[]secret")
				}
				p++
				s50 := v.List[:0]
				p = odjsonrt.SkipSpace(data, p)
				if uint(p) < uint(len(data)) && data[p] == ']' {
					p++
				} else {
					if cap(s50) == 0 {
						s50 = make([]secret, 0, odjsonrt.CapFor[secret](&odjsonCapHolderList))
					}
					for {
						var e51 secret
						if uint(p) >= uint(len(data)) || data[p] <= ' ' {
							p = odjsonrt.SkipSpace(data, odjsonrt.SkipIndent(data, p))
						}
						p, err = e51.odjsonParse(data, p, sc)
						if err != nil {
							return p, err
						}
						s50 = append(s50, e51)
						p = odjsonrt.SkipSpace(data, p)
						if uint(p) >= uint(len(data)) {
							return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
						}
						if data[p] == ',' {
							p++
							continue
						}
						if data[p] == ']' {
							p++
							break
						}
						return p, odjsonrt.ErrSyntax(data, p, "after array element")
					}
					odjsonCapHolderList.Record(len(s50))
				}
				if s50 == nil {
					s50 = []secret{}
				}
				v.List = s50
			}
		}
	next45:
		{
			p = odjsonrt.SkipSpace(data, p)
			if uint(p) >= uint(len(data)) {
				return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
			}
			switch data[p] {
			case ',':
				p++
			case '}':
				return p + 1, nil
			default:
				return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
			}
		}
	}
}

// odjsonParseV2 is odjsonParse under encoding/json/v2's semantics, for
// input a jsontext.Decoder has already validated when strict is false,
// and for bytes nobody has looked at when it is true.
func (v *Holder) odjsonParseV2(data []byte, p int, sc *odjsonrt.StringCache, strict bool) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		*v = Holder{}
		return np, nil
	}
	if uint(p) >= uint(len(data)) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "Holder")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if uint(p) < uint(len(data)) && data[p] == '}' {
		return p + 1, nil
	}
	var seen [1]uint64
	_ = seen
	unknown, umark := odjsonrt.UnknownNames(sc)
	var ufilter uint64
	_ = ufilter
	for {
		if uint(p) >= uint(len(data)) || data[p] <= ' ' {
			p = odjsonrt.SkipSpace(data, odjsonrt.SkipIndent(data, p))
		}
		kp := p
		rest := data[p:]
		if len(rest) > 1 {
			switch rest[1] {
			case 's':
				if len(rest) >= 8 && string(rest[:8]) == "\"secret\"" {
					p += 8
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m52
				}
			case 'p':
				if len(rest) >= 5 && string(rest[:5]) == "\"ptr\"" {
					p += 5
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m53
				}
			case 'l':
				if len(rest) >= 6 && string(rest[:6]) == "\"list\"" {
					p += 6
					if np := odjsonrt.AfterName(data, p); np > 0 {
						p = np
					} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
						return p, err
					}
					goto m54
				}
			}
		}
		{
			var key []byte
			key, p, err = odjsonrt.ParseKeyV2(data, p, strict)
			if err != nil {
				return p, err
			}
			switch string(key) {
			case "secret":
				goto m52
			case "ptr":
				goto m53
			case "list":
				goto m54
			}
			if strict {
				var dup bool
				if unknown, dup = odjsonrt.UnknownName(sc, unknown, umark, &ufilter, key); dup {
					return kp, odjsonrt.ErrDuplicateName(data, kp, key)
				}
			}
			p = odjsonrt.SkipSpace(data, p)
			p, err = odjsonrt.SkipValueV2(data, p, strict)
			if err != nil {
				return p, err
			}
			goto next55
		}
	m52:
		{
			if strict && seen[0]&(1<<0) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 0
			p, err = v.Secret.odjsonParseV2(data, p, sc, strict)
			if err != nil {
				return p, err
			}
			goto next55
		}
	m53:
		{
			if strict && seen[0]&(1<<1) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 1
			if np56, ok57 := odjsonrt.ParseNull(data, p); ok57 {
				v.Ptr = nil
				p = np56
			} else {
				if v.Ptr == nil {
					v.Ptr = new(secret)
				}
				p, err = (*v.Ptr).odjsonParseV2(data, p, sc, strict)
				if err != nil {
					return p, err
				}
			}
			goto next55
		}
	m54:
		{
			if strict && seen[0]&(1<<2) != 0 {
				return kp, odjsonrt.ErrDuplicateNameAt(data, kp)
			}
			seen[0] |= 1 << 2
			if np58, ok59 := odjsonrt.ParseNull(data, p); ok59 {
				p = np58
				v.List = nil
			} else {
				if uint(p) >= uint(len(data)) || data[p] != '[' {
					return p, odjsonrt.ErrType(data, p, "[]secret")
				}
				p++
				s60 := v.List[:0]
				p = odjsonrt.SkipSpace(data, p)
				if uint(p) < uint(len(data)) && data[p] == ']' {
					p++
				} else {
					if cap(s60) == 0 {
						s60 = make([]secret, 0, odjsonrt.CapFor[secret](&odjsonCapHolderList))
					}
					for {
						var e61 secret
						if uint(p) >= uint(len(data)) || data[p] <= ' ' {
							p = odjsonrt.SkipSpace(data, odjsonrt.SkipIndent(data, p))
						}
						p, err = e61.odjsonParseV2(data, p, sc, strict)
						if err != nil {
							return p, err
						}
						s60 = append(s60, e61)
						p = odjsonrt.SkipSpace(data, p)
						if uint(p) >= uint(len(data)) {
							return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
						}
						if data[p] == ',' {
							p++
							continue
						}
						if data[p] == ']' {
							p++
							break
						}
						return p, odjsonrt.ErrSyntax(data, p, "after array element")
					}
					odjsonCapHolderList.Record(len(s60))
				}
				if s60 == nil {
					s60 = []secret{}
				}
				v.List = s60
			}
		}
	next55:
		{
			p = odjsonrt.SkipSpace(data, p)
			if uint(p) >= uint(len(data)) {
				return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
			}
			switch data[p] {
			case ',':
				p++
			case '}':
				odjsonrt.EndUnknownNames(sc, unknown, umark)
				return p + 1, nil
			default:
				return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
			}
		}
	}
}

// odjsonParseFrom decodes the next value in dec into v,
// driving the decoder token by token so the document is
// parsed once rather than twice.
func (v *Holder) odjsonParseFrom(dec *jsontext.Decoder, sc *odjsonrt.StringCache) error {
	var err error
	_ = err
	if odjsonrt.WholeValue(dec) {
		var val jsontext.Value
		if val, err = dec.ReadValue(); err != nil {
			return err
		}
		_, err = v.odjsonParseV2(val, 0, sc, false)
		return err
	}
	switch odjsonrt.NextKind(dec) {
	case 'n':
		if _, err = dec.ReadToken(); err != nil {
			return err
		}
		*v = Holder{}
		return nil
	case '{':
	default:
		return odjsonrt.ErrKindFrom(dec, "Holder")
	}
	if _, err = dec.ReadToken(); err != nil {
		return err
	}
	for odjsonrt.NextKind(dec) != '}' {
		var key jsontext.Value
		key, err = dec.ReadValue()
		if err != nil {
			return err
		}
		idx := -1
		switch string(key) {
		case "\"secret\"":
			idx = 0
		case "\"ptr\"":
			idx = 1
		case "\"list\"":
			idx = 2
		}
		if idx < 0 && bytes.IndexByte(key, '\\') >= 0 {
			if name, ok := odjsonrt.UnquoteName(key); ok {
				switch string(name) {
				case "secret":
					idx = 0
				case "ptr":
					idx = 1
				case "list":
					idx = 2
				}
			}
		}
		switch idx {
		case 0:
			if err = v.Secret.odjsonParseFrom(dec, sc); err != nil {
				return err
			}
		case 1:
			if odjsonrt.NextKind(dec) == 'n' {
				if _, err = dec.ReadToken(); err != nil {
					return err
				}
				v.Ptr = nil
			} else {
				if v.Ptr == nil {
					v.Ptr = new(secret)
				}
				if err = (*v.Ptr).odjsonParseFrom(dec, sc); err != nil {
					return err
				}
			}
		case 2:
			switch odjsonrt.NextKind(dec) {
			case 'n':
				if _, err = dec.ReadToken(); err != nil {
					return err
				}
				v.List = nil
			case '[':
				if _, err = dec.ReadToken(); err != nil {
					return err
				}
				s62 := v.List[:0]
				if odjsonrt.NextKind(dec) != ']' && cap(s62) == 0 {
					s62 = make([]secret, 0, odjsonrt.CapFor[secret](&odjsonCapHolderList))
				}
				for odjsonrt.NextKind(dec) != ']' {
					var e63 secret
					if err = e63.odjsonParseFrom(dec, sc); err != nil {
						return err
					}
					s62 = append(s62, e63)
				}
				if _, err = dec.ReadToken(); err != nil {
					return err
				}
				if len(s62) > 0 {
					odjsonCapHolderList.Record(len(s62))
				}
				if s62 == nil {
					s62 = []secret{}
				}
				v.List = s62
			default:
				return odjsonrt.ErrKindFrom(dec, "[]secret")
			}
		default:
			if _, err = dec.ReadValue(); err != nil {
				return err
			}
		}
	}
	_, err = dec.ReadToken()
	return err
}

// odjsonSizeHolder sizes the buffer the encoders allocate.
var odjsonSizeHolder odjsonrt.SizeHint

// MarshalJSON implements encoding/json.Marshaler.
func (v Holder) MarshalJSON() ([]byte, error) {
	buf, err := v.odjsonAppend(odjsonSizeHolder.New(), odjsonrt.ModeHTML)
	if err != nil {
		return nil, err
	}
	odjsonSizeHolder.Record(buf)
	return buf, nil
}

// UnmarshalJSON implements encoding/json.Unmarshaler.
func (v *Holder) UnmarshalJSON(data []byte) error {
	// The cache plays the part of encoding/json/v2's string cache: a
	// value that recurs in the document is allocated once.
	sc := odjsonrt.GetStringCache()
	p, err := v.odjsonParse(data, odjsonrt.SkipSpace(data, 0), sc)
	odjsonrt.PutStringCache(sc)
	if err != nil {
		return err
	}
	return odjsonrt.EndOfDocument(data, p)
}

// MarshalJSONTo implements encoding/json/v2.MarshalerTo.
func (v Holder) MarshalJSONTo(enc *jsontext.Encoder) error {
	// Under a plain json.Marshal, from encoding/json/v2 or encoding/json,
	// the value is appended straight into the encoder's buffer at any
	// depth; see odjsonrt.BeginDirectEncodeMode for what qualifies and
	// for the mode, which does that call's escaping itself since nothing
	// downstream looks at the bytes.
	if buf, m, ok := odjsonrt.BeginDirectEncodeMode(enc); ok {
		n := len(buf)
		buf, err := v.odjsonAppend(buf, m)
		if err != nil {
			return err
		}
		odjsonSizeHolder.Record(buf[n:])
		odjsonrt.EndDirectEncode(enc, buf)
		return nil
	}
	// Otherwise WriteValue copies what it is given, so the scratch buffer
	// can go straight back to the pool. ModeStream leaves the HTML escaping
	// and the UTF-8 validation to the encoder, which performs both while
	// reformatting the value either way.
	buf := odjsonrt.GetBuffer()
	var err error
	if buf.B, err = v.odjsonAppend(buf.B, odjsonrt.ModeStream); err == nil {
		odjsonSizeHolder.Record(buf.B)
		err = enc.WriteValue(buf.B)
	}
	odjsonrt.PutBuffer(buf)
	return err
}

// UnmarshalJSONFrom implements encoding/json/v2.UnmarshalerFrom.
func (v *Holder) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	// The cache plays the part of json/v2's own string cache: a value
	// that recurs in the document is allocated once.
	sc := odjsonrt.GetStringCache()
	var err error
	// Under a plain json.Unmarshal the value is parsed straight out of
	// the decoder's buffer at any depth; see odjsonrt.BeginDirectDecodeAt
	// for what qualifies. Nobody has validated those bytes, so
	// odjsonParseV2 rejects what jsontext would have.
	if data, p, ok := odjsonrt.BeginDirectDecodeAt(dec); ok {
		var end int
		if end, err = v.odjsonParseV2(data, p, sc, true); err == nil {
			odjsonrt.EndDirectDecodeAt(dec, p, end)
		}
	} else {
		err = v.odjsonParseFrom(dec, sc)
	}
	odjsonrt.PutStringCache(sc)
	return err
}
