// Code generated by odjson. DO NOT EDIT.
//
// Source: odjson

package embed

import (
	"github.com/mazrean/odjson/odjsonrt"
)

// odjsonAppend appends the JSON encoding of v to dst.
func (v *Deep) odjsonAppend(dst []byte, m odjsonrt.StringMode) ([]byte, error) {
	var err error
	_ = err
	start := len(dst)
	dst = append(dst, ",\"deep_only\":"...)
	dst, err = odjsonrt.AppendStringChecked(dst, string(v.DeepOnly), m)
	if err != nil {
		return nil, err
	}
	dst = append(dst, ",\"shared\":"...)
	dst, err = odjsonrt.AppendStringChecked(dst, string(v.Shared), m)
	if err != nil {
		return nil, err
	}
	if len(dst) == start {
		dst = append(dst, '{', '}')
	} else {
		dst[start] = '{'
		dst = append(dst, '}')
	}
	return dst, nil
}

// odjsonParse decodes the JSON object starting at p into v and
// returns the offset just past it. Strings are interned through
// sc, which may be nil.
func (v *Deep) odjsonParse(data []byte, p int, sc *odjsonrt.StringCache) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		return np, nil
	}
	if p >= len(data) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "Deep")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if p < len(data) && data[p] == '}' {
		return p + 1, nil
	}
	for {
		var key []byte
		p = odjsonrt.SkipSpace(data, p)
		idx := -1
		if rest := data[p:]; len(rest) > 1 {
			switch rest[1] {
			case 'd':
				switch {
				case len(rest) >= 11 && string(rest[:11]) == "\"deep_only\"":
					idx, p = 0, p+11
				}
			case 's':
				switch {
				case len(rest) >= 8 && string(rest[:8]) == "\"shared\"":
					idx, p = 1, p+8
				}
			}
		}
		if idx >= 0 {
			if p < len(data) && data[p] == ':' {
				p = odjsonrt.SkipSpace(data, p+1)
			} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
				return p, err
			}
		} else {
			key, _, p, err = odjsonrt.ParseKey(data, p)
			if err != nil {
				return p, err
			}
			switch string(key) {
			case "deep_only":
				idx = 0
			case "shared":
				idx = 1
			}
			if idx < 0 {
				fold := !odjsonrt.ASCII(key)
				switch {
				case (len(key) == 9 || fold) && odjsonrt.EqualFold(key, "deep_only"):
					idx = 0
				case (len(key) == 6 || fold) && odjsonrt.EqualFold(key, "shared"):
					idx = 1
				}
			}
		}
		switch idx {
		case 0:
			if np1, ok2 := odjsonrt.ParseNull(data, p); ok2 {
				p = np1
			} else {
				var x3 string
				x3, p, err = odjsonrt.ParseStringCached(data, p, sc)
				if err != nil {
					return p, err
				}
				v.DeepOnly = x3
			}
		case 1:
			if np4, ok5 := odjsonrt.ParseNull(data, p); ok5 {
				p = np4
			} else {
				var x6 string
				x6, p, err = odjsonrt.ParseStringCached(data, p, sc)
				if err != nil {
					return p, err
				}
				v.Shared = x6
			}
		default:
			p = odjsonrt.SkipSpace(data, p)
			p, err = odjsonrt.SkipValue(data, p)
			if err != nil {
				return p, err
			}
		}
		p = odjsonrt.SkipSpace(data, p)
		if p >= len(data) {
			return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
		}
		switch data[p] {
		case ',':
			p++
		case '}':
			return p + 1, nil
		default:
			return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
		}
	}
}

// AppendDeep appends the JSON encoding of v to dst.
func AppendDeep(dst []byte, v *Deep) ([]byte, error) {
	return v.odjsonAppend(dst, odjsonrt.ModeHTML)
}

// odjsonSizeDeep sizes the buffer MarshalDeep allocates.
var odjsonSizeDeep odjsonrt.SizeHint

// MarshalDeep returns the JSON encoding of v.
func MarshalDeep(v *Deep) ([]byte, error) {
	buf, err := v.odjsonAppend(odjsonSizeDeep.New(), odjsonrt.ModeHTML)
	if err != nil {
		return nil, err
	}
	odjsonSizeDeep.Record(buf)
	return buf, nil
}

// UnmarshalDeep decodes the JSON document data into v.
func UnmarshalDeep(data []byte, v *Deep) error {
	// The cache plays the part of encoding/json/v2's string cache: a
	// value that recurs in the document is allocated once.
	sc := odjsonrt.GetStringCache()
	p, err := v.odjsonParse(data, odjsonrt.SkipSpace(data, 0), sc)
	odjsonrt.PutStringCache(sc)
	if err != nil {
		return err
	}
	return odjsonrt.EndOfDocument(data, p)
}

// odjsonAppend appends the JSON encoding of v to dst.
func (v *Mid) odjsonAppend(dst []byte, m odjsonrt.StringMode) ([]byte, error) {
	var err error
	_ = err
	start := len(dst)
	dst = append(dst, ",\"deep_only\":"...)
	dst, err = odjsonrt.AppendStringChecked(dst, string(v.Deep.DeepOnly), m)
	if err != nil {
		return nil, err
	}
	dst = append(dst, ",\"shared\":"...)
	dst, err = odjsonrt.AppendStringChecked(dst, string(v.Shared), m)
	if err != nil {
		return nil, err
	}
	dst = append(dst, ",\"mid_only\":"...)
	dst = odjsonrt.AppendInt(dst, int64(v.MidOnly))
	if len(dst) == start {
		dst = append(dst, '{', '}')
	} else {
		dst[start] = '{'
		dst = append(dst, '}')
	}
	return dst, nil
}

// odjsonParse decodes the JSON object starting at p into v and
// returns the offset just past it. Strings are interned through
// sc, which may be nil.
func (v *Mid) odjsonParse(data []byte, p int, sc *odjsonrt.StringCache) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		return np, nil
	}
	if p >= len(data) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "Mid")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if p < len(data) && data[p] == '}' {
		return p + 1, nil
	}
	for {
		var key []byte
		p = odjsonrt.SkipSpace(data, p)
		idx := -1
		if rest := data[p:]; len(rest) > 1 {
			switch rest[1] {
			case 'd':
				switch {
				case len(rest) >= 11 && string(rest[:11]) == "\"deep_only\"":
					idx, p = 0, p+11
				}
			case 's':
				switch {
				case len(rest) >= 8 && string(rest[:8]) == "\"shared\"":
					idx, p = 1, p+8
				}
			case 'm':
				switch {
				case len(rest) >= 10 && string(rest[:10]) == "\"mid_only\"":
					idx, p = 2, p+10
				}
			}
		}
		if idx >= 0 {
			if p < len(data) && data[p] == ':' {
				p = odjsonrt.SkipSpace(data, p+1)
			} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
				return p, err
			}
		} else {
			key, _, p, err = odjsonrt.ParseKey(data, p)
			if err != nil {
				return p, err
			}
			switch string(key) {
			case "deep_only":
				idx = 0
			case "shared":
				idx = 1
			case "mid_only":
				idx = 2
			}
			if idx < 0 {
				fold := !odjsonrt.ASCII(key)
				switch {
				case (len(key) == 9 || fold) && odjsonrt.EqualFold(key, "deep_only"):
					idx = 0
				case (len(key) == 6 || fold) && odjsonrt.EqualFold(key, "shared"):
					idx = 1
				case (len(key) == 8 || fold) && odjsonrt.EqualFold(key, "mid_only"):
					idx = 2
				}
			}
		}
		switch idx {
		case 0:
			if np7, ok8 := odjsonrt.ParseNull(data, p); ok8 {
				p = np7
			} else {
				var x9 string
				x9, p, err = odjsonrt.ParseStringCached(data, p, sc)
				if err != nil {
					return p, err
				}
				v.Deep.DeepOnly = x9
			}
		case 1:
			if np10, ok11 := odjsonrt.ParseNull(data, p); ok11 {
				p = np10
			} else {
				var x12 string
				x12, p, err = odjsonrt.ParseStringCached(data, p, sc)
				if err != nil {
					return p, err
				}
				v.Shared = x12
			}
		case 2:
			if np13, ok14 := odjsonrt.ParseNull(data, p); ok14 {
				p = np13
			} else {
				if x15, np16, ok17 := odjsonrt.ParseDecimal(data, p); ok17 {
					v.MidOnly = int(x15)
					p = np16
				} else {
					var x18 int64
					x18, p, err = odjsonrt.ParseInt(data, p, 64)
					if err != nil {
						return p, err
					}
					v.MidOnly = int(x18)
				}
			}
		default:
			p = odjsonrt.SkipSpace(data, p)
			p, err = odjsonrt.SkipValue(data, p)
			if err != nil {
				return p, err
			}
		}
		p = odjsonrt.SkipSpace(data, p)
		if p >= len(data) {
			return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
		}
		switch data[p] {
		case ',':
			p++
		case '}':
			return p + 1, nil
		default:
			return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
		}
	}
}

// AppendMid appends the JSON encoding of v to dst.
func AppendMid(dst []byte, v *Mid) ([]byte, error) {
	return v.odjsonAppend(dst, odjsonrt.ModeHTML)
}

// odjsonSizeMid sizes the buffer MarshalMid allocates.
var odjsonSizeMid odjsonrt.SizeHint

// MarshalMid returns the JSON encoding of v.
func MarshalMid(v *Mid) ([]byte, error) {
	buf, err := v.odjsonAppend(odjsonSizeMid.New(), odjsonrt.ModeHTML)
	if err != nil {
		return nil, err
	}
	odjsonSizeMid.Record(buf)
	return buf, nil
}

// UnmarshalMid decodes the JSON document data into v.
func UnmarshalMid(data []byte, v *Mid) error {
	// The cache plays the part of encoding/json/v2's string cache: a
	// value that recurs in the document is allocated once.
	sc := odjsonrt.GetStringCache()
	p, err := v.odjsonParse(data, odjsonrt.SkipSpace(data, 0), sc)
	odjsonrt.PutStringCache(sc)
	if err != nil {
		return err
	}
	return odjsonrt.EndOfDocument(data, p)
}

// odjsonAppend appends the JSON encoding of v to dst.
func (v *LeftConflict) odjsonAppend(dst []byte, m odjsonrt.StringMode) ([]byte, error) {
	var err error
	_ = err
	start := len(dst)
	dst = append(dst, ",\"Clash\":"...)
	dst, err = odjsonrt.AppendStringChecked(dst, string(v.Clash), m)
	if err != nil {
		return nil, err
	}
	dst = append(dst, ",\"left\":"...)
	dst, err = odjsonrt.AppendStringChecked(dst, string(v.Left), m)
	if err != nil {
		return nil, err
	}
	if len(dst) == start {
		dst = append(dst, '{', '}')
	} else {
		dst[start] = '{'
		dst = append(dst, '}')
	}
	return dst, nil
}

// odjsonParse decodes the JSON object starting at p into v and
// returns the offset just past it. Strings are interned through
// sc, which may be nil.
func (v *LeftConflict) odjsonParse(data []byte, p int, sc *odjsonrt.StringCache) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		return np, nil
	}
	if p >= len(data) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "LeftConflict")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if p < len(data) && data[p] == '}' {
		return p + 1, nil
	}
	for {
		var key []byte
		p = odjsonrt.SkipSpace(data, p)
		idx := -1
		if rest := data[p:]; len(rest) > 1 {
			switch rest[1] {
			case 'C':
				switch {
				case len(rest) >= 7 && string(rest[:7]) == "\"Clash\"":
					idx, p = 0, p+7
				}
			case 'l':
				switch {
				case len(rest) >= 6 && string(rest[:6]) == "\"left\"":
					idx, p = 1, p+6
				}
			}
		}
		if idx >= 0 {
			if p < len(data) && data[p] == ':' {
				p = odjsonrt.SkipSpace(data, p+1)
			} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
				return p, err
			}
		} else {
			key, _, p, err = odjsonrt.ParseKey(data, p)
			if err != nil {
				return p, err
			}
			switch string(key) {
			case "Clash":
				idx = 0
			case "left":
				idx = 1
			}
			if idx < 0 {
				fold := !odjsonrt.ASCII(key)
				switch {
				case (len(key) == 5 || fold) && odjsonrt.EqualFold(key, "Clash"):
					idx = 0
				case (len(key) == 4 || fold) && odjsonrt.EqualFold(key, "left"):
					idx = 1
				}
			}
		}
		switch idx {
		case 0:
			if np19, ok20 := odjsonrt.ParseNull(data, p); ok20 {
				p = np19
			} else {
				var x21 string
				x21, p, err = odjsonrt.ParseStringCached(data, p, sc)
				if err != nil {
					return p, err
				}
				v.Clash = x21
			}
		case 1:
			if np22, ok23 := odjsonrt.ParseNull(data, p); ok23 {
				p = np22
			} else {
				var x24 string
				x24, p, err = odjsonrt.ParseStringCached(data, p, sc)
				if err != nil {
					return p, err
				}
				v.Left = x24
			}
		default:
			p = odjsonrt.SkipSpace(data, p)
			p, err = odjsonrt.SkipValue(data, p)
			if err != nil {
				return p, err
			}
		}
		p = odjsonrt.SkipSpace(data, p)
		if p >= len(data) {
			return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
		}
		switch data[p] {
		case ',':
			p++
		case '}':
			return p + 1, nil
		default:
			return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
		}
	}
}

// AppendLeftConflict appends the JSON encoding of v to dst.
func AppendLeftConflict(dst []byte, v *LeftConflict) ([]byte, error) {
	return v.odjsonAppend(dst, odjsonrt.ModeHTML)
}

// odjsonSizeLeftConflict sizes the buffer MarshalLeftConflict allocates.
var odjsonSizeLeftConflict odjsonrt.SizeHint

// MarshalLeftConflict returns the JSON encoding of v.
func MarshalLeftConflict(v *LeftConflict) ([]byte, error) {
	buf, err := v.odjsonAppend(odjsonSizeLeftConflict.New(), odjsonrt.ModeHTML)
	if err != nil {
		return nil, err
	}
	odjsonSizeLeftConflict.Record(buf)
	return buf, nil
}

// UnmarshalLeftConflict decodes the JSON document data into v.
func UnmarshalLeftConflict(data []byte, v *LeftConflict) error {
	// The cache plays the part of encoding/json/v2's string cache: a
	// value that recurs in the document is allocated once.
	sc := odjsonrt.GetStringCache()
	p, err := v.odjsonParse(data, odjsonrt.SkipSpace(data, 0), sc)
	odjsonrt.PutStringCache(sc)
	if err != nil {
		return err
	}
	return odjsonrt.EndOfDocument(data, p)
}

// odjsonAppend appends the JSON encoding of v to dst.
func (v *RightConflict) odjsonAppend(dst []byte, m odjsonrt.StringMode) ([]byte, error) {
	var err error
	_ = err
	start := len(dst)
	dst = append(dst, ",\"Clash\":"...)
	dst, err = odjsonrt.AppendStringChecked(dst, string(v.Clash), m)
	if err != nil {
		return nil, err
	}
	dst = append(dst, ",\"right\":"...)
	dst, err = odjsonrt.AppendStringChecked(dst, string(v.Right), m)
	if err != nil {
		return nil, err
	}
	if len(dst) == start {
		dst = append(dst, '{', '}')
	} else {
		dst[start] = '{'
		dst = append(dst, '}')
	}
	return dst, nil
}

// odjsonParse decodes the JSON object starting at p into v and
// returns the offset just past it. Strings are interned through
// sc, which may be nil.
func (v *RightConflict) odjsonParse(data []byte, p int, sc *odjsonrt.StringCache) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		return np, nil
	}
	if p >= len(data) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "RightConflict")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if p < len(data) && data[p] == '}' {
		return p + 1, nil
	}
	for {
		var key []byte
		p = odjsonrt.SkipSpace(data, p)
		idx := -1
		if rest := data[p:]; len(rest) > 1 {
			switch rest[1] {
			case 'C':
				switch {
				case len(rest) >= 7 && string(rest[:7]) == "\"Clash\"":
					idx, p = 0, p+7
				}
			case 'r':
				switch {
				case len(rest) >= 7 && string(rest[:7]) == "\"right\"":
					idx, p = 1, p+7
				}
			}
		}
		if idx >= 0 {
			if p < len(data) && data[p] == ':' {
				p = odjsonrt.SkipSpace(data, p+1)
			} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
				return p, err
			}
		} else {
			key, _, p, err = odjsonrt.ParseKey(data, p)
			if err != nil {
				return p, err
			}
			switch string(key) {
			case "Clash":
				idx = 0
			case "right":
				idx = 1
			}
			if idx < 0 {
				fold := !odjsonrt.ASCII(key)
				switch {
				case (len(key) == 5 || fold) && odjsonrt.EqualFold(key, "Clash"):
					idx = 0
				case (len(key) == 5 || fold) && odjsonrt.EqualFold(key, "right"):
					idx = 1
				}
			}
		}
		switch idx {
		case 0:
			if np25, ok26 := odjsonrt.ParseNull(data, p); ok26 {
				p = np25
			} else {
				var x27 string
				x27, p, err = odjsonrt.ParseStringCached(data, p, sc)
				if err != nil {
					return p, err
				}
				v.Clash = x27
			}
		case 1:
			if np28, ok29 := odjsonrt.ParseNull(data, p); ok29 {
				p = np28
			} else {
				var x30 string
				x30, p, err = odjsonrt.ParseStringCached(data, p, sc)
				if err != nil {
					return p, err
				}
				v.Right = x30
			}
		default:
			p = odjsonrt.SkipSpace(data, p)
			p, err = odjsonrt.SkipValue(data, p)
			if err != nil {
				return p, err
			}
		}
		p = odjsonrt.SkipSpace(data, p)
		if p >= len(data) {
			return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
		}
		switch data[p] {
		case ',':
			p++
		case '}':
			return p + 1, nil
		default:
			return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
		}
	}
}

// AppendRightConflict appends the JSON encoding of v to dst.
func AppendRightConflict(dst []byte, v *RightConflict) ([]byte, error) {
	return v.odjsonAppend(dst, odjsonrt.ModeHTML)
}

// odjsonSizeRightConflict sizes the buffer MarshalRightConflict allocates.
var odjsonSizeRightConflict odjsonrt.SizeHint

// MarshalRightConflict returns the JSON encoding of v.
func MarshalRightConflict(v *RightConflict) ([]byte, error) {
	buf, err := v.odjsonAppend(odjsonSizeRightConflict.New(), odjsonrt.ModeHTML)
	if err != nil {
		return nil, err
	}
	odjsonSizeRightConflict.Record(buf)
	return buf, nil
}

// UnmarshalRightConflict decodes the JSON document data into v.
func UnmarshalRightConflict(data []byte, v *RightConflict) error {
	// The cache plays the part of encoding/json/v2's string cache: a
	// value that recurs in the document is allocated once.
	sc := odjsonrt.GetStringCache()
	p, err := v.odjsonParse(data, odjsonrt.SkipSpace(data, 0), sc)
	odjsonrt.PutStringCache(sc)
	if err != nil {
		return err
	}
	return odjsonrt.EndOfDocument(data, p)
}

// odjsonAppend appends the JSON encoding of v to dst.
func (v *UntaggedSide) odjsonAppend(dst []byte, m odjsonrt.StringMode) ([]byte, error) {
	var err error
	_ = err
	start := len(dst)
	dst = append(dst, ",\"Winner\":"...)
	dst, err = odjsonrt.AppendStringChecked(dst, string(v.Winner), m)
	if err != nil {
		return nil, err
	}
	if len(dst) == start {
		dst = append(dst, '{', '}')
	} else {
		dst[start] = '{'
		dst = append(dst, '}')
	}
	return dst, nil
}

// odjsonParse decodes the JSON object starting at p into v and
// returns the offset just past it. Strings are interned through
// sc, which may be nil.
func (v *UntaggedSide) odjsonParse(data []byte, p int, sc *odjsonrt.StringCache) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		return np, nil
	}
	if p >= len(data) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "UntaggedSide")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if p < len(data) && data[p] == '}' {
		return p + 1, nil
	}
	for {
		var key []byte
		p = odjsonrt.SkipSpace(data, p)
		idx := -1
		if rest := data[p:]; len(rest) > 1 {
			switch rest[1] {
			case 'W':
				switch {
				case len(rest) >= 8 && string(rest[:8]) == "\"Winner\"":
					idx, p = 0, p+8
				}
			}
		}
		if idx >= 0 {
			if p < len(data) && data[p] == ':' {
				p = odjsonrt.SkipSpace(data, p+1)
			} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
				return p, err
			}
		} else {
			key, _, p, err = odjsonrt.ParseKey(data, p)
			if err != nil {
				return p, err
			}
			switch string(key) {
			case "Winner":
				idx = 0
			}
			if idx < 0 {
				fold := !odjsonrt.ASCII(key)
				switch {
				case (len(key) == 6 || fold) && odjsonrt.EqualFold(key, "Winner"):
					idx = 0
				}
			}
		}
		switch idx {
		case 0:
			if np31, ok32 := odjsonrt.ParseNull(data, p); ok32 {
				p = np31
			} else {
				var x33 string
				x33, p, err = odjsonrt.ParseStringCached(data, p, sc)
				if err != nil {
					return p, err
				}
				v.Winner = x33
			}
		default:
			p = odjsonrt.SkipSpace(data, p)
			p, err = odjsonrt.SkipValue(data, p)
			if err != nil {
				return p, err
			}
		}
		p = odjsonrt.SkipSpace(data, p)
		if p >= len(data) {
			return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
		}
		switch data[p] {
		case ',':
			p++
		case '}':
			return p + 1, nil
		default:
			return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
		}
	}
}

// AppendUntaggedSide appends the JSON encoding of v to dst.
func AppendUntaggedSide(dst []byte, v *UntaggedSide) ([]byte, error) {
	return v.odjsonAppend(dst, odjsonrt.ModeHTML)
}

// odjsonSizeUntaggedSide sizes the buffer MarshalUntaggedSide allocates.
var odjsonSizeUntaggedSide odjsonrt.SizeHint

// MarshalUntaggedSide returns the JSON encoding of v.
func MarshalUntaggedSide(v *UntaggedSide) ([]byte, error) {
	buf, err := v.odjsonAppend(odjsonSizeUntaggedSide.New(), odjsonrt.ModeHTML)
	if err != nil {
		return nil, err
	}
	odjsonSizeUntaggedSide.Record(buf)
	return buf, nil
}

// UnmarshalUntaggedSide decodes the JSON document data into v.
func UnmarshalUntaggedSide(data []byte, v *UntaggedSide) error {
	// The cache plays the part of encoding/json/v2's string cache: a
	// value that recurs in the document is allocated once.
	sc := odjsonrt.GetStringCache()
	p, err := v.odjsonParse(data, odjsonrt.SkipSpace(data, 0), sc)
	odjsonrt.PutStringCache(sc)
	if err != nil {
		return err
	}
	return odjsonrt.EndOfDocument(data, p)
}

// odjsonAppend appends the JSON encoding of v to dst.
func (v *TaggedSide) odjsonAppend(dst []byte, m odjsonrt.StringMode) ([]byte, error) {
	var err error
	_ = err
	start := len(dst)
	dst = append(dst, ",\"Winner\":"...)
	dst, err = odjsonrt.AppendStringChecked(dst, string(v.Winner), m)
	if err != nil {
		return nil, err
	}
	if len(dst) == start {
		dst = append(dst, '{', '}')
	} else {
		dst[start] = '{'
		dst = append(dst, '}')
	}
	return dst, nil
}

// odjsonParse decodes the JSON object starting at p into v and
// returns the offset just past it. Strings are interned through
// sc, which may be nil.
func (v *TaggedSide) odjsonParse(data []byte, p int, sc *odjsonrt.StringCache) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		return np, nil
	}
	if p >= len(data) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "TaggedSide")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if p < len(data) && data[p] == '}' {
		return p + 1, nil
	}
	for {
		var key []byte
		p = odjsonrt.SkipSpace(data, p)
		idx := -1
		if rest := data[p:]; len(rest) > 1 {
			switch rest[1] {
			case 'W':
				switch {
				case len(rest) >= 8 && string(rest[:8]) == "\"Winner\"":
					idx, p = 0, p+8
				}
			}
		}
		if idx >= 0 {
			if p < len(data) && data[p] == ':' {
				p = odjsonrt.SkipSpace(data, p+1)
			} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
				return p, err
			}
		} else {
			key, _, p, err = odjsonrt.ParseKey(data, p)
			if err != nil {
				return p, err
			}
			switch string(key) {
			case "Winner":
				idx = 0
			}
			if idx < 0 {
				fold := !odjsonrt.ASCII(key)
				switch {
				case (len(key) == 6 || fold) && odjsonrt.EqualFold(key, "Winner"):
					idx = 0
				}
			}
		}
		switch idx {
		case 0:
			if np34, ok35 := odjsonrt.ParseNull(data, p); ok35 {
				p = np34
			} else {
				var x36 string
				x36, p, err = odjsonrt.ParseStringCached(data, p, sc)
				if err != nil {
					return p, err
				}
				v.Winner = x36
			}
		default:
			p = odjsonrt.SkipSpace(data, p)
			p, err = odjsonrt.SkipValue(data, p)
			if err != nil {
				return p, err
			}
		}
		p = odjsonrt.SkipSpace(data, p)
		if p >= len(data) {
			return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
		}
		switch data[p] {
		case ',':
			p++
		case '}':
			return p + 1, nil
		default:
			return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
		}
	}
}

// AppendTaggedSide appends the JSON encoding of v to dst.
func AppendTaggedSide(dst []byte, v *TaggedSide) ([]byte, error) {
	return v.odjsonAppend(dst, odjsonrt.ModeHTML)
}

// odjsonSizeTaggedSide sizes the buffer MarshalTaggedSide allocates.
var odjsonSizeTaggedSide odjsonrt.SizeHint

// MarshalTaggedSide returns the JSON encoding of v.
func MarshalTaggedSide(v *TaggedSide) ([]byte, error) {
	buf, err := v.odjsonAppend(odjsonSizeTaggedSide.New(), odjsonrt.ModeHTML)
	if err != nil {
		return nil, err
	}
	odjsonSizeTaggedSide.Record(buf)
	return buf, nil
}

// UnmarshalTaggedSide decodes the JSON document data into v.
func UnmarshalTaggedSide(data []byte, v *TaggedSide) error {
	// The cache plays the part of encoding/json/v2's string cache: a
	// value that recurs in the document is allocated once.
	sc := odjsonrt.GetStringCache()
	p, err := v.odjsonParse(data, odjsonrt.SkipSpace(data, 0), sc)
	odjsonrt.PutStringCache(sc)
	if err != nil {
		return err
	}
	return odjsonrt.EndOfDocument(data, p)
}

// odjsonAppend appends the JSON encoding of v to dst.
func (v *PtrPart) odjsonAppend(dst []byte, m odjsonrt.StringMode) ([]byte, error) {
	var err error
	_ = err
	start := len(dst)
	dst = append(dst, ",\"ptr_only\":"...)
	dst = odjsonrt.AppendInt(dst, int64(v.PtrOnly))
	if len(dst) == start {
		dst = append(dst, '{', '}')
	} else {
		dst[start] = '{'
		dst = append(dst, '}')
	}
	return dst, nil
}

// odjsonParse decodes the JSON object starting at p into v and
// returns the offset just past it. Strings are interned through
// sc, which may be nil.
func (v *PtrPart) odjsonParse(data []byte, p int, sc *odjsonrt.StringCache) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		return np, nil
	}
	if p >= len(data) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "PtrPart")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if p < len(data) && data[p] == '}' {
		return p + 1, nil
	}
	for {
		var key []byte
		p = odjsonrt.SkipSpace(data, p)
		idx := -1
		if rest := data[p:]; len(rest) > 1 {
			switch rest[1] {
			case 'p':
				switch {
				case len(rest) >= 10 && string(rest[:10]) == "\"ptr_only\"":
					idx, p = 0, p+10
				}
			}
		}
		if idx >= 0 {
			if p < len(data) && data[p] == ':' {
				p = odjsonrt.SkipSpace(data, p+1)
			} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
				return p, err
			}
		} else {
			key, _, p, err = odjsonrt.ParseKey(data, p)
			if err != nil {
				return p, err
			}
			switch string(key) {
			case "ptr_only":
				idx = 0
			}
			if idx < 0 {
				fold := !odjsonrt.ASCII(key)
				switch {
				case (len(key) == 8 || fold) && odjsonrt.EqualFold(key, "ptr_only"):
					idx = 0
				}
			}
		}
		switch idx {
		case 0:
			if np37, ok38 := odjsonrt.ParseNull(data, p); ok38 {
				p = np37
			} else {
				if x39, np40, ok41 := odjsonrt.ParseDecimal(data, p); ok41 {
					v.PtrOnly = int(x39)
					p = np40
				} else {
					var x42 int64
					x42, p, err = odjsonrt.ParseInt(data, p, 64)
					if err != nil {
						return p, err
					}
					v.PtrOnly = int(x42)
				}
			}
		default:
			p = odjsonrt.SkipSpace(data, p)
			p, err = odjsonrt.SkipValue(data, p)
			if err != nil {
				return p, err
			}
		}
		p = odjsonrt.SkipSpace(data, p)
		if p >= len(data) {
			return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
		}
		switch data[p] {
		case ',':
			p++
		case '}':
			return p + 1, nil
		default:
			return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
		}
	}
}

// AppendPtrPart appends the JSON encoding of v to dst.
func AppendPtrPart(dst []byte, v *PtrPart) ([]byte, error) {
	return v.odjsonAppend(dst, odjsonrt.ModeHTML)
}

// odjsonSizePtrPart sizes the buffer MarshalPtrPart allocates.
var odjsonSizePtrPart odjsonrt.SizeHint

// MarshalPtrPart returns the JSON encoding of v.
func MarshalPtrPart(v *PtrPart) ([]byte, error) {
	buf, err := v.odjsonAppend(odjsonSizePtrPart.New(), odjsonrt.ModeHTML)
	if err != nil {
		return nil, err
	}
	odjsonSizePtrPart.Record(buf)
	return buf, nil
}

// UnmarshalPtrPart decodes the JSON document data into v.
func UnmarshalPtrPart(data []byte, v *PtrPart) error {
	// The cache plays the part of encoding/json/v2's string cache: a
	// value that recurs in the document is allocated once.
	sc := odjsonrt.GetStringCache()
	p, err := v.odjsonParse(data, odjsonrt.SkipSpace(data, 0), sc)
	odjsonrt.PutStringCache(sc)
	if err != nil {
		return err
	}
	return odjsonrt.EndOfDocument(data, p)
}

// odjsonAppend appends the JSON encoding of v to dst.
func (v *Named) odjsonAppend(dst []byte, m odjsonrt.StringMode) ([]byte, error) {
	var err error
	_ = err
	start := len(dst)
	dst = append(dst, ",\"value\":"...)
	dst = odjsonrt.AppendInt(dst, int64(v.Value))
	if len(dst) == start {
		dst = append(dst, '{', '}')
	} else {
		dst[start] = '{'
		dst = append(dst, '}')
	}
	return dst, nil
}

// odjsonParse decodes the JSON object starting at p into v and
// returns the offset just past it. Strings are interned through
// sc, which may be nil.
func (v *Named) odjsonParse(data []byte, p int, sc *odjsonrt.StringCache) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		return np, nil
	}
	if p >= len(data) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "Named")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if p < len(data) && data[p] == '}' {
		return p + 1, nil
	}
	for {
		var key []byte
		p = odjsonrt.SkipSpace(data, p)
		idx := -1
		if rest := data[p:]; len(rest) > 1 {
			switch rest[1] {
			case 'v':
				switch {
				case len(rest) >= 7 && string(rest[:7]) == "\"value\"":
					idx, p = 0, p+7
				}
			}
		}
		if idx >= 0 {
			if p < len(data) && data[p] == ':' {
				p = odjsonrt.SkipSpace(data, p+1)
			} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
				return p, err
			}
		} else {
			key, _, p, err = odjsonrt.ParseKey(data, p)
			if err != nil {
				return p, err
			}
			switch string(key) {
			case "value":
				idx = 0
			}
			if idx < 0 {
				fold := !odjsonrt.ASCII(key)
				switch {
				case (len(key) == 5 || fold) && odjsonrt.EqualFold(key, "value"):
					idx = 0
				}
			}
		}
		switch idx {
		case 0:
			if np43, ok44 := odjsonrt.ParseNull(data, p); ok44 {
				p = np43
			} else {
				if x45, np46, ok47 := odjsonrt.ParseDecimal(data, p); ok47 {
					v.Value = int(x45)
					p = np46
				} else {
					var x48 int64
					x48, p, err = odjsonrt.ParseInt(data, p, 64)
					if err != nil {
						return p, err
					}
					v.Value = int(x48)
				}
			}
		default:
			p = odjsonrt.SkipSpace(data, p)
			p, err = odjsonrt.SkipValue(data, p)
			if err != nil {
				return p, err
			}
		}
		p = odjsonrt.SkipSpace(data, p)
		if p >= len(data) {
			return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
		}
		switch data[p] {
		case ',':
			p++
		case '}':
			return p + 1, nil
		default:
			return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
		}
	}
}

// AppendNamed appends the JSON encoding of v to dst.
func AppendNamed(dst []byte, v *Named) ([]byte, error) {
	return v.odjsonAppend(dst, odjsonrt.ModeHTML)
}

// odjsonSizeNamed sizes the buffer MarshalNamed allocates.
var odjsonSizeNamed odjsonrt.SizeHint

// MarshalNamed returns the JSON encoding of v.
func MarshalNamed(v *Named) ([]byte, error) {
	buf, err := v.odjsonAppend(odjsonSizeNamed.New(), odjsonrt.ModeHTML)
	if err != nil {
		return nil, err
	}
	odjsonSizeNamed.Record(buf)
	return buf, nil
}

// UnmarshalNamed decodes the JSON document data into v.
func UnmarshalNamed(data []byte, v *Named) error {
	// The cache plays the part of encoding/json/v2's string cache: a
	// value that recurs in the document is allocated once.
	sc := odjsonrt.GetStringCache()
	p, err := v.odjsonParse(data, odjsonrt.SkipSpace(data, 0), sc)
	odjsonrt.PutStringCache(sc)
	if err != nil {
		return err
	}
	return odjsonrt.EndOfDocument(data, p)
}

// odjsonAppend appends the JSON encoding of v to dst.
func (v *Promoted) odjsonAppend(dst []byte, m odjsonrt.StringMode) ([]byte, error) {
	var err error
	_ = err
	start := len(dst)
	dst = append(dst, ",\"deep_only\":"...)
	dst, err = odjsonrt.AppendStringChecked(dst, string(v.Mid.Deep.DeepOnly), m)
	if err != nil {
		return nil, err
	}
	dst = append(dst, ",\"shared\":"...)
	dst, err = odjsonrt.AppendStringChecked(dst, string(v.Mid.Shared), m)
	if err != nil {
		return nil, err
	}
	dst = append(dst, ",\"mid_only\":"...)
	dst = odjsonrt.AppendInt(dst, int64(v.Mid.MidOnly))
	dst = append(dst, ",\"left\":"...)
	dst, err = odjsonrt.AppendStringChecked(dst, string(v.LeftConflict.Left), m)
	if err != nil {
		return nil, err
	}
	dst = append(dst, ",\"right\":"...)
	dst, err = odjsonrt.AppendStringChecked(dst, string(v.RightConflict.Right), m)
	if err != nil {
		return nil, err
	}
	dst = append(dst, ",\"Winner\":"...)
	dst, err = odjsonrt.AppendStringChecked(dst, string(v.TaggedSide.Winner), m)
	if err != nil {
		return nil, err
	}
	if v.PtrPart != nil {
		dst = append(dst, ",\"ptr_only\":"...)
		dst = odjsonrt.AppendInt(dst, int64(v.PtrPart.PtrOnly))
	}
	dst = append(dst, ",\"Label\":"...)
	dst, err = odjsonrt.AppendStringChecked(dst, string(v.Label), m)
	if err != nil {
		return nil, err
	}
	dst = append(dst, ",\"named\":"...)
	dst, err = v.Named.odjsonAppend(dst, m)
	if err != nil {
		return nil, err
	}
	dst = append(dst, ",\"own\":"...)
	dst, err = odjsonrt.AppendStringChecked(dst, string(v.Own), m)
	if err != nil {
		return nil, err
	}
	if len(dst) == start {
		dst = append(dst, '{', '}')
	} else {
		dst[start] = '{'
		dst = append(dst, '}')
	}
	return dst, nil
}

// odjsonParse decodes the JSON object starting at p into v and
// returns the offset just past it. Strings are interned through
// sc, which may be nil.
func (v *Promoted) odjsonParse(data []byte, p int, sc *odjsonrt.StringCache) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		return np, nil
	}
	if p >= len(data) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "Promoted")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if p < len(data) && data[p] == '}' {
		return p + 1, nil
	}
	for {
		var key []byte
		p = odjsonrt.SkipSpace(data, p)
		idx := -1
		if rest := data[p:]; len(rest) > 1 {
			switch rest[1] {
			case 'd':
				switch {
				case len(rest) >= 11 && string(rest[:11]) == "\"deep_only\"":
					idx, p = 0, p+11
				}
			case 's':
				switch {
				case len(rest) >= 8 && string(rest[:8]) == "\"shared\"":
					idx, p = 1, p+8
				}
			case 'm':
				switch {
				case len(rest) >= 10 && string(rest[:10]) == "\"mid_only\"":
					idx, p = 2, p+10
				}
			case 'l':
				switch {
				case len(rest) >= 6 && string(rest[:6]) == "\"left\"":
					idx, p = 3, p+6
				}
			case 'r':
				switch {
				case len(rest) >= 7 && string(rest[:7]) == "\"right\"":
					idx, p = 4, p+7
				}
			case 'W':
				switch {
				case len(rest) >= 8 && string(rest[:8]) == "\"Winner\"":
					idx, p = 5, p+8
				}
			case 'p':
				switch {
				case len(rest) >= 10 && string(rest[:10]) == "\"ptr_only\"":
					idx, p = 6, p+10
				}
			case 'L':
				switch {
				case len(rest) >= 7 && string(rest[:7]) == "\"Label\"":
					idx, p = 7, p+7
				}
			case 'n':
				switch {
				case len(rest) >= 7 && string(rest[:7]) == "\"named\"":
					idx, p = 8, p+7
				}
			case 'o':
				switch {
				case len(rest) >= 5 && string(rest[:5]) == "\"own\"":
					idx, p = 9, p+5
				}
			}
		}
		if idx >= 0 {
			if p < len(data) && data[p] == ':' {
				p = odjsonrt.SkipSpace(data, p+1)
			} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
				return p, err
			}
		} else {
			key, _, p, err = odjsonrt.ParseKey(data, p)
			if err != nil {
				return p, err
			}
			switch string(key) {
			case "deep_only":
				idx = 0
			case "shared":
				idx = 1
			case "mid_only":
				idx = 2
			case "left":
				idx = 3
			case "right":
				idx = 4
			case "Winner":
				idx = 5
			case "ptr_only":
				idx = 6
			case "Label":
				idx = 7
			case "named":
				idx = 8
			case "own":
				idx = 9
			}
			if idx < 0 {
				fold := !odjsonrt.ASCII(key)
				switch {
				case (len(key) == 9 || fold) && odjsonrt.EqualFold(key, "deep_only"):
					idx = 0
				case (len(key) == 6 || fold) && odjsonrt.EqualFold(key, "shared"):
					idx = 1
				case (len(key) == 8 || fold) && odjsonrt.EqualFold(key, "mid_only"):
					idx = 2
				case (len(key) == 4 || fold) && odjsonrt.EqualFold(key, "left"):
					idx = 3
				case (len(key) == 5 || fold) && odjsonrt.EqualFold(key, "right"):
					idx = 4
				case (len(key) == 6 || fold) && odjsonrt.EqualFold(key, "Winner"):
					idx = 5
				case (len(key) == 8 || fold) && odjsonrt.EqualFold(key, "ptr_only"):
					idx = 6
				case (len(key) == 5 || fold) && odjsonrt.EqualFold(key, "Label"):
					idx = 7
				case (len(key) == 5 || fold) && odjsonrt.EqualFold(key, "named"):
					idx = 8
				case (len(key) == 3 || fold) && odjsonrt.EqualFold(key, "own"):
					idx = 9
				}
			}
		}
		switch idx {
		case 0:
			if np49, ok50 := odjsonrt.ParseNull(data, p); ok50 {
				p = np49
			} else {
				var x51 string
				x51, p, err = odjsonrt.ParseStringCached(data, p, sc)
				if err != nil {
					return p, err
				}
				v.Mid.Deep.DeepOnly = x51
			}
		case 1:
			if np52, ok53 := odjsonrt.ParseNull(data, p); ok53 {
				p = np52
			} else {
				var x54 string
				x54, p, err = odjsonrt.ParseStringCached(data, p, sc)
				if err != nil {
					return p, err
				}
				v.Mid.Shared = x54
			}
		case 2:
			if np55, ok56 := odjsonrt.ParseNull(data, p); ok56 {
				p = np55
			} else {
				if x57, np58, ok59 := odjsonrt.ParseDecimal(data, p); ok59 {
					v.Mid.MidOnly = int(x57)
					p = np58
				} else {
					var x60 int64
					x60, p, err = odjsonrt.ParseInt(data, p, 64)
					if err != nil {
						return p, err
					}
					v.Mid.MidOnly = int(x60)
				}
			}
		case 3:
			if np61, ok62 := odjsonrt.ParseNull(data, p); ok62 {
				p = np61
			} else {
				var x63 string
				x63, p, err = odjsonrt.ParseStringCached(data, p, sc)
				if err != nil {
					return p, err
				}
				v.LeftConflict.Left = x63
			}
		case 4:
			if np64, ok65 := odjsonrt.ParseNull(data, p); ok65 {
				p = np64
			} else {
				var x66 string
				x66, p, err = odjsonrt.ParseStringCached(data, p, sc)
				if err != nil {
					return p, err
				}
				v.RightConflict.Right = x66
			}
		case 5:
			if np67, ok68 := odjsonrt.ParseNull(data, p); ok68 {
				p = np67
			} else {
				var x69 string
				x69, p, err = odjsonrt.ParseStringCached(data, p, sc)
				if err != nil {
					return p, err
				}
				v.TaggedSide.Winner = x69
			}
		case 6:
			if v.PtrPart == nil {
				v.PtrPart = new(PtrPart)
			}
			if np70, ok71 := odjsonrt.ParseNull(data, p); ok71 {
				p = np70
			} else {
				if x72, np73, ok74 := odjsonrt.ParseDecimal(data, p); ok74 {
					v.PtrPart.PtrOnly = int(x72)
					p = np73
				} else {
					var x75 int64
					x75, p, err = odjsonrt.ParseInt(data, p, 64)
					if err != nil {
						return p, err
					}
					v.PtrPart.PtrOnly = int(x75)
				}
			}
		case 7:
			if np76, ok77 := odjsonrt.ParseNull(data, p); ok77 {
				p = np76
			} else {
				var x78 string
				x78, p, err = odjsonrt.ParseStringCached(data, p, sc)
				if err != nil {
					return p, err
				}
				v.Label = Label(x78)
			}
		case 8:
			p, err = v.Named.odjsonParse(data, p, sc)
			if err != nil {
				return p, err
			}
		case 9:
			if np79, ok80 := odjsonrt.ParseNull(data, p); ok80 {
				p = np79
			} else {
				var x81 string
				x81, p, err = odjsonrt.ParseStringCached(data, p, sc)
				if err != nil {
					return p, err
				}
				v.Own = x81
			}
		default:
			p = odjsonrt.SkipSpace(data, p)
			p, err = odjsonrt.SkipValue(data, p)
			if err != nil {
				return p, err
			}
		}
		p = odjsonrt.SkipSpace(data, p)
		if p >= len(data) {
			return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
		}
		switch data[p] {
		case ',':
			p++
		case '}':
			return p + 1, nil
		default:
			return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
		}
	}
}

// AppendPromoted appends the JSON encoding of v to dst.
func AppendPromoted(dst []byte, v *Promoted) ([]byte, error) {
	return v.odjsonAppend(dst, odjsonrt.ModeHTML)
}

// odjsonSizePromoted sizes the buffer MarshalPromoted allocates.
var odjsonSizePromoted odjsonrt.SizeHint

// MarshalPromoted returns the JSON encoding of v.
func MarshalPromoted(v *Promoted) ([]byte, error) {
	buf, err := v.odjsonAppend(odjsonSizePromoted.New(), odjsonrt.ModeHTML)
	if err != nil {
		return nil, err
	}
	odjsonSizePromoted.Record(buf)
	return buf, nil
}

// UnmarshalPromoted decodes the JSON document data into v.
func UnmarshalPromoted(data []byte, v *Promoted) error {
	// The cache plays the part of encoding/json/v2's string cache: a
	// value that recurs in the document is allocated once.
	sc := odjsonrt.GetStringCache()
	p, err := v.odjsonParse(data, odjsonrt.SkipSpace(data, 0), sc)
	odjsonrt.PutStringCache(sc)
	if err != nil {
		return err
	}
	return odjsonrt.EndOfDocument(data, p)
}

// odjsonAppend appends the JSON encoding of v to dst.
func (v *ShallowWins) odjsonAppend(dst []byte, m odjsonrt.StringMode) ([]byte, error) {
	var err error
	_ = err
	start := len(dst)
	dst = append(dst, ",\"deep_only\":"...)
	dst, err = odjsonrt.AppendStringChecked(dst, string(v.Deep.DeepOnly), m)
	if err != nil {
		return nil, err
	}
	dst = append(dst, ",\"shared\":"...)
	dst = odjsonrt.AppendInt(dst, int64(v.Shared))
	if len(dst) == start {
		dst = append(dst, '{', '}')
	} else {
		dst[start] = '{'
		dst = append(dst, '}')
	}
	return dst, nil
}

// odjsonParse decodes the JSON object starting at p into v and
// returns the offset just past it. Strings are interned through
// sc, which may be nil.
func (v *ShallowWins) odjsonParse(data []byte, p int, sc *odjsonrt.StringCache) (int, error) {
	var err error
	_ = err
	p = odjsonrt.SkipSpace(data, p)
	if np, ok := odjsonrt.ParseNull(data, p); ok {
		return np, nil
	}
	if p >= len(data) || data[p] != '{' {
		return p, odjsonrt.ErrType(data, p, "ShallowWins")
	}
	p++
	p = odjsonrt.SkipSpace(data, p)
	if p < len(data) && data[p] == '}' {
		return p + 1, nil
	}
	for {
		var key []byte
		p = odjsonrt.SkipSpace(data, p)
		idx := -1
		if rest := data[p:]; len(rest) > 1 {
			switch rest[1] {
			case 'd':
				switch {
				case len(rest) >= 11 && string(rest[:11]) == "\"deep_only\"":
					idx, p = 0, p+11
				}
			case 's':
				switch {
				case len(rest) >= 8 && string(rest[:8]) == "\"shared\"":
					idx, p = 1, p+8
				}
			}
		}
		if idx >= 0 {
			if p < len(data) && data[p] == ':' {
				p = odjsonrt.SkipSpace(data, p+1)
			} else if p, err = odjsonrt.AfterKey(data, p); err != nil {
				return p, err
			}
		} else {
			key, _, p, err = odjsonrt.ParseKey(data, p)
			if err != nil {
				return p, err
			}
			switch string(key) {
			case "deep_only":
				idx = 0
			case "shared":
				idx = 1
			}
			if idx < 0 {
				fold := !odjsonrt.ASCII(key)
				switch {
				case (len(key) == 9 || fold) && odjsonrt.EqualFold(key, "deep_only"):
					idx = 0
				case (len(key) == 6 || fold) && odjsonrt.EqualFold(key, "shared"):
					idx = 1
				}
			}
		}
		switch idx {
		case 0:
			if np82, ok83 := odjsonrt.ParseNull(data, p); ok83 {
				p = np82
			} else {
				var x84 string
				x84, p, err = odjsonrt.ParseStringCached(data, p, sc)
				if err != nil {
					return p, err
				}
				v.Deep.DeepOnly = x84
			}
		case 1:
			if np85, ok86 := odjsonrt.ParseNull(data, p); ok86 {
				p = np85
			} else {
				if x87, np88, ok89 := odjsonrt.ParseDecimal(data, p); ok89 {
					v.Shared = int(x87)
					p = np88
				} else {
					var x90 int64
					x90, p, err = odjsonrt.ParseInt(data, p, 64)
					if err != nil {
						return p, err
					}
					v.Shared = int(x90)
				}
			}
		default:
			p = odjsonrt.SkipSpace(data, p)
			p, err = odjsonrt.SkipValue(data, p)
			if err != nil {
				return p, err
			}
		}
		p = odjsonrt.SkipSpace(data, p)
		if p >= len(data) {
			return p, odjsonrt.ErrSyntax(data, p, "unexpected end of JSON input")
		}
		switch data[p] {
		case ',':
			p++
		case '}':
			return p + 1, nil
		default:
			return p, odjsonrt.ErrSyntax(data, p, "after object key:value pair")
		}
	}
}

// AppendShallowWins appends the JSON encoding of v to dst.
func AppendShallowWins(dst []byte, v *ShallowWins) ([]byte, error) {
	return v.odjsonAppend(dst, odjsonrt.ModeHTML)
}

// odjsonSizeShallowWins sizes the buffer MarshalShallowWins allocates.
var odjsonSizeShallowWins odjsonrt.SizeHint

// MarshalShallowWins returns the JSON encoding of v.
func MarshalShallowWins(v *ShallowWins) ([]byte, error) {
	buf, err := v.odjsonAppend(odjsonSizeShallowWins.New(), odjsonrt.ModeHTML)
	if err != nil {
		return nil, err
	}
	odjsonSizeShallowWins.Record(buf)
	return buf, nil
}

// UnmarshalShallowWins decodes the JSON document data into v.
func UnmarshalShallowWins(data []byte, v *ShallowWins) error {
	// The cache plays the part of encoding/json/v2's string cache: a
	// value that recurs in the document is allocated once.
	sc := odjsonrt.GetStringCache()
	p, err := v.odjsonParse(data, odjsonrt.SkipSpace(data, 0), sc)
	odjsonrt.PutStringCache(sc)
	if err != nil {
		return err
	}
	return odjsonrt.EndOfDocument(data, p)
}
